### ISSUE TITLE
Need help ASAP: Floating point exception: 8

### ISSUE THREAD

**Issue by sunilkpai** [Emotiv/community-sdk#101]
I am having a floating point exception: 8 on my Mac trying to run the C++ example AverageBandPowers and MotionDataLogger. Is this because signals are not being sent to the dongle? I have a class deadline, and this issue is pretty urgent, so a quick reply would be much appreciated! Thanks for making a great SDK interface for developers like me! Sunil

**Comment by nguoithichkhampha** [comment]
Maybe have bug in our example. I will check again.

**Comment by hoangphamemotiv** [comment]
Hi sunilkpai. 
we checked this issue. but dont see a error. can you send me a capture of error, where the error raised or more infos in case?

**Comment by sunilkpai** [comment]
Hi, 

The issue is as follows. When using the qt projects, I get a compiler error ("framework cannot find edk") and so I just use the cmake file. When I do that, everything compiles, but unfortunately, while I pass the EDK_OK flag for the IEEEngineConnect, I don't pass the next one. Here's an example for AverageBandPowers (which is urgent for us atm):

`int result = IEE_GetAverageBandPowers(engineUserID, channelList[i], &theta, &alpha, 
					                                     &low_beta, &high_beta, &gamma);
                cout<<engineUserID<<"\n";
                cout<<channelList[i]<<"\n";
                cout<<"edk ok?\n";
                if(result == EDK_OK){
                    cout<<"yep\n";
                    ofs << theta << ",";
                    ofs << alpha << ",";
                    ofs << low_beta << ",";
                    ofs << high_beta << ",";
                    ofs << gamma << ",";
                    ofs << std::endl;

					std::cout << theta << "," << alpha << "," << low_beta << ",";
                    std::cout << high_beta << "," << gamma << std::endl;
                }
                else{
                    cout<<"nope :(\n";
                }`

I keep getting "nope :(" at the output, meaning that even though IEEEngineConnect works, it doesn't pass the next check. I tried changing to poor 3008 and using ControlPanel but that did not work either.

**Comment by fokdemall** [comment]
Hi sunilkpai ,

I am facing the exact same problem... Did you manage to fix that ?
It's pretty urgent for me, too ...

**Comment by tungntEmotiv** [comment]
Hi All,

Please pull the latest code and re-test. I will close the issue and re-open if the issue occur again. 
Thank you
