### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by keliomer** [Emotiv/community-sdk#102]
The [link](http://emotiv.com/api/3.3.1/) for the API documentation is dead since the emotiv.com overhaul. We should really be pointing to the docs in [here](https://github.com/Emotiv/community-sdk/tree/master/doc/api_doc) (and making it display prettier) or link to the proper location of the API docs on emotiv.com (From what I can tell it points to this repository as the documentation)

**Comment by patdotme** [comment]
Thanks @keliomer we just migrated to a new site so some links may have been overlooked. It will be fixed shortly.

**Comment by patdotme** [comment]
Moved to http://emotiv.github.io/community-sdk/
cheers
