### ISSUE TITLE
license and distribution questions regarding edk.dll

### ISSUE THREAD

**Issue by dmedine** [Emotiv/community-sdk#103]
This isn't an issue so much as a question...two questions actually.

1. Is the edk.dll that comes with the premium sdk the same as the one here in the community edition, and
2. I have written an application for data logging that I wish to distribute. Can I distribute the (premium) dll with my application?

Thank you.

**Comment by mdtdev** [comment]
This is an important issue with the recent changes at Emotiv regarding their shift to monthly licenses and web based data hosting.

**Comment by patdotme** [comment]
Hi @dmedine 
1. The edk.dll that comes with the Premium SDK is NOT the same as the one here in the Community Edition
2. The license with Premium SDK does NOT allow re-distribution to 3rd party or public in any form.
Cheers.

**Comment by dmedine** [comment]
Thank you for clarifying this.
