### ISSUE TITLE
SavingAndLoadingProfileCloud.py cannot login

### ISSUE THREAD

**Issue by jason818919** [Emotiv/community-sdk#104]
Hi there~
I ran SavingAndLoadingProfileCloud.py in the example code with my own pass but it resulted in the following error message.

> Your login attempt has failed. The username or password may be incorrect
terminate called without an active exception

My pass is something like this:

userName = "foo@bar.com"
password = "ABCde"

I only modified the above part of the code.

Is this a bug from the database?

**Comment by patdotme** [comment]
Hi @jason818919 you need to use your EmotivID and password to login, which can be created here id.emotivcloud.com
The same username you used to login to emotiv.com.

**Comment by jason818919** [comment]
Hi @patdotme 

My account has been registered a long time ago in emotiv.com and I has bought a lot of headsets under this account. Furthermore, I have registered a new account and tried to run SavingAndLoadingProfileCloud.py again, but it still resulted in failure...
Is there anything wrong in example code ? I am building applications on new headsets, and this bug really strangles my progress : (

Thank you!
