### ISSUE TITLE
EEG data

### ISSUE THREAD

**Issue by clavdam** [Emotiv/community-sdk#105]
Before buying an Emotiv product I would want to know if source data files contain EEG signal or is it a preprocessed signal ? Is it possible to perform a real-time analysis ?
Could you send me an example of source data file ?
Thank you so much

**Comment by patdotme** [comment]
Hi @clavdam you can access the output of Facial Expression and Mental Commands, motion sensor, and band powers for certain frequency range. However real-time EEG data access is not available via SDK. You can buy a subscription plan with the Pure.EEG software from Emotiv web store which can record EEG data in EDF format and export for analysis later.
