### ISSUE TITLE
Recording raw EEG with Community edition

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [Emotiv/community-sdk#108]
Is it possible to record the raw EEG data in MATLAB with the community edition?

**Comment by patdotme** [comment]
@Kulbhushan-Chand Community Edition does not support raw EEG data recording in MATLAB.
You can choose a subscription plan for Pure.EEG on emotiv.com to do recording, export the data to CSV after the session has been saved, and read it in MATLAB to analysis.

**Comment by Kulbhushan-Chand** [comment]
Thanks for reply,
But I want unlimited recording option, since we are into research we do not want to limit our options.
Isn't paying 799$ will make the EPOC+ to provide the full and unlimited EEG access?

**Comment by mdtdev** [comment]
No. It used to work that way but recently the company changed their policy. It is forcing us to reconsider them now, too. We paid for a site license a couple years back, and got grandfathered in, but new people have to pay a subscription. Which isn't even legal for researchers with IRBs and grants!

But as of now raw EEG is subscription only for new systems.
