### ISSUE TITLE
Missing file: bedk.jar

### ISSUE THREAD

**Issue by Donaldong** [Emotiv/community-sdk#109]
Hi,

I can't find bedk.jar in the newest sdk. 
So I can't build the updated android examples.

**Comment by nguoithichkhampha** [comment]
Hi,
Now, we release library on jcenter. When you use gradle, lib will be auto loaded into your project.
You can check new version in here:
https://bintray.com/nguoithichkhampha/maven/community/view

**Comment by Donaldong** [comment]
Thanks!
