### ISSUE TITLE
Epoc to Processing 

### ISSUE THREAD

**Issue by asadjm** [Emotiv/community-sdk#110]
I want to be able to interface my Emotiv Epoc with Processing to create some visuals based on the data I get from the Epoc. I want to be able to access facial expressions and the expressive suit for excitement levels etc.

Most places on the internet recommend MindYourOSCs for this purpose but after weeks of trying I’ve given up on it. It crashes everytime and doesn’t connect. What other ways are there for me to access live data from the Epoc to Processing?

**Comment by hoangphamemotiv** [comment]
Hi asadjm. 
you mean, you got crashing on MindYourOSCs right? Did you use it with a EPOC or EPOC+ headset. 
i think current version of this app is old version.so, it maybe dont work with EPOC+ headset.

**Comment by asadjm** [comment]
Hey! Appreciate the response. Yes MindYourOSCs keeps crashing. I'm using it with an EPOC headset on a Mac. It connects perfectly with OSC part but the Emotiv part gets stuck on "waiting". As soon as any data actually passes through either the control panel or the composer, it crashes with the following error 

"Assertion failed: (sizeof(emoState_t) == emoStateBytes.size()), function serialize, file ../../include/EmoEventLib/EmoEvent.h, line 306."

I'm using Xavier 3.1.17

Would certainly make my life easier if it starts working :)

**Comment by nguoithichkhampha** [comment]
Hi @asadjm ,
MindYourOSCs use our old library. Have some difference between old and new library . We fixed this bug on latest version. You can try Xavier 3.3.3
