### ISSUE TITLE
cannot load dll lib

### ISSUE THREAD

**Issue by ekkasitsmithipanon** [Emotiv/community-sdk#111]
When I run the premium example, eeg_logger.py, on windows with python 2.7.11
I receive this error message. Is there any solution for this?
I put the edk.dll edk.lib in system32 and the same directory as my eeg_logger.py

    Error : cannot load dll lib
    
    Traceback (most recent call last):
    File "C:\Users\Ekkasit\Desktop\Emotiv Python EEG\eeg_logger.py", line 44, in 
    eEvent = libEDK.IEE_EmoEngineEventCreate()
    NameError: name 'libEDK' is not defined

And this this some code from the eeg_logger.py

    try :
        if sys.platform.startswith('win32'):     
            libEDK = cdll.LoadLibrary("edk.dll")
        if sys.platform.startswith('linux'):
            srcDir = os.getcwd()    
            libPath = srcDir + "/libedk.so"        
            libEDK = CDLL(libPath)
    except :
        print 'Error : cannot load dll lib'

and

    write = sys.stdout.write
    eEvent = libEDK.IEE_EmoEngineEventCreate()

This is what i get 

    Traceback (most recent call last):
      File "C:\Users\Ekkasit\Desktop\Emotiv Python EEG\eeg_logger.py", line 16, in <module>
        libEDK = cdll.LoadLibrary("edk.dll")
      File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
        return self._dlltype(name)
      File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
        self._handle = _dlopen(self._name, mode)
    WindowsError: [Error 193] %1 is not a valid Win32 application

when i run only

    if sys.platform.startswith('win32'):     
    libEDK = cdll.LoadLibrary("edk.dll")

instead of the one before

**Comment by ekkasitsmithipanon** [comment]
Traceback (most recent call last):
  File "C:\Users\Ekkasit\Desktop\Emotiv Python EEG\eeg_logger.py", line 16, in <module>
    libEDK = cdll.LoadLibrary("edk.dll")
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application


this is what i get when i run only

if sys.platform.startswith('win32'):     
    libEDK = cdll.LoadLibrary("edk.dll")

instead of

try :
    if sys.platform.startswith('win32'):     
        libEDK = cdll.LoadLibrary("edk.dll")
    if sys.platform.startswith('linux'):
        srcDir = os.getcwd()    
        libPath = srcDir + "/libedk.so"        
        libEDK = CDLL(libPath)
except :
    print 'Error : cannot load dll lib'

**Comment by hoangphamemotiv** [comment]
Hi ekkasitsmithipanon. 

i just fixed this error. ^^!. you can update code from the Github. Thank Ekkasitsmithipanon. 

if sys.platform.startswith('win32'):
        libEDK = cdll.LoadLibrary("../../bin/win32/edk.dll")
    elif sys.platform.startswith('linux'):
        srcDir = os.getcwd()
	if platform.machine().startswith('arm'):
            libPath = srcDir + "/../../bin/armhf/libedk.so"
	else:
            libPath = srcDir + "/../../bin/linux64/libedk.so"
        libEDK = CDLL(libPath)
    else:
        raise Exception('System not supported.')

**Comment by ivankras** [comment]
Even with the code corrected, I get the same error

**Comment by hoangphamemotiv** [comment]
Hi @ivankras 
what version of python are you using? 64bit or 32bit? the code above work well on 32bit
