### ISSUE TITLE
MotionDataLogger gets null instead of data (need help ASAP)

### ISSUE THREAD

**Issue by Yorkst** [Emotiv/community-sdk#113]
I'm trying to run  MotionDataLogger from C# examples

64bit version of edk.dll and glut64.dll, as well as DotNetEmotivSDK-vs2010.dll are in the same folder with executable, and there is also an environment variable EMOTIV, pointing to them

When I run MotionDataLogger project from "examples" folder, the result of "engine.GetMotionData((UInt32)userID);" is always null. The project is is set to target 64bit beforehand. 

I use Windows 8, 64 bit, Emotiv Epoc +

The state of the receiver:
[https://s32.postimg.org/cb88buh5x/IMG_20160628_212421.jpg](url)
The state of the headset:
[https://s31.postimg.org/cxhurfvsr/headset.png](url)

I've read that I need to set headset in plus mode before getting data, but when I add this as a callback to "User added" event, I get exception, saying, that parameter is out of range, i.e. the result of GetHeadsetSettings returns values which are incorrect for SetHeadsetSettings:

```
static void engine_UserAdded_Event(object sender, EmoEngineEventArgs e)
        {
            Console.WriteLine("User Added Event has occured");

            // record the user 
            userID = (int)e.userId;

            // ask for up to 1 second of buffered data
            engine.MotionDataSetBufferSizeInSec(1);

            UInt32 mode = 0;
            UInt32 eegRate = 0;
            UInt32 eegRes = 0;
            UInt32 memRate = 0;
            UInt32 memRes = 0;
            engine.GetHeadsetSettings((UInt32)userID, out mode, out eegRate, out eegRes, out memRate, out memRes);
            engine.SetHeadsetSettings((UInt32)userID,  mode,  eegRate,  eegRes,  memRate,  memRes);
        }
```

The variables are all zero, except memRes, which is 3

Here is the project, retargeted for 64bit, which logs to console, when data is null:
[http://www.fast-files.com/getfile.aspx?file=116371](url)

**Comment by hoangphamemotiv** [comment]
Hi Yorkst. 
To change setting of a Epoc+ headset. you need connect it to your PC with a cable, then call SetheadsetSettings API anywhere after EngineConnect() called. 
UserAdded event is a event to detect a dongle or a headset is connect to Emoengine, so, i think it dont be used in case. 

\param EPOCmode     
--- If 0, then EPOC mode is EPOC.
--- If 1, then EPOC mode is EPOC+.
\param eegRate      
--- If 0, then EEG sample rate is 128Hz.
--- If 1, then EEG sample rate is 256Hz.
\param eegRes       
--- If 0, then EEG resolution is 14bit.
--- If 1, then EEG resolution is 16bit.
\param memsRate     
--- If 0, then motion sample rate is OFF.
--- If 1, then motion sample rate is 32Hz.
--- If 2, then motion sample rate is 64Hz.
--- If 3, then motion sample rate is 128Hz.
\param memsRes      
--- If 0, then motion resolution is 12bit.
--- If 1, then motion resolution is 14bit.
--- If 2, then motion resolution is 16bit.

UInt32 mode = 0;
UInt32 eegRate = 0;
UInt32 eegRes = 0;
UInt32 memRate = 0;
UInt32 memRes = 0;

it mean you set your headset to EPOC mode. it dont have motion data.

**Comment by Yorkst** [comment]
We already used a different setup, but just for clarity

SetHeadsetSettings requires userID parameter explicitly. 

engine.SetHeadsetSettings(engine.EngineGetNumUser(),1,1,1,3,2)
fails with incorrect id exception

engine.SetHeadsetSettings(0,1,1,1,3,2)
fails with incorrect id exception

**Comment by Yorkst** [comment]
Did you mean a usb charger cable?

**Comment by Yorkst** [comment]
//The code used:
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Emotiv;

namespace RootCS
{
    class Program
    {
        static void Main(string[] args)
        {
            var engine = EmoEngine.Instance;
            engine.Connect();
            engine.SetHeadsetSettings(engine.EngineGetNumUser(), 1, 1, 1, 3, 2);
        }
    }
}

**Comment by hoangphamemotiv** [comment]
Hi Yorkst. 

You need connect your headset to PC via a cable line. then run this tool to set a setting to it. 

engine.EngineGetNumUser() return value of "number of users have been connected". 
so, i think you should push value 0 for 1 headset. 

Thank Yorkst.
