### ISSUE TITLE
EmoKey 3.3.3 some trigger conditions not working

### ISSUE THREAD

**Issue by t7ank** [Emotiv/community-sdk#114]
Hello

I'm trying to use emokey for research in next 1-2 weeks. But i have found buggy trigger section.

Mental commands does not work!
If i select "Drop", it is shown in EmoKey as "Drop" but i click on it again "Rotate Clockwise" is select. I think it is index problem, beacuse anything i select 6th item from current one gets selected.
Also if i select "Smirk left" then Emokey prints "m" if i select "Smirk Right" Emokey prints ",". I have binded those commands to keys [pgDown] and [pgUp], not "m" and ",".

Please fix it as soon as possible, because we are waitting with proceeding with research.

**Comment by t7ank** [comment]
@hoangphamemotiv when fix will be released? EmoKey is buggy (impossible to use) when using mental commands

**Comment by hoangphamemotiv** [comment]
hi @t7ank . 
we are checking this issue again. If it is ready a bug, we will fix it as soon as posible.

**Comment by hoangphamemotiv** [comment]
Hi @t7ank 

we fixed this error on last commit (4337084). pls check it. 

Thank @t7ank . ^^!
