### ISSUE TITLE
Python API on MAC

### ISSUE THREAD

**Issue by albertorepo** [Emotiv/community-sdk#115]
Hi folks,

I'm trying to use the python examples on my iMac. However, when I have to load the libraries, there is no option for Mac in the following code:
`try:
    if sys.platform.startswith('win32'):
        libEDK = cdll.LoadLibrary("../../bin/win32/edk.dll")
    elif sys.platform.startswith('linux'):
        srcDir = os.getcwd()
        if platform.machine().startswith('arm'):
            libPath = srcDir + "/../../bin/armhf/libedk.so"
        else:
            libPath = srcDir + "/../../bin/linux64/libedk.so"
        libEDK = CDLL(libPath)
    else:
        raise Exception('System not supported.')
except Exception as e:
    print 'Error: cannot load EDK lib:', e
    exit()`

I have tried to load both possibilities (dll and so) but none works.

Thank you.

**Comment by hoangphamemotiv** [comment]
hi @albertorepo . 
make sure that you used bit version of edk lib is same with Python bit version.

**Comment by albertorepo** [comment]
It seems that I'm using 64-bits python
`
print("%x" % sys.maxsize, sys.maxsize > 2**32)
`
`
('7fffffffffffffff', True)
`

And I am using the Current version of edk (lib/Mac/edk.framework/edk).

When I try to load the dll and the shared object, I get:

> Error: cannot load EDK lib: dlopen(../../bin/win64/edk.dll, 6): no suitable image found.  Did find:
	../../bin/win64/edk.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00


> Error: cannot load EDK lib: dlopen(../../bin/linux64/libedk.so, 6): no suitable image found.  Did find:
	../../bin/linux64/libedk.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

**Comment by nguoithichkhampha** [comment]
Hi albertorepo
Currently, example python doesn't support on Mac.
We are writing wrapper to full support python on multi platform.
But if you want to try python example on Mac, you can add this code:
if sys.platform.startswith('darwin'):
    	libEDK = cdll.LoadLibrary("../../lib/Mac/edk.framework/edk")
