### ISSUE TITLE
Develop a new app based on the signals

### ISSUE THREAD

**Issue by nezhakid** [Emotiv/community-sdk#116]
I am a college student in China,my team is going to develop an android app based on the emotion signals given out by Emotiv Insight as a project.We are wondering that if the signals of differnt emotions are given out by the device directly to the computer or they can only be identified in a certain app ?

**Comment by hoangphamemotiv** [comment]
Hi @nezhakid . 

EEG data is get from a Emotiv headset. then pass processing in edk lib to detect detections. so you can use Emotiv API to get those detecions and create your apps.
