### ISSUE TITLE
What need to buy?

### ISSUE THREAD

**Issue by nezhakid** [Emotiv/community-sdk#117]
I'm a college student in China ,and we have a team planning to develop a android app based on the data read from Emotiv Insight .In order to finish our project on time ,we need to start right away.Despite of the device and a USB receiver,what else should we buy ?We would really appreciate it if you guys would give us some advice asap!!

**Comment by nezhakid** [comment]
Is the charging cable included if we buy the emotiv insight device ??

**Comment by nguoithichkhampha** [comment]
yes, charging cable included in box insight device. If you develop a android app , you just need a android device support bluetooth 4.0 run on OS 4.4.4 or above and Insight headset, no need USB receiver
