### ISSUE TITLE
issue with Profile loading when using EmoEngine

### ISSUE THREAD

**Issue by landret** [Emotiv/community-sdk#118]
Hi,

I have a problem occuring when using EmotivCloudClient.INSTANCE.EC_LoadUserProfile(). 
When connecting to EmoEngine, profile loading fails when I try to load a profile from the Cloud in which training has been done. The loading works only when connecting to Control Panel or Emo Composer.

Could you help me with that?
Thanks,
Christophe

**Comment by hoangphamemotiv** [comment]
Hi @landret 

Did you upload your profile to Cloud before loading it?
And before call a Loading or Saving a profile from/to Cloud , you need call: EmotivCloudClient.EC_GetProfileId(userCloudID, profileName)
we have a Cloud Profile here: https://github.com/Emotiv/community-sdk/blob/master/examples/C%23/SavingAndLoadingProfileCloud/Program.cs

Thanks. ^^!
