### ISSUE TITLE
GeNextEvent always returns EDK_NO_EVENT

### ISSUE THREAD

**Issue by albertorepo** [Emotiv/community-sdk#119]
Greetings, 

I recently acquired a Emotiv Insight. However, I did not buy the Emotiv Dongle. 

Right now I am using it with my iMac (version El Capitan). Since my iMac does not have Bluetooth 4.0 (BTLE) I had to connect a dongle. I am able to use the headset with the Emotiv Control Panel (both desktop and web versions).

The problem comes when I try to run the Java or Python examples included in the Community SDK. Everything goes well, nothing crashes. However, I am not able to detect anything because of this line of code:

state = Edk.INSTANCE.IEE_EngineGetNextEvent(eEvent);

or Python equivalent:

state = libEDK.IEE_EngineGetNextEvent(eEvent)

The variable state always take value 0x0600 which means, following the documentation and the SDK implementation, EDK_NO_EVENT.

If I use Emocomposer, it works well and receive the states in a correct way.

So I would want to overcome this problems and be able to code my own applications using Java (or another language like Python).

Best,

Alberto.

**Comment by zrz93** [comment]
I'm having the same problem for both python and java. Is there any possible solution?

**Comment by twaligora** [comment]
What is the solution for this problem? I see only that the problem was closed? Is there any fix for this provided? I have the same problem with C++ api and one of the example: FacialExpression.
Example is started, user is added but then no EVENT is triggered at all.

**Comment by mneckoee** [comment]
I have the same problem in FFTexample for Android. I test it on a Redmi note 4 android version 6.
edkJava.IEE_EngineGetNextEvent(handleEvent) always returns EDK_NO_EVENT. what should I do?
