### ISSUE TITLE
I have bought neuroMousecontrol and it is not working with latest Xavier Control panel (3.3.3)

### ISSUE THREAD

**Issue by t7ank** [Emotiv/community-sdk#120]
I have bought neuroMouseControl program from your Emotiv Store, but it is not working. Can you please contact third-party developers that you have changed Control panel connectivity with other programs?

**Comment by hoangphamemotiv** [comment]
Hi @t7ank.
Please send us an email to hello@emotiv.com for further assistance.

Thanks. ^^!
