### ISSUE TITLE
IS_MentalCommandGetCurrentAction is always returing 1.0 and IS_MentalCommandGetCurrentActionPower is always returning 0

### ISSUE THREAD

**Issue by albertorepo** [Emotiv/community-sdk#123]
Hi folks,

I have been having problems with the demos of the Emotiv SDK.

When I connect my Insight to the Controlpanel and I run the EmoStateLogger example for Java under Windows 10, the above two methods are not working properly.

However, if I do the same with the Composer, it works perfectly.

Moreover, the facial expression detection is working correctly with both the Insight and Composer.

Am I doing anything wrong?

**Comment by hoangphamemotiv** [comment]
hi @albertorepo 
Could you show me more detail on your question? 
You mean, you connected CP to EmostateLogger? but, what issue did you get that you said it dont work correctly?
