### ISSUE TITLE
[Java] When training starts, engine never returns the IEE_MentalCommandTrainingStarted code 

### ISSUE THREAD

**Issue by albertorepo** [Emotiv/community-sdk#124]
Hi,

I'm trying to write a Java application to train the Insight. I've just translate the C++ example and everything goes well until I call:
`Edk.INSTANCE.IEE_MentalCommandSetTrainingAction(userId.getValue(), EmoState.IEE_MentalCommandAction_t.MC_NEUTRAL.ToInt();
Edk.INSTANCE.IEE_MentalCommandSetTrainingControl(userId.getValue(), Edk.IEE_MentalCommandTrainingControl_t.MC_START.getType();`

Both lines return EDK_OK code, but the engine never notify the IEE_MentalCommandTrainingStarted code.

**Comment by hoangphamemotiv** [comment]
Hi @albertorepo . 

Did you check IEE_MentalCommandTrainingStarted in IEE_MentalCommandEvent event?
You can look it at: 
https://github.com/Emotiv/community-sdk/blob/master/examples/C%2B%2B/MentalCommandWithCloudProfile/MentalCommandWithCloudProfile.cpp

line 316.

**Comment by albertorepo** [comment]
Yes I did, I pretty much "translate" that example.

`int eventType = Edk.INSTANCE.IEE_EmoEngineEventGetType(eEvent);
if (eventType == Edk.IEE_Event_t.IEE_UserAdded.ToInt())
	System.out.println("New user " + engineUserID.getValue() + " added");

else if (eventType == Edk.IEE_Event_t.IEE_UserRemoved.ToInt())
	System.out.println("User " + engineUserID.getValue() + " has been removed.");

else if (eventType == Edk.IEE_Event_t.IEE_EmoStateUpdated.ToInt())
	Edk.INSTANCE.IEE_EmoEngineEventGetEmoState(eEvent, eState);

else if (eventType == Edk.IEE_Event_t.IEE_MentalCommandEvent.ToInt())
	handleMentalCommandEvent(engineUserID, eEvent);`

**Comment by tungntEmotiv** [comment]
Hi @albertorepo 
Please make sure that the next event gotten in each loop (Eg: int state = IEE_EngineGetNextEvent(eEvent);). Could you help to print out the eventType received inside handleMentalCommandEvent() function and show the results from console when run training_start command?

Thank you

**Comment by albertorepo** [comment]
Hi @tungntEmotiv
Here is the console output:
```
Logged in as bertocasta
=============================================================
Please do follow steps:
A. Press 1 to Active training session.
B. Press 2 to Start training NEUTRAL. When completed, press 3.
C. Press 3 to Start training RIGHT. When completed, press 4
D. Press 4 to Start training LEFT.
E. Press 5 to Set ActivationLevel.
=============================================================
Otherwise, press key below for more:

Press 6 to Read ActivationLevel.
Press 7 to Get OveralSkillRating.
Press 8 to Save Profile Data to the cloud.
Press 9 to Load Profile Data from cloud.

Press 0 for help.
Press r to start live classification.
Press q to quit.
=============================================================
New user 0 added
EmoState has been updated
EmoState has been updated
1

Setting MentalCommand active actions (MC_LEFT | MC_RIGHT) for user 0
2
Starting training NEUTRAL!
User 0 has been removed.
New user 0 added
EmoState has been updated
EmoState has been updated
```

As you can see, the application neve receives a IEE_MentalCommandEvent.

Thanks for your help, btw.

**Comment by hoangphamemotiv** [comment]
i look at : "User 0 has been removed."
uhm. have issue with your dongle or BTLE on connecting to machine? maybe we shouldnt remove dongle connection while training session. ^^!

**Comment by albertorepo** [comment]
I haven't experimented any issue while connecting, but sometimes the connection goes down and returns in a second. Could be that an issue during training?

**Comment by hoangphamemotiv** [comment]
Can you send me your example? i will help to check it. 
if you agree, you can send me it at here or via my email.

**Comment by albertorepo** [comment]
Sure, there it goes.

**Comment by tungntEmotiv** [comment]
Hi @albertorepo 

sorry for the late reply :(. Yes, you can send us to tungnt@emotiv.vn or hoangpham@emotiv.vn.

**Comment by albertorepo** [comment]
Hi @tungntEmotiv 

No problem :). I've already send it to you both.

**Comment by hoangphamemotiv** [comment]
Hi @albertorepo . 

i fixed some errors on your example and sent you it via email. pls check it. thanks. ^^!
