### ISSUE TITLE
Question : Action power during training 

### ISSUE THREAD

**Issue by NTTLuke** [Emotiv/community-sdk#126]
Hi , 
I would like to say if there is a way to retrieve the “action power” during the mental command training (MentalCommandTrainingStartedEventEventHandler) as Xavier Control Panel has been doing during the training actions.
I’m working with c# language.

Thanks in advance guys , you are "super" !

**Comment by hoangphamemotiv** [comment]
Hi @NTTLuke . 
In Control Panel, i think you ticked "Animate model according to training action", it is a face action to help you more easier on training.
