### ISSUE TITLE
Average Band Power Issue

### ISSUE THREAD

**Issue by LadyTech** [Emotiv/community-sdk#127]
Hello all, 

I am currently using both the Insight and the Epoc+. I can get both devices to sync to my computer. When running the Average Band Power program in C#, the program does not consistently give me the average band power. I am currently unable to get the band power despite using an unmodified program. What could be the problem here?

**Comment by mdtdev** [comment]
What do you mean by _consistently_? The EPOC's data are fragile enough that rapid changes in band power happen often.

**Comment by LadyTech** [comment]
Thank you for your quick response. I think I have found one of my problems. When the computer's bluetooth is on while the dongle is in, the result is no signal. By turning off my computer's bluetooth I am able to get the Epoc+ working again. However, the Insight does not work as seamlessly. 

Consistently, meaning that the code works one time and not the next. If you go into the debugger, sometimes the band pass values are 0, other times they are actual values. I still have an issue with the Insight and its connection but this solves some of the problem.
