### ISSUE TITLE
java, netbeans, edk.dll not found

### ISSUE THREAD

**Issue by landret** [Emotiv/community-sdk#129]
Hi,

I am using java with Netbeans on a 64bit PC.
For 64bit application, I use a 64bit JRE with edk.dll(64bit) and jna.jar.
For 32bit application, I use a 32bit JRE with edk.dll(32bit) and the same jna.jar.

1st question: For 32bit application, Netbeans cannot find the edk.dll(32bit) even if it is put in System32. Which means I cannot compile the code. Why?

2nd question: For 64bit application, when I run the program, Netbeans can find the edk.dll(64bit) only if it is put in System32 folder.
When I put the dll in the root of my Netbeans project folder or in the jdk..\jre\lib\ext\ folder, Netbeans can’t find the dll while it should find it.
Why?

Thanks for your help
Regards,
Christophe

**Comment by hoangphamemotiv** [comment]
Hi @landret 
as we talked at Emotiv forum, 
"Try to install “Redistributable Packages” follow 32b or 64b edk.dll that you want to use.
https://www.microsoft.com/en-us/download/details.aspx?id=40784
or the easiest way, you find and push msvcp120.dll and msvcr120.dll is same folder with EDk lib"

did you try it? any lucky?
