### ISSUE TITLE
Assertion failed: (trainingTimeInSec > 0.0)

### ISSUE THREAD

**Issue by stevemulligan** [Emotiv/community-sdk#130]
I'm trying to run the FacialExpression demo in the SDK (MacOS) and when I try to train one of the facial expressions with Xavier Composer I get this error:

Assertion failed: (trainingTimeInSec > 0.0), function IEE_FacialExpressionGetTrainingTime, file ../../core/edkDll/Iedk.cpp, line 1117.

The application halts in EngineWidget.mm on line 171:

    IEE_FacialExpressionGetTrainingTime(userID, &value);

Also the Engine Log window in the Composer is very small. It would be nice if there was a way to make it bigger or copy the data out of there.

**Comment by hoangphamemotiv** [comment]
Hi @stevemulligan 
A training session dont allow from Xavier Composer. pls try with a real headset. 
Thanks. ^^!
