### ISSUE TITLE
Assertion failed: (false), function expressionToClass

### ISSUE THREAD

**Issue by stevemulligan** [Emotiv/community-sdk#131]
I'm using iOS on the device (not simulator) trying to train WINK_LEFT.  The headset is connected, then I call like this:

int res = IEE_FacialExpressionSetTrainingAction(0,  FE_WINK_LEFT);

And I get this error:

Assertion failed: (false), function expressionToClass, file /Volumes/DATA/Git/bedk_windows/src/core/Detection/expressiv/NTExpressiv/NTExpressivDetectionManager.cpp, line 764.

When I run the FacialExpressions demo for MacOS (not the phone) it works fine. Only iOS is throwing this error.

**Comment by hoangphamemotiv** [comment]
Hi @stevemulligan . 
We dont need to train Wink and Blink detections. ^^!. 
We support to train: Raise Brow, Furrow Brow, smile, clench, laugh, smirk. 

Thanks. ^^!
