### ISSUE TITLE
HeadsetInformationLogger returns no data

### ISSUE THREAD

**Issue by twaligora** [Emotiv/community-sdk#132]
Hi,

I am running HeadsetInformationLogger example on RPI3 and Emotiv Insight headset. 
Device is successfully paired and connected over bluetooth:

Device ED:9C:26:5C:55:24
        Name: Insight (59684227)
        Alias: Insight (59684227)
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: yes
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (81072f40-9f3d-11e3-a9dc-0002a5d5c51b)

test.csv file is containing only one row:
Time, Wireless Strength, Battery Level, AF3, T7, Pz, T8, AF4
0,2,-1,0, 0, 0, 0, 0, 

By adding some logs to the code we can see that engine still returns EDK_NO_EVENT while calling IEE_EngineGetNextEvent method.

The same situation is present in the other examples. The only one example which is working fine is the GyroData. 

Can you please analyze what might be the problem here. I don't think that this might be the problem with BT since Gyro is working fine.

Thanks for your help
Best regards,
Tomasz Waligora

**Comment by hoangphamemotiv** [comment]
Hi @twaligora .

Could you tell me which version of EDK library you are using? and on which platform? Windows, Mac OS....
EDK_NO_EVENT even happen when EDK cannot get any data from your headset.

**Comment by twaligora** [comment]
Hi,

The EDK version is libedk.so.3.3.3 for ARM.  The platform is Raspberry Pi 3, Raspbian GNU/Linux 8 (jessie) with Linux raspi 4.4.21-v7+ kernel.

The strange thing is that gyro example is the only one which works fine. For other there is EDK_NO_EVENT.

**Comment by twaligora** [comment]
Hi,

Any update on this issue?

**Comment by havietnam** [comment]
Hi,
Can you use BTLE connection?
Bug will be fix in next release.

**Comment by twaligora** [comment]
Hi,
What you mean by using the BTLE connection?
We are using the bluetooth. 
Can you please tell why there is no problem with gyro but with the other like facialExpresion and mentalCommand?
This is some known bug?
When is planned this next release?

Please provide some more details about this issue.
