### ISSUE TITLE
Ubuntu 14.04, bluetooth not connecting

### ISSUE THREAD

**Issue by Nikeshbajaj** [Emotiv/community-sdk#133]
As described  l[ink](https://github.com/Emotiv/community-sdk/blob/master/doc/Connecting%20on%20Ubuntu%20and%20Debian.md)  I setup and configured.
At Configure stage : Configure

Add EnableGatt = true to file /etc/bluetooth/main.conf
Backup then edit file /etc/dbus-1/system.d/bluetooth.conf, remove 1 from all the lines, such as:
`<allow send_interface="org.bluez.Agent1"/> to <allow send_interface="org.bluez.Agent"/>`
`<allow send_interface="org.bluez.GattDescriptor1"/> to <allow send_interface="org.bluez.GattDescriptor"/>`
This line in not in my bluetooth.conf file  `<allow send_interface="org.bluez.GattDescriptor1"/>`

After 
sudo /etc/init.d/bluetooth stop
sudo ./src/bluetoothd -n -E --plugin=audio
-------------------  I got following displayed on terminal---------------
bluetoothd[9941]: Bluetooth daemon 5.37
bluetoothd[9941]: Starting SDP server
bluetoothd[9941]: Ignoring (cli) hostname
bluetoothd[9941]: Ignoring (cli) wiimote
bluetoothd[9941]: Ignoring (cli) autopair
bluetoothd[9941]: Ignoring (cli) policy
bluetoothd[9941]: Ignoring (cli) a2dp
bluetoothd[9941]: Ignoring (cli) avrcp
bluetoothd[9941]: Ignoring (cli) network
bluetoothd[9941]: Ignoring (cli) input
bluetoothd[9941]: Ignoring (cli) hog
bluetoothd[9941]: Ignoring (cli) gap
bluetoothd[9941]: Ignoring (cli) scanparam
bluetoothd[9941]: Ignoring (cli) deviceinfo
bluetoothd[9941]: Bluetooth management interface 1.10 initialized

but in other terminal
bluetoothct1: command not found

Can you please help , what is not configured properly?

**Comment by havietnam** [comment]
You must install bluez package:
`sudo apt-get install bluez`

Right command is **bluetoothctl**, not bluetoothct**1**
