### ISSUE TITLE
How to find Excitement 

### ISSUE THREAD

**Issue by nadunindunil** [Emotiv/community-sdk#134]
Hi,
I am working on a project to measure the excitement of a person. Since the performance metric in SDK is deprecated we have to use the raw values can someone suggest me a solution to measure the excitement?

**Comment by hoangphamemotiv** [comment]
Hi @nadunindunil 
You can find it here: https://github.com/Emotiv/advanced-sdk/tree/master/examples/C%2B%2B/PerformanceMetricsDemo
make sure that you have a Emotiv library allow you access to Performance Metrics. 

Thanks. ^^!

**Comment by nadunindunil** [comment]
@hoangphamemotiv thank you for the reply.
My emotiv insight firmware is not supporting to premium SDK 3.3.3, that's why I asked the question how to generate excitement from the raw values.

**Comment by hoangphamemotiv** [comment]
We almost release v3.4 Advanced SDK, it allow you access to EEG and Performance Metrics data. pls get information from Emotiv website. 

Thanks. ^^!

**Comment by evanfantr** [comment]
It has been a year and still the Performance Metric project is not working (because of serious licensing issues)
