### ISSUE TITLE
Is artefact removal necessary?

### ISSUE THREAD

**Issue by minegu** [Emotiv/community-sdk#136]
I am using Average Band Powers that comes with eMotiv Community SDK, and get Theta, Alpha, Low Beta, High Beta values.
Do I have to do any artefact removal after getting this data from channels?

Do I have to do any median, mean subtraction, or use it as it is? And what is the maximum and minimum values that I should get in each band?

Best regards,

**Comment by notnot** [comment]
Hello minegu, i can't answer your question, but i am curious about the data you are getting. I am also working with the band power, and i get very low values when i don't move my face, and very high values when i move my face. How can we detect brain activity when the device seems to basically be measuring muscle contractions? What is your experience?
