### ISSUE TITLE
HeadsetInformationLogger returns no data (more information needed)

### ISSUE THREAD

**Issue by twaligora** [Emotiv/community-sdk#138]
Hi,

This is a follow up for bug:
https://github.com/Emotiv/community-sdk/issues/132

Which was already closed with no details.

We need following answers:

What you mean by using the BTLE connection?
We are using the bluetooth.
Can you please tell why there is no problem with gyro but with the other like facialExpresion and mentalCommand?
This is some known bug?
When is planned this next release?

Please provide some more details about this issue.

**Comment by havietnam** [comment]
Hi,
Can you execute bluetoothctl and run some commands at prompt:
`list-attributes [dev]`
`select-attribute <attribute>`
`notify on`
After run `notify on`, You will see data from headset. If not, there is problem with BTLE connection.

**Comment by twaligora** [comment]
Hi,

After connecting to the emotive device, following attributes are listed:
`list-attributes ED:9C:26:5C:55:24`

`NEW] Primary Service
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0001
        Generic Access Profile
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0001/char0002
        Device Name
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0001/char0004
        Appearance
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0001/char0006
        Peripheral Preferred Connection Parameters
[NEW] Primary Service
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0008
        Generic Attribute Profile
[NEW] Primary Service
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009
        Vendor specific
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a
        Vendor specific
[NEW] Descriptor
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a/desc000c
        Client Characteristic Configuration
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000d
        Vendor specific
[NEW] Descriptor
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000d/desc000f
        Client Characteristic Configuration
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char0010
        Vendor specific
[NEW] Primary Service
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0012
        Battery Service
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0012/char0013
        Battery Level
[NEW] Descriptor
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0012/char0013/desc0015
        Client Characteristic Configuration
[NEW] Primary Service
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0016
        Device Information
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0016/char0017
        Manufacturer Name String
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0016/char0019
        Serial Number String
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0016/char001b
        Hardware Revision String
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0016/char001d
        Firmware Revision String
[NEW] Characteristic
        /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0016/char001f
        Software Revision String`

I select the following one:
`select-attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a`

After `notify on` I am able to see data over BTLE:
`...
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x27
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x97
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x48
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0xd7
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0xe1
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0xa9
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0xc7
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x0d
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x0d
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x5b
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x49
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0xc9
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x00
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x00
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x49
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x02
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x0c
[CHG] Attribute /org/bluez/hci0/dev_ED_9C_26_5C_55_24/service0009/char000a Value: 0x7f
...`

But after running HEadsetInformationLogger, still I cannot see any entries in test.csv file.
I will remind you that Gyro example is working fine so I don't suspect the problem with bluetooth.

What else we can check?

**Comment by havietnam** [comment]
Fixed with 503c3f6

**Comment by twaligora** [comment]
Hi,

With provided fix the gyro which is actual working is not working anymore...
Still "Cannot acquire data" is printed in the console.

**Comment by twaligora** [comment]
Hi,

It look that is working fine with the new version of the library. 
Thanks a lot for the help!
