### ISSUE TITLE
"Cannot connect to Emotiv Cloud" when executing SavingAndLoadingProfileCloud.py

### ISSUE THREAD

**Issue by sean-tll** [Emotiv/community-sdk#139]
Hi,

We are trying to development Python programs to using Emotiv Epoc to control HROS1 Humanoid robot (Raspberry Pi 3) using facial expression. However, when we try to load the profile data using SavingAndLoadingProfileCloud.py it breaks out with the error "Cannot connect to Emotiv Cloud". We have tried this program on different machines, not only on the Raspberry Pi 3, it returns this error every time. We can access to Emotiv Cloud using web browser so it should not be the problem of our network setting. Any ideas? Thanks in advance!

**Comment by havietnam** [comment]
Please update new edk. We fixed.
