### ISSUE TITLE
Epoc+ Android

### ISSUE THREAD

**Issue by lutfor3737** [Emotiv/community-sdk#141]
I have epoc+ device. Is the following example is for only insight? 
https://github.com/Emotiv/community-sdk/tree/master/examples/Android/motiondatalogger)

**Comment by nguoithichkhampha** [comment]
Hi @lutfor3737 , default example connect with Insight headset. If you want to connect with epoc+ headset you can change code in MainActivity.java:
/*Connect device with Insight headset*/
				int number = IEdk.IEE_GetInsightDeviceCount();
				if(number != 0) {
					if(!lock){
						lock = true;
						IEdk.IEE_ConnectInsightDevice(0);
					}
				}
				/**************************************/
				/*Connect device with EPOC Plus headset*/
//				int number = IEdk.IEE_GetEpocPlusDeviceCount();
//				if(number != 0) {
//					if(!lock){
//						lock = true;
//						IEdk.IEE_ConnectEpocPlusDevice(0,false);
//					}
//				}
				/**************************************/

**Comment by lutfor3737** [comment]
Thanks. Just noticed that.I am getting "INSTALL_FAILED_NO_MATCHING_ABIS" error while running this one in the Android emulator in the Android studio. Am I missing something?

**Comment by nguoithichkhampha** [comment]
You must be run on real device to connect headset.

**Comment by lutfor3737** [comment]
Great. thanks. It is running.
