### ISSUE TITLE
Problems connection with emoengine - don't recognize mental commands

### ISSUE THREAD

**Issue by ppeter1418** [Emotiv/community-sdk#143]
I have a very serious problem that. The program that I wrote based on examples but does not work as it should. It does not work with the helmet of communication. It can not recognize mental commands on the basis of currently loaded user profile. But it recognize facial expressions. Attached is a program I wrote. It is possible that something was wrong. Very please to explain step by step how I solve the problem or ready-made code that connects to the helium. My application for 2 months is ready, but I miss the last item. Connections with a emoengine.
[MY_emostate_Logger05.09.txt](https://github.com/Emotiv/community-sdk/files/612064/MY_emostate_Logger05.09.txt)

**Comment by hoangphamemotiv** [comment]
Hi @ppeter1418
To get Mental Commands actions and power, we should load a profile for it first and training your actions. then it will send power via EmostateUpdate event
You can see "How to save/load a profile" here: https://github.com/Emotiv/community-sdk/blob/master/examples/Python/SavingAndLoadingProfileCloud.py
Login with your EmotivID -> Saving profie -> Loading that profile -> Training Mental Command -> Using EmostateUpdate event to get Actions and Power of MentalCommand

Thanks. ^^!

**Comment by ppeter1418** [comment]
Hi, It still doesn't work. I think it's problem with your server, because you can't help me from 6 months. It's embarrassing.
