### ISSUE TITLE
emotiv-matlab connection

### ISSUE THREAD

**Issue by masoudmaleki** [Emotiv/community-sdk#144]
hello
i can not connect emotiv to matlab. when i run the eeglogger ihave this error: 
(https://cloud.githubusercontent.com/assets/24210292/20650791/c7ce8b48-b4df-11e6-8d8a-f51d74a1ed5d.jpg)

i used these:
Emotiv SDK Premium Edition v3.3.3
Emotiv Xavier ControlPanel v3.1.19
Emotiv Xavier TestBench v3.1.19
Emotiv EPOC Control Panel v2.0.0.21

please help me
thank you

**Comment by hoangphamemotiv** [comment]
Hi @masoudmaleki 
Can you try to change line 96 from: AllOK = calllib('edk','IEE_EngineConnect', default)
to AllOK = calllib('edk','IEE_EngineConnect', 'Emotiv Systems-5')

and i saw : IEE_GetEdittionName was not found in the lib. so, pls remove it in your example

**Comment by masoudmaleki** [comment]
hi @hoangphamemotiv  
i tried it but now i have this :
![image](https://cloud.githubusercontent.com/assets/24210292/20830300/94b3c154-b888-11e6-809f-af2738caf83b.png)
also you said that i should remove IEE_GetEdittionName. it is not in the eegloger.m
how can i remove it?
thank you so much
