### ISSUE TITLE
WHAT IS EC ERROR CODE 258

### ISSUE THREAD

**Issue by shawnsexton** [Emotiv/community-sdk#145]
I SAVE A PROFILE OK WITH PYTHON EXAMPLE BUT LOADING GIVES CODE 258

**Comment by duytan90** [comment]
@shawnsexton 
258 DEC is 102 HEX, also check this file for the error code
https://github.com/Emotiv/community-sdk/blob/164dac1f3dee195d2fcbaa9dfc1b8daa6b3d3d57/include/IedkErrorCode.h#L27

**Comment by shawnsexton** [comment]
thanks i overlooked the hex conversion. i need a better explanation of this error andd what to do about it.

**Comment by shawnsexton** [comment]
My question was not fully answered. 

Shawn Sexton
678-296-0525
sexton@alumni.nd.edu
