### ISSUE TITLE
[MacOS Compatibility]: Connection to BTLE does not work

### ISSUE THREAD

**Issue by olivierpichon** [Emotiv/community-sdk#146]
Hi guys,

I am using an Emotiv Insight without dongle on a Mac which is BTLE compatible.

EmotivXavierControlPanel works well, it connects to the device, we can also see it in the list of "associated devices":

<img width="421" alt="screen shot 2016-11-30 at 8 14 09 pm" src="https://cloud.githubusercontent.com/assets/3260198/20748364/9ddc4472-b739-11e6-9948-c0b364384d9e.png">

However, the `IEE_EngineConnect()` of the API does not work. It does not connect to the device, we can't see it in the list of associated devices. As a result, `GeNextEvent` always returns EDK_NO_EVENT as pointed out in this issue which was closed without providing any solution:
https://github.com/Emotiv/community-sdk/issues/119

Using the composer and `IEE_EngineRemoteConnect` just works fine. Also, it looks like plugging the device to the USB allows to connect to it properly. (At least `GeNextEvent()` returns `EDK_OK` in this scenario).

Would it be possible to modify the SDK so that whatever connection mechanism used in the control panel is also used in the SDK?

Lots of developers are using a Mac device. @nguoithichkhampha fixed the compilation process which was not even working in https://github.com/Emotiv/community-sdk/issues/122. 

Now, out of the box, this SDK does not work with any Apple BTLE embedded devices. That would be amazing to fix this before to call this SDK "Mac OS compatible".

Thanks a lot for your help guys!

**Comment by nguoithichkhampha** [comment]
@olivierpichon , C++ example not support connect BLE  on Mac yet. You can try ObjectiveC example to see how do work with BLE.

**Comment by mneckoee** [comment]
I have the same problem in FFTexample for Android. I test it on a Redmi note 4 android version 6. 
edkJava.IEE_EngineGetNextEvent(handleEvent) always returns EDK_NO_EVENT. what should I do?
