### ISSUE TITLE
iOS EXC_BAD_ACCESS after a few seconds

### ISSUE THREAD

**Issue by codingyourlife** [Emotiv/community-sdk#147]
I have the new iPod touch (Model MKH22FD/A) and when I run the github iOS MotionDataLogger example I run into this EXC_BAD_ACCESS error
![screen shot 2016-12-04 at 16 05 54](https://cloud.githubusercontent.com/assets/10122382/20867060/23dad8e0-ba3c-11e6-804d-80e52e545587.png)

**Comment by nguoithichkhampha** [comment]
@codingyourlife , thanks for your feedback. We will check it again.

**Comment by codingyourlife** [comment]
9.0.1
