### ISSUE TITLE
Raw EEG channel data in android

### ISSUE THREAD

**Issue by lutfor3737** [Emotiv/community-sdk#150]
I need all 14 channels EEG raw data for my research in Android.  Is it possible ? I am running motionLogger example(https://github.com/Emotiv/community-sdk/tree/master/examples/Android/motiondatalogger) for Android. Something like 
double[] eeg_data =	IEdk.IEE_MotionDataGet(IEdk.IEE_DataChannel_t.IED_AF3);

is not working.

**Comment by nguoithichkhampha** [comment]
@lutfor3737 , You can not get EEG raw data with community-sdk.

**Comment by lutfor3737** [comment]
How can I get EEG raw data in android? I need it for my research.

**Comment by hoangphamemotiv** [comment]
Hi @lutfor3737 
Android SDK with EEG data is in our planning. but, we have some issues on it at the moment. so, we will release SDK 3.4 with EEG API for Windows, MAC and Linux first then Android, IOS. 

Thanks. ^^!
