### ISSUE TITLE
emotiv-matlab connection 2

### ISSUE THREAD

**Issue by masoudmaleki** [Emotiv/community-sdk#151]
hi 
i tried to connect emotiv and matlab. but i have this error:
![image](https://cloud.githubusercontent.com/assets/24210292/20882571/5464429a-baea-11e6-8157-77decfdaed91.png)

please help me
thank you so much
@hoangphamemotiv

**Comment by masoudmaleki** [comment]
@hoangphamemotiv  @nguoithichkhampha 
I would be very grateful if you could solve my problem that i have it from 4 month ago. i can not progress in my project. i am waiting for you. ngoc in emotiv group also know my problem.
thank you so much

**Comment by soultranscender** [comment]
Hi @masoudmaleki 
You can use the Emotiv's Research SDK 2.0.0.20 with OpenVibe Acquisition server to write to a file in GDF format. The GDF file can be easily converted to matlab using th Biosig toolbox in matlab. 
Well I have a question at this stage. As the signals in Matlab look amplified than they should actually be, I am certain that EPOC+ is using some different kind of amplifier than the EPOC EEG headset. Can you suggest what can I try in Matlab to solve this. If you want to EEG data you can contact me on jguruprasad@riteh.hr
