### ISSUE TITLE
It still doesn't work. Problems connection with emoengine - don't recognize mental commands

### ISSUE THREAD

**Issue by ppeter1418** [Emotiv/community-sdk#152]
Hi, It still doesn't work. I think it's problem with your server, because you can't help me from 6 months. It's embarrassing. Number of last issue #143

**Comment by hoangphamemotiv** [comment]
Hi @ppeter1418 i saw something wrong in your examples. i am rewrite it for you. wait for me

**Comment by ppeter1418** [comment]
Hi,
 
I would be very grateful if you could solve my problem. I look forward to your email.
 
Peter
 
W dniu 2016-12-09 11:37:08 użytkownik Pham Hoang <notifications@github.com> napisał:
Hi @ppeter1418 i saw something wrong in your examples. i am rewrite it for you. wait for me

**Comment by hoangphamemotiv** [comment]
Hi ppeter1418
i rewrote Mental Command with Cloud Profile attached it here. pls get it then send me feedback when you get a issue on it. i hope it can help your work. 

thanks. ^^!


[MentalCommandDemo.zip](https://github.com/Emotiv/community-sdk/files/645152/MentalCommandDemo.zip)
![mentalcommandwithprofilecloud](https://cloud.githubusercontent.com/assets/13273932/21088760/d2cda386-c064-11e6-9903-66cffaf7aad5.png)

**Comment by ppeter1418** [comment]
Hi,
 
Thank you very much for your help. When I test the operation of the program, I will let you know.
 
Regards,
 
Peter
 
W dniu 2016-12-12 06:18:11 użytkownik Pham Hoang <notifications@github.com> napisał:
Hi ppeter1418
i rewrote Mental Command with Cloud Profile attached it here. pls get it then send me feedback when you get a issue on it. i hope it can help your work.
thanks. ^^!
MentalCommandDemo.zip

**Comment by ppeter1418** [comment]
Hi,
 
Thanks a lot! It works. Great! But I have one big problem. I think I can save profile but I can't load profile. When I use option: load_profile I get same errors. When I gave variable getNumberProfile=1 load profile failed. I don't know what is wrong. I am asking you for help. In attachement is error.
 
Regards,
 
Peter
 
W dniu 2016-12-12 06:18:11 użytkownik Pham Hoang <notifications@github.com> napisał:
Hi ppeter1418
i rewrote Mental Command with Cloud Profile attached it here. pls get it then send me feedback when you get a issue on it. i hope it can help your work.
thanks. ^^!
MentalCommandDemo.zip

**Comment by hoangphamemotiv** [comment]
Hi
i tested load_profile. it works. could you tell me which steps you get the error. and what value did that API return?
remember that, you should save profile first then load a same name with that profile saved. 

Thanks. ^^!

**Comment by hoangphamemotiv** [comment]
Hi. 
my wrong. ^^!. i missed getNumberProfile = libEDK.EC_GetAllProfileName(userCloudID.value) . it should be called just one time before Load/Save a profile. this API to get all profile infos from Cloud. 

pls check it again. thank you. ^^!

[MentalCommandDemo.zip](https://github.com/Emotiv/community-sdk/files/647805/MentalCommandDemo.zip)

**Comment by ppeter1418** [comment]
Thanks a lot! When I will test it I will send you answer. I ran it and loaded some profile and it works. But when I loaded unexisting profile it also display: loading finished. I couldn't check that is this loaded profile works.
 
Regards,
 
Peter
 
W dniu 2016-12-13 03:21:52 użytkownik Pham Hoang <notifications@github.com> napisał:
Hi.
my wrong. ^^!. i missed getNumberProfile = libEDK.EC_GetAllProfileName(userCloudID.value) . it should be called just one time before Load/Save a profile. this API to get all profile infos from Cloud.
pls check it again. thank you. ^^!
MentalCommandDemo.zip

**Comment by hoangphamemotiv** [comment]
Hi 
Remember that you should save your profile to Cloud again when you finished training session. 
and there are 2 APIs are useful for you to check Skill Rating: 
IEE_MentalCommandGetActionSkillRating
IEE_MentalCommandGetOverallSkillRating
so, you can training many times to make skill rating grow. ^^!

Thanks. ^^!

**Comment by ppeter1418** [comment]
Hi, I tested this script from you and now I have one big problem. It doesn't save profile by name but only save. When I load profile I can load only one profile (last saved profile) and it doesn"t matter which name I choose. I can choose unexisting profile name and it always load last profile. Please help. Thanks in advance.
 
Regards,
 
Peter
 
W dniu 2016-12-15 03:12:29 użytkownik Pham Hoang <notifications@github.com> napisał:
Closed #152.
