### ISSUE TITLE
Several "errors" (are they errors or I missed something?) with Python, Java, C++ (VS 2015)

### ISSUE THREAD

**Issue by EDario333** [Emotiv/community-sdk#156]
[EMOTIV Premium SDK_.pdf](https://github.com/Emotiv/community-sdk/files/691782/EMOTIV.Premium.SDK_.pdf)
Also I ran the project with VS 2015, these are the screen captures and the results are the same: none output in emostate_logger.csv
[01-VS 2015.pdf](https://github.com/Emotiv/community-sdk/files/691787/01-VS.2015.pdf)
[02-simulating events.pdf](https://github.com/Emotiv/community-sdk/files/691788/02-simulating.events.pdf)
[03-simulating events.pdf](https://github.com/Emotiv/community-sdk/files/691789/03-simulating.events.pdf)

**Comment by hoangphamemotiv** [comment]
Thank @EDario333 . we will check this issue again and feedback you soon. ^^!

**Comment by nguyenvinhbinhktdo** [comment]
Hi EDario333,
To answer your question I would like to know which version your Emotiv Xavier composer  is?

**Comment by EDario333** [comment]
@nguyenvinhbinhktdo Emotiv Xavier Composer version 3.3.3 build 457e842

**Comment by nguyenvinhbinhktdo** [comment]
In fact, I have checked Emotiv Xavier Composer version 3.3.3, the issue you give is right, please wait for the new released version soon.

**Comment by EDario333** [comment]
Thank you so much. I was starting to freaking out me, I was thinking that something I was doing wrong...

Do you have some date for the next release?

P.S.: Such a great attention, congratulations!

**Comment by hoangphamemotiv** [comment]
@EDario333 We updated Composer version 3.5.0. please try it. thanks. ^^!
