### ISSUE TITLE
C# mentalcommandevent doesn't fire

### ISSUE THREAD

**Issue by par00036** [Emotiv/community-sdk#159]
Hi. I've about reached my wits end.  I've read all the previous posts, tried the demos included in the sample code to no avail.  It feels like there is a bug in the edk.dll preventing mental command event from firing with any value other than mc_neutral.  Please help.

I've attached my code and here's my logic in a nutshell.
wire up headset events
connect to the headset
log into the cloud profile and execute a save profile
`var saved = EmotivCloudClient.EC_SaveUserProfile(_usercloudId, HeadsetUserId, profiles[0].Name,
	EmotivCloudClient.profileFileType.TRAINING);
`
start the processing / listening thread
navigate to a training page
set active actions to lift
train neutral mental command
save to cloud profile
train lift mental command
save to cloud profile
watch for lift mental command events -> nothing ever happens here it's always just neutral

i also tried the same with the mentalcommandwithcloudprofile exe and it also didn't do anything.  No mental command events were ever fired.

**Comment by hoangphamemotiv** [comment]
Hi @par00036 

start the processing / listening thread
navigate to a training page
set active actions to lift
train neutral mental command
save to cloud profile -> remove it
train lift mental command
save to cloud profile -> remove it

- just one time save to cloud at the end of all training sessions. 
- with the project is a new project, you should save the project one time first before training sessions staring. 
- Did you get a success event each time traning a actions? then accept that action?
- to train from 2 actions: (with C++, others are same)
`ulong action1 = (ulong)IEE_MentalCommandAction_t::MC_PUSH;
    ulong action2 = (ulong)IEE_MentalCommandAction_t::MC_PULL;
    ulong listAction = action1 | action2;

    int errorCode = EDK_OK;
errorCode = IEE_MentalCommandSetActiveActions(userID, listAction);`
   
- you can check which action trained or not and it is in the profile or not by API: 

`//! Get a list of the actions that have been trained by the user
IEE_MentalCommandGetTrainedSignatureActions`

**Comment by par00036** [comment]
Thanks for your reply.

I've modified the routine as follows. Here are the return codes from each
wire up headset events
connect to the headset
log into the cloud profile and execute a save Default profile - returns EDK_PROFILE_CLOUD_EXISTED
start the processing / listening thread
navigate to a training page
set active actions to lift
train neutral mental command - success event fires; training accepted; trained actions=Neutral
train lift mental command- success event fires; training accepted; trained actions=Neutral,Lift
update cloud profile - returns 0
watch for lift mental command events - no events still fire

so, I've verified the headset thinks the commands are trained and that i'm attached to a profile, but nothing else happens.  If it helps, i'm adding my code.  

[MindControl.zip](https://github.com/Emotiv/community-sdk/files/715678/MindControl.zip)

To run it, add your cloud creds to the app.config file, then compile, and run.  Wait for the connection page to light up, then click the training button. Click the mental training radio button, click the neutral radio button, click train, click the lift button, click train, then try to think about lift and watch the debug window for mental command event logs.

If you see anything that i'm doing wrong please let me know.  However, i've included the edk.dll that i got from github just in case there is something you can see that is wrong with the dll.

Thanks for looking this over.  I appreciate it.

**Comment by RuVT** [comment]
A little question: Does the MentalCommandSetActiveActions need to be called before  the methods MentalCommandSetTrainingAction and MentalCommandSetTrainingControl?

I been reading the documentation and the code changes but it does no specify that, and that can cause confusion using the library.

**Comment by par00036** [comment]
From what I can tell, yes. It definitely has to be set before you try to train it.
-jon

Sent from my Windows Phone
________________________________

**Comment by hoangphamemotiv** [comment]
Hi @par00036 . QA checked MentalCommand on C# again. it works well. do you think you should training your actions again? Did you training neutral? we should training neutral everytime. ^^!

**Comment by par00036** [comment]
Hi hoang.  Every time my application starts I perform the mental command training.  Yes. I always start with neutral.  Then I train the lift command.  Both indicate a success, however, afterwards, no mental command events fire.  Out of curiosity, did you QA check the mental command with the dll that has been published to [GitHub](https://github.com/Emotiv/community-sdk/blob/master/bin/win64/edk.dll)? I ask because I noticed something funky with it when I downloaded it.  it has no publisher or version information with it, so I was just curious if it got built wrong and possibly had a bug.
![edk_missing_version](https://cloud.githubusercontent.com/assets/25167493/22277270/dd0844fe-e27f-11e6-812f-61e9599cc511.png)

**Comment by hoangphamemotiv** [comment]
Hi @par00036 . yes, QA checked the library from the Github. and we have created all Emotiv app on it.

**Comment by par00036** [comment]
hi @hoangphamemotiv . thanks for looking at that. were you able to take a look at the code I uploaded to see if there was anything obviously wrong?  I also can't get the mental command example app to work so, i'm just out of ideas... :(  thanks for all your help so far.

**Comment by akin-tekeoglu** [comment]
I have got same exact problem. Any further advice ?

**Comment by xuanbw** [comment]
I have got same exact problem too,need your help!

**Comment by akin-tekeoglu** [comment]
Actually i solved this issue. But i cant remember how i did it. Make sure you train neutral multiple time.

**Comment by xuanbw** [comment]
Just need train neutral multiple time is ok?

**Comment by xuanbw** [comment]
Just need train neutral multiple time is ok?

**Comment by akin-tekeoglu** [comment]
I cant remember exactly. Try this out and tell me what happened.

**Comment by xuanbw** [comment]
@akin-tekeoglu  have to leave for a moment，I‘ll try tomorrow and then tell you the result，thanks for your help！ 
may I have your MSN，so that we can contact conveniently

**Comment by akin-tekeoglu** [comment]
Sorry i dont have that thing. But you can e-mail me akin.tekeoglu@gmail.com

**Comment by xuanbw** [comment]
ok

**Comment by duytan90** [comment]
1. You have to train NEUTRAL
2. You have to train **ALL** the actions that listed in **ulong listAction**
If you have
> ulong listAction = action1 | action2

and `action1` is PUSH, `action2` is LIFT, then you have to train NEUTRAL, PUSH and LIFT

3. Maximum action can be put inside `ulong listAction` is 4 (excluded NEUTRAL)
> ulong listAction = action1 | action2 | action3 | action4

Hope that helps.

**Comment by xuanbw** [comment]
I have trained the MC_NEUTRAL,MC_LEFT,No matter how I do，there is no MC_LEFT command fire，what should i do？please help check the code in the proram.zip
[Program.zip](https://github.com/Emotiv/community-sdk/files/958272/Program.zip)

**Comment by xuanbw** [comment]
@akin-tekeoglu ,are you there?please help me

**Comment by barrybriggs** [comment]
Not sure this will help but I had a similar problem with the training events not firing in my Windows application. Note that the provided samples in the SDK are all console (command line) applications and that the main body of the program consists of putting the call `ProcessEvents()` in a loop. 

In a Windows GUI app, Windows manages the event loop. You have to find a way to periodically call `ProcessEvents()` so that the events fire. For my application it appears to be sufficient to have a timer fire every second; and in the timer tick routine I call `ProcessEvents()` -- which then causes the training events to be invoked.

**Comment by cmsperandio** [comment]
Hello I have the same problem.

I´m working on Emotiv Insight with Windows Forms using C# and Visual Studio 2017.
Since the examples working in a loop with the function engine.ProcessEvents().
I tried using from 5 to 1000 msec, but not works fine...
Alfter a click to started the training but never ends... Never I can check if it is ok or not.
Using the console works fine.
Please could you help me with this part of the code in order to complete my project.
Below you can see the part of the code to implement a training of NEUTRAL.
        private void btGrabarNeutral_Click(object sender, EventArgs e)
        {
            //genero loop
            running = true;
            //engine.Connect();
            while (running)
            {
                //Application.DoEvents();
                //Application.DoEvents();
                
                engine.ProcessEvents();
                 //Application.DoEvents();
                //Application.DoEvents();
        
            EmoEngine.Instance.MentalCommandSetTrainingAction((uint)userID, EdkDll.IEE_MentalCommandAction_t.MC_NEUTRAL);
            EmoEngine.Instance.MentalCommandSetTrainingControl((uint)userID, EdkDll.IEE_MentalCommandTrainingControl_t.MC_START);
                //log("grabando estado neutral");
                // debo aceptar o rechazar la grabacion del comando
            
            EmoEngine.Instance.MentalCommandSetTrainingControl((uint)userID, EdkDll.IEE_MentalCommandTrainingControl_t.MC_ACCEPT);
            }
            // log("grabado neutral");
        }

**Comment by duytan90** [comment]
Hi @cmsperandio, I'm not sure that is correct way to handle Mental Commands event in your code or how you implemented `btGrabarNeutral_Click` function.
You may want to check the [example](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/C%23/MentalCommandWithLocalProfile/Program.cs#L163) again. There is [callback](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/C%23/MentalCommandWithLocalProfile/Program.cs#L220) like this involves with calling `MC_ACCEPT`
```C
        /// <summary>
        /// Function pointer of callback functions which will be called when MentalCommandTrainingSucceededEvent occurs
        /// </summary>
        /// <param name="sender">Object which triggers the event</param>
        /// <param name="e">Contains metadata of the event</param>
        public delegate void MentalCommandTrainingSucceededEventHandler(object sender, EmoEngineEventArgs e);
```
I can't give you exact solution, but step by step debugging the example with break points should help.

**Comment by jjzwaard** [comment]
I run into the same problem. Even if I use their example code (C#) (and stick as much as possible to their example), I still get MC_NEUTRAL. Does anyone have a solution for this yet?
