### ISSUE TITLE
The libbedk.so library uses a vulnerable version of OpenSSL

### ISSUE THREAD

**Issue by ruizrube** [Emotiv/community-sdk#161]
Details here:
https://www.emotiv.com/forums/topic/the-libbedk-so-library-uses-the-1-0-1m-version-of-openssl/

**Comment by nguoithichkhampha** [comment]
@ruizrube Android SDK already update OpenSSL to 1.0.1t . Please update latest version 3.3.4

**Comment by ruizrube** [comment]
Thanks!
