### ISSUE TITLE
EmotivBTLE.[msi|dmg]

### ISSUE THREAD

**Issue by inclusite** [Emotiv/community-sdk#162]
hi,
where could I find the EmotivBTLE.dmg and EmotivBTLE.msi files? I need them for testing purposes as long as you are not supporting Javascript integration until next releases.
Could you please provide me with those files?
Otherwise, do you have a time estimation for the Javascript support?
Thanks so much in advance.

**Comment by hoangphamemotiv** [comment]
Hi @inclusite . 
at the moment, we have no planning for support javascript yet. we will back to it in the future. 

Thanks. ^^!
