### ISSUE TITLE
what kind of license do I need for emotional state data

### ISSUE THREAD

**Issue by ofZach** [Emotiv/community-sdk#163]
I have an insight device.

If I run xavier control panel everything looks ok

<img width="645" alt="screen shot 2017-01-23 at 1 51 17 pm" src="https://cloud.githubusercontent.com/assets/142897/22218478/00b149ac-e175-11e6-91e3-3b0ef7a777e9.png">

I see data coming in

<img width="631" alt="screen shot 2017-01-23 at 1 51 30 pm" src="https://cloud.githubusercontent.com/assets/142897/22218481/053a2d36-e175-11e6-885c-6e2bbc97d687.png">

If I run the EmotionState app (objective c/ mac) I see the following output: 

```

2017-01-23 13:55:14.228 EmotionalState[24592:8551679] License error code: 2010
2017-01-23 13:55:14.229 EmotionalState[24592:8551679] Haven't been active license
Date From  : 1969-12-31 19:00:00
Date To    : 1969-12-31 19:00:00
Seat number: 0
Total Quota: 0
Total quota used    : 0
Quota limit in day  : 0
Quota used in day   : 0
Quota limit in month: 0
Quota used in month : 0
License type : No type
2017-01-23 13:55:14.286 EmotionalState[24592:8551629] User Added

```

the output is just flatlines

<img width="493" alt="screen shot 2017-01-23 at 1 50 56 pm" src="https://cloud.githubusercontent.com/assets/142897/22218525/3cac33d6-e175-11e6-8905-ce5e7c4558fb.png">

do I need a license to get this example to work ?  I'm confused as to what this SDK is, I thought it was not the paid SDK and therefore doesn't require a license?  If I need a license, where do I get one?

thanks

**Comment by vivek306** [comment]
have the same problem .. the program seems to find the user but when it returns null I try to retrieve the data from the engine.. it was my understanding the community sdk was free (can u please let me know where i could get the license key too)

**Comment by ofZach** [comment]
@vivek306 we are going to return this device -- we've found the muse to be much more hackable and developer friendly and we're also testing w/ openBCI now...   both these devices are way more friendly in terms of letting you get access to the data.

**Comment by vivek306** [comment]
@ofZach agreed!! ironically getting eeg data from this device is more for commercial companies i guess and not for hobbyists.... openBCI is quite cool (looking into this) ... by the way did u manage to get a license?

**Comment by ofZach** [comment]
no I didn't find out how to get a license - I find emotive's whole business model confusing and developer hostile.  switching to friendlier devices.

**Comment by lubricationTheory** [comment]
I too urgently need to obtain the license and I have experimental work to do with the headset.

**Comment by maverickemotiv** [comment]
Our Community SDK provides access to frequency bands, expressions, mental commands and aggregate performance metrics. Access to raw EEG including the API license is available through a subscription with our Pure.EEG software. At present, access to our performance metrics requires a request via a support ticket, however we are currently restructuring the way we deliver our APIs to be more flexible moving forward. As these options become available we will be making updates on our website.

**Comment by ofZach** [comment]
why provide these examples if they don't work?   Personally I find this all really confusing.  

I love how muse and openBCI support their developers -- switching to those devices.

**Comment by vivek306** [comment]
i got to agree with @ofZach (if only i knew about openBCI before i wouldn't be in this situation) ... none of the examples in c sharp works for me.. including (frequency bands, expressions, mental commands and aggregate performance metrics) ... all seems to require a license.

**Comment by hoangphamemotiv** [comment]
Hi @ofZach , @vivek306 . PM example it can work if you activated a SDK license, default values of PM without license is 0. with frequency bands, expressions, mental commands , they dont need license to run

**Comment by ofZach** [comment]
where does one even get an SDK license ?   Are these examples part of the premium SDK?  Does it cost money?  What kind of license is this?

This is what I see about on the website about the community SDK -- there's no info about license, nor how to apply for one

<img width="583" alt="screen shot 2017-02-01 at 9 48 04 pm" src="https://cloud.githubusercontent.com/assets/142897/22535305/2ce8501a-e8c8-11e6-9952-f1861fcfbc89.png">

the only info I can find about license is this which is totally cryptic: 

https://github.com/Emotiv/community-sdk/blob/master/SDK_LICENSE_ACTIVATION.md

I think there's some missing info here.  You should either (a) provide some info on the main readme.md about what developers should do (b) add some info to the website with steps to get the license you need (c) remove these examples which do not work. 

very frustrated with how developer hostile this is.

**Comment by hoangphamemotiv** [comment]
the current repo works fine with all features you see above (FE, MC, inertial sensor, FFT). we just want to merge all examples in to one repo, so you dont need to find many repo for all features (PM and EEG also). you are right, we missed some infos about license. we will implement it soon. thank you

**Comment by ofZach** [comment]
that is confusing because on your page you see two SDKs, my impression is that the community one is free and the other one costs $ (it's not clear at all how much, etc) 

<img width="1162" alt="screen shot 2017-02-01 at 10 31 41 pm" src="https://cloud.githubusercontent.com/assets/142897/22536248/4e222246-e8ce-11e6-80b1-97f20218045d.png">

If you have it all in one repo, you might better explain which examples are not going to work so developers don't waste their time...   This is really frustrating.

**Comment by vivek306** [comment]
finally got more insight from the customer service. U get the license for the api if u get a subscription for the pure eeg software (60 sessions, with 30 mins/session and <1min is not considered a session).. what if i am debugging the code that is prone to have multiple errors? (less that one minute time is kinda of a joke @hoangphamemotiv  isnt it? wont at least 5 mins be required?) .. Sadly we had to go with emotiv as we need it asap for an experiment .. @ofZach if you have time get the openBCI (slightly more expensive device) but all the code are open-sourced http://openbci.com/community/

**Comment by tanpv** [comment]
hi

Thanks all your suggestion on SDK. We are working on to make Readme more clear on what example could run without license and what example need license.

About the policy to count session after 1 min of connect to Engine, we are thinking about this and will make it more clear later.

Best Regard.

**Comment by evanfantr** [comment]
Developer team says we need "EEG+PM" License to use Performance Metric project. 
Yet Customer Support team says these licenses are not available (only EEG license) so we cannot get the emotion data.

I bought the license then found out my license is not enough (EEG license) to get the PM data. This is false advertisement!

It feels like there are serious communication problems between EMOTIV departments
--

**Comment by Kaxkul** [comment]
Here is my feedback as well. Which approximately similar situation as all people before. 
I bought the device 3 months ago with the attention to run an experiment using the "emotional state"  but I found out the limitation of the SDK license. Since almost 2 months trying to get a clear answer from Emotiv to know which license can include the "emotional state" and I got explained from the customer service that Advanced license should be okay and when I released the license I still couldn't get an access to the data I need and I still need to submit a proposal to get the Prime license so more wasting time and money. 

few days ago I tried to submit a proposal to get the Prim SDK I just surprised from the questions they ask you. The want to know your project idea and the revenue you are expecting to have as well and more and more details!!!  Come on you need free ideas without any signed NDA plus get money for your license!!! In addition, and just for fun after the form has been submitted they told me they didn't receive it and when I contacted the customer service they asked to send it again and I did so they didn't receive it either then the customer service tried by them self's and they didn't receive any submission either. Then they figured out that the submission form is not working :))  please do attention for simple stuff.

For me seems they don't have clear business plan for them SDK license and I don't see any usefulness with the device if you are not able to get the emotion state data.

My conclusion now is sale my device and move to another company as this unsupportable situation
