### ISSUE TITLE
Using C# SDK DataSetMarker not sending a marker to EEG stream

### ISSUE THREAD

**Issue by shahalh** [Emotiv/community-sdk#165]
When I'm trying to send a marker to the EEG stream, it is not registered, and there is no indication of failure.
This same code used to work.

This is what I'm calling with userId = 0 (current headset) and various markers (2,4,6 for example).

        public static Int32 IEE_DataSetMarker(UInt32 userId, Int32 marker)
        {
            return Unmanaged_IEE_DataSetMarker(userId, marker);
        }

Any idea why the markers are not being registered?

**Comment by tungntEmotiv** [comment]
Hi @shahalh 
As the api's description, the api only return EDK_OK (0) if marker is set successfully otherwise EDK_ERROR_CODE returned.

**Comment by shahalh** [comment]
Hi @tungntEmotiv ,
The problem is that I'm getting EDK_OK (0) but the marker is not set.
At the end of the recording I'm examining the EmotivSensor.dat which used to show the markers I set but the latest SDK version doesn't set the markers and they are not present in the file.
Any idea why? Any dependencies i'm missing?
I'm using C#.
Thanks,

**Comment by tungntEmotiv** [comment]
Could you tell me what way did you record your file? you used EEG list API, right? 
when you set a marker via IEE_DataSetMarker API, your marker will be set in EEG data and is gotten by EEG API list or is stored in EDF file with Pure.EEG app.

**Comment by shahalh** [comment]
Hi @tungntEmotiv,
I'm using the SDK programmatically. I'm not using the Pure.EEG app.
Based on the C# EEG_Data_Logger example project, I'm connecting to the engine, waiting for the user added event and then calling the GetData function.
`Dictionary<EdkDll.IEE_DataChannel_t, double[]> data = engine.GetData((uint)userID);`
During recording i'm calling IEE_DataSetMarker and I expect a subsequent call to engine.GetData((uint)userID) to return the EEG data and the marker I had sent.
This used to work well but doesn't work right now.
I hope this is clearer now.

I'm not sure what the " EEG list API" is, can you explain?
Thanks,
Shahal

**Comment by manhtien2607** [comment]
Hi Shahalh

There might be some delay on the call. Have you logged EEG data with marker to csv file to check if your marker is sent?

**Comment by shahalh** [comment]
Yes I have.
All the EEG is logged to  a file from beginning to end and I can't seem to find the marker.
The same code used to work with the older Epoc device and older sdk.

**Comment by tanpv** [comment]
Hi Hi Shahalh,

Could you please copy and paste all your code to here. We will try on our side ?

**Comment by shahalh** [comment]
Based on the EEG_Data_Logger.cs from the SDK, I added the set marker call.
I can't verify it right now because our license has expired so i'm not getting the raw EEG stream.
But I have checked it several times previously and the marker was never received when using the getData() call.
I only added:

		if (i % 1000 == 0 && p.userID > 0)
		{
			p.engine.DataSetMarker((uint)p.userID, i);
		}

But here is the example code:

	using System;
	using System.Collections.Generic;
	using Emotiv;
	using System.IO;
	using System.Threading;
	using System.Reflection;

	namespace EEG_Data_Logger
	{
		class EEG_Logger
		{
			EmoEngine engine;   // Access to the EDK is via the EmoEngine 
			int userID = -1;    // userID is used to uniquely identify a user's headset
			string filename = "EEG_Data_Logger.csv"; // output filename        

			EEG_Logger()
			{
				// create the engine
				engine = EmoEngine.Instance;
				engine.UserAdded += new EmoEngine.UserAddedEventHandler(engine_UserAdded_Event);

				// connect to Emoengine.            
				engine.Connect();

				// create a header for our output file
				WriteHeader();
			}

			void engine_UserAdded_Event(object sender, EmoEngineEventArgs e)
			{
				Console.WriteLine("User Added Event has occured");

				// record the user 
				userID = (int)e.userId;

				// enable data aquisition for this user.
				engine.DataAcquisitionEnable((uint)userID, true);

				// ask for up to 1 second of buffered data
				engine.DataSetBufferSizeInSec(1);

			}
			void Run()
			{
				// Handle any waiting events
				engine.ProcessEvents();

				// If the user has not yet connected, do not proceed
				if ((int)userID == -1)
					return;

				Dictionary<EdkDll.IEE_DataChannel_t, double[]> data = engine.GetData((uint)userID);

				if (data == null)
				{
					return;
				}

				int _bufferSize = data[EdkDll.IEE_DataChannel_t.IED_TIMESTAMP].Length;

				Console.WriteLine("Writing " + _bufferSize.ToString() + " sample of data ");

				// Write the data to a file
				TextWriter file = new StreamWriter(filename, true);

				for (int i = 0; i < _bufferSize; i++)
				{
					// now write the data
					foreach (EdkDll.IEE_DataChannel_t channel in data.Keys)
						file.Write(data[channel][i] + ",");
					file.WriteLine("");

				}
				file.Close();

			}

			public void WriteHeader()
			{
				TextWriter file = new StreamWriter(filename, false);

				string header = "COUNTER, INTERPOLATED, RAW_CQ, AF3, F7, F3, FC5, T7, P7, O1, O2, P8," +
					"T8, FC6, F4, F8, AF4, GYROX, GYROY, TIMESTAMP, ES_TIMESTAMP, FUNC_ID, FUNC_VALUE, MARKER, SYNC_SIGNAL";

				file.WriteLine(header);
				file.Close();
			}

			static void Main(string[] args)
			{
				Console.WriteLine("EEG Data Reader Example");

				EEG_Logger p = new EEG_Logger();

				for (int i = 0; i < 5000; i++)
				{
					if (i % 1000 == 0 && p.userID > 0)
					{
						p.engine.DataSetMarker((uint)p.userID, i);
					}
					p.Run();
					Thread.Sleep(10);
				}
			}
		}
	}

**Comment by tungntEmotiv** [comment]
Hi @shahalh 

There miss a channel at header. could you add MARKER_HARDWARE to the header after Timestamp.
One more thing, i think you shoud remove condition p.userID > 0 because the userID = 0 here 

Thanks for raising the issue
If youu have any concern, feel free contact me. Thank you

**Comment by shahalh** [comment]
Hi,
I connected the headset both with USB and bluetooth and I did get a user Id > 0, so this was ok in the example I sent. This is not our real production code.
Were you able to get the markers according to the example? If so, can you please zip and share your'e full example including the dlls that you are referencing? Are you using 32bit or 64bit edk.dll?
Thanks,

**Comment by tungntEmotiv** [comment]
Hi @shahalh 

Oh yes, Please pull code from  develop branch on Git for my patch.
I have some changes as below in EEG_Data_Logger.cs

`
public void WriteHeader()
        {
            TextWriter file = new StreamWriter(filename, false);

            string header = "COUNTER, INTERPOLATED, RAW_CQ, AF3, F7, F3, FC5, T7, P7, O1, O2, P8," +
                "T8, FC6, F4, F8, AF4, GYROX, GYROY, TIMESTAMP, **MARKER_HARDWARE,** ES_TIMESTAMP, FUNC_ID, FUNC_VALUE, MARKER, SYNC_SIGNAL";
            
            file.WriteLine(header);
            file.Close();
        }

        static void Main(string[] args)
        {
            Console.WriteLine("EEG Data Reader Example");            

            EEG_Logger p = new EEG_Logger();

            for (int i = 0; i < 5000; i++)
            {
                //Example for set marker to data stream
                **//if (i % 37 == 0)
                //{
                //    p.engine.DataSetMarker((uint)p.userID, i);
                //}**
                
                p.Run();
                Thread.Sleep(10);
            }
        }`

I use the edk.dll 32bit on the github.

**Comment by shahalh** [comment]
I can confirm that the example is working now :-)
I have received a new license for the SDK raw data and it works.
The change in the header was helpful, although I was already looking at the 1 before last value in the csv file.
Thank you very much for your help.

**Comment by shahalh** [comment]
@tungntEmotiv Can you help me with a second issue?
There used to be a another function which sets the SYNC_SIGNAL (the last column which is returned from the raw EEG, the one before the last is the MARKER):

    DataSetSychronizationSignal((uint) m_userID, marker_id);

This function is no longer available in the latest SDK, we used to set the "SYNC_SIGNAL" field with the desired value in conjunction with the setMarker and this field persisted until a new value was set, usually we set it back to 0 alongside side with the marker. (we set a begin marker and end marker).
How can I set this field in the EEG? it is always 0.

**Comment by tungntEmotiv** [comment]
Hi @shahalh 

I have checked the api work well at C++ example. So I think the api have been wrapped for C#
Thank you for your raising. Please wait for the update.

**Comment by shahalh** [comment]
Hi @tungntEmotiv,
Your last comment gave me an idea to complete the missing code in C# and after doing so the function worked because it exists in the edk.dll functionality.
Here it is:

## Add to EEGData.cs:
`[DllImport("edk.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_DataGetSamplingRate")]
        static extern Int32 Unmanaged_IEE_DataGetSamplingRate(UInt32 userId, out UInt32 pSamplingRate);`

And

`public static Int32 IEE_DataSetSychronizationSignal(UInt32 userId, Int32 marker)
        {
            return Unmanaged_IEE_DataSetSychronizationSignal(userId, marker);
        }`

## Add to EmoEngine.cs:
`        /// <summary>`
`        /// Sets the sync signal`
`        /// </summary>`
`        /// <param name="userId">user ID</param>   `         
`        /// <param name="marker">value of the marker</param>     `
`        public void DataSetSychronizationSignal(UInt32 userId, Int32 marker)
        {
            errorHandler(EEGData.IEE_DataSetSychronizationSignal(userId, marker));
        }
`

Then the actual call can be used without compile errors:
`emoEngine.DataSetSychronizationSignal((uint) m_userID, marker_id);`

**Comment by tungntEmotiv** [comment]
Hi @shahalh 

That's great. Your changes have worked successfully, havent you?. Could we use your update for C# example and share to others ? 
Thank you. 
If you haven't any question. i will close the issue here

**Comment by shahalh** [comment]
Hi @tungntEmotiv,
The changes worked.
Please feel free to use the code, it is there for everyone.
I would have created a pull request but the repository tree has changed a little...
