### ISSUE TITLE
NOTHING IS WORKING!!!

### ISSUE THREAD

**Issue by dop3mine** [Emotiv/community-sdk#166]
I CONNECTED ZE DEVICE To COMPUTA ANDD IT IS NAT RIDING ZE SIGNALS FROM ZE EGG HEADSET. I PAID A LOT OF MONAY FOR THIS AND IT IS NOT WORKING. EXAMPLAS IN REPO NOT WORK. A LOT OF BUG EVERYWHER. CAN SOMEONE OF UR COMPANI HELP AND FIX THIS ISSUES FOR ME PLEAZ?

**Comment by dop3mine** [comment]
OK IZ STILL NAT WORKING!!!

**Comment by manhtien2607** [comment]
Hi 
Can you please attach the screenshot, so we can trouble shoot issues with sample code

Tien

**Comment by hoangphamemotiv** [comment]
Hi @dop3mine . Can you tell me what error you got when run the examples? 
you may want to check How to run examples at here: https://github.com/Emotiv/community-sdk/tree/master/doc

**Comment by dop3mine** [comment]
OKEY. HER IZ ZE SCREN SHOOT. 
![image](https://cloud.githubusercontent.com/assets/15755210/22544727/e523357c-e92d-11e6-9379-35c77f0bf3eb.png)

**Comment by dop3mine** [comment]
I TRI TO REED MY EMOTION. PLEAZE HELP!

**Comment by tanpv** [comment]
hi dop3mine,

Do you already follow guideline for Java example at 

https://github.com/Emotiv/community-sdk/blob/master/doc/How%20to%20run%20Java%20examples.pdf  ?

That is detail guide how to run example with Java, We already tested it and I run OK from my side

**Comment by dop3mine** [comment]
@tanpv TANK JU! I HAV COMPLITED THIZ PDF STEP. I HAV LOODED JNA JAR BUT NAT WORK ON MICRASAFT WINDOW 8. I HAVING ZE EXCEPTIAN THIZ = Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'edk': Native library (win32-x86-64/edk.dll) not found in resource path. I AM COPY ZE EDK DLL FILE IN ZE RESOURCE PATH BUT ZIS FILE NAT BEN LOADING. WHY IS THIZ? I AM RELLY UPSAT AS THIZ NAT WORKING AS EXPECTED. PLEAZE HELP ME BY FIXING THIZ ISSUE?

**Comment by hoangphamemotiv** [comment]
Hi @dop3mine 
===
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'edk': Native library (win32-x86-64/edk.dll)
===
as in the "How to run examples"
- if you installed JDK 64bit you need to set JRE to folder store JRE 64bit and set PATH of variable is win64. 
- it is same with 32bit.
