### ISSUE TITLE
emotiv afftective suite 

### ISSUE THREAD

**Issue by vaishali-jadhav** [Emotiv/community-sdk#168]
hello,
I had to work on emotiv afftectiv suite as there is no training for detections, how the data is collected and where it is saved. how to access the data and work on it.

**Comment by hoangphamemotiv** [comment]
Hi @vaishali-jadhav . we dont need training for affectiv/performance metric detections. to get Performance Metric detections you need a SDK license. you can see this in the table here: https://github.com/Emotiv/community-sdk#api-code-example

**Comment by vaishali-jadhav** [comment]
Hello,
         I have license SDK developer kit version2.0.0.20. which is the
code that help me to get the performance metric.what platform will it
support. I m having Windows 7.


vaishali Jadhav

**Comment by vaishali-jadhav** [comment]
how to run .dll files in matlab so that I can run the code of Expressive and Affective in matlab.
