### ISSUE TITLE
build error for Ubuntu 16.04

### ISSUE THREAD

**Issue by koolakoff** [Emotiv/community-sdk#169]
Got build error the community-sdk on my Ubuntu 16.04 LTS.
(I’ve used the How to build C++ examples with Cmake.txt)

```
CMakeFiles/ActivateLicense.dir/ActivateLicense.cpp.o: In functionmain’:
ActivateLicense.cpp:(.text+0x71f): undefined reference to `IEE_ActivateLicense’
ActivateLicense.cpp:(.text+0x76e): undefined reference to `IEE_LicenseInformation’
ActivateLicense.cpp:(.text+0x819): undefined reference to `_getch()’
collect2: error: ld returned 1 exit status`
```

The /bin/linux64/libedk.so.3.3 does not contain these symbols

Can you please advice where can I find the correct lib or how to build on Ubuntu? Or maybe I have to install any extra package on my Ubuntu?

**Comment by koolakoff** [comment]
Attached the full build log
[log.txt](https://github.com/Emotiv/community-sdk/files/749934/log.txt)

**Comment by hoangphamemotiv** [comment]
Hi @koolakoff . at the moment, Ubuntu is not supported by SDK 3.4 with licensing.
you can see this in the table here: https://github.com/Emotiv/community-sdk#api-code-example
