### ISSUE TITLE
How to use MentalCommandWithLocalProfile?

### ISSUE THREAD

**Issue by Teseium** [Emotiv/community-sdk#171]
What about the path "C:/1/161.emu"? 
Do I need to put my own path?
The example gave me "Can't load profile."
In the last Getting_Started_With_Emotiv_SDK.pdf, indicates Boost C++ Library is needed, What about this?

**Comment by hoangphamemotiv** [comment]
Hi @Teseium 

161.emu is name of profile. i think it is not in your PC. so, we got "Can't load profile". You need save a profile at the first before want to load it. 

Thanks
