### ISSUE TITLE
Getting User added or User removed alert in infinite loop in Android

### ISSUE THREAD

**Issue by bizzareshishir** [Emotiv/community-sdk#172]
Handler handler = new Handler() {
		@Override
		public void handleMessage(Message msg) {
			switch (msg.what) {

				case 0:
					int state = IEdk.IEE_EngineGetNextEvent();
					if (state == IEdkErrorCode.EDK_OK.ToInt()) {
						int eventType = IEdk.IEE_EmoEngineEventGetType();
						userId = IEdk.IEE_EmoEngineEventGetUserId();
						if(eventType == IEE_Event_t.IEE_UserAdded.ToInt()){
							Log.e("SDK","User added");
							Toast.makeText(MainActivity.this, "User added", Toast.LENGTH_SHORT).show();
							isEnablGetData = true;

						}
						if(eventType == IEE_Event_t.IEE_UserRemoved.ToInt()){
							Log.e("SDK","User removed");
							Toast.makeText(MainActivity.this, "User removed", Toast.LENGTH_SHORT).show();
							isEnablGetData = false;
						}
					}

					break;
				case 1:

					/**************************************/
				/*Connect device with EPOC Plus headset*/
					int number = IEdk.IEE_GetEpocPlusDeviceCount();
					if(number != 0) {
						if(!lock){
							lock = true;
							IEdk.IEE_ConnectEpocPlusDevice(0,false);
						}
					}
					/**************************************/
					else lock = false;
					break;
				case 2:
					IEdk.IEE_MotionDataUpdateHandle(userId);
					int sample = IEdk.IEE_MotionDataGetNumberOfSample(userId);
					if(sample > 0){
						for(int sampleIdx =0; sampleIdx < sample; sampleIdx++)
						{
							for(int j=0;j< Channel_list.length;j++){
								double[] eeg_data = IEdk.IEE_MotionDataGet(Channel_list[j]);
								addData(eeg_data[sampleIdx]);
							}
							try {
								motion_writer.newLine();
							} catch (IOException e) {
								// TODO Auto-generated catch block
								e.printStackTrace();
							}
						}
					}

					break;
			}

		}

	};

**Comment by nguoithichkhampha** [comment]
@bizzareshishir , event user added appear when headset connected and user removed when headset disconnected. Sometimes you will see:
User Added
User Removed
User Added
Because after headset connected but doesn't send data. Sdk will auto call function disconnect.this loop run until headset send data success.
