### ISSUE TITLE
EPOC (not plus) unable to detect on android

### ISSUE THREAD

**Issue by superusercrysis** [Emotiv/community-sdk#173]
As stated on the title, I am currently using Emotiv EPOC not plus. I am not able to connect to the android phone (Xperia X). I am using the provided examples.
Is it compatible to EPOC? or the SDK is only for EPOC+ and Insight?

**Comment by nguoithichkhampha** [comment]
Hi @superusercrysis , Connection between Emotiv headset and Android device is bluetooth low energy. Epoc headset don't support bluetooth . So, you should use Epoc Plus or Emotiv Insight to can work with Android devices.
Thanks
