### ISSUE TITLE
EPOC+ does not connect with bluetooth!

### ISSUE THREAD

**Issue by AssiotisCy** [Emotiv/community-sdk#174]
Hello i am trying to run the Mental Command application that is available on android folder. It looks like i cant establish connect with my Nexus 6P.

state = IEdk.IEE_EngineGetNextEvent();
                Log.d("", "run: "+state);
				if (state == IEdkErrorCode.EDK_OK.ToInt()) {
                    int eventType = IEdk.IEE_EmoEngineEventGetType();
					switch (eventType) {

The state that is equal with get next event is not equal with the Edk_ok instead is equal with the No_event.

Does anyone know why? 
I already sent an email to the Emotiv's Customer Support and they told me that on their device work just fine.

Thank you for your time

**Comment by nguoithichkhampha** [comment]
Hi @AssiotisCy , Did you see event "user added" ? Please make sure you don't connect headset with device by hand.
