### ISSUE TITLE
Java examples, port as primitive type short.

### ISSUE THREAD

**Issue by MartinsIrbe** [Emotiv/community-sdk#175]
In Java examples, `Edk.INSTANCE.IEE_EngineRemoteConnect(host, port, devId)` I noticed that the port is of primitive type `short`, which means that `short` max value is `32767`, however there are total of `65535` available ports.

**Comment by hoangphamemotiv** [comment]
Hi @MartinsIrbe 
you are right. Thank you for your feedback. 
Emotiv Control Panel use port 3008,  EmoComposer use port 1726. lucky that they are in the range . but the range should be 65535. 

Thanks. ^^!
