### ISSUE TITLE
About testing the example of MentalControlDemo with the method mentioned in the pdf

### ISSUE THREAD

**Issue by SuyuanLiu** [Emotiv/community-sdk#176]
In the page of 18 of the pdf,at the back of the page,it says "In the Emotive select Connect to Composer and accept the default values and then enter a new profile name",What does "Emotive",Emotive Xavier Control Pannel?And i didn't find where to enter a new profile name.Is anything wrong with my comprehension?

**Comment by hoangphamemotiv** [comment]
Hi @SuyuanLiu . uhm. you meant about what examples: MentalControlDemo? i think in each examples it should have a value to add profile name that you want
