### ISSUE TITLE
emotiv-matlab connection 3

### ISSUE THREAD

**Issue by masoudmaleki** [Emotiv/community-sdk#178]
Hi 
it is me again,
some days ago (exactly, on Dec 5, 2016) I submitted the issue #151  (still open, and still I can't run it successfully)...
I would be very grateful if you could solve my problem that i have it from 8 month ago. i can not progress in my thesis. 
thank you so much
i tried to connect emotiv and matlab. but i have this error:
![image](https://cloud.githubusercontent.com/assets/24210292/23338586/99baf0aa-fc17-11e6-9150-a54414dea2a4.png)

**Comment by tungntEmotiv** [comment]
Hi @masoudmaleki 

We have updated for eeglogger.m . Please pull the latest code from [](https://github.com/Emotiv/community-sdk/tree/master/examples_extra_prime/Matlab)

**Comment by nguyenvinhbinhktdo** [comment]
Hi @masoudmaleki, my skype: binhnv1903 , you can chat with me I will support you online

**Comment by fsalsayegh** [comment]
Hello @masoudmaleki, I have the same issue ...did you find a solution?

**Comment by nguyenvinhbinh** [comment]
Hi @fsalsayegh,
have you pulled the latest code examples_extra_prime then run it on matlab 32 bit?

**Comment by fsalsayegh** [comment]
hello @nguyenvinhbinhktdo , yes I did but I got another error 

**Error using calllib
Array must be numeric or logical or a pointer to one**

**Error in eeglogger (line 96)
                    dlmwrite('eegloger.csv',data2(i,1:mycolumn),'-append','delimiter',';','precision','%.2f');**

**Comment by nguyenvinhbinh** [comment]
my skype is : binhnv1903, I can support you online. could make sure that:
1. you pull out the latest  community SDK (all folder, not only eegloger.m);
2. Show API.m (basics folder) run well and it show you list of function 
3. your matlab is a 32bit version;
3. headset connect well (check with control panel), Hide code lines below
for i=1:nSamplesTaken
                    dlmwrite('eegloger.csv',data2(i,1:mycolumn),'-append','delimiter',';','precision','%.2f');

                end
then run eeglogger.m and data still run on the command line screen
