### ISSUE TITLE
MentalCommandWithCloudProfile does not build on Ubuntu

### ISSUE THREAD

**Issue by koolakoff** [Emotiv/community-sdk#179]
The MentalCommandWithCloudProfile example does not compiles on Ubuntu.

```
[ 72%] Building CXX object examples_basic/C++/MentalCommandWithCloudProfile/CMakeFiles/MetaCommandWithCloudProfile.dir/MentalCommandWithCloudProfile.cpp.o
In file included from /usr/include/c++/5/thread:35:0,
                 from /home/kulapet/project/community-sdk/examples_basic/C++/MentalCommandWithCloudProfile/MentalCommandWithCloudProfile.cpp:13:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
```

Note, I had to update top level CMakeList.txt and exclude all License-required examples and items not listed as 'supported for ubuntu' in https://github.com/Emotiv/community-sdk#api-code-example 

Note, even if I pass '-std=c++11' and fix syntax error related to Win/Linux compiler differences, even though I get link error
```

[100%] Linking CXX executable ../../../Programs/SavingLoadingCloudProfile
CMakeFiles/SavingLoadingCloudProfile.dir/main.cpp.o: In function `main':
main.cpp:(.text+0x7cf): undefined reference to `EC_UploadProfileFile'
main.cpp:(.text+0x8ca): undefined reference to `EC_DownloadProfileFile'
collect2: error: ld returned 1 exit status
e
```

As I understood from previous similar post (https://github.com/Emotiv/community-sdk/issues/170) the issue was retested. So maybe I have something missing in my Ubuntu SW or any config broken?

**Comment by havietnam** [comment]
Please try:
`cd MentalCommandWithCloudProfile`

`export LD_LIBRARY_PATH=../../../bin/linux64`

`g++ --std=c++11 MentalCommandWithCloudProfile.cpp -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I../../../include -L../../../bin/linux64/ -ldbus-1 -ledk`
