### ISSUE TITLE
Problems with facial expresion using new devices. 

### ISSUE THREAD

**Issue by agallardol** [Emotiv/community-sdk#180]
Hello,

I have worked with Emotiv Epoc for 5 years and have gone through the different versions of the device.

Yesterday came several Emotiv Insight Mode 1.0 devices that I should distribute, the problem is that in my application the facial expressions do not work, when I blink the system detects that I did it many times and even happens that it detects facial expressions even when I have not done them, I have tried everything and I made sure that the device is well positioned, worse still the problems occur.

To make sure that it was not a problem with my application, I used Emotiv Xavier Control Panel 3.3.3 and the same happens, the system detects facial expressions when I have not done them and if I blink, it detects more than 1 (sometimes up to 4) .

Finally I tried with several devices that came to me, and with all the same thing happens.

Anyone else has happened? I hope you can help me.

**Comment by nguoithichkhampha** [comment]
@agallardol , our detection have a default threshold. it may not have high accurate for all of user. So, for high accurate please use training with facial expression. the threshold in the detection will match with your brain.
