### ISSUE TITLE
How to map mental commands to custom actions

### ISSUE THREAD

**Issue by LauraHawkins** [Emotiv/community-sdk#181]
We are trying to make a brain mouse with the emotive sdk kit. We used the rule in the xavier control panel to do clicking but could not find a way to move the mouse using that. Now we are trying to use the sdk and are looking at the mental commands with local profile example but cannot find where it actually registers commands so we can map them to custom actions. Any idea where we can find code that does this? Help would be much appreciated.

**Comment by nguyenvinhbinhktdo** [comment]
In fact, to move mouse, we have calculate the motion of headset by using motion data. (you can study MotionDataLoger project in example ), we depend on the motion data to calculate Yaw, Pitch , Roll of headet then map them with movement of a mouse. Formulas and al·go·rithms to calculate them are quite complicated and will be integrated in later Emotiv SDK 
see more at
https://www.youtube.com/watch?v=C7JQ7Rpwn2k

**Comment by tungntEmotiv** [comment]
Hi @LauraHawkins 
Do you have any question? Temporarily, i close the issue, and reopen when you have any question

**Comment by LauraHawkins** [comment]
sorry, didn't see your initial response. I am still a little confused. I
understand that the software allows you to move the mouse using the
built-in gyroscope. However, I am trying to adapt it to move the mouse
ppurely with mental commands. I found a way to map mental commands to mouse
clicks using the Xavier control panel, but it did not have a way to move
the mouse. I moved on to the community SDK, and am looking through
examples, but cannot find the code where it actually registers mental
commands so I can map them to custom actions. do you know where I can find
an example that registers mental commands that I can use to trigger my own
custom actions?

Best,
Laura Hawkins
