### ISSUE TITLE
The code that connect Emotive Insight to the Application code  

### ISSUE THREAD

**Issue by tahanimohammed** [Emotiv/community-sdk#183]
I will make an Android gamming application through Emotive Insight so I want the code to connect Emotive Insight to the application code.

Thanks

**Comment by tungntEmotiv** [comment]
Hi @tahanimohammed,

Sorry because of late response. Have you ever referenced to Andriod examples ( https://github.com/Emotiv/community-sdk/tree/master/examples_basic/Android ) ? Is it helpful ?

Thanks
tnguyen

**Comment by tahanimohammed** [comment]
Thank you
