### ISSUE TITLE
Unity Rolling Ball with mental command different than Push

### ISSUE THREAD

**Issue by Stezii** [Emotiv/community-sdk#184]
currently I am playing with the Community SDK and Unity. I modified the Rolling Ball example in EmotivCtrl.cs so that it trains for a Pull command instead of Push. When I execute the application, the training won’t start. Instead, the following error is thrown:

`EmoEngineException: Unknown error
Emotiv.EmoEngine.errorHandler (Int32 errorCode)
Emotiv.EmoEngine.MentalCommandSetTrainingControl (UInt32 userId, IEE_MentalCommandTrainingControl_t control)
EmotivCtrl.TrainPush () (at Assets/scripts/EmotivCtrl.cs:149)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:153)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:634)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:769)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:53)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:35)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:44)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:52)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:269)
UnityEngine.EventSystems.EventSystem:Update()`

I could not figure out why this happens. I used the precompiled DotNetEmotivSDK-vs2010.dll.
I also compiled DotNetEmotivSDK.dll with .NET3.5 by myself. Then, the error isn’t thrown, but again the training doesn’t start. It has to be mentioned that I had to comment out the EmotivCloud stuff to get the code instantly running. No idea if this caused sideeffects at this point.

**Comment by RuVT** [comment]
Hello.
Since I uploaded the Unity Examples, the Emotiv SDK has had many changes.
If you want to use the old precompiled DotNetEmotivSDK.dll you have to use the old Edk.dll too, you can use git to go back to the commit 04226b6 where the code works.

You can use the new code too but I know from other case with similar problem that you have to call the function **MentalCommandSetActiveActions** from de sdk so it can detect the actions.

Try to change the code in your project so it looks like this:

```
public void TrainPull() {
        //Declare the actions to listen
        uint action1 = (uint)EdkDll.IEE_MentalCommandAction_t.MC_PULL;
        uint action2 = (uint)EdkDll.IEE_MentalCommandAction_t.MC_PUSH;
        uint listAction = action1 | action2;
        //Set the actions 
        EmoEngine.Instance.MentalCommandSetActiveActions(0, listAction);
        //engine.MentalCommandSetActiveActions(0, (uint)EdkDll.IEE_MentalCommandAction_t.MC_PULL);
        engine.MentalCommandSetTrainingAction((uint)engineUserID, EdkDll.IEE_MentalCommandAction_t.MC_PULL);
        engine.MentalCommandSetTrainingControl((uint)engineUserID, EdkDll.IEE_MentalCommandTrainingControl_t.MC_START);
}
```

**Comment by Stezii** [comment]
I'm using latest edk.dll (4.5 Mbyte) in conjunction with precompiled DotNetEmotivSDK-vs2010.dll. I also added MentalCommandSetActiveActions and training works now. Thanks! As far as I recognized, up to four mental commands are allowed to be passed in a list, right? 

___
However, when I accept the training an error is thrown (see below). Nevertheless, the training is practically accepted in the end since I'm able to perform tasks in live operation. 

`EmoEngineException: Unknown error
Emotiv.EmoEngine.errorHandler (Int32 errorCode)
Emotiv.EmoEngine.MentalCommandSetTrainingControl (UInt32 userId, IEE_MentalCommandTrainingControl_t control)
EmotivCtrl.AcceptTraining (Boolean accept) (at Assets/Emotiv/scripts/EmotivCtrl.cs:232)
MessageBox+<init>c__AnonStorey0.<>m__1 () (at Assets/Emotiv/scripts/MessageBox.cs:37)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:154)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:637)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:773)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:52)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:35)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:44)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()`

**Comment by RuVT** [comment]
can you send the code that is in your _Assets/Emotiv/scripts/EmotivCtrl.cs:232_ ?
It seems that in that line you are sending a wrong parameter to the **MentalCommandSetTrainingControl** method.
It needs to be like this code: 

`EmoEngine.Instance.MentalCommandSetTrainingControl(0,EdkDll.IEE_MentalCommandTrainingControl_t.MC_ACCEPT);`

Also if you use the latest Edk.dll, then **compile your own DotNetEmotivSDK.dll** so you dont have problems, the Emotiv dev team change the core Edk.dll library writen in C++, the DotNetEmotivSDK its a **wrapper** so we can access those functions in C#, so if you use the latest Edk.dll those functions can have been **changed** and dont match the deffinition in the old DotNetEmotivSDK wrapper.

**Comment by Stezii** [comment]
Training (e. g. Drop):
`public void TrainDrop()
    {
        SetActiveActions();
        engine.MentalCommandSetTrainingAction((uint)engineUserID, EdkDll.IEE_MentalCommandAction_t.MC_DROP);
        engine.MentalCommandSetTrainingControl((uint)engineUserID, EdkDll.IEE_MentalCommandTrainingControl_t.MC_START);
    }`


Accepting a training:
`public void AcceptTraining(bool accept)
    {
        if (accept)
        {
            engine.MentalCommandSetTrainingControl ((uint)engineUserID, EdkDll.IEE_MentalCommandTrainingControl_t.MC_ACCEPT);
		} else {
			engine.MentalCommandSetTrainingControl ((uint)engineUserID, EdkDll.IEE_MentalCommandTrainingControl_t.MC_REJECT);
        }
        //Debug.Log(engine.MentalCommandGetTrainedSignatureActions((uint)engineUserID));
    }`

**Comment by RuVT** [comment]
Your functions looks ok to me, try to compile your own DotNetEmotivSDK.dll so we can descart that possibility, use the solution in _example_basic/C#/_ and .NetFramework 3.5, more instructions [here](https://docs.google.com/document/d/1zJCRSXfqEjjS3az3vCEFCTNA828HEM5TFkrUeKSwjGo/edit?usp=sharing).

**Comment by junior1807** [comment]
any way someone could make a video tutorial on set up as far as windows, and mac machines come about ? that would be so beneficial for users like myself new to all of this.

**Comment by RuVT** [comment]
A video tutorial is time consuming to make so here are some steps:

1. Download and install Unity3D, if you want to compile for Mac, Windows or Android there are options in the installer.
2. Donwload or clone this repository.
3. Create a Folder some where in your system and copy there the EDK.dll (If your machine its 64 bits use x64 version, else use x86)
4. Add a system variable using the path of the folder you just created. This depends on you OS, so you have to find out the specific way for system.
5. Compile the DotNetEmotivSDK.
5.1. Got to the C# forder in the repository copy on your machine and open the DotNetEmotivSDK project with Visual Studio.
5.2. Right click on the project DotNetEmotivSDK in the Solution Explorer (Right Panel), click on Properties.
5.3. On the Application Tab, select Target Framework to .Net Framework 3.5 (The default that Unity Uses), save changes (Ctrl+S).
5.4. Right click on the project DotNetEmotivSDK in the Solution Explorer, select Build.
5.5. Go to the project folder /bin/Debug or /bin/Release and search for the DotNetEmotivSDK.dll.
6. Add the compiled DotNetEmotivSDK.dll to the assets folder in Unity, when scripting add the "`using Emotiv;`" statement.
7. Done, you can write code using the Emotiv library.

**Comment by Stezii** [comment]
Recompilation and adapting the wrapper calls fixed the issue.
