### ISSUE TITLE
MentalCommandWithCloudProfile example not working (Java, Linux Mint 64 bits)

### ISSUE THREAD

**Issue by LMPombar** [Emotiv/community-sdk#189]
I'm using Linux Mint 64 bits and Eclipse to work with an Epoc+ headset and SDK ver. 3.3.3.

I'm having many problems getting the Java MentalCommandWithCloudProfile example to work:

-For some reason, the function `EmotivCloudClient.INSTANCE.EC_GetUserDetail(userCloudID)` in line 65, right after login in, returns an EDK_UNKNOWN_ERROR. It tells me that I'm missing some certificate ("Error adding certificate") and even after trying everything I have thought about, it still doesn't work.

-Mental Trainings ALWAYS fail. I have been unable to get them to return Success even with all sensors in green. Training with the Xavier Panel Control gives no problems at all, so I can't grasp what the problem is. I was trying to implement mental command training in my own application, but neither work. 

Can this be a bug or am I doing something wrong?
I really need to solve this to continue with my project.

Thank you very much,

Laura

**Comment by LMPombar** [comment]
Any ideas?

**Comment by tungntEmotiv** [comment]
Hi @LMPombar 

Yes, Thanks for your rasing. The issue is same as https://github.com/Emotiv/community-sdk/issues/195
We will fix it in next version of sdk.
Thanks

**Comment by LMPombar** [comment]
Thank you for your answer.
When are you planning on releasing the next version of the sdk?

**Comment by hoangphamemotiv** [comment]
Hi @LMPombar 
we will focus on version for Windows and Mac first then hope will have Linux version soon. 

Thanks. ^^!
