### ISSUE TITLE
Raspberry Pi Zero W

### ISSUE THREAD

**Issue by LadyTech** [Emotiv/community-sdk#190]
Hello Emotiv. I am currently working with a Raspberry Pi Zero. Does your armhf codes work for the Raspberry Pi Zero W? I am having some trouble getting the libraries to load in python. If not, what raspberry pi do you support?

Thanks,

**Comment by tungntEmotiv** [comment]
Hi @LadyTech 

From version 3.3.1, we have supported Debian 8.3 Jessie (armhf) on Raspberry Pi 2. 
What is your problem getting the libraries ?

Thanks,
tnguyen

**Comment by LadyTech** [comment]
When I run the code, it "restarts" in python and "loads" the library. However, the library does not load correctly. I tired to explicitly state the location of the library and it did not help. In short, I run the example on my windows computer and it runs with no issue, however on the pi it will run and never print any statements because it fails to load the library.

I was trying to run the averagebandpower.py code in your examples. 

import sys
import os
import platform
import time
import ctypes

from array import *
from ctypes import *
from __builtin__ import exit

if sys.platform.startswith('win32'):
    import msvcrt
elif sys.platform.startswith('linux'):
    import atexit
    from select import select

from ctypes import *

try:
    if sys.platform.startswith('win32'):
        libEDK = cdll.LoadLibrary("../../bin/win32/edk.dll")
    elif sys.platform.startswith('linux'):
        srcDir = os.getcwd()
	if platform.machine().startswith('arm'):
            libPath = srcDir + "/../../bin/armhf/libedk.so"
	else:
            libPath = srcDir + "/../../bin/linux64/libedk.so"
        libEDK = CDLL(libPath)
    else:
        raise Exception('System not supported.')
except Exception as e:
    print 'Error: cannot load EDK lib:', e
    exit()

IEE_EmoEngineEventCreate = libEDK.IEE_EmoEngineEventCreate

I used this code and It created a libPath and executes libEDK but not the IEE_EmoEngineEventCreate. No errors are thrown in the process.

**Comment by havietnam** [comment]
What is connection you use? BTLE or Dongle?
