### ISSUE TITLE
How do I program the headset to be used to control a Lego Mindstorm Ev3

### ISSUE THREAD

**Issue by SciGuy44** [Emotiv/community-sdk#194]
I know this is sort of a redundant question, but I am in middle school and am really interested in science and engineering, I've built many things such a  bicycle generator, hydroponic system, etc. But I'm pretty new to the coding world, I know a bit of JavaScript and a bit of python but that's about it. I just purchased an emotiv insight headset and I was hoping I could have it control a Lego mind storm Ev3 robot any suggestions on how to do so? Thanks.

**Comment by tungntEmotiv** [comment]
Hi @SciGuy44 

Thank you use the emotiv product :).

About your question, You can reference the below link for some python examples to learn how to use edk library for your app. I think the MotionDataLogger example might be useful for your application. 
https://github.com/Emotiv/community-sdk/tree/master/examples_basic/Python

If you have any concern, feel free contact us. We look forward your progress
