### ISSUE TITLE
Raspberry PI issue

### ISSUE THREAD

**Issue by Rymarx** [Emotiv/community-sdk#195]
Hello I'm having an issue while trying to connect to cloud profile with raspberry pi 3 model b. I'm using python 2.7.
I have tried SavingAndLoadingProfileCload and MentalCommandWithCloadProfile and the outcome is the same.
It starts to connect, in console writes that logged in, but after that gets me an error. 
exit()
"raise SystemExit(code)"
SystemExit: None
libEDK.EC_GetUserDetail(userCloadIDP) gets 1 and after that program shuts down. 
The funny part is that on windows python this code works fine, but on raspberry don't.
Could you help me, maybe I'm missing something or maybe python don't have some modules installed so it won't work
Any help is appreciated. Thank you.

**Comment by havietnam** [comment]
This issue occurs because your Emotiv cloud profile contains Unicode character (not parse correctly in Linux).
We will fix in next version.
You can work around by change your profile information,  using only ASCII character.

**Comment by Rymarx** [comment]
Thank you
