### ISSUE TITLE
Save cloud profile locally

### ISSUE THREAD

**Issue by inclusite** [Emotiv/community-sdk#196]
Hi,
I found out in the developer forum (https://www.emotiv.com/forums/topic/saving-profile-in-python-without-cloud/ ) that the EDK v3.4 allows to save the trainned profile locally.
Is it already available?
Can anyone tell me which method should I use? or a code example preferably java?

**Comment by hoangphamemotiv** [comment]
Hi @inclusite 
this is example for saving profile in Local. it is C++ example but i think you will be easy to read. we will implement this example to Python soon. 

https://github.com/Emotiv/community-sdk/blob/master/examples_basic/C%2B%2B/MentalCommandWithLocalProfile/MentalCommandWithLocalProfile.cpp

Thanks. ^^!

**Comment by inclusite** [comment]
Thanks so much
