### ISSUE TITLE
Some questions regarding training

### ISSUE THREAD

**Issue by barrybriggs** [Emotiv/community-sdk#197]
Hopefully some fairly simple questions.

1. I read in one of the posts that you should train *all* of the mental commands you pass into `MentalCommandSetActiveActions()` -- is this true? I.e., if you just want to test one command you should only set one active action?
2. Neutral training. There appear to be two ways to train neutral, one is a separate API and the other is to use the standard training API's. Can someone explain the difference and the usage?
3. Can training be persisted or do I have to train every time I launch the app?
4. Do you have a sense of what the maximum practical number of mental commands that can be trained are? 
5. Is there anything magical about the particular mental commands enumerated in `dkDll.IEE_MentalCommandAction_t` i.e., is there any way to define your own actions?

**Comment by tungntEmotiv** [comment]
Hi @barrybriggs 

Please see the below comment for answer
1) Yes, You can set one active action once but you only set new action after the previous action training has completed.
2) Do you mean api IEE_MentalCommandStartSamplingNeutral() ? if yes, the api provide neutral training for long period (30 seconds ) or until IEE_MentalCommandStopSamplingNeutral() called
 The period of standard training APIs is approximately 8 seconds
3) Yes, the training can be persisted with same profile.
4)  maximum is 4 distinct training actions
5)  Currently, User can not define action

**Comment by barrybriggs** [comment]
Thanks this is very helpful. To clarify:

1. My question was slightly different. I'll ask it another way: should I call `MentalCommandSetActiveActions()` each time I train, or can I call it just once with all the commands I intend to train? Right now I call once with all four commands OR'd together. Should I call it just before each training?

2. Regarding neutral: what is the difference between `engine.MentalCommandSetTrainingAction(currentUser, EdkDll.IEE_MentalCommandAction_t.MC_NEUTRAL);` and `IEE_MentalCommandStartSamplingNeutral()`? Which one should I use (and why)? 

3. Regarding persistence: I think I get it. The flow is:
First time: call `IEE_GetBaseProfile(eProfile);`
Then do the trainings 
When done, save the profile buffer to disk
Next time: load the profile buffer from disk
then call` IEE_SetUserProfile(userID, profileBuf, profileSize)` to set it

Is that right? 

Re: 4 and 5-- got it, thanks.

**Comment by barrybriggs** [comment]
Oh, and one other question. Does "userid" correspond to "headset id" one for one? Or can you have multiple users for a headset, that is, can you have different profiles for different people (say if you wanted to pass the headset around)?

**Comment by tungntEmotiv** [comment]
Hi @barrybriggs 
Yes, i will clarify my answer:
1) You should call it  just once with all the commands I intend to train
2) ngine.MentalCommandSetTrainingAction -> period of neutral training time = 8 seconds  but IEE_MentalCommandStartSamplingNeutral() = 30 seconds or until IEE_MentalCommandStopSamplingNeutral() called.  Choosing which api depend on your time, skill (train skill). Normally, you can choose standard training api with durarion 8 seconds.
3) yes, that right

6) headsetID and userID is same here. If you use Control panel application, you can see that can create many profiles for one user
