### ISSUE TITLE
Bluez cannot find EPOC+

### ISSUE THREAD

**Issue by ihayet** [Emotiv/community-sdk#198]
I followed the instructions given in the readme. But, the bluetoothctl could not find the EPOC+. Can anyone help me in this regard?

Thanks in advance.

**Comment by tungntEmotiv** [comment]
Hi @ihayet 
Which version of bluetooth agent did you install ? We support from 5.37 as below link
https://github.com/Emotiv/community-sdk/blob/master/doc/Connecting%20on%20Ubuntu%20and%20Debian.md

**Comment by ihayet** [comment]
@tungntEmotiv  I have used bluez 5.37 at first according to the instructions. As it did not work, I tried the bluez 5.43 version. But, to no avail. However, when I power on both the dongle and the headset, they seem to be automatically paired. Even though, the headset is not listed when "scan on" command is run in the bluez shell, the example Java programs can run without any error and gives output from headset.
