### ISSUE TITLE
Python quit unexpectedly while using the edk plug-in

### ISSUE THREAD

**Issue by nadunindunil** [Emotiv/community-sdk#199]
Hi, I am running Emotiv SDK on mac OSX Sierra 10.12 and when I run the AverageBandPowers.py file an error message as "Python quit unexpectedly while using the edk plug-in" shows. 
could you please suggest an answer to tackle this issue? 

Thanks in advance!

**Comment by tungntEmotiv** [comment]
Hi @nadunindunil 
Which version of your python. I recommend you use python 2.7 or later

**Comment by nadunindunil** [comment]
Hi @tungntEmotiv 
I am using Python 2.7.10 in OSX 10.12

**Comment by nadunindunil** [comment]
Hi @tungntEmotiv, any updates on this issue?
