### ISSUE TITLE
I have this error!

### ISSUE THREAD

**Issue by Moralitos28** [Emotiv/community-sdk#200]
I simply run the projects examples in C # and give me this error that I should do?
> The System.BadImageFormatException exception occurred.
  HResult = 0x8007000B
  Message = Unable to load the file or assembly 'DotNetEmotivSDK, Version = 0.8.4.0, Culture = neutral, PublicKeyToken = null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  Origin = MentalCommandWithCloudProfile
  Tracking the battery:
   At MentalCommandWithCloudProfile.Program.Main (String [] args) in C: \ Users \ Carl Moral \ Documents \ Matilda \ community-sdk-master \ examples_basic \ C # \ MentalCommandWithCloudProfile \ Program.cs: line 300
``

**Comment by tungntEmotiv** [comment]
Hi @Moralitos28 

Do you have choose x64/ x86 / win32 for active solution platform instead of mixed platform on Visual Studio ?
