### ISSUE TITLE
Problem with emostate_logger.py

### ISSUE THREAD

**Issue by javiersivack** [Emotiv/community-sdk#201]
Hello, 
I'm having some problem with this. Most of the values are 0. But when using xavier control panel performance metrics, it looks that is working ok.

I'm working with a emotiv insight.
I'm attaching the file it generates. 
[ES.zip](https://github.com/Emotiv/community-sdk/files/998125/ES.zip)

Thanks in advance.
Javier Sivack

**Comment by evanfantr** [comment]
Developer team says we need "EEG+PM" License to use Performance Metric project. Yet Customer Support team says these licenses are not available so we cannot get the emotion data. 

It feels like there are serious communication problems between EMOTIV departments

**Comment by hoangphamemotiv** [comment]
Hi @evanfantr 
Thank you for your feedback. 

Yes, you need "EEG + PM" license (Prime) to use Performance Metric project. 
for this issue: "Yet Customer Support team says these licenses are not available so we cannot get the emotion data."
i think Costomer Support wanted to say, to get Prime license, you need contact to us via hello at emotiv.com. the license is not available on the website.

**Comment by hoangphamemotiv** [comment]
Could you send me your ticket ID for supporting?
