### ISSUE TITLE
OSX: Not receiving Updates from XavierComposer

### ISSUE THREAD

**Issue by adriangoe** [Emotiv/community-sdk#202]
Tested in both Python and Java:

I can succesfully use `IEE_EngineRemoteConnect` to connect to XavierEmoComposer on my Mac with the most recent edk.framework. When XavierEmoComposer is not running I receive an error.

BUT: While the same EmoScript sent through cOmposer will record Events both in XavierControlPanel and when performing the same actions (in python or Java) on a Windows machine, on OSX (10.12.4) I only ever get `Ox600` or EDK_NO_EVENT as a response to `IEE_EngineGetNextEvent`. 

Has anyone else experienced the same problem and knows a solution? I cannot identify other applications interfering on port 1726 but it appears to be a problem where Mac EmoComposer and Mac edk.framework do not work well together. I don't yet have access to an actual headset to verify if the same problem occurs when working without Composer.

**Comment by manhtien2607** [comment]
hi 

On EmoComposer, you need to check on Auto reset checkbox and press Send. Then call remote connect should return emoengine event

**Comment by adriangoe** [comment]
I am aware of that and I am receiving a response which is always `EDK_NO_EVENT` in the python `emostate_logger.py` or java example. I know composer is successfully sending events though, because I can read them when I use the ControlPanel instead. 

To illustrate what I mean I added a print call with the current state returned from `IEE_EngineGetNextEvent(eEvent)` at every iteration while EmoComposer was sending events:
<img width="772" alt="screen shot 2017-05-16 at 11 47 13 am" src="https://cloud.githubusercontent.com/assets/14338700/26100264/ac306d2e-3a2d-11e7-8e2e-2866a70b2e79.png">

**Comment by manhtien2607** [comment]
thanks for your screenshot, it seems to be a problem with Mac library, i will check with objectivC sample to confirm it is native library or wrapper of python,java error

**Comment by adriangoe** [comment]
@manhtien2607 it appears that this is an issue with the 3.4 edk. I have now tried replacing the edk.framework with the 3.3 version and am now able to see that XavierComposer receives an `Expressiv_Get` request in the emoengine log, but then the python sample crashes for me.

I found a very similar issue reported in https://github.com/Emotiv/community-sdk/issues/185, so perhaps the issue is only that XavierComposer has not been updated to 3.4 for Mac yet? If so, could there be an update soon? I was hoping to be able to use performance metrics in my tool for which I require the 3.4 edk

**Comment by hoangphamemotiv** [comment]
Hi @adriangoe . we updated new version of Composer version 3.5.0. could you check it with the example?

**Comment by adriangoe** [comment]
@hoangphamemotiv , thank you for the update! The connection to the 3.5 Composer does indeed work now, but the program still crashes do to some missing ctype definitions:

For example, the following lines are missing:
```
EngineGetNextEvent = libEDK.IEE_EngineGetNextEvent
EngineGetNextEvent.restype = c_int
EngineGetNextEvent.argtypes = [c_void_p]

EmoEngineEventGetType = libEDK.IEE_EmoEngineEventGetType
EmoEngineEventGetType.restype = c_int
EmoEngineEventGetType.argtypes = [c_void_p]

EmoEngineEventGetUserId = libEDK.IEE_EmoEngineEventGetUserId
EmoEngineEventGetUserId.restype = c_int
EmoEngineEventGetUserId.argtypes = [c_void_p]

EmoEngineEventGetEmoState = libEDK.IEE_EmoEngineEventGetEmoState
EmoEngineEventGetEmoState.restype = c_int
EmoEngineEventGetEmoState.argtypes = [c_void_p, c_void_p]
```

If you'd like I'll put in a PR to fix this specific example

**Comment by 594464259** [comment]
![e74f140b59909429d18589485d77132](https://user-images.githubusercontent.com/44285737/50384997-6c52a880-0708-11e9-952c-28ad9c2610bf.png)
![6dd135ab4423131d8973a58ab283ed5](https://user-images.githubusercontent.com/44285737/50384999-6e1c6c00-0708-11e9-87d5-045a139e06c8.png)

I have struggled for several weeks, what should  I do ?

**Comment by 594464259** [comment]
> ![e74f140b59909429d18589485d77132](https://user-images.githubusercontent.com/44285737/50384997-6c52a880-0708-11e9-952c-28ad9c2610bf.png)
> ![6dd135ab4423131d8973a58ab283ed5](https://user-images.githubusercontent.com/44285737/50384999-6e1c6c00-0708-11e9-87d5-045a139e06c8.png)
> 
> 我已经挣了几个星期，我该怎么办？


Why I can't connect emocomposer
