### ISSUE TITLE
save or load profile failure

### ISSUE THREAD

**Issue by Glazera** [Emotiv/community-sdk#203]
Hi,
I’m creating an application in Java and at this moment i’m trying to detect mental commands. I’m using the MentalCommandWithCloudProfile.java example but i can’t save or load the user profile to the cloud. I have also tried the SavingAndLoadingProfileCloud.java example, also without success. I create more than one user in the cloud but always return the same failure result, however when i run the code for the first time to a new user the save works, but after that the save doesn’t work anymore.
Let me complement saying that i have tried to follow the steps to the training as shown in the code below (from MentalCommandWithCloudProfile.java) and i’m using Emotiv Epoc+ with the 3.3.3 sdk version.

`
System.out.println("Please do follow steps:");

        System.out.println("A. Press 1 to Active training session.");
        System.out.println("B. Press 2 to Start training NEUTRAL. When completed, press 3.");
        System.out.println("C. Press 3 to Start training RIGHT. When completed, press 4");
        System.out.println("D. Press 4 to Start training LEFT.");
        System.out.println("E. Press 5 to Set ActivationLevel.");
     System.out.println("=============================================================");

        System.out.println("Otherwise, press key below for more:");
        System.out.println();
        System.out.println("Press 6 to Read ActivationLevel.");
        System.out.println("Press 7 to Get OveralSkillRating.");
        System.out.println("Press 8 to Save Profile Data to the cloud.");
        System.out.println("Press 9 to Load Profile Data from cloud.");`

I lost hours searching in the forum but with no answer, so anyone can help me?

**Comment by tungntEmotiv** [comment]
Hi @Glazera 

Thank for your question. The issue might your Emotiv cloud profile contains Unicode character (not parse correctly in Linux) -> EC_GetUserDetail() return value 1. Please see the issue #195.
A workaround, You can check and remove Unicode character from your user information, only use ascii character.
Or you can wait sdk 3.5 for fixing this issue.

**Comment by Glazera** [comment]
I found out that the code of examples MentalCommandWithCloudProfile.java and SavingAndLoadingProfileCloud.java are wrong.
First because when using the method EC_UpdateUserProfile the parameter profileId should be the variable result, that is returned from  the method GetProfileId, instead of profileID.getValue().

wrong -` if (EmotivCloudClient.INSTANCE.EC_UpdateUserProfile(userCloudID, engineUserID, profileID.getValue()) == EdkErrorCode.EDK_OK.ToInt()) {`

right -` if (EmotivCloudClient.INSTANCE.EC_UpdateUserProfile(userCloudID, engineUserID, result) == EdkErrorCode.EDK_OK.ToInt()) {`

Second , in the method EC_UserProfile the parameter profileID.getValue() should be replaced by EmotivCloudClient.INSTANCE.EC_ProfileIDAtIndex(userCloudID, 0), as seen below.

wrong -`if (EmotivCloudClient.INSTANCE.EC_LoadUserProfile(userCloudID, engineUserID, profileID.getValue(), -1) == EdkErrorCode.EDK_OK.ToInt()) 				System.out.println("Loading finished");`

right - `if (EmotivCloudClient.INSTANCE.EC_LoadUserProfile(userCloudID, engineUserID, EmotivCloudClient.INSTANCE.EC_ProfileIDAtIndex(userCloudID, 0),                         -1) == EdkErrorCode.EDK_OK.ToInt())`

After this changes the code works fine. I finish saying that i found this solution watching the same example but for C#.
