### ISSUE TITLE
Example code EmoStateLogger.java always return 1536 (No Event)

### ISSUE THREAD

**Issue by zhangyuanxun** [Emotiv/community-sdk#204]
Hi,

I'm using emotiv device to do some researches. And I use the sdk example code EmoStateLogger.java always return 1536. Do you what reason is? 

My system is Mac OSX 10.12.4.

Thanks,
Yuanxun

**Comment by tungntEmotiv** [comment]
Hi @zhangyuanxun 
That's weird. Which sdk versions are you using ?
