### ISSUE TITLE
How to map mental commands to custom actions

### ISSUE THREAD

**Issue by randylewis7** [Emotiv/community-sdk#205]
We are trying to make a brain mouse with the emotive sdk kit. We used the rule in the xavier control panel to do clicking but could not find a way to move the mouse using that. Now we are trying to use the sdk and are looking at the mental commands with local profile example but cannot find where it actually registers commands so we can map them to custom actions. Any idea where we can find code that does this? Help would be much appreciated. My friend asked this question before and the topic was closed but we didn't get a satisfactory answer.

**Comment by peterpoliwoda** [comment]
The code for the profiles is included in the `/basic_examples` folder in the SDK.These however use the cloud based profiles that you can save into the EmotivCloud module and then technically load them up again.
The thing is, none of the examples work on a Mac (tried Java, Python and external NodeJs one working with the C++ version) which makes it really hard to start coding something up.

Let me join in asking if there's a way to access a local instance of the recorded mental commands profile, or perhaps, exporting the ones from the control panel into the cloud and then reload them?

**Comment by ddemsahin** [comment]
> The code for the profiles is included in the `/basic_examples` folder in the SDK.These however use the cloud based profiles that you can save into the EmotivCloud module and then technically load them up again.
> The thing is, none of the examples work on a Mac (tried Java, Python and external NodeJs one working with the C++ version) which makes it really hard to start coding something up.
> 
> Let me join in asking if there's a way to access a local instance of the recorded mental commands profile, or perhaps, exporting the ones from the control panel into the cloud and then reload them?

I am trying to run basic examples on Mac as well. Specifically, Unity example. I wonder did you find a way to run them ?

**Comment by randylewis7** [comment]
No, I never figured it out. Good luck!
