### ISSUE TITLE
unity error

### ISSUE THREAD

**Issue by andy112247** [Emotiv/community-sdk#206]
i use the (community-sdk)latest version \examples_basic\C# or  \examples_extra_prime\C#\DotNetEmotivSDK
Build DotNetEmotivSDK with .net3.5 x64  and run in unity 
it will be wrong 

Assets/scripts/EmotivCtrl.cs(90,81): error CS0117: `Emotiv.EmotivCloudClient' does not contain a definition for `EC_OK'

use community-sdk 3.3version  it will not appear like the above error
but....

DllNotFoundException: edk.dll
Emotiv.EdkDll.IEE_EmoEngineEventCreate ()
Emotiv.EmoEngine..ctor ()
Emotiv.EmoEngine.get_Instance ()
EmotivCtrl.Awake () (at Assets/scripts/EmotivCtrl.cs:26)

and 
NullReferenceException: Object reference not set to an instance of an object
CameraCtrl.LateUpdate () (at Assets/scripts/CameraCtrl.cs:30)
more  999+ erroe

http://i.imgur.com/z4c8q5L.png

**Comment by RuVT** [comment]
Can you please be more specific? 
Also try to take care of your writing, I just get that you have a DllNotFoundException problem, that means that Unity cant find where the edk.dll is. 

Do you followed this instructions?
https://docs.google.com/document/d/1zJCRSXfqEjjS3az3vCEFCTNA828HEM5TFkrUeKSwjGo/edit?usp=sharing

There are some steps to setup some system variables so unity can read the dlls.

**Comment by andy112247** [comment]
http://i.imgur.com/56nnzma.png
i have path C:\emotiv (from community-sdk-3.3.3 & community-sdk-develop)\bin\win32
also reBuild  DotNetEmotivSDK (x86)
but 
Assets/scripts/EmotivCtrl.cs(90,81): error CS0117: `Emotiv.EmotivCloudClient' does not contain a definition for `EC_OK'

**Comment by RuVT** [comment]
Use "EDK_OK" instead of "EC_OK", the new SDK changed some of the constant names.

**Comment by hoangphamemotiv** [comment]
Hi @andy112247 . 

For SDK 3.4 we use "EDK_OK" on ERROR_CODE instead of "EC_OK". 
But in SDK 3.3.3 it is still EC_OK. so, could you check your header files and version of SDK lib to see the issue?

**Comment by andy112247** [comment]
THAK YOU 
I use version 3.4 sdk
1.copy \bin\win32 to c:\\emotiv
2.add system path emotiv c:\\emotiv
3.open unity for x86
4.open \examples\Unity\RollingBall
5.build \C#\DotNetEmotivSDK
6.copy DotNetEmotivSDK.dll to unity
7.change ec_ok ->edk_ok

but 
RollingBall\Assets\scripts\EmotivCtrl.cs(67,67): Error CS0117: 'Emotiv.EmotivCloudClient' 不包含 'EDK_OK' 的定義 (CS0117) (Assembly-CSharp)
不包含  = no include
i think maybe \bin\win32 is not latest version ?

**Comment by andy112247** [comment]
use Emotiv.EmotivCloudClient.EC_OK 
->
Assets/scripts/EmotivCtrl.cs(90,67): error CS0117: `Emotiv.EmotivCloudClient' does not contain a definition for `EC_OK'


use EmotivCloudClient.EC_Connect () == Emotiv.EmotivCloudClient.EDK_OK
Assets/scripts/EmotivCtrl.cs(90,67): error CS0117: `Emotiv.EmotivCloudClient' does not contain a definition for `EDK_OK'

**Comment by RuVT** [comment]
The error code definition is inside EdkDll class, use `EdkDll.EDK_OK` instead of `Emotiv.EmotivCloudClient.EC_OK`

**Comment by andy112247** [comment]
Thank you, @RuVT .
but why 
Assets/scripts/EmotivCtrl.cs(114,38): error CS1501: No overload for method `EC_GetProfileId' takes `2' arguments
is unity bug?

int profileId = EmotivCloudClient.EC_GetProfileId (userCloudID,profileName.text);
public static extern int EC_GetProfileId(int userCloudID, String profileName, ref int profileID);

**Comment by andy112247** [comment]
and i run \examples\Unity\RollingBall\Builds\RollingBall_Win.exe
error message show 
The gyro could not be calibrated.  The headset must remain still for at least 0.5 secs.

**Comment by RuVT** [comment]
The definition if EC_GetProfileId has been changed, the new definition takes 3 arguments:

`EC_GetProfileId(int userCloudID, String profileName, ref int profileID);`

look at the new implementation of the function in this code: 
https://github.com/Emotiv/community-sdk/blob/master/examples_basic/C%23/SavingAndLoadingProfileCloud/Program.cs

The problem with the gyro is not a problem, not a bad one, it happends when you move a lot the headset, just wait 0.5 seconds with the headset still, is not a problem just a message to know when the gyro needs to be recalibrated.

**Comment by andy112247** [comment]
hahaha Thank you, @RuVT .
Just used for me
int profileId_temp=0;
int profileId = EmotivCloudClient.EC_GetProfileId (userCloudID, profileName.text,ref profileId_temp);
Also succeeded
Thank you very much for your help
