### ISSUE TITLE
blink, wink_left, wink_right in android

### ISSUE THREAD

**Issue by abujbr** [Emotiv/community-sdk#209]
hi
is there any example for detecting blink, wink_left or wink_right for android platform 

thanks :)

**Comment by duytan90** [comment]
Hey @abujbr, It's called Facial Expression, you may want take a look at this example https://github.com/Emotiv/community-sdk/tree/master/examples_basic/Android/FacialExpression

**Comment by abujbr** [comment]
found it thanks :)

I was searching for this code

 IEdk.IEE_EmoEngineEventGetEmoState();
                    if (IEmoStateDLL.IS_FacialExpressionIsRightWink() == 1||IEmoStateDLL.IS_FacialExpressionIsLeftWink() == 1||IEmoStateDLL.IS_FacialExpressionIsBlink()==1)
