### ISSUE TITLE
Error: cannot load EDK lib: examples_basic/Python/../../bin/linux64/libedk.so: file too short

### ISSUE THREAD

**Issue by wangwuqi** [Emotiv/community-sdk#212]
I run the python example in ubuntu16.04, and it cant work
```
wuqi@wuqi-VirtualBox:/media/sf_Ubuntushare/community-sdk-master/examples_basic/Python$ python MotionDataLogger.py 
Error: cannot load EDK lib: /media/sf_Ubuntushare/community-sdk-master/examples_basic/Python/../../bin/linux64/libedk.so: file too short
```

**Comment by havietnam** [comment]
Hi wangwuqi,
Is your libedk.so correct symlinks? This file is linked to libedk.so.3.
 You can quick fix by:
`#cp -f libedk.so.3.3.3 libedk.so.3 && ln -s libedk.so.3 libedk.so
`
Then try again

**Comment by Shahad56** [comment]
How to include those files to raspberry pi??
could you teach me??
