### ISSUE TITLE
emostate_logger.py symbol error

### ISSUE THREAD

**Issue by dcampbell24** [Emotiv/community-sdk#214]
This is on Ubuntu 17.04
```
➤ python --version
Python 2.7.13
```
```sh
➤ python emostate_logger.py 
Traceback (most recent call last):
  File "emostate_logger.py", line 120, in <module>
    IS_PerformanceMetricGetRelaxationModelParams = libEDK.IS_PerformanceMetricGetRelaxationModelParams
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/dlc/code/community-sdk/examples_basic/Python/../../bin/linux64/libedk.so: undefined symbol: IS_PerformanceMetricGetRelaxationModelParams
```

Does anyone know the cause of this issue?

**Comment by tungntEmotiv** [comment]
Hi @dcampbell24 
Same as [issue_210](https://github.com/Emotiv/community-sdk/issues/210). Currently, We dont support sdk 3.4 on Linux. Please wait next version of sdk
Thank you

**Comment by dcampbell24** [comment]
I am using version 3.3.3, the latest distributed for Linux in this repository. When will the next version be released?

**Comment by ecalot** [comment]
I think IS_PerformanceMetricGetRelaxationModelParams is a Performance Metric Symbol and was deprecated in 3.*

**Comment by hoangphamemotiv** [comment]
Hi @dcampbell24 

we will try to release Performance Metric feature for Linux next time. 
at the moment, please try the feature on Windows and Mac . 

Thanks. ^^!
