### ISSUE TITLE
Error updating local training profile (C#, Visual Studio 2017)

### ISSUE THREAD

**Issue by LMPombar** [Emotiv/community-sdk#218]
Hello, 

I'm trying to save and load local profiles with my Mental Training application in C#. 
Whenever I try to update a mental training action after loading a profile, I get this error:
`I am emoengine thread and crashed with Matrix Bound Error : Out of bounds error exception`

I'm unsure if this could be an error in my program or a bug on the Emotiv library.
I'm loading my profile like this:

```csharp
static void loadProfile()
{
     if (EdkDll.IEE_LoadUserProfile(0, profileName) == EdkDll.EDK_OK)
         Console.WriteLine("Profile loaded correctly");
     else
         Console.WriteLine("Can't load profile");
}
```

And after accepting a mental training I save the profile like this:

```csharp
internal static void engine_MentalCommandTrainingSucceeded(object sender, EmoEngineEventArgs e)
{
   ...
   if (EdkDll.IEE_SaveUserProfile(0, MainClass.profileName) == EdkDll.EDK_OK)
         Console.WriteLine("Profile saved correctly");
   else
         Console.WriteLine("Can't save profile");
}
```

The profile name is a string with the next format: `'./UserName.emu'` and it seems to be created properly each time. However, once I load it, any mental training will cause the error mentioned before.

Any ideas?

**Comment by LMPombar** [comment]
Please, I need help with this issue. I cannot finish my program until it is fixed.

**Comment by tungntEmotiv** [comment]
Hi @LMPombar 
I have tried to reproduce the issue with similar example (MentalCommandWithLocalProfile at C++) but there is no error. 
The error "I am emoengine thread and crashed with Matrix Bound Error : Out of bounds error exception" --> a exception in event handling but the root cause not clear.
The latest sdk version 3.5 is available now. Please get the sdk, the re-run your code and tell me the result.
Thank you

**Comment by LMPombar** [comment]
Hello @tungntEmotiv, 

I was using sdk version 3.4 up to now. 
I have updated to 3.5, and I'm not getting the error anymore, but the problem with mental trainings continues. 
Now, after training a mental action and getting it saved properly, the .emu file will get corrupted. 
Therefore after training I'm unable of loading the profile and therefore I lose all training data. Sometimes I get a System.AccessViolationException when 
accessing the profile file after that. 
Losing all training data is definitely a problem for continues uses of the application. 

I await your answer. 
Thank you very much, 

Laura 



----- Mensaje original -----

De: "tungntEmotiv" <notifications@github.com> 
Para: "Emotiv/community-sdk" <community-sdk@noreply.github.com> 
CC: "LMPombar" <l.mpombar@udc.es>, "Mention" <mention@noreply.github.com> 
Enviados: Lunes, 31 de Julio 2017 9:35:01 
Asunto: Re: [Emotiv/community-sdk] Error updating local training profile (C#, Visual Studio 2017) (#218) 



Hi @LMPombar 
I have tried to reproduce the issue with similar example (MentalCommandWithLocalProfile at C++) but there is no error. 
The error "I am emoengine thread and crashed with Matrix Bound Error : Out of bounds error exception" --> a exception in event handling but the root cause not clear. 
The latest sdk version 3.5 is available now. Please get the sdk, the re-run your code and tell me the result. 
Thank you

**Comment by LMPombar** [comment]
The saving problem seems to be solved when I don't save it until the end of the execution of the program, right before disconnecting the EmoEngine.
Is this how it's supposed to work?

**Comment by LMPombar** [comment]
The saving problem seems to be solved when I don't save it until the end of the execution of the program, right before disconnecting the EmoEngine.
Is this how it's supposed to work?

**Comment by tungntEmotiv** [comment]
Hi @LMPombar 
Yes, you can implement a key for exit while loop as MentalCommandWithCloudProfile example. After training finished -> save profile -> exit out of while loop. 
I will add a new example MentalCommandWithLocalProfile tomorrow for demo.

**Comment by LMPombar** [comment]
Thank you very much for your help. I will be checking the example to understand the proper way of doing it.
