### ISSUE TITLE
Can't connect over bluetooth on Ubuntu 17.04

### ISSUE THREAD

**Issue by dcampbell24** [Emotiv/community-sdk#219]
I followed the directions [here][bluetooth] and the connection fails:

[bluetooth]: https://github.com/Emotiv/community-sdk/blob/master/doc/Connecting%20on%20Ubuntu%20and%20Debian.md
```
[bluetooth]# connect CD:40:EC:FA:54:DC
Attempting to connect to CD:40:EC:FA:54:DC
Failed to connect: org.bluez.Error.Failed
```

**Comment by duytan90** [comment]
Hi @dcampbell24, have you tried with Ubuntu 16.04 LTS? The guide only mention about supporting Ubuntu14.04/15.10 and Debian 8.3 although I managed to get it work on Ubuntu 16.04.
http://imgur.com/a/BsLRX
Maybe you missed any configuring step?
