### ISSUE TITLE
FFTSample gives 1536 state no

### ISSUE THREAD

**Issue by minegu2017** [Emotiv/community-sdk#223]
Hello,
I have downloaded Community SDK and run FFTSample on Android 6.0.

When I run the code, on line 133,
int state = IEdk.IEE_EngineGetNextEvent();
				Log.e("TAG",String.valueOf(state));

The value of state becomes  1536.
What should I do to run the example. Myemotiv downloaddded from google play store runs without any problem.
Best

**Comment by minegu2017** [comment]
Hello, anyone will reply soon?
The Emotiv sdk version is 3.3.4

**Comment by duytan90** [comment]
Hey @minegu2017, have you tried modify this part of example bases on your headset type?
https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Android/FFTSample/app/src/main/java/com/example/fftsample/MainActivity.java#L149
The value of state indicates that your phone (yes these examples only run on real device) wasn't connected to your headset.

**Comment by minegu2017** [comment]
Yes, I have changed that to EPOC+ part.

**Comment by duytan90** [comment]
Once the app (example) fired up, it would ask for some permissions, and you will need to enable Location Service with High Accuracy. Also let try turn off/on the EPOC+ few times each 5 seconds.

**Comment by minegu2017** [comment]
Hello,

I have turned the Location service on, closed/opened EPOC+ a couple of
times. Nothing has changed.
Last year, I have developed another android app with Mantalcommand and it
was working. I am an experienced
programmer. When I have upgraded Android studio and gradle versions, it
started not functioning. I have also
tried to re-run the code I have developed last year, it does not work
either.
It has to do with emotiv SDK, or Android SDK versions. Let me write the
current versions I am using:

Android Studio 2.3.3

Android 6.0.1 (on phone)

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.example.fftsample"
        minSdkVersion 19
        targetSdkVersion 22
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles
getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    compile 'com.android.support:support-v4:23.0.1'
    compile 'com.emotiv.sdk:community:3.3.+@aar'
}

**Comment by minegu2017** [comment]
Hello,
I have manipulated the code a little bit, now it worked. I am not really
sure whether it is SDK problem, or coding problem.
Thanks,

**Comment by duytan90** [comment]
That's good to know. Sometimes low battery would make it harder to connect via Bluetooth though.

**Comment by minegu2017** [comment]
Thanks a lot for your help.
Best regards,

**Comment by viralparekh** [comment]
@minegu2017  can you elaborate how you managed to solve the problem.
I am working on FFTsample android app. I have also changed the code to connect it with epoch+
```
int number = IEdk.IEE_GetEpocPlusDeviceCount();
Log.e("#v","device count :"+number);
if(number != 0) {
if(!lock){
lock = true;
IEdk.IEE_ConnectEpocPlusDevice(0,false);
}
}
```

I am still getting a number of devices 0.
Can you give me some direction where can I look?

**Comment by minegu2017** [comment]
Hello. The Location service should be on, Bluetooth should be on, but EPOC+
should not be connected, only in devices in range.And EPOC+ device should
be on and charged well. And if you prepare this setup, it sees each other
somehow.
I haven't changed the code otherwise.
Best,

**Comment by viralparekh** [comment]
@minegu2017,  It worked.  I didn't turn on the location service.
I needed to switch on off it several times but finally, it is working.
Thank you for a prompt reply.

**Comment by minegu2017** [comment]
Blessings.
