### ISSUE TITLE
Unable to get .edf to work in EEG Lab

### ISSUE THREAD

**Issue by jimenyer** [Emotiv/community-sdk#224]
Hi, 

I am having issues uploading and viewing the .edf files in EEGLAB. I know that the issue has to do with the current .edf format. I already tried the two different way of fixing the format. However, none of them are working. 
Below you will see the graph that I currently get when I upload the current .edf file.  Please Help
 
![image](https://user-images.githubusercontent.com/30293586/28371386-d878135e-6c6a-11e7-8b65-f0df7873a93e.png)

All I want is a .edf file with 5 channels so I can see and analyze the data recorded. 

Please tell me what am I doing wrong? 

Please help, 
YJ

**Comment by hoangphamemotiv** [comment]
Hi @jimenyer 

Could you send us your file for checking? ^^!

**Comment by jimenyer** [comment]
Hi @hoangphamemotiv, 

Thank you for replying back :) 

Attached you will see my edf files and below you will see the details of how i am converting the files. 

1st method 
I downloaded the.  edf converter
I selected the .edf file that I wanted to convert 
The converter generated a file 
I went to EEGLAB and uploaded  new converted file
I went to see the data (see attachment) used the function (channel data scroll) 

2nd Method  
I downloaded  EdfHeaderConverter.exe
I copied getfiletype.m and sopen.m files to 'plugins\Biosig3.1.0\biosig\t200_FileAccess'.
I went to EEGLab click File > Import data > Using EEGLab functions and plugin > From EDF/EDF+/GDF files
I installed Biosig. 
I uploaded a .edf file and the same thing happen
 
[LearningTask_PA_01_edf_Files.zip](https://github.com/Emotiv/community-sdk/files/1165819/LearningTask_PA_01_edf_Files.zip)

I am not sure what I am doing wrong.

**Comment by nguyenvinhbinhktdo** [comment]
I downloaded your edf file, convert with EdfHeaderCOnverter (SDK 3.5 in github, develop branch).
file edf after converting run on eeglab (matlab 2015 32bit) without any error. about 5 channels you want to see -> you can seclect in option when you convert edf in eeglab

**Comment by jimenyer** [comment]
uhm, I been trying to do it and is not working for me. Did you my screenshots? 
What am I doing wrong? 

I just do not know. Can you send me a screenshot of that?

**Comment by nguyenvinhbinhktdo** [comment]
Hi @jimenyer , 
after converting edf file with Edf HeaderCOnverter , let's do as below:
1. Open it with eeglab (Figure 1);
1.1  when opening file, select chanel you wan to see (figure 2); you enter a numer corespoding with your channel(you can run eeglab example and get index of channels in csv file). with insight headset , 1= COUNTER, 3= AF3...
2. change Value  (Figure 3, 4) -> scale in graph is suitable with amplitude channel
3. You can adjust time range to display (Figure 5)
[EEglab.Emotiv.zip](https://github.com/Emotiv/community-sdk/files/1186425/EEglab.Emotiv.zip)
