### ISSUE TITLE
MotionDataLogger.py Gyro data

### ISSUE THREAD

**Issue by aro280994** [Emotiv/community-sdk#225]
I used MotionDataLogger.py but I don't know if Gyro X, Y and Z data give me correct information about the sensors. How can I know if the values are correct?
I'm using Emotiv Epoc+ headset.

**Comment by alanshare** [comment]
Hi @aro280994, the values you recieved from MotionDataLogger were raw data from sensors. To get exact rotation velocity of headset around X, Y, Z-axis, it requires some more calculations.
We are developing a program to solve your problem, please check this link to see the demo: https://www.youtube.com/watch?v=LJv8ROHaoc4
