### ISSUE TITLE
Mental State: NEUTRAL 	 Power: 0.0 and Battery Level: -1 out of 5

### ISSUE THREAD

**Issue by wangwuqi** [Emotiv/community-sdk#226]
I run MentalCommandWithCloudProfile.py and follow the instruction step by step, **after typing command 'running', but all the value of Power is 0.0** in the prints. Also,   **the Battery Level: -1 out of 5**

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: D:\jupyter_notebooks\emotiv_test\MentalCommandWithCloudProfile.py =
========================================================================
Example to show how to train Mental Commands from EmoEngine/EmoComposer.
========================================================================
Press '1' to start and connect to the EmoEngine                         
Press '2' to connect to the EmoComposer                                 
>> 
1
Logged in as robot
Enter your command. Enter "help" for commands
>>
New User 0 added
Following step for training...
1. save_profile (create/save profile to Cloud) or load_profile 
2. set_actions
3. training_action [neutral/push/pull]
4. training_start
5. training_accept or training_reject
Optional: training_erase, status, report
Battery Level: -1 out of 5
Wireless Strength: Good Signal
Number of Contact: 18
IEE_CHAN_CMS 	 : Good
IEE_CHAN_DRL 	 : Good
IEE_CHAN_FP1 	 : No Signal
IEE_CHAN_AF3 	 : No Signal
IEE_CHAN_F7 	 : Good
IEE_CHAN_F3 	 : No Signal
IEE_CHAN_FC5 	 : Good
IEE_CHAN_T7 	 : Good
IEE_CHAN_P7 	 : Good
IEE_CHAN_Pz 	 : Poor
IEE_CHAN_O1 	 : Good
IEE_CHAN_O2 	 : Good
IEE_CHAN_P8 	 : Good
IEE_CHAN_T8 	 : Good
IEE_CHAN_FC6 	 : Good
IEE_CHAN_F4 	 : Good
IEE_CHAN_F8 	 : Good
IEE_CHAN_AF4 	 : Good
PUSH and PULL set active for userMental Command Signature for User  00  . UPDATED!

Setting Mental Command Training Action NEUTRAL for user 0 !
Training forMental Command Training for User  NEUTRAL0  Start! STARTED!

Mental Command Training for User 0 SUCCEEDED! Type "training_accept" or "training_reject"
Accepting Training for NEUTRAL
Mental Command Training for User 0  COMPLETED!
PUSH and PULL set active for user 0 .
Mental Command Signature for User 0  UPDATED!
Setting Mental Command Training Action PUSH for user 0 !
Training forMental Command Training for User  PUSH0  Start! STARTED!

Mental Command Training for User 0 SUCCEEDED! Type "training_accept" or "training_reject"
Accepting Training for PUSH
Mental Command Training for User 0  COMPLETED!
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power: 0.0
Mental State: NEUTRAL 	 Power:
Traceback (most recent call last):
  File "D:\jupyter_notebooks\emotiv_test\MentalCommandWithCloudProfile.py", line 428, in <module>
    print "Mental State:",IEE_MentalCommandAction_enum[mental_state],"\t Power:",power
  File "C:\Python27\lib\idlelib\PyShell.py", line 1356, in write
    return self.shell.write(s, self.tags)
KeyboardInterrupt
>>> 
```

**Comment by wangwuqi** [comment]
solved

**Comment by tungntEmotiv** [comment]
Hi @wangwuqi 

We have a new sdk version: 3.5. Please update and re-check battery level issue and inform me the result. In my quick test with new version i dont see the issue.
Thank you.

**Comment by LMPombar** [comment]
I have this problem too even with sdk 3.5. The headset battery levels are always -1. 
I ran the HeadsetInformationLogger example in C# and got this:

> User Added Event has occured
> 0,GOOD_SIG,-1,
> 0,NO_SIG,-1,
> 3,959649,NO_SIG,0,
> 3,959649,GOOD_SIG,0,
> 4,37242,GOOD_SIG,0,
> 4,435962,GOOD_SIG,4,
> 4,531125,GOOD_SIG,4,
> 4,562945,GOOD_SIG,4,
> 4,689929,GOOD_SIG,4,
> 4,816912,GOOD_SIG,4,
> 4,943896,GOOD_SIG,-1,
> 5,070879,GOOD_SIG,-1,
> 5,205243,GOOD_SIG,-1,
> 5,331827,GOOD_SIG,-1,
> 5,45821,GOOD_SIG,-1,
> 5,584594,GOOD_SIG,-1,
> 5,711077,GOOD_SIG,-1,
> 5,845341,GOOD_SIG,-1,
> 5,971624,GOOD_SIG,-1,
> 6,097808,GOOD_SIG,-1,
> 6,224092,GOOD_SIG,-1,
> 6,358155,GOOD_SIG,-1,
> 6,484139,GOOD_SIG,-1,
> 6,610522,GOOD_SIG,-1,
> 6,736706,GOOD_SIG,-1,
> 6,862689,GOOD_SIG,-1,
> 6,988473,GOOD_SIG,-1,
> 7,114457,GOOD_SIG,-1,
> 7,24044,GOOD_SIG,-1,
> ...

The only other number I get is always 4, even though the headset is almost discharged (in every other test I've done, whenever I don't get a -1 I always get a 4, which is weird), so I can never be sure of the headset true battery levels and therefore it may suddenly run out of battery.

**Comment by hoangphamemotiv** [comment]
Hi @LMPombar 

this is a issue in the headset firmware. sometime the battery lv is -1. could you unplugin your dongle or reconnect BTLE to resolve this issue?

**Comment by LMPombar** [comment]
Yes, after unplugin and plugin the dongle sometimes it gets a value of 4 for a second or so, and then returns to -1. But I found it strange that the only other value I get aside from -1 is 4. I've been using the headset continuously since yesterday and I still get a 4.

**Comment by roxelana** [comment]
Hi all,

I'm experiencing the same issues with the Python 3.5 SDK MentalCommand example code.  The output was the same just before and just after unplugging and replugging the dongle.  Here is my output:

Press '1' to start and connect to the EmoEngine
Press '2' to connect to the EmoComposer
>>
1
Logged in as (name)
Enter your command. Enter "help" for commands
>>
New User 0 added
status
Battery Level: -1 out of 5
Wireless Strength: Good Signal
Number of Contact: 18
IEE_CHAN_CMS     : Good
IEE_CHAN_DRL     : Good
IEE_CHAN_FP1     : Good
IEE_CHAN_AF3     : Good
IEE_CHAN_F7      : Good
IEE_CHAN_F3      : Good
IEE_CHAN_FC5     : Good
IEE_CHAN_T7      : Good
IEE_CHAN_P7      : Good
IEE_CHAN_Pz      : No Signal
IEE_CHAN_O1      : Good
IEE_CHAN_O2      : No Signal
IEE_CHAN_P8      : No Signal
IEE_CHAN_T8      : Good
IEE_CHAN_FC6     : Good
IEE_CHAN_F4      : Good
IEE_CHAN_F8      : Good
IEE_CHAN_AF4     : Good

**Comment by hoangphamemotiv** [comment]
yes. we are still checking this issue. hope fix it soon.

**Comment by Tcppa** [comment]
Hi there. How did you solve the NEUTRAL 0.0 problem?
I'm running SDK version 3.4 -> MentalCommandWithLocalProfile and all it shows is continuously NEUTRAL: 0.0.
Thank you

**Comment by wangwuqi** [comment]
have anyone encountered and solved the power value problem?

**Comment by hoangphamemotiv** [comment]
Hi all.
The issue Battery level = -1 is a bug in our firmware in Epoc+ headset, sometime it happen. we are sorry about this issue. 
for issue about the NEUTRAL 0.0, maybe you missed some steps on training profile? can you tell me more detail about that?

**Comment by TommasoChiantini** [comment]
Thanks for answering!
Is a release of the firmware expected to fix the bug? 
Is it possible to upgrade the firmware on current epoc + headset?

**Comment by hoangphamemotiv** [comment]
We are fixing this issue. and it will be updated in next version of Cortex service. 
SDK 3.5.1 is final version of SDK library.

**Comment by abartolomei** [comment]
Hi all.
how do you know which epoc+ firmware is affected by this problem? 
Is there a serial number to understand if the headset is affected by this problem?

**Comment by hoangphamemotiv** [comment]
Hi all
We checked the battery issue in software and hardware . the issue often happen on aged battery. 
we also fixed some issues related to battery level in next release  Cortex v1.4 which will be released very soon.
