### ISSUE TITLE
EmoKey not executing?

### ISSUE THREAD

**Issue by roxelana** [Emotiv/community-sdk#229]
Hi everyone!

The SDK lists instructions for EmoKey here: https://github.com/duytan90/SDKdocs/blob/master/User%20Manual%20for%20Emotiv%20Xavier%20Composer%20and%20EmoKey/readme.md

It says that the "light" under enabled turns green when conditions are satisfied.  Why are mine gold, and does this explain why it's not sending the keystrokes to my window?  Do some keystrokes not work in EmoKey?  See screenshot...

Thanks!

![screenshot 20](https://user-images.githubusercontent.com/30724611/28983960-d20dd186-7929-11e7-9d4b-82c793847823.png)

**Comment by hoangphamemotiv** [comment]
Hi @roxelana 
i see, you got the document from : https://github.com/duytan90  user: duytan90 and it is outdate. could you check with latest version 3.5.0 of Emokey? 
https://github.com/Emotiv/community-sdk/tree/master/tools/XavierEmoKey

Thanks. ^^!

**Comment by roxelana** [comment]
Hi again,
I eventually got it working with Version 3.3.2, and am now using 3.5.  One thing I am noticing across both versions is that, if I click that I want it to react to "Push," and it does not work, when I double-click on "Push" it says "Right," as if it had automatically dropped down.  It is also inconsistent, and even when Xavier Control Panel shows with 97% certainty that I am producing my intended signal, the keystroke is not sent.  Have you seen this with others?  Any idea what is happening or how to fix it?
Thanks!

**Comment by roxelana** [comment]
If it helps, I am using Windows 64, and am sending to a specified window.

**Comment by roxelana** [comment]
Hi again, see screenshots so you get a sense of what is going on.  I am connected to Xavier but the lights are just not activating.  Couldn't get a photo earlier this afternoon, but even when the lights were green, nothing happened in my Tkinter widget.  
![screenshot 21](https://user-images.githubusercontent.com/30724611/29048810-896acdc0-7ba0-11e7-993b-7b62ee016d58.png)
![screenshot 23](https://user-images.githubusercontent.com/30724611/29048794-7b050b74-7ba0-11e7-9cdd-98fe29b821f0.png)

**Comment by tungntEmotiv** [comment]
Hi @roxelana 
Thank for your raising the issue. I have reproduced your issue. Yes, that is a issue between CP and Emokey. 
I have also checked Composer with Emokey -> work well.
We are working on Control Panel 3.5 and hope release the version asap.

**Comment by roxelana** [comment]
Great, thanks!  Do you know if it's related to issue #231?

**Comment by tungntEmotiv** [comment]
I havent try with Tkinter. But i think can work with Tkinter. Yes, i am checking the issue with CP 3.3.3

**Comment by roxelana** [comment]
Thanks, I appreciate it.  Have you heard of any others having the issue, or have you replicated the problem, of EmoKey not sending certain keystrokes?  Or maybe it is just a matter of how I have set up my code to receive the keystrokes, if the emulations are different than the real key presses?
Also, are you sure the problem is with the Control Panel?  My current Control Panel seems to work just fine and former versions of EmoKey seem to have sent at least some letters.  Maybe the issue is just that Emokey 3.5 isn't connecting?

**Comment by ivankras** [comment]
Hi! I've got Emokey 3.5 (same happened on 3.3.4) and an EPOC+ running on Windows 10. I set a mapping. When I try to use it, even comparing to Xavier Control Panel response, I get no answer from Emokey, not even a green "Enabled" when trying with a simple raise brow to get an 'a' character. I'm becoming dissapointed, so I expect a solution, soon

**Comment by tungntEmotiv** [comment]
Hi @ivankras 
The Emokey 3.5 only work well with Control Panel 3.5 which we are developing. We hope to release the new version of Control Panel  next week. Please wait us. Thank you

Hi @roxelana  I have replied your issues with Tkinter at https://github.com/Emotiv/community-sdk/issues/231. Please check, if you have any concern or have solution , dont mind contacting us.
