### ISSUE TITLE
Error at IEE_LicenseAuthorization of edk.dll 

### ISSUE THREAD

**Issue by paigepham** [Emotiv/community-sdk#230]
Hi ALL,
I have trouble in running license activator with C++. I believe there is error within IEEE_LicenseAuthorization that an error code can not be returned. 

I think that the error is within the EDK dll file. Is there anyway that we can fix this?
Thanks!

**Comment by hoangphamemotiv** [comment]
Hi @paigepham 
What version of the lib are you using? The API only in v3.5.

**Comment by paigepham** [comment]
I used the most updated version (3.5) and I have purchased the EmotivPro which should allow me to do activate the license.
Thanks.

**Comment by paigepham** [comment]
Hi Hoang,
I also tried to ran the EmotivTool version 2 and the program stops working as I tried to authorize the license using debit number.
By the way do you have any idea what is debit number should I use to authorize the license?
Thank you so much.

**Comment by hoangphamemotiv** [comment]
Debit to allow you get a number of session from your license. 
Hum. Look like the api is not available in the lib. But, i just checked it, everything still okay. Could you check your project again to make sure the lib is 3.5?

**Comment by paigepham** [comment]
I specified the path for lib directly from the Emotiv SDK folder which i believe it should be the updated version. Other than that, please show me how to find out the version of lib that i am using.
I have noticed that I have to update all platform toolset from Version 120 to 141 for all projects before running ActivateLicense.
Thanks.

**Comment by hoangphamemotiv** [comment]
Hi @paigepham 
Could you send me your lib? i will check it. did you build the example as 32bit or 64bit?

**Comment by paigepham** [comment]
I built the example as 32bit. The lib file is attached.
Thanks.
[lib.zip](https://github.com/Emotiv/community-sdk/files/1208133/lib.zip)

**Comment by hoangphamemotiv** [comment]
Hi @paigepham . i got files you sent. but, after that i removed your message because it contains your build which can access to your license. 
i run ActivateLicense.exe. it works for me. and i checked the lib, the lib is correct. i think your project has some issues in config.

**Comment by paigepham** [comment]
Hi Hoang,

I use the C++ solution example directly from the Sdk, so I figured there shouldn't be any problem with the configuration. I believe that different platform version is the issue as I am using version 141 and the sample is v120.
I checked all the lib and include paths and also reconfigured the paths but it doesn't seem doing anything.

Tien Pham

Integrated Engineering Student

Twin Cities Engineering Program

Minnesota State University, Mankato

On Aug 8, 2017, at 9:25 PM, Pham Hoang <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @paigepham<https://github.com/paigepham> . i got files you sent. but, after that i removed your message because it contains your build which can access to your license.
i run ActivateLicense.exe. it works for me. and i checked the lib, the lib is correct. i think your project has some issues in config.

**Comment by hoangphamemotiv** [comment]
Hi @paigepham . 
Could you send me teamviewID?

**Comment by paigepham** [comment]
Hi Hoang,
I have tried to use LabVIEW to get ddl directly to use all functions from the dll and it works. The AuthorizeLicense and EC_connect both work fine. However, I got code 0x2022 (EDK License no EEG even though it is EmotivPro) at DataUpdateHandle when UserID is 4096. 
In my Emotiv account I saw that the device limit and installation are both 3, when I am using on 1 device only.

**Comment by hoangphamemotiv** [comment]
Hi @paigepham . 
you got device limited because you share your license here a public place. so, someone can use it. 
i just removed your image above. and fix the issue for you. please take care next time. ^^!
please try again. thanks.

**Comment by paigepham** [comment]
Hi Hoang,
Thank you so much for your help with the installation and license. 
I still get the 0x0001 from DataUpdateHandle function. What I have now for the function is 
intptr_t IEE_DataUpdateHandle(int32_t usedID, intptr_t hData);
The return value of this function is 0 if the value of userID is 0, but it is 8226 as long as the userID is 4096.
