### ISSUE TITLE
EmoKey only sending certain keystrokes

### ISSUE THREAD

**Issue by roxelana** [Emotiv/community-sdk#231]
Hello!  I've opened a new ticket because this is a different issue than #229.

I am trying to navigate a Python Tkinter widget using EmoKey.  When I use actual keystrokes manually entered from my keyboard, it works just like it's supposed to.  I have created one event handler, let's call it handlername, and tried binding it to the mouse left button click and to the lowercase letter a, just to test.  When I use EmoKey (3.3.3 -- I actually couldn't get my signals to be enabled in 3.5), it continually works on the mouse left button click, which I can tell because it only performs the function when the mouse arrow is hovering over the element, but the green "enabled" signal does not even activate for the "a" mapping.  When I had Lb.focus_set() on for this handler, even the mouse click did not work. Similarly, another function using a hot key (down arrow) shows the green "enabled" signal but the widget action does not occur, even though it works just fine with the manual keypress.

My questions: does Emokey send some functions and not others?  Is there something I'm missing about the way it emulates keystrokes which differs from manual keypresses that would help me bind to them in Python?  Could it even be my computer?  I am using Windows 10, 64-bit.

Thank you!  I look forward to your assistance and am excited to use Emokey!

**Comment by roxelana** [comment]
An update:
I've confirmed via Microsoft Word that at least the letter "a" is getting sent when I use EmoKey 3.3.4.  So that's good.  It just wasn't showing in my widget.
Now the question is how to get the Tkinter widget to recognize the keystroke.  It doesn't work as expected when I issue the keystroke, even though I can see that the keystroke is emulated.  I've tried sending it to either child or to the top layer, setting the keyboard focus, sending it to the command prompt, etc... Can it work in Tkinter?
Will keep trying and post with updates as I move ahead!

**Comment by tungntEmotiv** [comment]
Hi @roxelana 
I am not familliar with Tkinter but i have create a mini example to get input from keyboard. Then i have tried with Emokey 3.3.3 (with CP 3.3.3) -> work well. So i think it work in Tkinter. I am using  Python 3.5.1.
You can see the below picture
![emokey_tkinter](https://user-images.githubusercontent.com/21233798/29443936-cfb5bcc8-8405-11e7-9b1e-2ebd6481a98c.png)

Could you tried again with new version python ?
