### ISSUE TITLE
Raspbian Jessie GyroData is not working

### ISSUE THREAD

**Issue by JaviHer93** [Emotiv/community-sdk#232]
Test environment: Raspbian Jessie 
Target: Insight
Connection Method: USB Dongle
Language: C++

I tested the example Gyro Data under macOS and works perfectly, but then when I tried to run it under Raspbian the same example does'nt work, the program just display the EDK_GYRO_NOT_CALIBRATED message "Gyro is not calibrated. Please stay still." and never stop. 

I downloaded the new libedk.so3.3.3 but it doesn't work, also I try changing the libedkso.3.3.1, because  I saw in  a preview Issue under Ubuntu that with that version works, but I still getting those messages.

Any suggestions? Thank you!

**Comment by JaviHer93** [comment]
New update

I tried using the MotionDataLogger, and again it doesn't work.
**Also, I tested under macOS and again, it works. I made a littles changes here is the console output:**


Buffer size in secs:1
User added
Updated 4
Sample: 0
106,8107,8360,8259,6537,4305,8078,8174,7756,7950,0.00781616,
Sample: 1
107,8102,8359,8256,6576,4393,8083,8174,7756,7950,0.0156323,
Sample: 2
108,8106,8354,8257,6602,4398,8078,8176,7756,7952,0.0234485,
Sample: 3
109,8109,8357,8256,6516,4404,8073,8172,7755,7947,0.0312647,

Updated 4
Sample: 0
110,8107,8357,8262,6557,4427,8084,8175,7753,7950,0.0391449,
Sample: 1
111,8109,8357,8256,6561,4349,8093,8173,7764,7951,0.0470251,
Sample: 2
112,8114,8367,8252,6544,4340,8091,8173,7764,7951,0.0549053,
Sample: 3
113,8103,8369,8260,6532,4279,8091,8175,7754,7950,0.0627855,

**And here is the console output from Raspbian Jessie:**

Updated 4
Sample: 0
128,14222,9304,11074,15821,11596,15332,8574,6006,563,3.06365,
Sample: 1
128,13721,10366,8292,9665,4950,14508,9826,11025,6086,3.07205,
Sample: 2
56,14069,12168,7857,10148,5887,14109,3036,4754,10027,3.08046,
Sample: 3
128,16205,11528,2187,8383,1984,11161,7059,14081,191,3.08881,

Updated 8
Sample: 0
128,3320,8252,9723,10694,6827,7869,16014,15260,16004,3.09721,
Sample: 1
128,2527,15573,2262,911,11404,5839,5102,14786,14164,3.10562,
Sample: 2
97,14634,15428,9154,3409,7898,6671,14944,4090,1379,3.11402,
Sample: 3
38,15320,13878,4104,2409,14494,12845,3630,10962,14100,3.12243,
Sample: 4
128,10356,8315,2309,750,8188,293,10057,1364,6444,3.13083,
Sample: 5
111,3240,3277,14159,10191,6888,16102,670,5237,11884,3.13919,
Sample: 6
128,753,9940,15495,12451,3847,499,3251,9548,10998,3.14754,
Sample: 7
41,1490,9946,598,8145,15999,5824,8258,720,4284,3.1559,

Updated 4
Sample: 0
2,5325,12358,13269,9454,6203,12713,3294,12554,4195,3.16425,
Sample: 1
128,1157,1412,9649,11103,102,5731,1810,11930,8434,3.17265,
Sample: 2
122,10037,6038,4170,5184,13010,1810,7511,10462,5226,3.18106,
Sample: 3
128,9396,2082,11844,6516,14749,2477,934,2981,2010,3.18946,

Updated 4
Sample: 0
100,9381,3212,8255,585,5947,12686,8951,3463,2143,3.19785,
Sample: 1
96,4484,14358,6219,1023,16356,3227,6202,3131,10215,3.20623,
Sample: 2
128,9152,13792,9445,16119,8977,8169,4350,11230,11810,3.21461,
Sample: 3
20,12601,8085,1373,2218,4518,6129,4380,3492,10906,3.223,

**I really need to find a way to fix this soon, if someone may give any suggestion I'll really appreciate it.**

**Comment by havietnam** [comment]
Can you tell me headset ID and firmware version?
You can use Control Panel to get.

**Comment by JaviHer93** [comment]
Here is the info that I get from Control Panel

hardware information:
User 0: Headset [0x925]

**Comment by JaviHer93** [comment]
Any update?

**Comment by havietnam** [comment]
@JaviHer93 
Now, you can check out a698ef1 and check again. I found a bug and fixed.
Thanks
