### ISSUE TITLE
Can't connect with Emotiv Cloud

### ISSUE THREAD

**Issue by ireneeperez** [Emotiv/community-sdk#234]
Hello all, 
I'm having some troubles with Emotiv Cloud APIs in Ubuntu 16.04.
First of all, API prints repeatedly ```error adding certificate```
Even with this, I'm able to connect to Emotiv Cloud and log in. I can even get a list of the available profiles within my account.
But, I'm not able to load a profile. I can't find the profile ID using EC_GetProfileId function (it returns a value which is not EDK_OK). Also, the function EC_LoadUserProfile returns another value.
In the end, the result of all of this is that all the detection features are broken when trying to load a profile.
In addition to this, EC_UploadProfileFile and EC_DownloadProfileFile are not available in libedk.so file:

```
/home/irene/community-sdk-master/examples_basic/C++/SavingAndLoadingProfileCloud/main.cpp:189: referencia a `EC_UploadProfileFile' sin definir
/home/irene/community-sdk-master/examples_basic/C++/SavingAndLoadingProfileCloud/main.cpp:213: referencia a `EC_DownloadProfileFile' sin definir
collect2: error: ld returned 1 exit status
```

PS: I'm using C++ API in Ubuntu 16.04.4 (x64) with GCC 5.4.0

**Comment by tungntEmotiv** [comment]
Hi @ireneeperez 
You might get the issue of profile which fixed in the latest sdk 3.5. We regret that we only support sdk 3.3.3 on ubuntu . Can you get the latest library on mac/ win ?

**Comment by ireneeperez** [comment]
First of all, thanks for answering, @tungntEmotiv .

Regarding your question, I can't because I'm using Emotiv with ROS to publish messages in another ROS machine, which moves a robot. Everything works properly except for this issue I've explained, and I don't have enough time to start programming a new way of communicating.
Do you know when will the latest SDK be released on Ubuntu? It'll be really helpful for my project.

**Comment by Mforcen** [comment]
I have the same problem there.
I have been using Ubuntu for some projects, and I would like to add support for Emotiv Systems, but some functions are not working in libedk.so.3.3.3, so it would be good to know when a new version of SDK will be released for Linux.
Thanks in advance.

**Comment by hoangphamemotiv** [comment]
Hi @Mforcen . 
We haven't had exact release day for SDK 3.5 for Linux. hope it will come in near future. 
Thanks. ^^!
