### ISSUE TITLE
Can't get Emotiv to work on Unity Android built

### ISSUE THREAD

**Issue by KHvic** [Emotiv/community-sdk#236]
According to the documentation (from Unity Plugin Support)

I have to modify UnityActivityPlayer.java and AndroidManifest.xml
However, the documentation isn't very clear where to edit them. And it is apparent that the device is not connected to my application

The following stuff I did: 
1. placed libedk.so in Unity Editor Asset/Plugin/Android/libs
2. Modified UnityActivityPlayer.java located at Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Source\com\unity3d\player according to the image in documentation.
3. Modified AndroidManifest.xml according to the image in documentation and placed it in Asset/Plugin/Android

I am using version 3.3.3
Any idea?

**Comment by HachemLamti** [comment]
I am just getting the same error. Did anyone managed to make the default projects (controlpannel or mentalcommand) deployed on Android platform ? The documentation is very poor and make the plugin doesn't worth its price

**Comment by KHvic** [comment]
I have tried various method for the past 2 weeks. Still can't get it to work unfortunately.

**Comment by HachemLamti** [comment]
I noticed that the android librairies used in emotivcontrolpanel project
are different from those used in mentalcommand. For the former, an error
"user id not identified" is displayed (it was the same error when you don't
plug the usb adapter for desktop platform). On the other side, for the
mental command project, no error is displayed but it doesn't work. I even
added a bluetooth plugin to connect the application to the headgear but
none of these came with fruitful results.

Please help

**Comment by KHvic** [comment]
I am sorry, I can't help you out on this as I am also still figuring out how.
Hope they will get back to us here.

@nguoithichkhampha  @hoangphamemotiv 

Can you help us out on this matter. @HachemLamti

**Comment by hoangphamemotiv** [comment]
Hi @KHvic , @HachemLamti 

Did you put Plugins folder from : .\Emotiv_Plugin\Plugins to example\MentalCommand\Assets\Plugins ?
i think the issue come from the app cannot load the edk lib. 
Could you send more infos in log tools while the app running?

**Comment by KHvic** [comment]
hi @hoangphamemotiv ,

libedk.so is placed in the correct directory, I have checked the builded .apk file by unzipping the content, confirmed libedk.so is there.

Other than that, the app does ask for bluetooth permission, so the AndroidManifest.xml should also be correct.

All that is left is editing of UnityActivityPlayer.java, this part I am not too sure about it as it wasn't too clear in the documentation.

How would I be able to get the log regarding this? thanks

**Comment by hoangphamemotiv** [comment]
Hi @KHvic, 

you can get some logs by a tool as here: https://unity3d.com/learn/tutorials/topics/mobile-touch/building-your-unity-game-android-device-testing
after than you can search : "unity" text to find a log from your app built by Unity.

**Comment by miscrealitystudios** [comment]
use unity 5.6 32 bit and place edk.dll file inside assets/plugins
