### ISSUE TITLE
Crash in objective-c edk IEE_EngineGetNextEvent / Curl_resolv_timeout / addbyter

### ISSUE THREAD

**Issue by jpenca** [Emotiv/community-sdk#238]
hello,

the SDK frequently crashes for us. Xcode doesn't print a stack trace, but looks like it's in IEE_EngineGetNextEvent, a EXC_BAD_ACCESS is thrown, related to some functions "addbyter" and "Curl_resolv_timeout".

Could this be user error? If not, this is a serious issue rendering the EDK unusable for us.

**Comment by duytan90** [comment]
Hi @jpenca, does the crash happen on original example code? If so can you specify your Macbook specs, Xcode/OSX version?

**Comment by jpenca** [comment]
Hi @duytan90 - at this time the pro license subscription which we purchased refuses to function on the macOS machine so I cannot test this further.

**Comment by duytan90** [comment]
Have you tried basic examples (which doesn't require paid license) on your Mac @jpenca ? About the license issue, you may need to contact/send ticket to Emotiv Customer Support. Also on MacOS, you can use either C++, Java or Objective-C examples.
