### ISSUE TITLE
State of documentation

### ISSUE THREAD

**Issue by matanster** [Emotiv/community-sdk#240]
I find the documentation set clumsy and sub-optimal for getting started, and moreso for understanding short of days of experimentation, which API provide which ability for which supported device. I humbly think the developer program should get a serious upgrade or retrofit, to properly enable interested developers having a taste for efficiency.

**Comment by tungntEmotiv** [comment]
Hi @matanster 

Thanks for your feedback. Yes, we are going forward to make Emotiv's product/ software clearer and easier for developers.
I would like to share with you about my experiences how to approach the community-sdk for first time at Emotiv
1) README
2) Overview Getting_started_with_Emotiv_SDK.pdf
3) Praticing examples -> make me more understand about APIs(description in header files)
4) Try others Emotiv's product (Control panel, composer, emokey, ...), Emotiv Tool for checking and activating license....
...
Once again, thank you. If you have any feedback , please let us know.
Regards,
Tung
