### ISSUE TITLE
Multiple dongles, EPOC+, C#: Slowdown in raw data acquisition

### ISSUE THREAD

**Issue by jpenca** [Emotiv/community-sdk#241]
Hi,
using the C# API, we are getting raw data from EPOC+ using the provided sample code. We modified this code to keep track of 2 connected users, and iterate over these to acquire data for both of them.

We are seeing a problem here - with only one device connected, the data stream looks good and is coming in quick (something like 6-8 frames for each GetData call in the Run loop)

As soon as the second device connects, there is a massive drop in performance. the buffered chunks for both devices are much larger and it looks like there are dropouts as well.

Is there a pattern you would recommend to fix this? Looks like an issue with your SDK to me, but wouldn't know since there isn't really an example which shows how to read raw data from multiple devices.

thanks!

**Comment by hoangphamemotiv** [comment]
Hi @jpenca, 

this is a issue in our SDK with multi headset. look like the buffer not good in this case. we will check the issue and fix it soon. 
in other info, data streams can be slower but, it shouldn't lost sample for you.
