### ISSUE TITLE
Integrate Emotiv Community SDK with C# projects

### ISSUE THREAD

**Issue by DA93** [Emotiv/community-sdk#242]
Dears,

I have an experience with Emotiv Research edition SDK, and now, i'm doing my best to move to
Emotiv Community SDK. But it seems that the two versions of Emotiv SDK are different! 
When i tried to use the new version to make use of the new version of EPOC+ headset, i was not able to integrate the SDK with my C# project; since edk_utils.dll is no longer available in this version. As a result of that, when I try to create an instance of User profile class to hold user profile, as the following line of code,  it shows me: "The type or namespace of 'Profile' could not be found".

public static Profile profile = new Profile() ;  

i would appreciate it if i can know how can i integrate and make use of Emotiv Community SDK to develop C# applications ASAP.
And thank you in advance.

**Comment by hoangphamemotiv** [comment]
Hi @DA93, 
Your SDK version is old. so, the wrapper changed some thing. 
in new versions, we dont use edk_utils.dll anymore, it integrated to edk.dll. so you can remove it out of your project. 
For training profile feature, you may want to try with Training_Profile cloud and local to see how it works in new versions. 
thanks. ^^!

**Comment by DA93** [comment]
Thank you @hoangphamemotiv for your quick reply!
Regarding to create an instance of training profile on local [or on cloud], it's not mentioned in your guideline here: [https://github.com/Emotiv/community-sdk/blob/master/doc/How%20to%20run%20C%23%20example.pdf](url)

Notice that Emotiv SDK has been used to solve a complex problem in a research based project. So, the goal of the project is to investigate and solve project's problem, not to wasting developers' time to discover how can they create an instance of Emotiv Training_Profile in C#  to hold user's trained brain signals ^ ^!

Your clarifications are highly appreciated :)
And thank you in advance!

**Comment by DA93** [comment]
Hi @hoangphamemotiv ,
Reference to EEG Data Logger Example, here:
https://github.com/Emotiv/community-sdk/blob/master/examples_extra_prime/C%23/EEG_Data_Logger/EEG_Data_Logger.cs
there's no user profile has been created. Does that mean no need to create a user profile in Community version?  how the signal pattern recognition will be done, so ?

thanks :)

**Comment by hoangphamemotiv** [comment]
Hi @DA93 
training profile is used for Mental command and facial expressiv features. for reading EEG data, you dont need the profile, EDK will read your EEG data from your headset while you wear it.

**Comment by DA93** [comment]
Hi @hoangphamemotiv ,
Thank you for your reply. I know that training profile is used for detecting either Mental command or Facial expressions features! We need to detect 4 different facial expressions for each user. How can we implement that in Community version if Profile class is not in EDK.dll ?!!

Looking forward to answer the question clearly ^_^ !
Thanks in advance :)

**Comment by hoangphamemotiv** [comment]
Hi @DA93 . 
To detect 4 different user on FE and MC features, you may need 4 different training profiles. 
here is examples for training profile on C#: https://github.com/Emotiv/community-sdk/tree/master/examples_basic/C%23/MentalCommandWithCloudProfile
https://github.com/Emotiv/community-sdk/tree/master/examples_basic/C%23/MentalCommandWithLocalProfile
