### ISSUE TITLE
PleaseHelp:( Which is the easy way to get the brain waves data from the Insight?

### ISSUE THREAD

**Issue by SAMJAYHK** [Emotiv/community-sdk#243]
Sorry for my question. I’m basic programmer and now I have got the Emotiv Insight from my friend. I went do develop a Mobile Application included Android and iOS platform like “MyEmotiv”. I had saw the Office Document (https://www.emotiv.com/developer) but I could’t saw any sdk example is get the brain waves data like Alpha/Beta/Theta from the Insight (I had tried all Android example). So could you guys tell me which way (or any document which I must be see) can help me to do that? Thank you for help:)

**Comment by hoangphamemotiv** [comment]
Hi @SAMJAYHK 
For Android library, we will have a new version of v3.5.1 soon. at the moment, you may want to try other features as Mantal Command, Facial Expressiv...

thanks. ^^!

**Comment by SAMJAYHK** [comment]
@hoangphamemotiv 
Thank you for your reply. So as your answer, is it meaning I can't get the raw EEG data on the android library V3.5.0? And it will be enabled on the version number v3.5.1? Thank you for your help:)

**Comment by hoangphamemotiv** [comment]
SDK v3.5.0 support WIN, MAC. (so you can't get EEG data on the android library)
SDK v3.5.1 support IOS and Android.

you are welcome.

**Comment by AaronMikaelian** [comment]
@hoangphamemotiv
Hello, is there a planned release date for the v3. 5.1 SDK? Looking forward to it, thanks.

**Comment by hoangphamemotiv** [comment]
Hi @AaronMikaelian . 

we are still working on IOS and Android 3.5. there are some issues with them at the moment. we will try to fix it as soon as possible

**Comment by hoangphamemotiv** [comment]
SDK v3.5.1 supported Android
https://github.com/Emotiv/community-sdk/releases/tag/v3.5.1-WIN-MAC-ANDROID
