### ISSUE TITLE
Limited IEE Input Channels on Android

### ISSUE THREAD

**Issue by JonathanAJ** [Emotiv/community-sdk#245]
Why on android IEE_InputChannels_t have only six channels?
```
IEE_CHAN_CMS(0), 
		IEE_CHAN_AF3(3),
		IEE_CHAN_T7(7),
		IEE_CHAN_Pz(9),
		IEE_CHAN_T8(12),
		IEE_CHAN_AF4(16);
```

**Comment by JonathanAJ** [comment]
Epoc+ have 14 channels.

**Comment by hoangphamemotiv** [comment]
Hi @JonathanAJ 

Android is still v3.3.3, it works fine with Insight headset, to make it works with Epoc+ you can add more channels of EPOC+ in the header files. this error will be fixed in new version of Android SDK 3.5

**Comment by JonathanAJ** [comment]
How add more channels for EPOC+?
Wich header files in android SDK?
Where is the code this?

**Comment by hoangphamemotiv** [comment]
@JonathanAJ . here is the list of channel. 
typedef enum IEE_InputChannels_enum {
        
        IEE_CHAN_CMS = 0,
        IEE_CHAN_DRL,
        IEE_CHAN_FP1,
        IEE_CHAN_AF3,
        IEE_CHAN_F7,
        IEE_CHAN_F3,
        IEE_CHAN_FC5,
        IEE_CHAN_T7,
        IEE_CHAN_P7,
        IEE_CHAN_Pz,
        IEE_CHAN_O1 = IEE_CHAN_Pz,
        IEE_CHAN_O2,
        IEE_CHAN_P8,
        IEE_CHAN_T8,
        IEE_CHAN_FC6,
        IEE_CHAN_F4,
        IEE_CHAN_F8,
        IEE_CHAN_AF4,
        IEE_CHAN_FP2,
    } IEE_InputChannels_t;
