### ISSUE TITLE
Some questions regarding Frequency Band example

### ISSUE THREAD

**Issue by kkenzo** [Emotiv/community-sdk#246]
1. If I want to get entire Beta from12-25Hz, do I simply sum up low beta and high beta?

2. For Low Beta, on emotiv website, it says 12-18Hz. While on the code comment it says 12-16Hz, which is correct?

Please help me out, thanks.

**Comment by tungntEmotiv** [comment]
Hi @kkenzo 
Thanks for your questions.
1) Yes, user only can get average power of  low beta and high beta
2) Code comment is correct. Could you take a shoot the wrong value on emotiv website and send for me ? We will correct asap.
Once again, thank you

**Comment by KHvic** [comment]
@tungntEmotiv 
https://emotiv.zendesk.com/hc/en-us/articles/208378593-Frequency-Bands-what-are-they-and-how-do-I-access-them-

**Comment by tungntEmotiv** [comment]
Yes, @KHvic . Thank you so much.
