### ISSUE TITLE
RollingBall example, MacOS Sierra, Unity 2017.1.1f1

### ISSUE THREAD

**Issue by limi44** [Emotiv/community-sdk#248]
I'm trying to run the RollingBall example in Unity 2017.1.1f1 and MacOS Sierra (10.12.6) following the setup instructions. I'm not clear on how I should be setting up the link to "edk.dll" as the DLL was built for win32/win64. I've tried placing it in the project folder and assets folder, and both times I get the error:

DLLNotFoundException: edk.dll
Emotiv.EdkDll.IEE_EmoEngineEventCreate ()

I'm using the newest version of the SDK (3.5.0). I've followed the instructions here to update 'EC_OK' and 'EC_GetProfileId' already: https://github.com/Emotiv/community-sdk/issues/206

**Comment by hoangphamemotiv** [comment]
Hi @limi44 
RollingBall example is still using SDK 3.3.3 with some old API. but it is enough for using basic features. 
you are using MacOS Sierra, please link Unity to MacOS library , the library should be put in Plugin folder.

**Comment by ddemsahin** [comment]
> I'm trying to run the RollingBall example in Unity 2017.1.1f1 and MacOS Sierra (10.12.6) following the setup instructions. I'm not clear on how I should be setting up the link to "edk.dll" as the DLL was built for win32/win64. I've tried placing it in the project folder and assets folder, and both times I get the error:
> 
> DLLNotFoundException: edk.dll
> Emotiv.EdkDll.IEE_EmoEngineEventCreate ()
> 
> I'm using the newest version of the SDK (3.5.0). I've followed the instructions here to update 'EC_OK' and 'EC_GetProfileId' already: #206

Hello,
I am receiving DllNotFoundException: edk.dll error from Unity (Version 2018.2.10f1)
Also, I am a Mac user (High Sierra 10.13.6) and getting the same error as you did 

DLLNotFoundException: edk.dll
Emotiv.EdkDll.IEE_EmoEngineEventCreate ()

How did you fix yours?

**Comment by miscrealitystudios** [comment]
Use unity 5.6 32 bit version and place edk.dll inside plugin folder it will resolve the problem.
