### ISSUE TITLE
The SDK directory "..." does not exists.

### ISSUE THREAD

**Issue by manini** [Emotiv/community-sdk#251]
Dear all,
I download community sdk  from GitHub, but when I try to build FFTSample using gradlew.bat it complains that the SDK folder is missing. In the GIT repository inside the folder community-sdk/examples_basic/Android there isn’t any SDK folder (The message showed running gradlew.bat is  "The SDK directory "..." does not exists."). Is there something wrong in my building procedure? Where are the compiled librariers required by the project?  
Thank you for your attention and cooperation!

**Comment by duytan90** [comment]
Hi @manini, from the [build.grade](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Android/FFTSample/build.gradle) file, the libraries are stored at [jcenter](http://jcenter.bintray.com/com/emotiv/sdk/community/)

**Comment by manini** [comment]
Hi duytan90,
thank you for your answer. I've never used gradle to build my apps... I expect to find in some place a share object file like libedk.so where the emotiv functions are defined, but if I open jcenter I find these files: 
community-3.3.4-javadoc.jar,  community-3.3.4-javadoc.jar.asc, community-3.3.4-sources.jar, community-3.3.4-sources.jar.asc, community-3.3.4.aar, community-3.3.4.aar.asc, community-3.3.4.pom, community-3.3.4.pom.asc
The open community-3.3.4-sources.jar file contains com.emotiv.insight and then some java files, but no .so file. 
Where is the library that contains functions to be used in Android? Thank you again for patience and support!

**Comment by duytan90** [comment]
You can treat the [community-3.3.4.aar](http://jcenter.bintray.com/com/emotiv/sdk/community/3.3.4/:community-3.3.4.aar) as a compression file and unzip it. Please look for "libbedk.so" at "community-3.3.4.aar\jni\armeabi\" folder.

**Comment by manini** [comment]
Thanks a lot for your suggestion! 
.so Library found inside .aar file.
