### ISSUE TITLE
'IEE_DataSetBufferSizeInSec' and 'IEE_DataUpdateHandle' return 1280

### ISSUE THREAD

**Issue by lidh15** [Emotiv/community-sdk#252]
I use the advanced sdk 3.5 in windows 10 x64 with matlab 2016b 64-bit. While using eeglogger I got 1280 from these two functions and no data is available. What's the problem?

**Comment by tungntEmotiv** [comment]
Hi @lidh15
Thanks for your question. 
The error code said that the emo engine have not initialized . The engine need to be initialized by IEE_EngineConnect() as line 30 https://github.com/Emotiv/community-sdk/blob/master/examples_extra_prime/Matlab/eeglogger.m

**Comment by hoangphamemotiv** [comment]
@lidh15 
i think you want to try Matlab 32bit. ^^!
