### ISSUE TITLE
When will update android sdk to v3.5?

### ISSUE THREAD

**Issue by JonathanAJ** [Emotiv/community-sdk#253]
Hello.

I'm developer android and need sdk v3.5 to android, because the version 3.3.4 is very limited. When will update android sdk to v3.5? Someone helpe-me...

**Comment by hoangphamemotiv** [comment]
Hi @JonathanAJ .

Android SDK 3.5 still in progressing. we will try to update it as soon as possible

**Comment by hoangphamemotiv** [comment]
SDK v3.5.1 supported Android. 
https://github.com/Emotiv/community-sdk/releases/tag/v3.5.1-WIN-MAC-ANDROID
