### ISSUE TITLE
EmotivCloudClient.EC_DownloadProfileFile on Android does not exist!

### ISSUE THREAD

**Issue by JonathanAJ** [Emotiv/community-sdk#254]
- How do I save the profile locally on **Android**?

- EC_LoadUserProfile() saves '*.emu' on android? where?

-  "Mental Commands" application, below, save the .emu in "sdcard/EmoProFile/*.emu"
   - https://play.google.com/store/apps/details?id=com.emotiv.mentalcommandsapp 
   - Why does not sdk have it?

**Comment by JonathanAJ** [comment]
@tungntEmotiv @hoangphamemotiv @nguoithichkhampha help

**Comment by nguoithichkhampha** [comment]
@JonathanAJ EC_LoadUserProfile() save in memory, don't create a local file
Sorry, we don't have plan to public the feature save profile locally in community sdk
