### ISSUE TITLE
EmoStateLogger (Java Example) not showing anything

### ISSUE THREAD

**Issue by KnightOheart** [Emotiv/community-sdk#255]
Hello,
I am using Windows 10 with Eclipse oxygen, and I'm testing Emotiv Example version 3.5 
When I run the java Program EmotStateLogger  - choosing option 1 which is EmoEngine, whether I turned on my Emotiv Insight Headset on or off, the output is  showing that I am connected and continue running. 
Can anyone know how I fix this?
Thanks,
![emoeniginex](https://user-images.githubusercontent.com/33151066/32099540-5eaacd0c-bb19-11e7-8c8a-598bcfbb9f4f.PNG)

**Comment by KnightOheart** [comment]
When I connect with headset, there's no received signal and when i turn off it still shows me that im connected and no error showing. However when I choose the second option it runs fine with EmoComposer.

**Comment by tungntEmotiv** [comment]
Hi @KnightOheart 
I am sorry for late response. Have you resolved this issue? . 
Firstly, The IEE_EngineConnect to initialize the connection to EmoEngine which dont depend on Headset on or off. If headset off , you will receive state = EDK_NO_EVENT(0x0600) when you use IEE_EngineGetNextEvent(). Sencondly, When you connect with headset, but there's no received signal, you should check headset connected or not, specially when connect through Bluetooth. and please print state when Get Next Event for debugging. Let me know your debugging. Thank you
