### ISSUE TITLE
Raspberry pi With C++ issue

### ISSUE THREAD

**Issue by Shahad56** [Emotiv/community-sdk#257]
Test environment: Raspbian Stretch
Target: Insight
Connection Method: USB Dongle
Language: C++

I tested the example Emo State Logger under Windows and works perfectly, but then when I tried to run it under Raspbian the same example doesn't work, I installed cmake, but when I run 'make command, the program just display the errors shown below:

pi@raspberrypi:~ $ cmake ../
CMake Error: The source directory "/home" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
pi@raspberrypi:~ $ cd /home/pi/community-sdk/build-folder
pi@raspberrypi:~/community-sdk/build-folder $ cmake ../
-- Link with: libedk.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/community-sdk/build-folder
pi@raspberrypi:~/community-sdk/build-folder $ make
[  5%] Built target AverageBandPowers
[ 11%] Built target EmostateLogger
[ 22%] Built target FacialExpression
[ 25%] Building CXX object examples_basic/C++/GyroData/CMakeFiles/Gyro.dir/main.cpp.o
/home/pi/community-sdk/examples_basic/C++/GyroData/main.cpp:28:21: fatal error: GL/glut.h: No such file or directory
 #include <GL/glut.h>
                     ^
compilation terminated.
examples_basic/C++/GyroData/CMakeFiles/Gyro.dir/build.make:62: recipe for target 'examples_basic/C++/GyroData/CMakeFiles/Gyro.dir/main.cpp.o' failed
make[2]: * [examples_basic/C++/GyroData/CMakeFiles/Gyro.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:250: recipe for target 'examples_basic/C++/GyroData/CMakeFiles/Gyro.dir/all' failed
make[1]: * [examples_basic/C++/GyroData/CMakeFiles/Gyro.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: * [all] Error 2

Any suggestions? Thank you!

**Comment by halybang** [comment]
@Shahad56 You must install glut library:
sudo apt-get install freeglut3-dev
