### ISSUE TITLE
C++ code not connecting to the headset

### ISSUE THREAD

**Issue by Shahad56** [Emotiv/community-sdk#260]
I connected may headset to the raspberry pi and runned EmoStateLogger but as you see in the picture, it keeps telling me "start receiving EmoState...." and when I open the excel sheet, its empty!
![23146320_1466432920137470_1487605266_n](https://user-images.githubusercontent.com/30973795/32334678-27ec45d8-bffc-11e7-8870-df6087b7b463.jpg)

I'm pretty sure the headset is connected because I tried with python code and it worked well, I just don't know what is wrong with C++ code!
Any help?? Thanks..

**Comment by hoangphamemotiv** [comment]
Hi @Shahad56 
look like your headset haven't connected to dongle yet
