### ISSUE TITLE
[python][macOS] skill rating equals 0.0

### ISSUE THREAD

**Issue by cypu** [Emotiv/community-sdk#261]
[prototype.txt](https://github.com/Emotiv/community-sdk/files/1440091/prototype.txt)
I created the script for mental command training/detection for local profile based on cloud profile one provided in examples.
Unfortunately skills rating for all of my actions are equal 0.0 even if I train specific actions

 multiple times.
I do that in this way:
1. loadLocalProfile()
2. trainAction()
3. save profile()

Loading profile

```
if IEE_LoadUserProfile(userID, 'profile.emu') == 0:
        print "Load Profile : done"
```

Saving profile

```
if IEE_SaveUserProfile(userID, 'profile.emu') == 0:
            print "Save profile done"
```

show report method:

```
def showTrainedActions():
    print "Report:"
    if libEDK.IEE_MentalCommandGetTrainedSignatureActions(userID, pActionOut) == 0:
        print "Trained Actions:",ActionOut.value,"\t (Should be 7)"
    else:
        print "Error in Retrieving Trained Signature Actions"
    if libEDK.IEE_MentalCommandGetActionSkillRating(userID,0x0001,pNeutralSkillRating) == 0:
        print "Neutral Skill Rating:",NeutralSkillRating.value
    else:
        print "Error in Retrieving Neutral Skill Rating"
    if libEDK.IEE_MentalCommandGetActionSkillRating(userID,0x0002,pPushSkillRating) == 0:
        print "Push Skill Rating:",PushSkillRating.value
    else:
        print "Error in Retrieving Neutral Skill Rating"
    if libEDK.IEE_MentalCommandGetActionSkillRating(userID,0x0004,pPullSkillRating) == 0:
        print "Pull Skill Rating:",PullSkillRating.value
    else:
        print "Error in Retrieving Neutral Skill Rating"
```

Can anyone tell me what I am doing wrong ? Number of trained actions is correct, but unfortunately skill rating not.
I also receive this error while I load the profile but the return value is 0.

```

17:35:11.521 I CognitivDetectionManagerG2 : Error in training: type 1 has no training data, aborting training...
17:35:11.521 I CognitivDetectionManagerG2 : Classifier cannot be built.
17:35:11.540 I Real detections initialized
New User 24577 added
17:35:11.564 E _EMOXC("f235f54545f0ed4e028184b90b563ddfa1e9d6336cdf1121c9f012026bca37c61afad6f12cd2ddef62") - C++ exception:  invalid signature
17:35:11.582 D MarkerControlDetection::init() : marker channel is not available
```

Please find attached my code.
Thanks in advance.

**Comment by hoangphamemotiv** [comment]
Hi @cypu you need retrain your action some times to improve kill rating

**Comment by cypu** [comment]
@hoangphamemotiv  I have tried that but it doesn't work. For cloud profile there is a method **EC_UpdateUserProfile** but unfortunately for local profile there is only SaveUserProfile and LoadUserProfile. There is no method update for local profile. 
Are you sure that without **update** functionality I am able to update local profile ?

**Comment by hoangphamemotiv** [comment]
SaveUserProfile is API for update profile also. @cypu

**Comment by cypu** [comment]
@hoangphamemotiv  ok thanks
