### ISSUE TITLE
Adding Delta to Average Band Powers Script

### ISSUE THREAD

**Issue by colaspolarbear** [Emotiv/community-sdk#262]
Hello Emotiv, 

Thank you for taking the time out to view my question. This is not an issue, only a request.  

According to your documentation the Average Band Powers script does not include Delta (0-4 Hz). Is there anyway that we can get the Average Band Powers script to be updated with Delta?

Thank you for your time.

**Comment by tungntEmotiv** [comment]
Hi @colaspolarbear ,

Yes, Thanks for your questions. We dont support Delta because the detection of delta is not more accurate and reliable than others wave.
