### ISSUE TITLE
License activation for EEG license question

### ISSUE THREAD

**Issue by aaronavi** [Emotiv/community-sdk#263]
Hi
When i am activating the license for EEG recording, there is "Remaining Sessions  :25" indicator
Is it the total remaining sessions of this license? or can you tell what is the period of time for which this indicator is valid?
and if i exceed this number of session, then i won't be able to record EEG data anymore?

please help
thanks

**Comment by tungntEmotiv** [comment]
Hi @aaronavi 
yes, it is total remaining sessions of the license. After activating your license with a debit number, you can get License information( IEE_LicenseInformation() ) and see the valid period: From date Too date .
Of course if you exceed this number of session, you wont be able to get EEG data anymore

**Comment by aaronavi** [comment]
Hi
Thanks for the response, if i may ask another question,
I have the EmotivPro software, does the license has any effect on the amount of sessions that i have, when i am using my own developed software using the SDK?

thanks

**Comment by tungntEmotiv** [comment]
Hi @aaronavi 
Yes, you can use the license with unlimited sessions for your development.
That is one of great advantages when you buy EmotivPRO license.
thank you
