### ISSUE TITLE
IEE_EngineRemoteConnect() returns EDK_EMOENGINE_PROXY_ERROR 0x0502

### ISSUE THREAD

**Issue by 1e7** [Emotiv/community-sdk#264]
Hello,
Trying to connect to Xavier Panel running on Win 7 64bit via **IEE_EngineRemoteConnect(127.0.0.1, 3008)** using the code from  https://github.com/Emotiv/community-sdk/tree/master/examples_basic/C%2B%2B/EmoStateLogger  (case 2, I just changed the port number to 3008) (edk win32 lib version 3.5). 

**Expected result:** Xavier (or EmoEngine) is accepting connection and mental states are sent to the remote program.

**Actual result:** IEE_EngineRemoteConnect() returns EDK_EMOENGINE_PROXY_ERROR (0x0502).

I double checked that the TCP packet(s) were accepted by the firewall and AV. Since 127.0.0.1 does not work I would assume that also the same code running on a separate machine won't work for me. Checked using, say, IEE_EngineRemoteConnect(192.168.0.xxx, 3008) and indeed the same 0x0502 result.

**Extra info:**
- The case 1 of the EmoStateLogger (IEE_EngineConnect()) works OK like any other sample apps using EmoStateLogger.
- All the functionality of Xavier Panel works and Emo engine local connectivity features seems to work locally on the Win 7 machine  since the XavierEmoKey also works with the EmoEngine/Xaview.
- I am using the Emotiv dongle. The firmware is 0x625 (the set 1.1 was purchased in ~Sep 2017), have not changed any settings of the firmware nor upgraded. Extra question caused by unclear Developers documentation: should this config be filled on the (each?) machine where Xavier Panel is running so it accepts incoming connections?
![image](https://user-images.githubusercontent.com/7920289/32725962-71244844-c877-11e7-824d-6e6e71b483ab.png)

Thanks for any pointers.

**Comment by 1e7** [comment]
The Composer and Panel are 3.3.3, the newest (and only) available in the Emotiv Store. Edk win32 lib is version 3.5.  Maybe this is the issue? 

**I find it hard to understand why the Store has older tools than minimum supported the official SDK.**

**Comment by 1e7** [comment]
Current solution is see is following on simple advice: **"The only SDK version supported with the Panel is  3.3.3"**. If it was included as a big text on the landing page https://github.com/Emotiv/community-sdk and the official SDK documentation and maybe even in the Store that would save me hours. :(

Existence of releases 3.4 and 3.5 on github is misleading, these versions suggest that they are compatible with Emotiv apps 3.3.3  which is not the case. Please follow the http://semver.org to see why I think so about the compatibility. Based on behavior of the current versions they shall be called 4.0/4.1 or 4.0/5.0 already.

**Comment by tungntEmotiv** [comment]
Hi @1e7 

Thanks for both your questions and opinions. We regret the issues affected to your work. 
1) use port 3008 to connect to Control Panel and port 1726 to connect to Composer. We have released CP 3.5 recently. Please get the latest version from website. We will update to release notes to inform the update.
2) About the UI of CP, actually we didnt update UI of Control Panel anymore. We are going to release a very excited Applications with beautiful UI and more many functions like Control Panel.
3) Actually, we named CP base on SDK version but not good in this case.  Thanks for your hint.
4) I see you show the EmotivTools for activating and debit licenses to able to get eeg data not related to Control Panel. 

Once again, thank you. If there any concern, feel free contact us

**Comment by AdityaSher** [comment]
> Hello,
> Trying to connect to Xavier Panel running on Win 7 64bit via **IEE_EngineRemoteConnect(127.0.0.1, 3008)** using the code from https://github.com/Emotiv/community-sdk/tree/master/examples_basic/C%2B%2B/EmoStateLogger (case 2, I just changed the port number to 3008) (edk win32 lib version 3.5).
> 
> **Expected result:** Xavier (or EmoEngine) is accepting connection and mental states are sent to the remote program.
> 
> **Actual result:** IEE_EngineRemoteConnect() returns EDK_EMOENGINE_PROXY_ERROR (0x0502).
> 
> I double checked that the TCP packet(s) were accepted by the firewall and AV. Since 127.0.0.1 does not work I would assume that also the same code running on a separate machine won't work for me. Checked using, say, IEE_EngineRemoteConnect(192.168.0.xxx, 3008) and indeed the same 0x0502 result.
> 
> **Extra info:**
> 
> * The case 1 of the EmoStateLogger (IEE_EngineConnect()) works OK like any other sample apps using EmoStateLogger.
> * All the functionality of Xavier Panel works and Emo engine local connectivity features seems to work locally on the Win 7 machine  since the XavierEmoKey also works with the EmoEngine/Xaview.
> * I am using the Emotiv dongle. The firmware is 0x625 (the set 1.1 was purchased in ~Sep 2017), have not changed any settings of the firmware nor upgraded. Extra question caused by unclear Developers documentation: should this config be filled on the (each?) machine where Xavier Panel is running so it accepts incoming connections?
>   ![image](https://user-images.githubusercontent.com/7920289/32725962-71244844-c877-11e7-824d-6e6e71b483ab.png)
> 
> Thanks for any pointers.

@1e7 can you please send me the emotive Control Panel? I cannot find it online and wish to use it.
