### ISSUE TITLE
trainning action left and right failed

### ISSUE THREAD

**Issue by wangwuqi** [Emotiv/community-sdk#270]
in #265 ,I add code to train left and right, but failed
[MentalCommandWithCloudProfile.py line 230](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L230)
```
elif commands[1] == "pull": 
    if libEDK.IEE_MentalCommandSetTrainingAction(userID, 0x0004) == 0:
        print "Setting Mental Command Training Action PULL for user",userID.value,"!"
        wrongargument = False
        if libEDK.IEE_MentalCommandSetTrainingControl(userID, 1) == 0: #MC_START
            libEDK.IEE_MentalCommandGetTrainingAction(userID, pTrainingActionOut)
            print "Training for", IEE_MentalCommandAction_enum[TrainingActionOut.value],"Start!"
        else:
            print "Start Training Failed"
            wrongargument = False
    else:
        print" Failed to set Mental Command Training Action PULL for user",userID.value,"!"

elif commands[1] == "left": 
    if libEDK.IEE_MentalCommandSetTrainingAction(userID, 0x0020) == 0:
        print "Setting Mental Command Training Action LEFT for user",userID.value,"!"
        wrongargument = False
        if libEDK.IEE_MentalCommandSetTrainingControl(userID, 1) == 0: #MC_START
            libEDK.IEE_MentalCommandGetTrainingAction(userID, pTrainingActionOut)
            print "Training for", IEE_MentalCommandAction_enum[TrainingActionOut.value],"Start!"
        else:
            print "Start Training Failed"
            wrongargument = False
    else:
        print" Failed to set Mental Command Training Action LEFT for user",userID.value,"!"
```
the result is as follows:
```
Setting Mental Command Training Action LEFT for user 4096 !
Start Training Failed
```

@duytan90

**Comment by duytan90** [comment]
@wangwuqi
You may need to fill the rest of the other actions in this [enum](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L65).
Then "define" your "to-be-training" actions [here](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L208). Notice how the actions are combined by Python Binary OR operator then passed as second argument in that function.
Total number of action can be activated is 4 at a time, excluding Neutral.

**Comment by wangwuqi** [comment]
thanks, I forgot to add  0x0020 and 0x0040 here, 
```
elif commands[0] == "set_and_training_actions":
	if (libEDK.IEE_MentalCommandSetActiveActions(userID, 0x0002 | 0x0004 | 0x0020 | 0x0040)== 0): #pull = 0x0004
	    print "PUSH and PULL set active for user", userID.value,"."             
	else:
	    print "Activating actions FAILED!"
```
is the following right?
```
IEE_MentalCommandAction_enum = ["NEUTRAL","PUSH","PULL","LEFT","RIGHT"]
```
then I run the code, and get the following error
```
in parsecommand
    print "Training for", IEE_MentalCommandAction_enum[TrainingActionOut.value],"Start!"
IndexError: list index out of range
```

**Comment by duytan90** [comment]
You should keep the first weird empty string in IEE_MentalCommandAction_enum array
```Python
IEE_MentalCommandAction_enum = ["","NEUTRAL", "PUSH", "PULL", "LEFT", "RIGHT"]
```
If you check `TrainingActionOut.value` which is passed as index in `IEE_MentalCommandAction_enum`, you could see that this `TrainingActionOut.value` is increased by 1 after function [IEE_MentalCommandGetTrainingAction](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L246) executes. That caused `IndexError: list index out of range` in your code. This worth a commend in the example.
Also using hard-coded values as in the original example is bad practice. Put those hexadecimal numbers into an IntEnum such as
```Python
 class MCAction(IntEnum):
        NEUTRAL                  = 0x0001
        PUSH                     = 0x0002
        PULL                     = 0x0004
        LIFT                     = 0x0008
        ...
```
and then maybe using them as
```Python
action0 = MCAction.NEUTRAL  # Required action
action1 = MCAction.PULL
action2 = MCAction.PUSH
...
actionList = action1 | action2
```
would be better.

**Comment by wangwuqi** [comment]
thank you, I solved the problem with dict
```
IEE_MentalCommandAction_enum = {1 : 'NEUTRAL', 2 : 'PUSH', 4 : 'PULL', 32 : 'LEFT', 64 : 'RIGHT'}
```
