### ISSUE TITLE
Can we have an updates Swift example?

### ISSUE THREAD

**Issue by drnicnic** [Emotiv/community-sdk#272]
Hi,

Would it be possible to provide the latest swift libraries for iOS 11?

We are building a Swift example on identifying stroke based on brain activity and I'd like to understand if this is possible using the Emotiv headset.

Kind Regards,

Nick

#IOS #244

**Comment by hoangphamemotiv** [comment]
Hi @drnicnic 
we are working on IOS. we will try to release soon. thanks. ^^!

**Comment by anilyilmaz** [comment]
Hi @hoangphamemotiv 

Is it possible to learn the current situation of ios sdk or swift example? Wondering because, having a problem to connection between epoc+ and iOS device.

Thanks for your help,
Anil.

**Comment by hoangphamemotiv** [comment]
Hi @anilyilmaz 

sorry for late, we are busy releasing some projects base on new Cortex. 
you can use : 
step 1: IEE_GetInsightDeviceCount(); and IEE_GetEpocPlusDeviceCount(); to detect how many current headsets connecting with OS. this method should be in threading for checking in real time
step 2: if nHeadset > 0 : use IEE_GetInsightDeviceState; or IEE_GetEpocPlusDeviceState(); to check "current state of a device"
step 3: IEE_ConnectEpocPlusDevice or IEE_ConnectInsightDevice to connect to a device in list that you want. after that a user_add event raise with a user_id. you can use this user_id to get data from headset.

**Comment by anilyilmaz** [comment]
Hi @hoangphamemotiv 

Thank you for your response. I would like to see these explained steps on a SDK documentation in first place. You guys need to update that too :)

Thanks again,
Anil.

**Comment by drnicnic** [comment]
Hi,

I've managed to create a Swift 4.0 example by including the Object-C libraries into my sample.  I want to track EEG data, however I'm not sure how to enable advanced license.  I have purchased this and I have activated the license key using the Emotiv Prime License tool.  How do I include this information into my XCode project?

**Comment by hoangphamemotiv** [comment]
Hi @drnicnic 
you can see the activate license sample here: https://github.com/Emotiv/community-sdk/tree/master/examples_extra_prime/ObjectiveC/Mac%20OS/ActivateLicense
we use the same API and flow for any languages 
remember that we support Windows, MacOS and Android at the moment

**Comment by drnicnic** [comment]
Thanks for the response, does this mean no support for iOS? Is there a way to read the raw EEG on iOS?

**Comment by hoangphamemotiv** [comment]
i'm sorry. Have no way to get raw EEG on iOS at the moment until  a iOS version release

**Comment by danilinares** [comment]
Is there any new about the iOS version release?

**Comment by hoangphamemotiv** [comment]
Hi @danilinares 
sorry about that. iOS is in the plan of Cortex v2. it may take a few months on working. we focus on Windows, Mac at the first.
