### ISSUE TITLE
what's the theory or principle in Xavier Controlpanel when we do mental command detection?

### ISSUE THREAD

**Issue by wangwuqi** [Emotiv/community-sdk#273]
when i train an action like push, i imagine to push the cube. After training, when i try to imagine pushing the cube, some kind of features or characters of the EEG can be detected and be translated to control command, then the is pushed.

is **motor imagery** used? but motor imagery uses the ERD/ERS phenomenon when people imagine left hand moving or right hand moving or feet other than imagine moving the cube.

or there is a difference when people conduct different **mental task**, and different part of the brain can be activated. then the brain activity can be discriminated with a classifier?

hoping to know more basic theory used in it?

**Comment by tungntEmotiv** [comment]
Hi @wangwuqi 
Many thanks for your question.
We do not use motor imagery for Mental Commands. We use patterns of activity from the whole brain, using classifiers which are user-trained
users CAN use similar patterns to motor imagery trials, but it is not necessary. Any distinguishable patterns can be detected, for example the user can imagine the taste of lemons to Push, the sound of violins to Pull or repeating the word "famous" for Lift, and so on, as long as they can reproduce the same patterns each time they want to activate the action
