### ISSUE TITLE
EEG file issue (again)

### ISSUE THREAD

**Issue by jimenyer** [Emotiv/community-sdk#274]
Please help! I am sorry to be bothering you again. I ran into the same issue. We had talked about this issue before (please see the previous conversation) but I am still having issues with my data.

I followed your instructions. But this is what I am getting. 
1. opened the filed with eeglab
2. I inserted the number corresponding to my channel (see picture 1) 
3. name it test_01 (see picture 2) 
4. Once I do that I saw that channels per frame changed to 1 (see picture 3) 
5. I selected plot channel data "scroll" and it gives me the counter, not the channel (see picture 4). 

Previous iinstructions 
Open it with eeglab (Figure 1);
1.1 when opening file, select chanel you wan to see (figure 2); you enter a numer corespoding with your channel(you can run eeglab example and get index of channels in csv file). with insight headset , 1= COUNTER, 3= AF3...
change Value (Figure 3, 4) -> scale in graph is suitable with amplitude channel
You can adjust time range to display (Figure 5)
1
![1 1](https://user-images.githubusercontent.com/30293586/33528501-6d192f2c-d82f-11e7-8236-358e11368bfa.PNG)
2
![2 2](https://user-images.githubusercontent.com/30293586/33528503-6fda0fb0-d82f-11e7-92a8-2831f5a06942.PNG)
3
![3 1](https://user-images.githubusercontent.com/30293586/33528504-71d98462-d82f-11e7-8651-321ff6dabd92.PNG)
4
![4 1](https://user-images.githubusercontent.com/30293586/33528507-73c9e5dc-d82f-11e7-899d-6952c8f8ef66.PNG)

**Comment by tungntEmotiv** [comment]
Hi @jimenyer 

Have you fixed this issue. Could you send us your edf file ? We will try to reproduce. 
Thank you

**Comment by infinityplus1** [comment]
I'm having the same issue with eeglab v14. I specified Channel list as 3:16 but eeglab loaded channel 1:14 instead.
I works fine in older version of eeglab v10.0.1.0b (the one that comes with old BCILAB 1.01 beta version)
