### ISSUE TITLE
channel corresponding relationship with 10-20 system

### ISSUE THREAD

**Issue by wangwuqi** [Emotiv/community-sdk#275]
according to **10-20 system**, 
![10-20](https://user-images.githubusercontent.com/22237278/33542822-8e35bab4-d90f-11e7-8f54-ba954ff22e99.jpg)

in [MentalCommandWithCloudProfile.py line 67](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L67)
```
IEE_InputChannels_enum = ["IEE_CHAN_CMS",
                          "IEE_CHAN_DRL",
                          "IEE_CHAN_FP1",
                          "IEE_CHAN_AF3",
                          "IEE_CHAN_F7",
                          "IEE_CHAN_F3",
                          "IEE_CHAN_FC5",
                          "IEE_CHAN_T7",
                          "IEE_CHAN_P7",
                          "IEE_CHAN_Pz",
                          "IEE_CHAN_O1",
                          "IEE_CHAN_O2",
                          "IEE_CHAN_P8",
                          "IEE_CHAN_T8",
                          "IEE_CHAN_FC6",
                          "IEE_CHAN_F4",
                          "IEE_CHAN_F8",
                          "IEE_CHAN_AF4",
                          "IEE_CHAN_FP2"]
```
what is channel 'IEE_CHAN_CMS', 'IEE_CHAN_DRL', 'IEE_CHAN_AF3' and 'IEE_CHAN_AF4'?
and could anyone show me the corresponding relationship between the channels in **IEE_InputChannels_enum** and the **10-20 system**.

**Comment by wangwuqi** [comment]
I think i've got it.
![inkedfree-converter com-international_10-20_system_for_eeg-mcn-64625644 - _li](https://user-images.githubusercontent.com/22237278/33545906-82a09e20-d91a-11e7-8c50-b207d96e4d56.jpg)

**Comment by tungntEmotiv** [comment]
Hi @wangwuqi 

Yes, Those are 2 latex electrodes behind ears in our system . You can see the below image 
![fig-5-emotiv-epocs-electrode-positioning-according-to-the-10-20-system-used-for](https://user-images.githubusercontent.com/21233798/33822857-af179ed8-de8b-11e7-8d55-99b14b90d4f5.png)

**Comment by wangwuqi** [comment]
ok, thanks @tungntEmotiv
