### ISSUE TITLE
[Python] Performance metrics

### ISSUE THREAD

**Issue by cypu** [Emotiv/community-sdk#277]
@hoangphamemotiv @tungntEmotiv Based on examples and documentation I have build a python script which displays normalised values of **focus** and **engagement**.
My values have almost always values between 0.3 and 0.5 and compared to the XavierControlPanel they are incorrect. Control panel shows me data from range 0.2 - 1.0, and I assume that Xavier Control Panel isn't wrong.

My questions are:
1. Does the Prime licence may solve that problem ?
2. ``` IS_GetHeadsetOn ``` this method returns me 1 no matter if the headset is on the head or off the head. How to use that method correctly ?
2. The similar situation is with method ``` IS_PerformanceMetricIsActive ```.  I receive 0 even if most of headset signal detectors are green on XavierControlPanel.

Does the information about python64 is still valid ? If yes, how can I run the python32 on osx if I have on EDK compiled on 64bit system. If no, is that mean that using python64 on macOS is fully supported ? 
![python](https://user-images.githubusercontent.com/5863328/33748206-42cd3e08-dc1b-11e7-85fa-13da85873573.png)

Do you think that the programming language matters with building application using EDK?

**Comment by hoangphamemotiv** [comment]
Hi @cypu . 
sorry for late

1. are you using a basic or Advance license? so values of PM are average of all PM state in 10seconds. yep, Prime license can solve the issue. 

2. IS_HeadsetOn is return from Emostate which updated by EEG data, so when headset off, the function is not updated. that is a error. we will fix it. 

3. IS_PerformanceMetricIsActive(EmoStateHandle state, IEE_PerformanceMetricAlgo_t type). this API for checking active detections (Excitement, Meditation....) in PM. so which detection did you got 0?
