### ISSUE TITLE
Android ProfileCloudExample Error

### ISSUE THREAD

**Issue by porkiz** [Emotiv/community-sdk#278]
I have successfully compiled and run the example android application. However, when I login I gets the error issue 'please check internet connection and connect again'. I was connected to the WIFI the entire time. Any help? 

I could not login into the emotiv cloud regardless.

**Comment by nguoithichkhampha** [comment]
@porkiz , we are going to release android sdk 3.5. this bug will be fixed on this version.

**Comment by hoangphamemotiv** [comment]
Hi @porkiz 
as @nguoithichkhampha info above, we released SDK 3.5.1 for android. you can check it here: 
https://github.com/Emotiv/community-sdk/releases/tag/v3.5.1-WIN-MAC-ANDROID

**Comment by porkiz** [comment]
Thank you fixed my problem. You can close the issue now
