### ISSUE TITLE
Unity data access

### ISSUE THREAD

**Issue by bhargavaganti** [Emotiv/community-sdk#280]
Hi i am not able to access the unity3d application working so can you please tell me how to connect and proceed and can i use unity + android + insight and if i can get source code of Myemotiv app it will be more helpful

**Comment by hoangphamemotiv** [comment]
Hi @bhargavaganti 

Sorry, we dont public MyEmotiv app source code. but it is created base on the APIs. you may need a Prime license to get Performance Metric data. 
we have released SDK v3.5.1 supported Android, so you can write Unity wrapper from that.

**Comment by bhargavaganti** [comment]
What about IOS

**Comment by hoangphamemotiv** [comment]
@bhargavaganti we are planning to build IOS for Cortex. so SDK will be later.

**Comment by Sourcetreehugger** [comment]
@hoangphamemotiv
