### ISSUE TITLE
Thread problem: No prompt when to accept or reject the training result

### ISSUE THREAD

**Issue by wangwuqi** [Emotiv/community-sdk#281]
I followed the help step by step, after start training, there's no prompt for accepting the training result. I don't know when to type accept command.
```
help
New UserFollowing step for training... 
40961. save (create/save profile to Cloud) or load  
added2. set

Train each action from "train [action]" > "start" > "accept/reject" step-by-step
3. train [neutral/push/pull/etc.] - Note: Always train neutral first, only train action 

   that defined in ACTIONLIST
4. start
5. accept or reject
Optional: erase, status, report, running
status
Battery Level: -1 out of 5
Wireless Strength: Good Signal
Number of Contact: 18
IEE_CHAN_CMS 	 : Good
IEE_CHAN_DRL 	 : Good
IEE_CHAN_FP1 	 : Good
IEE_CHAN_AF3 	 : Good
IEE_CHAN_F7 	 : Good
IEE_CHAN_F3 	 : Good
IEE_CHAN_FC5 	 : Good
IEE_CHAN_T7 	 : Good
IEE_CHAN_P7 	 : Good
IEE_CHAN_Pz 	 : Good
IEE_CHAN_O1 	 : Good
IEE_CHAN_O2 	 : Good
IEE_CHAN_P8 	 : Good
IEE_CHAN_T8 	 : Good
IEE_CHAN_FC6 	 : Good
IEE_CHAN_F4 	 : Good
IEE_CHAN_F8 	 : Good
IEE_CHAN_AF4 	 : Good
set
Actions set active for user 4096 .
train neutral
Mental Command Signature for UserSet action MC_NEUTRAL for training 
 
4096start
 Training  UPDATED! 
MC_NEUTRAL  start! Mental Command Training for User
 
```

**Comment by wangwuqi** [comment]
there is a problem with the thread, every time after i typed the command, the printing result appeared with the next command. and after i trained actions, i typed running and press Enter key, there's no power value printed. So i press Enter key again, then showed the power values printed.

**Comment by wangwuqi** [comment]
Another problem. These days, the power value is incorrect，showed as below
<img width="296" alt="power" src="https://user-images.githubusercontent.com/22237278/34431414-f7c91f18-eca9-11e7-9bf6-d855792ac417.PNG">

**Comment by duytan90** [comment]
Thanks for your feedback @wangwuqi . We will soon fix this issue. For now you can fix the example like this:
Edit [line 366](https://github.com/Emotiv/community-sdk/blob/c6375cf5ecc501ddffe77cc3b4b701545f197013/examples_basic/Python/MentalCommandWithCloudProfile.py#L366) to:
```python
print 'Current command: {} - Power: {}'.format(parseEdkEnum(MentalCommandActionEnum, mental_state), power)
```
and add this on top of script
```python
IS_MentalCommandGetCurrentActionPower = libEDK.IS_MentalCommandGetCurrentActionPower
IS_MentalCommandGetCurrentActionPower.argtypes = [c_void_p]
IS_MentalCommandGetCurrentActionPower.restype = c_float
```

**Comment by tungntEmotiv** [comment]
Hi @wangwuqi 
Thanks for your issue raising. I have fixed this issue. Please pull the latest.
Thanks @duytan90
