### ISSUE TITLE
support for 64-bit ARM linux?

### ISSUE THREAD

**Issue by dusty-nv** [Emotiv/community-sdk#283]
Hello, are there any known roadblocks to running community-sdk on arm64/aarch64 architecture (Ubuntu 16.04)?   32-bit armhf was noted in README.   Can you get the raw EEG data from it on Linux?

**Comment by tungntEmotiv** [comment]
Hi @dusty-nv 
Thanks for your questions
We used to support Ubuntu on SDK 3.3.3 but we dont support on SDK3.5. Please see the change log for more detail.
https://github.com/Emotiv/community-sdk/blob/master/CHANGELOG.md
Currently, we support SDK on Windows, Mac OS and Android.
