### ISSUE TITLE
Extraction of EmotivPRO Csv file.

### ISSUE THREAD

**Issue by Kaixzc** [Emotiv/community-sdk#286]
Hi, i face some problem with extraction of CSV file exported from EmotivPRO using matlab.
1) what are the row/column of raw data exported from emotivepro represent? 
2) how do i sort out base on the channel?

**Comment by duytan90** [comment]
Hi @Kaixzc, the CSV file that exported from EmotivPRO is a regular comma-separated values file. In the first row, you would see a cell looks like "labels:COUNTER INTERPOLATED AF3 T7 Pz T8 AF4 RAW_CQ GYROX GYROY MARKER MARKER_HARDWARE SYNC TIME_STAMP_s TIME_STAMP_ms CQ_AF3 CQ_T7 CQ_Pz CQ_T8 CQ_AF4", these are headers of 20 corresponding columns (channels) in the CSV file. In case your recorded with EPOC/EPOC+ there would be 40 columns (and related labels cell included).

**Comment by Kaixzc** [comment]
Hi @duytan90 thanks for the help! i get it now. Do you have any idea how can i change this column data into channel and its frequency ? ( For example AF3 thetha/alpha/beta/gama frequency value)

**Comment by duytan90** [comment]
@Kaixzc If you want to do it via EmotivPRO then it's unfeasible. If you know some programming, you can checkout Average Band Powers example (in [examples_basic](https://github.com/Emotiv/community-sdk/tree/master/examples_basic)), with a bit modification you should get what you want.

**Comment by Kaixzc** [comment]
@duytan90 thank you for your help! i will go and try it out.
