### ISSUE TITLE
Python >= 3.5 support?

### ISSUE THREAD

**Issue by nlhnt** [Emotiv/community-sdk#287]
Hello, is Python 3 support to be expected in any forseeable future?

**Comment by duytan90** [comment]
Hi @nlhnt, you need to modify python examples to make them compatible with Python 3, mostly about syntax.
For example this is modified [AverageBandPowers](https://github.com/Emotiv/community-sdk/files/1617785/AverageBandPowers.zip) example for Python 3.6 64-bit. I use Windows btw.

**Comment by nlhnt** [comment]
Hey thanks for the reply, I tried editing two examples, python doesn't give me any syntax errors, but my emotiv returns 1280 state when I try using Python 3.6.4 (Windows 10) and the example works just fine on Python 2.7.4.
Is there anything else I should edit besides prints and file operations?

**Comment by duytan90** [comment]
@nlhnt  You will need to make those functions from Emotiv SDK explicit, such as:
```python
IEE_EngineConnect = libEDK.IEE_EngineConnect
IEE_EngineConnect.restype = c_int
IEE_EngineConnect.argtypes = [c_void_p]
```
Refer to the [API Reference](http://emotiv.github.io/community-sdk/globals_func.html) for more info about these function signature (for the restype and argtypes)
Almost every function from Emotiv SDK returns an error code, which can be "translate" into more meaningful string with `parseEdkEnum` function (defined in utilities.py).
`parseEdkEnum(ErrorCodeEnum, 1280)` return "EDK_EMOENGINE_UNINITIALIZED", that mean calling IEE_EngineConnect was unsuccessful.

For the `IEE_EngineConnect`, I think the same, so you should call `libEDK.IEE_EngineConnect(create_string_buffer(b"Emotiv Systems-5"))` instead.

**Comment by nlhnt** [comment]
Every seems to be working fine, I only faced issue using the 64 bit Python - PerformanceMetrics do not always work in 64 bit mode - switching to 32 bit Python fixed the issue.

**Comment by yongruihuang** [comment]
> Hi @nlhnt, you need to modify python examples to make them compatible with Python 3, mostly about syntax.
> For example this is modified [AverageBandPowers](https://github.com/Emotiv/community-sdk/files/1617785/AverageBandPowers.zip) example for Python 3.6 64-bit. I use Windows btw.

ImportError: No module named 'utilities'?
I am using python3.5 in windows64
