### ISSUE TITLE
Please help me on these issues

### ISSUE THREAD

**Issue by harshdabas1** [Emotiv/community-sdk#288]
I received the device and when I am using it I am facing two issues. Kindly address the following issues:
1. One electrode above the ear does not show contact even when it has been in contact and hydrated. All the basic troubleshooting steps have been performed by me.
2. The EEG zip files generated while using the myEmotiv app are password protected. So kindly let me know the password.
If not from where can I get the raw EEG data generated.

**Comment by hoangphamemotiv** [comment]
Hi @harshdabas1 
could you send a ticket to hello@emotiv.com? so we can support this issue to you. thanks.
