### ISSUE TITLE
Emotiv Cloud not connecting on ARMHF

### ISSUE THREAD

**Issue by mitchytan92** [Emotiv/community-sdk#289]
I am getting 1084 return to me when I called for EC_Connect when I use the libedk.so.3.3.3.
For libedk.so.3.3.2 and libedk.so.3.3.1, it is just returning 0 all the time even when there is no internet connection.

Update 1: Not very sure what I am doing but I tried recording what packets with Wireshark and it has an error "TLSv1.2 73 Alert (Level: Fatal, Description: Unknown CA)"

**Comment by mitchytan92** [comment]
Seems to be similar to this issue as well except I can’t even login.

https://github.com/Emotiv/community-sdk/issues/220

Can you all fix this bug on 3.3.3 if there is still no plans for 3.5.0?

**Comment by hoangphamemotiv** [comment]
Hi @mitchytan92 . 
at the moment, we have no plan for SDK 3.5 on Linux. but for a quick fix some issues, it is possible.

**Comment by Shahad56** [comment]
@hoangphamemotiv  your are not releasing SDK 3.5 for linux?! I thought you said it is going to be soon, and I was waiting for it :'(

**Comment by hoangphamemotiv** [comment]
Hi @Shahad56 
We are focusing on Cortex and applictions using Cortex. so, be hard to work on SDK 3.5 Linux at the moment. i'm so sorry for that. 
what do you think if there is a version without EEG and PM ?

**Comment by Shahad56** [comment]
@hoangphamemotiv  I'm working on a project with raspberry pi. I needed SDK 3.5 so I can load the trained profile to the raspberry so I won't have to use my computer. It seems like I'm going to have to use it:(

**Comment by havietnam** [comment]
@Shahad56 Which RPI/Linux version you used?
Maybe missing certificate. You need to update certifcate similar https://raspberrypi.stackexchange.com/questions/76419/entrusted-certificates-installation.

**Comment by mitchytan92** [comment]
Where can we get the CA cert for Emotivcloud?

**Comment by Shahad56** [comment]
@havietnam I'm working with Raspberry pi 3 model B running rasbian stretch v4.9.59
if I update this, will I be able to load the training profile from the cloud to the python code??
