### ISSUE TITLE
Obtaining EEG values from Emotiv Insight using Community SDK

### ISSUE THREAD

**Issue by harshdabas1** [Emotiv/community-sdk#290]
Sir, I am doing research in the area of BCMI. I wish to acquire the EEG data from the emotiv insight headset. I dont want to purchase subscription for the same. Kindly let me know how could I get the raw EEG values from the headset using your community sdk. If not kindly let me know how could I obtain the raw EEG values.
Thanking you

**Comment by hoangphamemotiv** [comment]
Hi @harshdabas1  
to get raw EEG from emotiv Headset you can use EmotivPro app or SDK library, Cortex with a license key. 
you can contact to hello@emotiv.com, so we can support you our best. 

thanks. ^^!
