### ISSUE TITLE
Emotiv Cloud

### ISSUE THREAD

**Issue by Shahad56** [Emotiv/community-sdk#293]
I need to know the size of the cloud.
I have two training profiles, one contains no trained data and the other contains trained data. When I upload the empty one I get "upload successful" right away, but when I upload the trained one it takes about 5 minutes and returns "upload failed". what is the problem and how can I fix it??

**Comment by tungntEmotiv** [comment]
Hi @Shahad56 
Thank you for your raising the issue. The issue We have checked and then expand size of profile to 15MB. So please try to upload the profile again. Thank you

**Comment by Shahad56** [comment]
once my training profile reaches 4000 KB, it won't load!
now I need to know something, If I wanted to load the training profile locally with MentalCommandWithLocalProfile.cpp, would my emostat_logger.py is going to be able to work with it??

**Comment by krithiha** [comment]
Where should I check the trained data size

**Comment by tungntEmotiv** [comment]
Hi @krithiha 
You could check size of created profile at %ProgramData%/EmotivControlPanel on windows  and ~/Library/Application Support/EmotivControlPanel on mac

**Comment by krithiha** [comment]
whenever I upload my profile I just get Upload failed after a few minutes. My training data is just 1530KB. How to fix this?

**Comment by tungntEmotiv** [comment]
Hi @krithiha 
In this case, Could you contact to our customer support team at hello@emotiv.com ? We might need  teamview to your computer. Thank you
