### ISSUE TITLE
Please update "Premium SDK" details. linked URL is 404

### ISSUE THREAD

**Issue by cookiengineer** [Emotiv/community-sdk#295]
The linked URL in the README leads to a 404: https://www.emotiv.com/sdk-premium-edition-application-form/

Please update the details in the README on whether or not the features listed to the EEG can be used via the SDK without an additional license or not.

**Comment by tungntEmotiv** [comment]
Hi @cookiengineer 

Yes, many thanks for your raising. We have some update about licensing but the link haven't updated . I have updated the link. Thank you
