### ISSUE TITLE
Cortex, ControlPanel and Composer

### ISSUE THREAD

**Issue by landret** [Emotiv/community-sdk#298]
Hi,

I am building an app using java. Using the Emotiv SDK, it is possible to get headset feedback from Emotiv Xavier ControlPanel and Composer servers. But is it still possible to get feedback from those two when using Cortex?
Thanks

**Comment by hoangphamemotiv** [comment]
@landret 
Could you raise the issue in https://github.com/Emotiv/cortex-example?
