### ISSUE TITLE
Developing games using Emotiv Insight and Unity

### ISSUE THREAD

**Issue by krithiha** [Emotiv/community-sdk#300]
Hi, I am developing a game similar to rolling ball using Unity. I need to use left,right,push mental commands. The rolling ball example worked fine for push.I have trained left,right commands using Xavier Control Panel.What should I do next. Should I use Emokey to to map Xavier Control Panel and Unity or is it enough if I just train and load the profile using code. It would be nice if anyone explains with an example for atleast anyone of the mental commands.

**Comment by hoangphamemotiv** [comment]
Hi @krithiha 
Push, left, right or all other Mantal Command detections are same. it mean, if you can train push, you can train other as the same. 
but remember the max of number MC detections you can train is  4. 
you can check Training MC example in C# examples (profile cloud or local). 
you also can use Cortex instable of SDK lib in your app by connect to Cortex via websocket.

**Comment by krithiha** [comment]
should I use Emokey to map Mental Commands to Unity?

**Comment by hoangphamemotiv** [comment]
it depends on your app requirements. but you can do it if you see training on Xaiver Control Panel is easier than training in your app itself.

**Comment by krithiha** [comment]
I need to use push,left,right in my game. For push, 
Vector3 movement = new Vector3(cam.transform.forward.x, cam.transform.forward.y, cam.transform.forward.z); 
has been used. What should I use for left,right ?
When using 3 MC's is it enough if I mention
es.MentalCommandGetCurrentAction () == EdkDll.IEE_MentalCommandAction_t.MC_PUSH/LEFT/RIGHT to detect the MC ? I am new to Unity and BCI . It would be nice if you can guide me.

**Comment by hoangphamemotiv** [comment]
@krithiha 
i think you can use some thing like that: 
Action RIGHT: turn right
Action LEFT: turn left
Action PUSH: Go straight
and you can get action power to make a strong action. and remember you need to training some time to make your action kill better.

**Comment by mahdiramadhan** [comment]
why max of number MC detections we can train is just 4?

**Comment by bchaperon** [comment]
@mahdiramadhan This is a limitation of the MC detection algorithm.
You can train only 4 actions (+neutral)

**Comment by mahdiramadhan** [comment]
@bchaperon I see emokey doesn't have any limitation to put action in condition, if we build new environment in the other engine like unity combine with mc in emokey, are we still can't train mc more than 4?

**Comment by mahdiramadhan** [comment]
That's so help me to understant this system, thanks
