### ISSUE TITLE
SDK python examples error

### ISSUE THREAD

**Issue by evahabeeb** [Emotiv/community-sdk#303]
Hello, I am trying to run the python examples from the SDK with EPOC+ but i keep getting this error: Emotiv Engine start up failed.
I don't get what is causing this error.

**Comment by tungntEmotiv** [comment]
Hi @evahabeeb 
Which is your platform? and what example have you run ?

**Comment by evahabeeb** [comment]
I am using raspberry pi debian with the python examples. I tried running all examples they all give the same error.

**Comment by zhezhang007** [comment]
@evahabeeb I get the same problem, Emotiv Engine start up failed. Did you solve it?
