### ISSUE TITLE
signal quality of channel "IEE_CHAN_FP2" and number of electrodes 

### ISSUE THREAD

**Issue by wangwuqi** [Emotiv/community-sdk#304]
in [MentalCommandWithCloudProfile.py line 91](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L91),there are **19** electrodes including **Pz** which has no corresponding electrode on epoc, then when I type 'status' to get the signal quality of each electrode, it get the right **NumContact which equals 18**, then print the result according to [line 169~172](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L172)
```
if NumContact != 0:
    for i in range(0, NumContact):
        SignalCondition = libEDK.IS_GetContactQuality(eState, i)
        print IEE_InputChannels_enum[i], "\t :", IEE_EEG_ContactQuality_enum[SignalCondition]
```
, so it prints the top 18 values of the [IEE_InputChannels_enum](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L91) and then forget the last channel "IEE_CHAN_FP2".
I tried to get the signal quality of channel "**IEE_CHAN_FP2**" with 
```
SignalCondition = libEDK.IS_GetContactQuality(eState, 18) 
```
but always got zero
what should i do?
Can I remove the value "**IEE_CHAN_Pz**" in [IEE_InputChannels_enum](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L91)  or I should change something else?

**Comment by tungntEmotiv** [comment]
Hi @wangwuqi ,
Yes, There is a duplicate issue at IEE_InputChannels_enum. So, we should keep one (Pz = O1). 
Please get the latest code for our change. Thank you so much for correct us.

**Comment by wangwuqi** [comment]
another question，there are **14** channels(AF3, F7, F3, FC5, T7, P7, O1, O2, P8, T8, FC6, F4, F8, AF4) and two reference channel in https://www.emotiv.com/epoc/, then why in [IEE_InputChannels_enum](https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Python/MentalCommandWithCloudProfile.py#L91) there are **18** channels including ''**IEE_CHAN_FP1**" and "**IEE_CHAN_FP1**" which is not in the epoch+'s technical specification?
<img width="499" alt="14channels" src="https://user-images.githubusercontent.com/22237278/37328060-b0e932cc-26d3-11e8-8f38-9088208cffdb.PNG">
