### ISSUE TITLE
EEGlogger.m in Matlab

### ISSUE THREAD

**Issue by khuanfoo0924** [Emotiv/community-sdk#306]
I have tried to run EEGlogger.m with the headset and license activated.
However, I am facing the following error. May someone lend me a hand?

Error using loadlibrary
Could not find file ../../include/IEegData.h.

Error in loadlibrary

Error in eeglogger (line 11)
    loadlibrary('../../bin/win64/edk.dll','../../include/IEegData.h','addheader','Iedk.h','alias','libIEEGDATA');

However, I have actually IEegData.h inside the directory. Thanks and I am looking forward to your reply.

Regards,
Chris

**Comment by duytan90** [comment]
Hi @khuanfoo0924, the parameters in `loadlibrary` functions are relative path, maybe you can replace them with absolute paths then try again?

**Comment by khuanfoo0924** [comment]
Thanks. I have specify the correct file directory to be as follows,

if (strcmp(bitVersion, 'win64'))
    loadlibrary('C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/include/Iedk.h','addheader','IedkErrorCode.h','addheader','IEmoStateDLL.h','addheader','FacialExpressionDetection.h','addheader','MentalCommandDetection.h','addheader','IEmotivProfile.h','addheader','EmotivLicense.h','alias','libIEDK');
    loadlibrary('C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/include/IEegData.h','addheader','Iedk.h','alias','libIEEGDATA');
else
    loadlibrary('C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/include/Iedk.h','addheader','IedkErrorCode.h','addheader','IEmoStateDLL.h','addheader','FacialExpressionDetection.h','addheader','MentalCommandDetection.h','addheader','IEmotivProfile.h','addheader','EmotivLicense.h','alias','libIEDK');
    loadlibrary('C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/include/IEegData.h','addheader','Iedk.h','alias','libIEEGDATA');
end

However, I am still facing the errors as shown below,

**Error using loadlibrary
Option IedkErrorCode.h is not a valid loadlibrary option.

Error in eeglogger (line 10)
    loadlibrary('C:/Users/User/Desktop/FYP
    Analysis/community-sdk-master/community-sdk-master/include/Iedk.h','addheader','IedkErrorCode.h','addheader','IEmoStateDLL.h','addheader','FacialExpressionDetection.h','addheader','MentalCommandDetection.h','addheader','IEmotivProfile.h','addheader','EmotivLicense.h','alias','libIEDK');** 

Hope to hearing from you soon. Thanks

**Comment by duytan90** [comment]
The first parameter should be path to the **edk.dll** file, then the **main header file** then **'addheader'** and including files. Maybe it would be like this:

```Matlab
if (strcmp(bitVersion, 'win64'))
loadlibrary('C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/bin/win64/edk.dll','C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/include/Iedk.h','addheader','IedkErrorCode.h','addheader','IEmoStateDLL.h','addheader','FacialExpressionDetection.h','addheader','MentalCommandDetection.h','addheader','IEmotivProfile.h','addheader','EmotivLicense.h','alias','libIEDK');
loadlibrary('C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/bin/win64/edk.dll','C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/include/IEegData.h','addheader','Iedk.h','alias','libIEEGDATA');
else
loadlibrary('C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/bin/win32/edk.dll','C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/include/Iedk.h','addheader','IedkErrorCode.h','addheader','IEmoStateDLL.h','addheader','FacialExpressionDetection.h','addheader','MentalCommandDetection.h','addheader','IEmotivProfile.h','addheader','EmotivLicense.h','alias','libIEDK');
loadlibrary('C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/bin/win32/edk.dll','C:/Users/User/Desktop/FYP Analysis/community-sdk-master/community-sdk-master/include/IEegData.h','addheader','Iedk.h','alias','libIEEGDATA');
end
```
