### ISSUE TITLE
How to get real-time EEG data with community-sdk

### ISSUE THREAD

**Issue by simba426** [Emotiv/community-sdk#307]
I have an EPOC+ device
and I also bought a Pure.eeg to view the real-time eeg and to record raw data for analysing.
now I want to get real-time data input to control some devices with headset but I found that Pure.eeg could only provide me with data in .csv form after I finished records and download them from cloud.
I learnt that 'examples_extra_prime' in community-sdk can help me get the real-time data in .csv form but I'm not sure how to do with it. The emoComposer seems to be different from Pure.eeg and I'm not clear about how the headset ,sdk and emoComposer connect to each other, could I just achieve the real-time data with Pure.eeg and community-sdk?
thanks!

**Comment by duytan90** [comment]
Hi @simba426, It's correct that Pure.EEG only support view EEG data in real-time and export recorded data as CSV/PDF format for later analyzing. You will need PRO license key to get (and use) EEG data from EPOC+ (as input to your own external applications), and of course some basic programming experience (to read the example code).
Ignore the Composer, it's purpose is to simulate the headset features, but you've already owned one.
