### ISSUE TITLE
IEE_EngineConnect method call freezes or kills application

### ISSUE THREAD

**Issue by bergnils** [Emotiv/community-sdk#309]
We are developing an Android application in Java using the Emotiv SDK and an Emotiv Insight headset.

We are testing the application on three different phone models and each one displays different results when the IEE_EngineConnect method is executed.

The first phone, a Samsung Galaxy S6 running Android 7.0, has no issues and we are able to connect to the headset with our application and receive data from it. The IEE_EngineConnect method works as intended (I presume)

The second phone, a ZTE Axon 7 runnning Android 7.1.1, gets "stuck" when calling the IEE_EngineConnect method. The application doesn't get past this method call.

Our third phone, a Samsung Galaxy S4 running Android 5.0.1, the application is killed with a 
`Fatal signal 6 (SIGABRT)` error message when calling the IEE_EngineConnect method.

Is there any fix to these issues? It is my understanding from reading http://emotiv.github.io/community-sdk/ that this method is required to connect to the headset and I would very much like to see the application run on more than one device.

I can provide code snippets if required.

**Comment by mneckoee** [comment]
I have the same issue on Redmi Note 4 Android version 6

**Comment by mneckoee** [comment]
changing 
Emotiv.IEE_EmoInitDevice(this); // "this" is the activity 
to 
Emotiv.IEE_EmoInitDevice(getApplicationContext()); 
worked for me!

**Comment by melkholy12** [comment]
> changing
> Emotiv.IEE_EmoInitDevice(this); // "this" is the activity
> to
> Emotiv.IEE_EmoInitDevice(getApplicationContext());
> worked for me!

This didn't work for me, and I'm still facing the same issue when calling IEE_EngineConnect() on different Android devices.

Has this issue been resolved?
