### ISSUE TITLE
How to run C++ program in CodeBlocks?

### ISSUE THREAD

**Issue by krithiha** [Emotiv/community-sdk#310]
Hi, I tried to run c++ program using Code blocks. But I am getting -ledk.lib not error every time I run it.Is there any other step I need to do before running the C++ programs?

**Comment by hoangphamemotiv** [comment]
Hi @krithiha 
can you send me the detail of the error? and what OS and IDE are you using ? 32b or 64bit compile?
the C++ examples can work without change anything

**Comment by krithiha** [comment]
I am using Windows 8.1 and CodeBlocks. It is 64bit compile

**Comment by hoangphamemotiv** [comment]
@krithiha 
please make sure you configed the example to get 64bit SDK lib
