### ISSUE TITLE
Emotiv insight on a Raspberry Pi 3

### ISSUE THREAD

**Issue by Noxrest** [Emotiv/community-sdk#311]
Hi im having trouble connecting the Emotiv Insight to Raspberry Pi 3, the problem seems to be the wireless dongle, using therminal scaning for usb devices and the dongle appears, but using hcitool to scan devices yields no results, i can run my program fine on a laptop but running the same exact program on the raspberry doesn´t work, im using IDLE 2 on both devices, any hints or help would be apreciated, thanks in advance.

**Comment by Noxrest** [comment]
anyone?

**Comment by havietnam** [comment]
Hi @Noxrest ,
You should copy file `70-emotiv.rules` to `/etc/udev/rules.d/` then restart udev service:
`$ sudo service udev restart`
Then you will see new HID device by:
`$ ls /dev/hidraw*`
