### ISSUE TITLE
Training Multiple Commands in Unity

### ISSUE THREAD

**Issue by esposen** [Emotiv/community-sdk#312]
Hello i am trying to train left and right actions in Unity using my
purchased Emotiv Unity Wrapper. I am able to activate, train, and use
single actions however have been unable to get it working for multiple
actions. Here is my current code for activating left and right:

```
uint action1 = (uint)EdkDll.IEE_MentalCommandAction_t.MC_LEFT;
uint action2 = (uint)EdkDll.IEE_MentalCommandAction_t.MC_RIGHT;
uint listAction = action1 | action2;
engine.MentalCommandSetActiveActions(userId, listAction);
Debug.Log("SET: " + listAction);
Debug.Log("GET: " + engine.MentalCommandGetActiveActions(userId));

```
Both logs print out 96 as the set and get. When i attempt to train and
use these actions nothing happens, i don't an error saying i haven't
activated the actions i am attempting to train. Can you see what i am
doing wrong? what should engine.MentalCommandGetActiveActions(userId))
return if both MC_RIGHT and MC_LEFT are active?

Any help would be greatly appreciated

**Comment by hoangphamemotiv** [comment]
Hi @esposen 
96 = 0110 0000 
it means LEFT and RIGHT are active. after that you can train those actions and Neutral then get action and power via API .

**Comment by esposen** [comment]
Hmm ok there must be something else wrong with what i am doing, thank you
for your help
