### ISSUE TITLE
How to use eeglogger on matlab?

### ISSUE THREAD

**Issue by numbstudent** [Emotiv/community-sdk#313]
Hello, I'm currently on an EEG research using Emotiv, and I'm new to Emotiv and Matlab.

When I ran eeglogger.m, it show these errors:

> Error loading library intermediate output follows.
> The actual error is at the end of this output.
> *********
> 
> Failed to parse type 'float markerHardwareColum = 0' original input ' float markerHardwareColum = 0 '
> Found on line 3067 of input from line 221 of file C:\\Users\\freesugar\\Downloads\\SDKkucing\\community-sdk-master\\include\\IEegData.h
> Error parsing argument for function IEE_DataSetMarkerWithEpoch function may be invalid.
> 
> Failed to parse type 'double epoch = 0' original input ' double epoch = 0 '
> Found on line 3067 of input from line 221 of file C:\\Users\\freesugar\\Downloads\\SDKkucing\\community-sdk-master\\include\\IEegData.h
> Error parsing argument for function IEE_DataSetMarkerWithEpoch function may be invalid.
> 
> Failed to parse type 'double epoch = 0' original input ' double epoch = 0 '
> Found on line 3082 of input from line 236 of file C:\\Users\\freesugar\\Downloads\\SDKkucing\\community-sdk-master\\include\\IEegData.h
> Error parsing argument for function IEE_DataSetNewModelMarker function may be invalid.
> *********
> Error using loadlibrary
> Building libIEEGDATA_thunk_pcwin64 failed.  Compiler output is:
> cl -I"C:\Program Files\MATLAB\R2017a\extern\include" /Zp8  /W3  /nologo  -I"C:\Users\freesugar\Documents\MATLAB"
> -I"C:\Users\freesugar\Downloads\SDKkucing\community-sdk-master\include" "libIEEGDATA_thunk_pcwin64.c" -LD
> -Fe"libIEEGDATA_thunk_pcwin64.dll"
> libIEEGDATA_thunk_pcwin64.c
> C:\Users\freesugar\Downloads\SDKkucing\community-sdk-master\include\IEegData.h(220) : error C2143: syntax error : missing
> ')' before '='
> C:\Users\freesugar\Downloads\SDKkucing\community-sdk-master\include\IEegData.h(220) : error C2072:
> 'IEE_DataSetMarkerWithEpoch' : initialization of a function
> C:\Users\freesugar\Downloads\SDKkucing\community-sdk-master\include\IEegData.h(221) : error C2059: syntax error : 'type'
> C:\Users\freesugar\Downloads\SDKkucing\community-sdk-master\include\IEegData.h(221) : error C2059: syntax error : ')'
> C:\Users\freesugar\Downloads\SDKkucing\community-sdk-master\include\IEegData.h(236) : error C2143: syntax error : missing
> ')' before '='
> C:\Users\freesugar\Downloads\SDKkucing\community-sdk-master\include\IEegData.h(236) : error C2072:
> 'IEE_DataSetNewModelMarker' : initialization of a function
> C:\Users\freesugar\Downloads\SDKkucing\community-sdk-master\include\IEegData.h(236) : error C2059: syntax error : ')'
> libIEEGDATA_thunk_pcwin64.c(405) : error C2059: syntax error : 'bad suffix on number'
> libIEEGDATA_thunk_pcwin64.c(405) : error C2146: syntax error : missing ';' before identifier 'doubleepoch'
> libIEEGDATA_thunk_pcwin64.c(405) : error C2146: syntax error : missing ';' before identifier 'Thunk'
> libIEEGDATA_thunk_pcwin64.c(409) : error C2146: syntax error : missing ';' before identifier 'p2'
> libIEEGDATA_thunk_pcwin64.c(409) : error C2065: 'p2' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(410) : error C2146: syntax error : missing ';' before identifier 'p3'
> libIEEGDATA_thunk_pcwin64.c(410) : error C2065: 'p3' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(415) : error C2065: 'p2' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(415) : error C2146: syntax error : missing ')' before identifier 'markerHardwareColum'
> libIEEGDATA_thunk_pcwin64.c(415) : error C2100: illegal indirection
> libIEEGDATA_thunk_pcwin64.c(415) : warning C4244: '=' : conversion from 'float' to 'int', possible loss of data
> libIEEGDATA_thunk_pcwin64.c(415) : error C2143: syntax error : missing ';' before 'const'
> libIEEGDATA_thunk_pcwin64.c(415) : error C2059: syntax error : ')'
> libIEEGDATA_thunk_pcwin64.c(416) : error C2065: 'p2' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(417) : error C2065: 'p3' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(417) : error C2146: syntax error : missing ')' before identifier 'epoch'
> libIEEGDATA_thunk_pcwin64.c(417) : error C2100: illegal indirection
> libIEEGDATA_thunk_pcwin64.c(417) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> libIEEGDATA_thunk_pcwin64.c(417) : error C2143: syntax error : missing ';' before 'const'
> libIEEGDATA_thunk_pcwin64.c(417) : error C2059: syntax error : ')'
> libIEEGDATA_thunk_pcwin64.c(418) : error C2065: 'p3' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(419) : error C2143: syntax error : missing ')' before '='
> libIEEGDATA_thunk_pcwin64.c(419) : error C2059: syntax error : '='
> libIEEGDATA_thunk_pcwin64.c(423) : error C2061: syntax error : identifier 'int32uint32uint32floatdoubleepoch'
> libIEEGDATA_thunk_pcwin64.c(423) : error C2059: syntax error : ';'
> libIEEGDATA_thunk_pcwin64.c(423) : error C2513: '/*global*/ ' : no variable declared before '='
> libIEEGDATA_thunk_pcwin64.c(423) : error C2059: syntax error : 'bad suffix on number'
> libIEEGDATA_thunk_pcwin64.c(423) : error C2146: syntax error : missing ';' before identifier 'Thunk'
> libIEEGDATA_thunk_pcwin64.c(424) : error C2084: function 'int Thunk(void (__cdecl *)(),const char *,int)' already has a
> body
>         libIEEGDATA_thunk_pcwin64.c(405) : see previous definition of 'Thunk'
> libIEEGDATA_thunk_pcwin64.c(428) : error C2146: syntax error : missing ';' before identifier 'p3'
> libIEEGDATA_thunk_pcwin64.c(428) : error C2065: 'p3' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(435) : error C2065: 'p3' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(435) : error C2146: syntax error : missing ')' before identifier 'epoch'
> libIEEGDATA_thunk_pcwin64.c(435) : error C2100: illegal indirection
> libIEEGDATA_thunk_pcwin64.c(435) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
> libIEEGDATA_thunk_pcwin64.c(435) : error C2143: syntax error : missing ';' before 'const'
> libIEEGDATA_thunk_pcwin64.c(435) : error C2059: syntax error : ')'
> libIEEGDATA_thunk_pcwin64.c(436) : error C2065: 'p3' : undeclared identifier
> libIEEGDATA_thunk_pcwin64.c(437) : error C2143: syntax error : missing ')' before '='
> libIEEGDATA_thunk_pcwin64.c(437) : error C2059: syntax error : '='
> 
> 
> Error in eeglogger (line 12)
>     
> loadlibrary(strcat(pth,'bin/win64/edk.dll'),strcat(pth,'/include/IEegData.h'),'addheader','Iedk.h','alias','libIEEGDATA'); 

Do you know what should I do to make it work? Thank you in advance

**Comment by duytan90** [comment]
Hey @numbstudent, please try [these steps](https://github.com/Emotiv/community-sdk/blob/master/examples_extra_prime/Matlab/readme.md) then run the scrip again.

**Comment by numbstudent** [comment]
Thank you, I'm using the 64bit version. I changed and it works.
