### ISSUE TITLE
Matlab and Mac

### ISSUE THREAD

**Issue by ramsys28** [Emotiv/community-sdk#314]
Hi,

I cannot load the libraries into matlab in mac. Matlab error is that this library is not a dynamic library... 

Any advise?

**Comment by duytan90** [comment]
Hi @ramsys28, the Matlab example doesn't support loading library on MacOS. So you will need to try it on Windows instead.

**Comment by ramsys28** [comment]
Hi @duytan90,

As you mention in your readme the average band should run in matlab and mac...
