### ISSUE TITLE
Unity DllNotFoundException: edk.dll + missing references. Steps missing in docs.

### ISSUE THREAD

**Issue by Sourcetreehugger** [Emotiv/community-sdk#315]
Hey,

Today I tried out the Unity example of Emotiv. The following error occured after following the steps in the documentation. 

DllNotFoundException: edk.dll
Emotiv.EdkDll.IEE_EmoEngineEventCreate ()
Emotiv.EmoEngine..ctor ()
Emotiv.EmoEngine.get_Instance ()
EmotivCtrl.Awake () (at Assets/scripts/EmotivCtrl.cs:26)

Found using 

Windows 10 64 bit.
Unity 5.3.4f1
Visual studio 2010

To reproduce:

1. Download Unity 5.6.4.f1 or higher as described in instructions.pdf
2. Git clone the community sdk
3. Point in system variables to community sdk folder of earlier commit in docs (very unclear in which folder this actually has to be), also tried bin folder but also did not work.
4. Reboot
5. Start Unity
6. Play main scene

There are some essential steps missing in the docs.
-At what folder should we point in the environment variables.
-How do you rebuild a DLL (if that is even nessacary)
-Why do we have to check out a previous commit for the DLL? 

![screenshot_1](https://user-images.githubusercontent.com/25456778/38261690-447798b0-376b-11e8-8305-27dae425e89b.png)

**Comment by hoangphamemotiv** [comment]
Hi @Sourcetreehugger 

are you using 32bit Unity or 64bit Unity? error "DllNotFoundException: edk.dll" can be from that

**Comment by Sourcetreehugger** [comment]
I'm using 64-bit Unity. Which version do you use?

**Comment by hoangphamemotiv** [comment]
@Sourcetreehugger  32bit is good for that example
between, you can use SDK lib 32bit and 64 bit on Unity. just take care : in UNITY_EDITOR mode, bit version of Unity need to same with bit version of SDK lib. 
in building exe file, you can choose and put the SDK lib same with your unity building config

**Comment by Sourcetreehugger** [comment]
Hi Hoangphamemotiv, 

Thanks for your quick reply. Please mention this in docs when we should use the 32 bit editor version of Unity. I will try it out and tell if the solution worked.

**Comment by hoangphamemotiv** [comment]
yes, thank @Sourcetreehugger . the Unity example is outdate of SDK version and document.

**Comment by Sourcetreehugger** [comment]
What should be in the C:/Emotiv folder that is added tot the PATH variable? Should it contain the contents of /bin in the sdk ?

**Comment by hoangphamemotiv** [comment]
you can put edk.dll and ms runtime lib in: 
Assets\Plugins\"platform"
or on windows, in Unity_Editor mode you can simple put those libs at the same folder with Assets folder
dont need to set PATH vaiable

**Comment by Sourcetreehugger** [comment]
I put edk.dll  and glut32.dll from the bin/win32  in Assets/Plugins/x86. Same result Dllnotfoundexception

**Comment by hoangphamemotiv** [comment]
@Sourcetreehugger 
you don't glut32.dll for your  project. 
vcruntime140.dll , msvcp140.dll should go with edk.dll. 
can you try to put those lib in the same folder with Assests folder?

**Comment by Sourcetreehugger** [comment]
Hey @hoangphamemotiv 

Vctruntime140.dll and msvcp140.dll was not part of the sdk at that time. I ended up putting the old edk.dll in the Editor folder of the unity 5.3.4 installation folder with the other dll's. 

I've wasted a lot of time on this. It would mean a lot to the community if the Unity project would be updated.

**Comment by Corstiaan** [comment]
Hi, I'm so glad you're updating the Unity example. While you're at it, could you tell us (or fix) the missing script on the Canvas gameobject? And maybe up the example to use Unity 2018/x64?

**Comment by Corstiaan** [comment]
Hi Hoang (or is Pham your first name?), thnx for your reply.
In the tutorial there's a script missing on the "Canvas" Gameobject. What scripts should be there?

**Comment by hoangphamemotiv** [comment]
Hi @Corstiaan 
Unity 64bit is the same fix with 32bit. build DotNetEmotivSDK.dll 64bit then put it and SDK libs 64bit to the same folder as 32bit dll. 

for Unity 2018, i have no the version at the moment. i will try on it later. ^^!

**Comment by hoangphamemotiv** [comment]
Hi @Corstiaan 
Do you think it effect to data work flow of the example? if not, i think it is good for a demo example

**Comment by miscrealitystudios** [comment]
just run the project on unity 5.6.4f1 (32 bit) https://download.unity3d.com/download_unity/ac7086b8d112/Windows32EditorInstaller/UnitySetup32-5.6.4f1.exe?_ga=2.106732291.1492338704.1547803086-1191492233.1542781227
