### ISSUE TITLE
Can't run eeglogger example on Matlab 64bit

### ISSUE THREAD

**Issue by hoangtran355** [Emotiv/community-sdk#317]
Hi,
I can't run the eeglogger.m example on Matlab 64bit, even when I "remove "default arguments" on each C/C++ header".

 Error in eeglogger (line 11)
    loadlibrary('../../bin/win64/edk.dll','../../include/IEegData.h','addheader','Iedk.h','alias','libIEEGDATA');

The example works just fine on the 32bit Matlab 2015. Could you please provide some help or more detail instruction? 
Thanks.

**Comment by duytan90** [comment]
Hi @hoangtran355, check out these steps if your installed MatLab is 64bit version.

**Comment by duytan90** [comment]
@hoangtran355, I've updated with the link to the readme file. Sorry for this silly mistake!
