### ISSUE TITLE
how to upload training profile into Emotiv Cloud?

### ISSUE THREAD

**Issue by krithiha** [Emotiv/community-sdk#318]
I tried to upload my training profile using Emotiv Xavier Control Panel. But whenever I do it, I just get upload failed. Is there any way to do it via code? If SavingAndLoadingProfileCloud does uploding to Emotiv Cloud?When I run that code i get this error
`1>------ Build started: Project: SavingAndLoadingProfileCloud, Configuration: Debug|x86 ------
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1124,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0,Profile=Client" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1124,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========`
Can anybody please help me with it?

**Comment by hoangphamemotiv** [comment]
Hi @krithiha 
Could you read the example document https://github.com/Emotiv/community-sdk/tree/master/doc ?
