### ISSUE TITLE
Error adding certificate

### ISSUE THREAD

**Issue by Cryzic** [Emotiv/community-sdk#320]
Hello.

I am new to the Emotiv BCI and I just working on the SDK. I am using the **_MentalCommandProfilewith CloudProfile.py_** and whenever executed, it shows an error like this and stops.

Kindly suggest what can be done or what am I missing ?

I also need to add Push Pull commands after training and I don't have an idea how to achieve that...but that's an issue for later ! :smile: 
```
~/catkin_ws/src/BCI/community-sdk-master/examples_basic/Python$ python2 MentalCommandWithCloudProfile.py
========================================================================
Example to show how to train Mental Commands from EmoEngine/EmoComposer.
========================================================================
error adding certificate
error adding certificate
Your login attempt has failed. The username or password may be incorrect
terminate called without an active exception
Aborted (core dumped)
```

**Comment by tungntEmotiv** [comment]
Hi @Cryzic 
The above issue is fail login. Please make sure correct username and password filled at line 37,38 of the file.

**Comment by Cryzic** [comment]
I tried that but doesn't show any change in progress.
I will update the issue if anything happens.
