### ISSUE TITLE
Debian problem while linking (C++)

### ISSUE THREAD

**Issue by ngdelima** [Emotiv/community-sdk#322]
Hi!

I recently bought an epoc+ and downloaded the sdk, I tried to cmake and then make the gyro example under debian and the following message come out:

Linking CXX executable ../../../Programs/Gyro
/home/nicolas/Documents/community-sdk-emotiv/community-sdk/bin/linux64/libedk.so: undefined reference to `dbus_set_error_from_message@LIBDBUS_1_3'
/home/nicolas/Documents/community-sdk-emotiv/community-sdk/bin/linux64/libedk.so: undefined reference to `dbus_message_copy@LIBDBUS_1_3'
/home/nicolas/Documents/community-sdk-emotiv/community-sdk/bin/linux64/libedk.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/nicolas/Documents/community-sdk-emotiv/community-sdk/bin/linux64/libedk.so: undefined reference to `dbus_watch_get_enabled@LIBDBUS_1_3'
/home/nicolas/Documents/community-sdk-emotiv/community-sdk/bin/linux64/libedk.so: undefined reference to `dbus_connection_close@LIBDBUS_1_3'
/home/nicolas/Documents/community-sdk-emotiv/community-sdk/bin/linux64/libedk.so: undefined reference to `dbus_watch_set_data@LIBDBUS_1_3'
/home/nicolas/Documents/community-sdk-emotiv/community-sdk/bin/linux64/libedk.so: undefined reference to `dbus_message_get_args@LIBDBUS_1_3'
/home/nicolas/Documents/community-sdk-emotiv/community-sdk/bin/linux64/libedk.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'

(and it goes on..)

Then I tried to compile a basic example (C++ under Debian jessie):

```
#include "Iedk.h"
#include <iostream>

int main(int argc, char** argv)
{
	if (IEE_EngineConnect() != EDK_OK) {
		std::cout << "Emotiv Driver start up failed.";
		return -1;
	}
  std::cout << "running";
  //IEE_HardwareGetVersion();
  IEE_EngineDisconnect();
   return 0;
}
```

Just in order to get all the linking done properly. 

I try this following commands:

- g++ -I./include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -L/usr/lib/x86_64-linux-gnu/ -ldbus-1 gyrodata.cpp -ledk

- g++ `pkg-config --libs --cflags dbus-1` -I./include gyrodata.cpp -ledk

Both commands give me the same errors:

/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_message_set_no_reply@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_message_get_path@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_connection_list_registered@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_watch_get_enabled@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_message_iter_recurse@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_connection_unref@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_type_is_basic@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_connection_set_timeout_functions@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `dbus_timeout_get_interval@LIBDBUS_1_3'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libedk.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'

That also are pretty similar (if not the same) as the former one. On this issue #186 it's was told to be because of a deprecated version of libdbus, but in my case apt says that both libdbus-1-3 and libdbus-1-dev are up-to-date.

I have two options in mind: that my libdbus needs a downgrade or that the sdk it's not meant to work on this Debian version (btw: uname -a outputs Linux winchester 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux).

I'm so sorry if it's seems to be pretty basic stuff, but I can't get round this and I got a tight deadline.

Thanks!

**Comment by havietnam** [comment]
Hi @ngdelima ,
This problem occurs because incompatible glibc++ version between Debian and Ubuntu.
Current, we only support Ubuntu 16.04. If you want to run on Debian, please use same glibc++ as Ubuntu.
Thanks and BR.
