### ISSUE TITLE
EMOTIV in Docker.

### ISSUE THREAD

**Issue by Cryzic** [Emotiv/community-sdk#323]
I am trying to run the emostate_logger.py [examples_basic] and after successfully connecting the headset and seeing the new state being recorded, the ES.csv file doesn't contain any relevant data.

The .csv file always shows the timestamp and signal strength (the value is always '2'). Am I missing the config file or the user profile that has been trained on the Emotiv ControlPanel ? If so, how can I access it and where should I include it in the docker container ?

**Comment by duytan90** [comment]
You should try it on Windows with Python 2.7 x86 version @Cryzic, also make sure you've got good contact quality of all the electrodes while recording (running the script).

**Comment by Cryzic** [comment]
@duytan90 Thank you for the reply but I want this to run on Linux itself. I train my facial expressions using Emotiv Composer and execute the script using _python2_ from my catkin_ws.

Need to make it work urgently. :sob:
