### ISSUE TITLE
libedk.so: invalid ELF header

### ISSUE THREAD

**Issue by LajosNeto** [Emotiv/community-sdk#325]
I have been trying to load the .so files on Ubuntu 16.04 and get the following error:
`OSError: /home/lajos/Documents/Projects/MFC/system/linux/libedk.so: invalid ELF header`
I got the files from bin/linux64 and could not manage how to solve itg.
Please, your support.

**Comment by havietnam** [comment]
Hi @LajosNeto ,
libedk.so is symlink to libedk.so.3.3.3. You have problem with symlink.
You can check:
`$file libedk.so`
You can fix by overwrite file, use below command:
`cp libedk.so.3.3.3 libedk.so`

**Comment by LajosNeto** [comment]
Hello!
I tried the suggested solution but still not work.
I am using Ubuntu 32 bit 16.04 LTS
