### ISSUE TITLE
Android : Connect to headset directly without using sdk

### ISSUE THREAD

**Issue by mneckoee** [Emotiv/community-sdk#328]
Hi, I can not use the sdk, because I didn't get data from headset by sdk so I try to connect to headset directly by google BLE sample. then I got EEG data from headset, like this :
6C 01 BC B5 BF 04 EF 28 BF 8F F5 88 94 77 04 50 4B 7F 7D 0B
6C 02 79 91 66 A9 07 69 56 13 59 B6 AA EB D6 72 4E CF 00 00
6D 01 20 35 35 B1 44 70 AF 8C E7 B3 CE 36 5B 75 E2 4A 7D 0B
6D 02 04 AA 20 A7 7F 54 E3 DB EC CA 09 11 52 1B E9 DF 00 00
.
.
.
Is there any document for data structure?

**Comment by mneckoee** [comment]
hi @hoangphamemotiv 
yes i tried EEGLogger and fftexample, but didn't get result, so I connected to headset directly with google BLE sample project. I use Android. Is there any document for data structure?

**Comment by hoangphamemotiv** [comment]
@mneckoee 
the data you got with google BLE sample project are encrypted. so, only use our SDK library or Cortex to get raw EEG. 
can you try to connect your headset with a example on Mac or Win?

**Comment by mneckoee** [comment]
I can connect to headset with emotiv google play app sample,
Is the project close source or open source ?!
