### ISSUE TITLE
How to connect research sdk licensing to ActivateLicense 

### ISSUE THREAD

**Issue by Ordepedro1** [Emotiv/community-sdk#329]
Hello,
I have the research license sdk. 
I'm contacting Emotiv for almost a week, I already provided my serial key and order number. I continue to wait by a way to read raw data in real time. 
I could use the EEG_Data_Logger but my serial key is different from the license key that they use. I think it's because the license key is for those who has Emotiv pro. Anyway, with the research edition I have the right to use it. 
Does anyone know a way to access it? Since I really have to work and I'm stuck for almost a week with Emotiv support?
 
Thank you

**Comment by Ordepedro1** [comment]
Sorry, 
but of course I cannot put my serialkey in here. Anyway I already sent it to Emotiv.
I have the the licensing validate until 2021, so they absolutely have to get me a way to access those data! 
I can't access EEG_Data_Logger cause it won't passes in the ActivateLicense script cause I don't bought Emotiv Pro. Anyway I have Emotiv Research SDK that contain access to raw data, so I must have permission to that raw data. 

It's been weeks already.

**Comment by hoangphamemotiv** [comment]
@Ordepedro1 
any license key can be activated by ActivateLicense  script, examples.
Emotiv Research SDK is a old version, it does not work with  a license key. so, please upgrade the SDK lib and your example to SDK 3.5
