### ISSUE TITLE
Problems with Java Sample Mental Command

### ISSUE THREAD

**Issue by raphaelwb** [Emotiv/community-sdk#330]
I'm having trouble running the basic Java example of MentalCommandWithCloudProfile

I followed the following steps:

1. On the EmotivXavierControlPanel: Create a user, did the training for the Neutral and Push actions and sent the profile to the cloud using the Upload button. In the Action tab you can see the change of states between Neutral and Push working within the expected.

2. To make the examples work in Java I have placed the libraries in the correct places according to the documentation. I believe the libraries are properly installed because the HeadsetInformationLogger is displaying information.

3. In the MentalCommandWithCloudProfile, include the username / password / profilename used in ControlPanel. When program starts the message New user 4096 added, then I use option 9 (Load Profile) and then the OveralSkillRating option and the displayed value is the same as the ControlPanel so I believe that the profile is being loaded correctly.

The problem is that even the action changing in the controlpanel does not show any changes in the java version. I did the same steps on a Mac OS High Sierra and Windows7. The result was the same. I'm using the Emotiv USB dongle and the device is EpoC +

Anyone have any suggestions?

Thank you

Raphael

**Comment by hoangphamemotiv** [comment]
Hi @raphaelwb 

did you use CP and the example same time in the test? then CP you see action changed but the example is not, right?
The example is used for training session with MC and save/load profile. if you want to get power and current action, you can call API : IS_MentalCommandGetCurrentAction and IS_MentalCommandGetCurrentActionPower after you get EmostateUpdate event.

**Comment by raphaelwb** [comment]
Hi Pham,

I've been trying to use the other examples, such as EmoStateLogger.java. This example uses exactly the functions you mentioned (lines 76 and 79). The strange thing is that the result of the IS_MentalCommandGetCurrentActionPower function is the same of que CP, but the result of the IS_MentalCommandGetCurrentAction function is always ZERO, regardless of what is being shown in the CP (Neural, Push, etc). Another test I did was to use the IS_MentalCommandIsActive command and it is returning 0 when in CP the system is inactive and 1 when it is active. Apparently there is a functional connection between the java application, the sdk and the device. What happens is that the MentalCommands and FacialExpression information is not passed on. I've seen other people commenting on this type of problem in the forum (https://github.com/Emotiv/community-sdk/issues/159). It seems to be a problem with the SDK. I'm trying to find an older version to see if it works, but I did not find it to download.

Do you have other sugestions?

Thank you.

Raphael

**Comment by hoangphamemotiv** [comment]
Hi @raphaelwb 
at the moment we haven't found any issues with Mental command Training work flow in SDK. 
as you see in #159 i think the issue came from steps flow not correct. Control Panel used those API also, so if CP can fire those actions, APIs should be the same. 

Did you try to run other languages? C#, C++...

**Comment by raphaelwb** [comment]
Hi Pham,

I have read all the details of issue # 159 and I have not been able to find a problem that he has made and that I am repeating. From what I understand he was making implementation errors and I'm not developing an application yet, I'm just running the github examples.

I have not tried other languages ​​yet, but I tried the same procedure on Mac OS High Sierra and Windows 7, getting the same result. If there are no errors in the SDK I'm probably doing something wrong.

I will describe exactly what I did to see if you encounter any problems.

1. I installed the software package that contains Emotiv Xavier ControlPanel 3.5.0
2. The headSet is positioned until all connections are set to Good (green).
3. I created a user in the CP and I used the Detections >> Mental Command menu to train Neutral and Push.
4. The training was successfully completed. The Action tab displays Current Action, Detection Status, Difficulty Level, and Overall Skill Rating.
5. As soon as Mental Command is executed the Current Action field changes to Push. The cube is moved and then returns to Neutral.
6. I left the CP running as detailed above.
7. After configuring the libraries in a development environment I run the com.emotiv.examples.EmoStateLogger (no code changes).
8. Repeat step 5 again. As the mental commands are executed, changes are made in the Detections >> Mental Command >> Action >> Current Action from Neutral to Push and then again to Neutral.
9. In line 76, regardless of the change in the CP is always returned ZERO, however, lines 79 (CurrentActionPower) reflects the information presented in the CP.
8. I made a slight modification to the code including the IS_MentalCommandIsActive command. This command works as expected and the information presented in CP (Detections >> Mental Command >> Action >> Detection Status) is reflected in the java code.

ps: I will try to use Composer by running on the same machine and modifying only line 19 of the code for option = 2. I'm also going to test the Xavier EmoKey. I will report the results as soon as I complete the tests.

I await new suggestions.

Thank you

**Comment by CharlesYZhu** [comment]
Hi Pham and @raphaelwb,

I'm also having the same issue. For the EmoStateLogger.java example, I was able to get readings for Facial Expressions but, like @raphaelwb System.out.println(EmoState,INSTANCE.IS_MentalCommandGetCurrentAction(eState)) only prints "0".

Do I need to load a profile or train commands in order for it to recognize different mental commands?

Thank you,
Charles

**Comment by raphaelwb** [comment]
Hi Pham,

As a agreed I am reporting more about my tests. 

I tested with the Xavier EmoKey and it is working as expected. The facial movements and mental commands arrive in the tool. I also did the tests using the Composer (int option = 2) instead of using the API and the data also arrives at EmoStateLogger.java. I did all tests using the API again (int option = 1) and the changes still do not reflect in the code.

I am without ideas on how to solve the problem.

If you have any suggestions, thank you.

Raphael

**Comment by nnzhan** [comment]
Hi Pham, 

I also searched around this issue, really can't find out the solution. You mentioned you have fixed bugs related to #143 and #152 but still I failed to load profile. It seems that this bug has existed for a long time.

Han

**Comment by hoangphamemotiv** [comment]
Hi everyone, sorry for late. we are focusing on Cortex Service new features. 
yep, we checked the example and got the same issue : 
1. Training MentalCommand on Control Panel 
2. upload the profile to Cloud
3. Use example to load the profile then detect the MC detections. 
we got the issue cannot load the profile. that why you cannot detect MC detections. Mr @tungntEmotiv is working on this issue. 

For now, you can make the first fix as below: 
- if you are using CP 3.4 , please go to : C:/Users/ "userName"/AppData/Local/Emotiv to get the profile as local. If you are using CP 3.5 please go to : C:/ProgramData/Emotiv/UserData
- Using the example: MentalCommandWithLocalProfile which use API: IEE_LoadUserProfile to load the profile, then you can get MC detections. 
We will try to fix the issue ASAP. thank you for your help.

**Comment by tungntEmotiv** [comment]
Hi @nnzhan , @raphaelwb 
We have fixed loading profile issue from Cloud. Please rerun the example with some modification to show Action type and action power. There are some notices:
1) Make sure your training profile in Control Panel  have been uploaded to Cloud successfully (a message will be popup).
2) Use EC_LoadUserProfile to load profile -> Load finished.
3) Modify code to show action power and action type after loading profile successfully as below
`else if (eventType == Edk.IEE_Event_t.IEE_EmoStateUpdated.ToInt()) {
					Edk.INSTANCE.IEE_EmoEngineEventGetEmoState(eEvent, eState); 
					if (isLoaded)   // will show if the profile loaded succesfully 
                                      {
						System.out.print("MentalCommandGetCurrentAction: ");
						System.out.println(EmoState.INSTANCE
								.IS_MentalCommandGetCurrentAction(eState));
						System.out.print("CurrentActionPower: ");
						System.out.println(EmoState.INSTANCE
								.IS_MentalCommandGetCurrentActionPower(eState));
					}
				
				}`
If you have any concern, Please contact with us.
Once again, many thanks for raising this issue.
