### ISSUE TITLE
Fetching raw EEG data from EmotivPro in mac 

### ISSUE THREAD

**Issue by tanujhasija** [Emotiv/community-sdk#337]
Hi, 

I have EmotivPro full license to access the raw EEG data. I wanted to stream the raw EEG data from
Emotivpro to MATLAB (or Python) in real time in MacOS to develop a real-time application. I have tried a few things with no success and it doesn't seem to be straightforward. It would be great if somebody who has already done this could help me or link me to a post if it is already been answered in the past. 

Thanks much.

**Comment by duytan90** [comment]
Hi @tanujhasija, both Python and Matlab examples in this repo load the edk.dll library so it won't work on MacOS.
Maybe you can write your own Python (or Matlab) program using Websocket Protocol to work with Emotiv headset via [Cortex Service](http://download.emotiv.com/wp-products/CortexApps/CortexApp-Installer-v1.3.0-mac.dmg)

**Comment by tanujhasija** [comment]
Hi @duytan90 . Thanks for your reply! Ok. Are you aware of some resources/libraries to work with Websockets in Python (or Matlab) specifically for emotiv? That would be really useful. 
Thanks!

**Comment by hoangphamemotiv** [comment]
Hi @tanujhasija 
do you think you must stream the raw EEG data from EmotivPro? you can use Matlab examples to connect to EmotivHeadset then get raw data directly via that examples

**Comment by tanujhasija** [comment]
Hi Pham, 

I don’t necessarily require it to be streamed from EmotovPro. Are you aware of the examples in Matlab that work directly with MacOs as well? So far I have only found windows examples. 

Thanks!
