### ISSUE TITLE
Unity example issue(s)

### ISSUE THREAD

**Issue by ariefpurnamamuharram** [Emotiv/community-sdk#338]
Hi,
I'm a new user in Emotiv; also beginner in Emotiv Community-SDK. I want to try Community-SDK basic example on Unity. Everything is fine when I build and run it; I just export it to unity, build & run, and finish. But, when I launch the application, my application didn't respond anything. I cann't train neutral and mental command, also my gyro function isn't working too. I've followed the setup instruction.
Do you have any solution(s) for that?
Thank you

Best regards,
Arief Purnama Muharram

**Comment by ariefpurnamamuharram** [comment]
![screenshot 1](https://user-images.githubusercontent.com/16641165/41971814-e822e49a-7a39-11e8-90ac-dc1c5f2ce89c.png)
![screenshot 2](https://user-images.githubusercontent.com/16641165/41971815-e8d0a832-7a39-11e8-929a-36add2b0ea7d.png)
![screenshot 3](https://user-images.githubusercontent.com/16641165/41971816-e9574b1c-7a39-11e8-8f67-fcc1d9ba959f.png)

**Comment by hoangphamemotiv** [comment]
Hi @ariefpurnamamuharram 
your issue is Unity cannot found the edk libraries. Did you update newest version of the Example?
is your Unity 32bit or 64bit? at the moment edk.dll in the example is 32bit. so if your Unity is 64bit, it cannot load edk.dll. pls change the edk lib in the example to 64bit.

**Comment by ariefpurnamamuharram** [comment]
Hi @hoangphamemotiv 
Thank you for your solution. The problem have been solved now.
Thank you.

Best regards,
**Arief Purnama Muharram**
