### ISSUE TITLE
DllNotFoundException: edk.dll

### ISSUE THREAD

**Issue by ddemsahin** [Emotiv/community-sdk#350]
Hello, 
I am receiving DllNotFoundException: edk.dll error from Unity (Version 2018.2.10f1)
Also, I am a Mac user (High Sierra 10.13.6)

EmotivXavierControlPanel is working perfect and I can see the trained data there ;
/Users/Shared/Emotiv/UserData/ddem_sahin

I followed the instructions for setup and copied edk.framework into ;
/Library/Frameworks

But still I am receiving the same error. We really have limitted time for our thesis project and I need an urgent help! 
Thanks! 
<img width="818" alt="screen shot 2018-10-03 at 23 14 56" src="https://user-images.githubusercontent.com/33202154/46442737-95dfe180-c762-11e8-8f55-ed0d32352188.png">

**Comment by nguoithichkhampha** [comment]
@ddemsahin , If you are working on Mac OS. Should not load library edk.dll. this is only for Windows.
Please check your code follow this instruction:
`
#if UNITY_STANDALONE_OSX
[DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventCreate")]
	static extern IntPtr IEE_EmoEngineEventCreate();
#elif UNITY_STANDALONE_WIN
[DllImport("edk.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventCreate")]
	static extern IntPtr IEE_EmoEngineEventCreate();
`

**Comment by ddemsahin** [comment]
> @ddemsahin , If you are working on Mac OS. Should not load library edk.dll. this is only for Windows.
> Please check your code follow this instruction:
> 
> #if UNITY_STANDALONE_OSX
> [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventCreate")]
> static extern IntPtr IEE_EmoEngineEventCreate();
> #elif UNITY_STANDALONE_WIN
> [DllImport("edk.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventCreate")]
> static extern IntPtr IEE_EmoEngineEventCreate();



> hi @ddemsahin
> look like the message is from a Windows Unity, not MacOS, right?
 It is from MAcOS. Do You have any idea why it is happening ?

**Comment by ddemsahin** [comment]
> @ddemsahin , If you are working on Mac OS. Should not load library edk.dll. this is only for Windows.
> Please check your code follow this instruction:
> 
> #if UNITY_STANDALONE_OSX
> [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventCreate")]
> static extern IntPtr IEE_EmoEngineEventCreate();
> #elif UNITY_STANDALONE_WIN
> [DllImport("edk.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventCreate")]
> static extern IntPtr IEE_EmoEngineEventCreate();

` [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_LicenseInformation")]        
        static extern Int32 Unmanged_IEE_LicenseInformation(IntPtr licenseInfo);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_AuthorizeLicense")]
        static extern Int32 Unmanged_IEE_AuthorizeLicense(String licenseID, Int32 debitNum);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_GetDebitInformation")]
        static extern Int32 Unmanged_IEE_GetDebitInformation(String licenseID, IntPtr debitInfos);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EngineConnect")]
        static extern Int32 Unmanged_IEE_EngineConnect(String security);

        [DllImport("edk.", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EngineRemoteConnect")]
        static extern Int32 Unmanged_IEE_EngineRemoteConnect(String szHost, UInt16 port);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EngineDisconnect")]
        static extern Int32 Unmanged_IEE_EngineDisconnect();

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EnableDiagnostics")]
        static extern Int32 Unmanged_IEE_EnableDiagnostics(String szFilename, Int32 fEnable, Int32 nReserved);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventCreate")]
        static extern IntPtr Unmanged_IEE_EmoEngineEventCreate();

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventFree")]
        static extern void Unmanged_IEE_EmoEngineEventFree(IntPtr hEvent);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoStateCreate")]
        static extern IntPtr Unmanged_IEE_EmoStateCreate();

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoStateFree")]
        static extern void Unmanged_IEE_EmoStateFree(IntPtr hState);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventGetType")]
        static extern IEE_Event_t Unmanged_IEE_EmoEngineEventGetType(IntPtr hEvent);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventGetUserId")]
        static extern Int32 Unmanged_IEE_EmoEngineEventGetUserId(IntPtr hEvent, out UInt32 pUserIdOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EmoEngineEventGetEmoState")]
        static extern Int32 Unmanged_IEE_EmoEngineEventGetEmoState(IntPtr hEvent, IntPtr hEmoState);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EngineGetNextEvent")]
        static extern Int32 Unmanged_IEE_EngineGetNextEvent(IntPtr hEvent);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EngineClearEventQueue")]
        static extern Int32 Unmanged_IEE_EngineClearEventQueue(Int32 eventTypes);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_EngineGetNumUser")]
        static extern Int32 Unmanged_IEE_EngineGetNumUser(out UInt32 pNumUserOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_SetHardwarePlayerDisplay")]
        static extern Int32 Unmanged_IEE_SetHardwarePlayerDisplay(UInt32 userId, UInt32 playerNum);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_HeadsetGetSensorDetails")]
        static extern Int32 Unmanged_IEE_HeadsetGetSensorDetails(IEE_InputChannels_t channelId, out IInputSensorDescriptor_t pDescriptorOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_HardwareGetVersion")]
        static extern Int32 Unmanged_IEE_HardwareGetVersion(UInt32 userId, out UInt32 pHwVersionOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_SoftwareGetVersion")]
        static extern Int32 Unmanged_IEE_SoftwareGetVersion(StringBuilder pszVersionOut, UInt32 nVersionChars, out UInt32 pBuildNumOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_HeadsetGetGyroDelta")]
        static extern Int32 Unmanged_IEE_HeadsetGetGyroDelta(UInt32 userId, out Int32 pXOut, out Int32 pYOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_HeadsetGyroRezero")]
        static extern Int32 Unmanged_IEE_HeadsetGyroRezero(UInt32 userId);

        //Set/Get headset setting for EPOC+ headset
        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_GetHeadsetSettings")]
        static extern Int32 Unmanaged_IEE_GetHeadsetSettings(UInt32 userId, out UInt32 EPOCmode, out UInt32 eegRate, out UInt32 eegRes, out UInt32 memsRate, out UInt32 memsRes);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_SetHeadsetSettings")]
        static extern Int32 Unmanaged_IEE_SetHeadsetSettings(UInt32 userId, UInt32 EPOCmode, UInt32 eegRate, UInt32 eegRes, UInt32 memsRate, UInt32 memsRes);

        //Motion Data
        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataCreate")]
        static extern IntPtr Unmanaged_IEE_MotionDataCreate();

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataFree")]
        static extern void Unmanaged_IEE_MotionDataFree(IntPtr hData);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataUpdateHandle")]
        static extern Int32 Unmanaged_IEE_MotionDataUpdateHandle(UInt32 userId, IntPtr hData);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataGet")]
        static extern Int32 Unmanaged_IEE_MotionDataGet(IntPtr hData, IEE_MotionDataChannel_t channel, Double[] buffer, UInt32 bufferSizeInSample);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataGetMultiChannels")]
        static extern Int32 Unmanaged_IEE_MotionDataGetMultiChannels(IntPtr hData, IEE_MotionDataChannel_t[] channelList, UInt32 nChannel, Double[][] buffer, UInt32 bufferSizeInSample);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataGetNumberOfSample")]
        static extern Int32 Unmanaged_IEE_MotionDataGetNumberOfSample(IntPtr hData, out UInt32 nSampleOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataSetBufferSizeInSec")]
        static extern Int32 Unmanaged_IEE_MotionDataSetBufferSizeInSec(Single bufferSizeInSec);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataGetBufferSizeInSec")]
        static extern Int32 Unmanaged_IEE_MotionDataGetBufferSizeInSec(out Single pBufferSizeInSecOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MotionDataGetSamplingRate")]
        static extern Int32 Unmanaged_IEE_MotionDataGetSamplingRate(UInt32 userId, out UInt32 pSamplingRate);


        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandEventGetType")]
        static extern IEE_MentalCommandEvent_t Unmanged_IEE_MentalCommandEventGetType(IntPtr hEvent);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionEventGetType")]
        static extern IEE_FacialExpressionEvent_t Unmanged_IEE_FacialExpressionEventGetType(IntPtr hEvent);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionSetThreshold")]
        static extern Int32 Unmanged_IEE_FacialExpressionSetThreshold(UInt32 userId, IEE_FacialExpressionAlgo_t algoName, IEE_FacialExpressionThreshold_t thresholdName, Int32 value);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionGetThreshold")]
        static extern Int32 Unmanged_IEE_FacialExpressionGetThreshold(UInt32 userId, IEE_FacialExpressionAlgo_t algoName, IEE_FacialExpressionThreshold_t thresholdName, out Int32 pValueOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionSetTrainingAction")]
        static extern Int32 Unmanged_IEE_FacialExpressionSetTrainingAction(UInt32 userId, IEE_FacialExpressionAlgo_t action);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionSetTrainingControl")]
        static extern Int32 Unmanged_IEE_FacialExpressionSetTrainingControl(UInt32 userId, IEE_FacialExpressionTrainingControl_t control);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionGetTrainingAction")]
        static extern Int32 Unmanged_IEE_FacialExpressionGetTrainingAction(UInt32 userId, out IEE_FacialExpressionAlgo_t pActionOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionGetTrainingTime")]
        static extern Int32 Unmanged_IEE_FacialExpressionGetTrainingTime(UInt32 userId, out UInt32 pTrainingTimeOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionGetTrainedSignatureActions")]
        static extern Int32 Unmanged_IEE_FacialExpressionGetTrainedSignatureActions(UInt32 userId, out UInt32 pTrainedActionsOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionGetTrainedSignatureAvailable")]
        static extern Int32 Unmanged_IEE_FacialExpressionGetTrainedSignatureAvailable(UInt32 userId, out Int32 pfAvailableOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionSetSignatureType")]
        static extern Int32 Unmanged_IEE_FacialExpressionSetSignatureType(UInt32 userId, IEE_FacialExpressionSignature_t sigType);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FacialExpressionGetSignatureType")]
        static extern Int32 Unmanged_IEE_FacialExpressionGetSignatureType(UInt32 userId, out IEE_FacialExpressionSignature_t pSigTypeOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandSetActiveActions")]
        static extern Int32 Unmanged_IEE_MentalCommandSetActiveActions(UInt32 userId, ulong activeActions);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetActiveActions")]
        static extern Int32 Unmanged_IEE_MentalCommandGetActiveActions(UInt32 userId, out UInt32 pActiveActionsOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetTrainingTime")]
        static extern Int32 Unmanged_IEE_MentalCommandGetTrainingTime(UInt32 userId, out UInt32 pTrainingTimeOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandSetTrainingControl")]
        static extern Int32 Unmanged_IEE_MentalCommandSetTrainingControl(UInt32 userId, IEE_MentalCommandTrainingControl_t control);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandSetTrainingAction")]
        static extern Int32 Unmanged_IEE_MentalCommandSetTrainingAction(UInt32 userId, IEE_MentalCommandAction_t action);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetTrainingAction")]
        static extern Int32 Unmanged_IEE_MentalCommandGetTrainingAction(UInt32 userId, out IEE_MentalCommandAction_t pActionOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetTrainedSignatureActions")]
        static extern Int32 Unmanged_IEE_MentalCommandGetTrainedSignatureActions(UInt32 userId, out UInt32 pTrainedActionsOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetOverallSkillRating")]
        static extern Int32 Unmanged_IEE_MentalCommandGetOverallSkillRating(UInt32 userId, out Single pOverallSkillRatingOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetActionSkillRating")]
        static extern Int32 Unmanged_IEE_MentalCommandGetActionSkillRating(UInt32 userId, IEE_MentalCommandAction_t action, out Single pActionSkillRatingOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandSetActivationLevel")]
        static extern Int32 Unmanged_IEE_MentalCommandSetActivationLevel(UInt32 userId, Int32 level);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandSetActionSensitivity")]
        static extern Int32 Unmanged_IEE_MentalCommandSetActionSensitivity(UInt32 userId,
                                            Int32 action1Sensitivity, Int32 action2Sensitivity,
                                            Int32 action3Sensitivity, Int32 action4Sensitivity);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetActivationLevel")]
        static extern Int32 Unmanged_IEE_MentalCommandGetActivationLevel(UInt32 userId, out Int32 pLevelOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetActionSensitivity")]
        static extern Int32 Unmanged_IEE_MentalCommandGetActionSensitivity(UInt32 userId,
                                            out Int32 pAction1SensitivityOut, out Int32 pAction2SensitivityOut,
                                            out Int32 pAction3SensitivityOut, out Int32 pAction4SensitivityOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandStartSamplingNeutral")]
        static extern Int32 Unmanged_IEE_MentalCommandStartSamplingNeutral(UInt32 userId);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandStopSamplingNeutral")]
        static extern Int32 Unmanged_IEE_MentalCommandStopSamplingNeutral(UInt32 userId);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandSetSignatureCaching")]
        static extern Int32 Unmanged_IEE_MentalCommandSetSignatureCaching(UInt32 userId, UInt32 enabled);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetSignatureCaching")]
        static extern Int32 Unmanged_IEE_MentalCommandGetSignatureCaching(UInt32 userId, out UInt32 pEnabledOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandSetSignatureCacheSize")]
        static extern Int32 Unmanged_IEE_MentalCommandSetSignatureCacheSize(UInt32 userId, UInt32 size);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_MentalCommandGetSignatureCacheSize")]
        static extern Int32 Unmanged_IEE_MentalCommandGetSignatureCacheSize(UInt32 userId, out UInt32 pSizeOut);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_GetAverageBandPowers")]
        static extern Int32 Unmanged_IEE_GetAverageBandPowers(UInt32 userId, IEE_DataChannel_t channel, Double[] theta, Double[] alpha, Double[] low_beta, Double[] high_beta, Double[] gamma);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FFTSetWindowingType")]
        static extern Int32 Unmanged_IEE_FFTSetWindowingType(UInt32 userId, IEE_WindowingTypes type);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_FFTGetWindowingType")]
        static extern Int32 Unmanged_IEE_FFTGetWindowingType(UInt32 userId, out IEE_WindowingTypes type);


        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsBlink")]
        static extern Boolean Unmanaged_IS_FacialExpressionIsBlink(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsLeftWink")]
        static extern Boolean Unmanaged_IS_FacialExpressionIsLeftWink(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsRightWink")]
        static extern Boolean Unmanaged_IS_FacialExpressionIsRightWink(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsEyesOpen")]
        static extern Boolean Unmanaged_IS_FacialExpressionIsEyesOpen(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsLookingUp")]
        static extern Boolean Unmanaged_IS_FacialExpressionIsLookingUp(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsLookingDown")]
        static extern Boolean Unmanaged_IS_FacialExpressionIsLookingDown(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsLookingLeft")]
        static extern Int32 Unmanaged_IS_FacialExpressionIsLookingLeft(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsLookingRight")]
        static extern Int32 Unmanaged_IS_FacialExpressionIsLookingRight(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetEyelidState")]
        static extern void Unmanaged_IS_FacialExpressionGetEyelidState(IntPtr state, out Single leftEye, out Single rightEye);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetEyeLocation")]
        static extern void Unmanaged_IS_FacialExpressionGetEyeLocation(IntPtr state, out Single x, out Single y);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetEyebrowExtent")]
        static extern Single Unmanaged_IS_FacialExpressionGetEyebrowExtent(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetSmileExtent")]
        static extern Single Unmanaged_IS_FacialExpressionGetSmileExtent(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetClenchExtent")]
        static extern Single Unmanaged_IS_FacialExpressionGetClenchExtent(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetUpperFaceAction")]
        static extern IEE_FacialExpressionAlgo_t Unmanaged_IS_FacialExpressionGetUpperFaceAction(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetUpperFaceActionPower")]
        static extern Single Unmanaged_IS_FacialExpressionGetUpperFaceActionPower(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetLowerFaceAction")]
        static extern IEE_FacialExpressionAlgo_t Unmanaged_IS_FacialExpressionGetLowerFaceAction(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionGetLowerFaceActionPower")]
        static extern Single Unmanaged_IS_FacialExpressionGetLowerFaceActionPower(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionIsActive")]
        static extern Boolean Unmanaged_IS_FacialExpressionIsActive(IntPtr state, IEE_FacialExpressionAlgo_t type);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_MentalCommandGetCurrentAction")]
        static extern IEE_MentalCommandAction_t Unmanaged_IS_MentalCommandGetCurrentAction(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_MentalCommandGetCurrentActionPower")]
        static extern Single Unmanaged_IS_MentalCommandGetCurrentActionPower(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_MentalCommandIsActive")]
        static extern Boolean Unmanaged_IS_MentalCommandIsActive(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_FacialExpressionEqual")]
        static extern Boolean Unmanaged_IS_FacialExpressionEqual(IntPtr a, IntPtr b);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_MentalCommandEqual")]
        static extern Boolean Unmanaged_IS_MentalCommandEqual(IntPtr a, IntPtr b);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_Create")]
        static extern IntPtr Unmanaged_IS_Create();

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_Free")]
        static extern void Unmanaged_IS_Free(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_Init")]
        static extern void Unmanaged_IS_Init(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_GetTimeFromStart")]
        static extern Single Unmanaged_IS_GetTimeFromStart(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_GetHeadsetOn")]
        static extern Int32 Unmanaged_IS_GetHeadsetOn(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_GetNumContactQualityChannels")]
        static extern Int32 Unmanaged_IS_GetNumContactQualityChannels(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_GetContactQuality")]
        static extern IEE_EEG_ContactQuality_t Unmanaged_IS_GetContactQuality(IntPtr state, Int32 electroIdx);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_GetContactQualityFromAllChannels")]
        static extern Int32 Unmanaged_IS_GetContactQualityFromAllChannels(IntPtr state, IEE_EEG_ContactQuality_t[] contactQuality, UInt32 numChannels);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_GetWirelessSignalStatus")]
        static extern IEE_SignalStrength_t Unmanaged_IS_GetWirelessSignalStatus(IntPtr state);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_Copy")]
        static extern void Unmanaged_IS_Copy(IntPtr a, IntPtr b);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_EmoEngineEqual")]
        static extern Boolean Unmanaged_IS_EmoEngineEqual(IntPtr a, IntPtr b);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_Equal")]
        static extern Boolean Unmanaged_IS_Equal(IntPtr a, IntPtr b);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IS_GetBatteryChargeLevel")]
        static extern void Unmanaged_IS_GetBatteryChargeLevel(IntPtr state, out Int32 chargeLevel, out Int32 maxChargeLevel);

        
        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_ProfileEventCreate")]
        static extern IntPtr Unmanged_IEE_ProfileEventCreate();

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_SetUserProfile")]
        static extern Int32 Unmanged_IEE_SetUserProfile(UInt32 userId, Byte[] profileBuffer, UInt32 length);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_GetUserProfile")]
        static extern Int32 Unmanged_IEE_GetUserProfile(UInt32 userId, IntPtr hEvent);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_GetBaseProfile")]
        static extern Int32 Unmanged_IEE_GetBaseProfile(IntPtr hEvent);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_GetUserProfileSize")]
        static extern Int32 Unmanged_IEE_GetUserProfileSize(IntPtr hEvt, out UInt32 pProfileSizeOut);


        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_GetUserProfileBytes")]
        static extern Int32 Unmanged_IEE_GetUserProfileBytes(IntPtr hEvt, Byte[] destBuffer, UInt32 length);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_LoadUserProfile")]
        static extern Int32 Unmanged_IEE_LoadUserProfile(UInt32 userID, String szInputFilename);

        [DllImport("edk", CallingConvention = CallingConvention.Cdecl, EntryPoint = "IEE_SaveUserProfile")]
        static extern Int32 Unmanged_IEE_SaveUserProfile(UInt32 userID, String szOutputFilename);
        `

Hi again, 
I changed `"edk.dll"` to `"edk"` in Edk.Dll.cs file. 
First, I changed just above that line  `static extern IntPtr IEE_EmoEngineEventCreate();`
Second, I changed in every line in order.
However, I am still getting the same error. 
It will be really nice if you can help me out. ddemsahin@gmail.com here is my email as well.

**Comment by nguoithichkhampha** [comment]
@ddemsahin , Can you setup a team viewer session ? we will help you debug.

**Comment by ddemsahin** [comment]
> @ddemsahin , Can you setup a team viewer session ? we will help you debug.

When will you be available ???

**Comment by hoangphamemotiv** [comment]
Hi @ddemsahin 

i uploaded Emotiv Unity Plugin to : https://github.com/Emotiv/community-sdk/tree/develop/include/Emotiv_Unity_Plugin 
Could you check it?

**Comment by ddemsahin** [comment]
> Hi @ddemsahin
> 
> i uploaded Emotiv Unity Plugin to : https://github.com/Emotiv/community-sdk/tree/develop/include/Emotiv_Unity_Plugin
> Could you check it?

Thanks for your immediate reply, I really appreciate it! 
I checked the update. However, probably I am missing a step in Git. I don't know is it too much to ask. But it will be great if you can check out through Teamviewer.

**Comment by hoangphamemotiv** [comment]
@ddemsahin in the plugin has a document (did you read it?) and the way to build edk bundle file on MacOS. just small step to make it work for you. 
after that you can tell me what issues you get. so i can help.

i am very happy if can help you via Teamview, but i am allowed to do it directly. you can contact to Customer support for asking.

**Comment by hoangphamemotiv** [comment]
i also pushed Unity plugin into https://github.com/Emotiv/community-sdk/tree/master/include/Emotiv_Unity_Plugin . you can check it for your working. thanks. ^^!

**Comment by yazeedhasan97** [comment]
Hi @[hoangphamemotiv](/hoangphamemotiv)
I followed the steps in connecting emotive to unity and now i am trying to open the Roll Ball example from the community SDK
but it keep give those two errors

DllNotFoundException: edk.dll
Emotiv.EdkDll.IEE_EmoEngineEventCreate () (at <cea289b984a6466198b4220c772e08fe>:0)
Emotiv.EmoEngine..ctor () (at <cea289b984a6466198b4220c772e08fe>:0)
Emotiv.EmoEngine.get_Instance () (at <cea289b984a6466198b4220c772e08fe>:0)
EmotivCtrl.Awake () (at Assets/scripts/EmotivCtrl.cs:26)


DllNotFoundException: edk.dll
Emotiv.EdkDll.IEE_EmoEngineEventCreate () (at <cea289b984a6466198b4220c772e08fe>:0)
Emotiv.EmoEngine..ctor () (at <cea289b984a6466198b4220c772e08fe>:0)
Emotiv.EmoEngine.get_Instance () (at <cea289b984a6466198b4220c772e08fe>:0)
playerCtrl.Start () (at Assets/scripts/playerCtrl.cs:39)


can you pls help me determin what is the exact problem here
