### ISSUE TITLE
Mental Commands not being read from cloud in java?

### ISSUE THREAD

**Issue by cedorland** [Emotiv/community-sdk#356]
I'm having a bit of trouble reading mental commands in java. I can log in to my emotiv cloud profile and the headset is connected (no errors), but no mental commands get read when I try to run live mode. I can't find any proper documentation for the Java SDK. Here's my code:

`int mode = 0; `
`private void readMentalCommands(){`
` ` ` ` ` ` `       int lastMentalCommand = -1;`
` ` ` ` ` ` `    	while(!finished) {`
` ` ` ` ` ` ` ` ` ` ` ` `    		state = Edk.INSTANCE.IEE_EngineGetNextEvent(eEvent);`
` ` ` ` ` ` ` ` ` ` ` ` `			if(state == EdkErrorCode.EDK_OK.ToInt()){`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `				int eventType = Edk.INSTANCE.IEE_EmoEngineEventGetType(eEvent);`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `				if (eventType == Edk.IEE_Event_t.IEE_EmoStateUpdated.ToInt()) {`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `	    			int currentCommand = EmoState.INSTANCE.IS_MentalCommandGetCurrentAction(eState);`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `	    			float currentPower=EmoState.INSTANCE.IS_MentalCommandGetCurrentActionPower(eState);`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `	    			if(lastMentalCommand!=currentCommand) {`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `	    				lastMentalCommand = currentCommand;`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `	    				mode = currentCommand;`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `	    				printString("Mode: "+currentCommand+"    ||    Strength: "+currentPower+"");`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `	    			}`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `	    		}`
` ` ` ` ` ` ` ` ` ` ` ` `			}else if(state != EdkErrorCode.EDK_NO_EVENT.ToInt()){`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `			printString("Internal error in Emotiv Engine!");`
` ` ` ` ` ` ` ` ` ` ` ` `			}`
` ` ` ` ` ` `	  	}`
` ` ` ` ` ` `  	return;`
`}`

There are no errors in the code, but nothing happens when I run live classification like this - not even a neutral state is published. Keep in mind, this is being run as a separate thread. The boolean 'finished' is being triggered separately, when the user wants to end live mode. What's going on?

**Comment by cedorland** [comment]
I edited the code to try something a bit different, but it still won't work. Almost the same behavior as the code above, but this time it tells me that the value of EmoState.INSTANCE.IS_MentalCommandGetCurrentAction(eState) is always 1. How should I be reading the current mental command? I have the action trained and it works really well in the EmotivBCI live mode.

New code:
`private void readMentalCommands(){`
` ` ` ` ` ` ` ` `int lastMentalCommand = Integer.MAX_VALUE;`
` ` ` ` ` ` ` ` `while(!finished) {`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `state = Edk.INSTANCE.IEE_EngineGetNextEvent(eEvent);`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `if(state == EdkErrorCode.EDK_OK.ToInt()){`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `int eventType = Edk.INSTANCE.IEE_EmoEngineEventGetType(eEvent);`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `Edk.INSTANCE.IEE_EmoEngineEventGetUserId(eEvent, engineUserID);`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `if (eventType == Edk.IEE_Event_t.IEE_EmoStateUpdated.ToInt()){`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `Edk.INSTANCE.IEE_EmoEngineEventGetEmoState(eEvent,eState);`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `int currentCommand=EmoState.INSTANCE.IS_MentalCommandGetCurrentAction(eState);`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `if(currentCommand!=lastMentalCommand) {`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `if(currentCommand==EmoState.IEE_MentalCommandAction_t.MC_NEUTRAL.ToInt())`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `printString("Mode: NEUTRAL");`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `if(currentCommand==EmoState.IEE_MentalCommandAction_t.MC_PUSH.ToInt())`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `printString("Mode: PUSH");`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `if(currentCommand==EmoState.IEE_MentalCommandAction_t.MC_PULL.ToInt())`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `printString("Mode: PULL");`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `if(currentCommand==EmoState.IEE_MentalCommandAction_t.MC_LEFT.ToInt())`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `printString("Mode: LEFT");`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `if(currentCommand==EmoState.IEE_MentalCommandAction_t.MC_RIGHT.ToInt())`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `printString("Mode: RIGHT");`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `}`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `}`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `lastMentalCommand = currentCommand;`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `}`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `}else if(state != EdkErrorCode.EDK_NO_EVENT.ToInt()){`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `printString("Internal error in Emotiv Engine!");`
` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `}`
` ` ` ` ` ` ` ` `}`
` ` ` ` ` ` ` ` `printString("Live mode has ended.");`
` ` ` ` ` ` ` ` `return;`
`}`

**Comment by bchaperon** [comment]
Hi @cedorland 
Did you successfully load your profile in your Java program?

**Comment by cedorland** [comment]
Logging in has been successful. I'm unclear on exactly how to load the user profile.
I'm currently using these calls:

`Edk.INSTANCE.IEE_EngineConnect("Emotiv Systems-5");`
`EmotivCloudClient.INSTANCE.EC_Connect();`
`EmotivCloudClient.INSTANCE.EC_Login(user, pass);`
`EmotivCloudClient.INSTANCE.EC_GetUserDetail(userCloudID);`
`EmotivCloudClient.INSTANCE.EC_GetProfileId(userCloudID.getValue(), profileName, profileID);`

which are all returning EdkErrorCode.EDK_OK, but the call

`EmotivCloudClient.INSTANCE.EC_LoadUserProfile(userCloudID.getValue(), engineUserID.getValue(), profileID.getValue(),-1);`
fails.

**Comment by hoangphamemotiv** [comment]
hi @cedorland 
sorry for late. i checked on loading a training profile created by BCI. yep, you correct, it load failed .something changed in new training profile format from Cortex service that make it doesn't compatible with SDK 3.5.1

**Comment by hoangphamemotiv** [comment]
@cedorland i think you can try with Cortex service. ^^!
here is examples of Cortex service https://github.com/Emotiv/cortex-example

**Comment by cedorland** [comment]
Does that mean I cannot complete this project in java? I don't see java support for Cortex.  
Is there a way I could make this work in java with the code I have? I could add MentalCommands training to my current program, and save profiles that way. Would that be possible?

**Comment by bchaperon** [comment]
Hello @cedorland 
The Cortex API is based on a Web Socket connection.
So you can use the Cortex API with any programming language that can connect to a Web Socket server.
That includes Java, and virtually all modern programing languages.
