### ISSUE TITLE
EmotivUnity

### ISSUE THREAD

**Issue by KaoZYC** [Emotiv/community-sdk#359]
![default](https://user-images.githubusercontent.com/22863290/49230128-ebb2cc00-f429-11e8-8828-3234a516a315.PNG)
Where does the software download?

**Comment by hoangphamemotiv** [comment]
can you tell more detail on your issue? @KaoZYC

**Comment by KaoZYC** [comment]
Does the edk.dll need to put in C:\Emotiv?

**Comment by hoangphamemotiv** [comment]
@KaoZYC . here is about plugin in Unity. 
https://docs.unity3d.com/Manual/UpgradeGuide5-Plugins.html

you can put edk.dll into Assets\Plugins\"OSName" . on windows Unity, please take care about bit version of Unity and edk.dll

**Comment by KaoZYC** [comment]
What something need to put in C:\Emotiv?

**Comment by hoangphamemotiv** [comment]
the folder C:/Emotiv is not important on any app of Emotiv. i am not sure how it generated. but you don't need to put anything to that folder yourseft

**Comment by KaoZYC** [comment]
Ok.Thank you for your help!
