### ISSUE TITLE
Use of serial port with Emotiv Epoc

### ISSUE THREAD

**Issue by Akankshatri18** [Emotiv/community-sdk#361]
Hii,
I need to use serial port with Emotiv Epoc headset for sending markers. What are the basic settings for the same? Whatever settings for serial port are shown through device manager I have done but don't know why Marker is coming with "0" value instead "1" and it's showing only in real time but neither in the replay  nor in the recorded edf files (may be because of zero value).  Is there anything in the setting which I am missing?Please guide me.

**Comment by hoangphamemotiv** [comment]
hi @Akankshatri18 
can you tell me what Emotiv application are you using on marker serial port feature? and it' version?
at the first look, i think the app haven't connected to your serial port device yet, so no thing sent as you think it is "0" value

**Comment by Akankshatri18** [comment]
Here I have attached the image of software which I am using. How can I be sure that serial port has connected , because still when system detecting TTL pulse, marker lines are coming in Marker window but with zero value. See in the another attached image.

![test bench_01](https://user-images.githubusercontent.com/45584735/49424844-d8a15280-f7c1-11e8-81fa-cc02a20f8231.PNG)



![test bench](https://user-images.githubusercontent.com/45584735/49424365-582e2200-f7c0-11e8-8a0b-f403a10f9c2f.PNG)

**Comment by hoangphamemotiv** [comment]
@Akankshatri18 
you are using a very old version. which we don't support anymore. 
btw, i see the app can get marker from serial port but with value of marker = 0. there are some issue can make that: 
- please make sure you set data bit = 8 bit. 
- try to change your value format to set what happen. see it can change another value or not. 
just some small changes to make it work.

**Comment by hoangphamemotiv** [comment]
@Akankshatri18 
now we released EmotivPro is a application of EEG, bandpower, Performance Metric. 
it has many features useful to you. https://www.emotiv.com/emotivpro/
please check it for your working. 
btw, you can email to our customer support for best help. thanks.

**Comment by Akankshatri18** [comment]
OK , Thanks a lot. I'll explore it and will contact customer support if needed.
