### ISSUE TITLE
emotiv cortex dose not respond 

### ISSUE THREAD

**Issue by asmasaad** [Emotiv/community-sdk#364]
Operating system: macOs version  10.13.6
Cortex service version: 1.8.357
cortex UI version: 1.8.97

---
after the last update of emotiv cortex  .
the cortex UI stop responding after I enter the password and emotv id 

 Thanks for your help

**Comment by hoangphamemotiv** [comment]
@asmasaad 
please raise a question at: https://github.com/Emotiv/cortex-v2-example
