### ISSUE TITLE
DllNotFoundException: edk.dll

### ISSUE THREAD

**Issue by yazeedhasan97** [Emotiv/community-sdk#367]
I followed the steps in connecting emotive to unity and now I am trying to open the Roll Ball example from the community SDK
but it keeps giving those two errors

DllNotFoundException: edk.dll
Emotiv.EdkDll.IEE_EmoEngineEventCreate () (at :0)
Emotiv.EmoEngine..ctor () (at :0)
Emotiv.EmoEngine.get_Instance () (at :0)
EmotivCtrl.Awake () (at Assets/scripts/EmotivCtrl.cs:26)

DllNotFoundException: edk.dll
Emotiv.EdkDll.IEE_EmoEngineEventCreate () (at :0)
Emotiv.EmoEngine..ctor () (at :0)
Emotiv.EmoEngine.get_Instance () (at :0)
playerCtrl.Start () (at Assets/scripts/playerCtrl.cs:39)

can you pls help me determin what is the exact problem here

**Comment by yazeedhasan97** [comment]
Hi @[hoangphamemotiv](/hoangphamemotiv)
any help pls

**Comment by hoangphamemotiv** [comment]
hi @yazeedhasan97 
the issue that the library DLL is not in correct folder. 
on different OSs, you can push the library into: Assets\Plugins\"OS name"
on Windows, if you run a Unity project on Debug mode you can push the library to folder above or in the same folder with file project. and the lib is 32 bit or 64 bit follow your Unity is 32bit or 64bit. 
if you run .exe file built, the lib is the same with bit version you choose to build the project. 

i removed Roll Ball example which outdated and added Mental Command Unity example in develop branch. i think it is useful to you. https://github.com/Emotiv/community-sdk/tree/develop/examples_basic/Unity/MentalCommand

**Comment by yazeedhasan97** [comment]
thanx a lot
the new update is really cool it worked and solved many other problems

**Comment by yazeedhasan97** [comment]
excuse me if I may ask
Is there a way to activate or deactivate the Inertial Sensor functionality via code ?!

**Comment by hoangphamemotiv** [comment]
Yep, sure. There are many features you can find in the plugin.
