### ISSUE TITLE
Emotiv Epoc+ not discoverable in EmotivPRO and EmotivBCI

### ISSUE THREAD

**Issue by zisulescu** [Emotiv/community-sdk#369]
Good day, 

I am having an issue connecting my Emotiv EPOC+ to the mentioned applications. BrainViz is working just fine, but the other applications, including Cortex, are not detecting the device. Any solutions? 

Thank you!

**Comment by hoangphamemotiv** [comment]
thank @zisulescu for your report. can you create a task in https://github.com/Emotiv/cortex-example/issues
we dont use this repo any more. thanks. ^^!
