### ISSUE TITLE
integrating EmotivEPOC to unity

### ISSUE THREAD

**Issue by rendezvous** [Emotiv/community-sdk#374]
I'm coding a small game on Unity to control using Emotiv Epoc. I'm trying to learn how to connect the device by looking at the unity example provided here (rolling ball). I have DotNetEmotivSDK.dll in my assets folder and I modified the path environment variable as mentioned in the instructions (edk.dll folder). However I don't understand how and where is the EmotivCtrl.cs script (where the connectionto the device is set) called in the Rolling Ball example, because if I put it in my project it does nothing.
I would like someone to tell me if what I'm doing is not the right way of connecting to Unity or if I'm missing something.

**Comment by RuVT** [comment]
Please check this:
https://github.com/Emotiv/community-sdk/blob/master/examples_basic/Unity/RollingBall/Assets/scripts/EmotivCtrl.cs

The Awake() method is the important one

**Comment by hoangphamemotiv** [comment]
thank @RuVT it is important. 
but that example is outdated. 
pls use our plugin for your work, https://github.com/Emotiv/community-sdk/tree/master/include/Emotiv_Unity_Plugin

**Comment by rendezvous** [comment]
thanks for your replies!
@hoangphamemotiv how should I add the plugin to my Unity project? Because I tried adding as a custom package, but there's no .unitypackage in there. Maybe something to do with the unity version?
Also, when I'll manage to add the plugin to unity, do I have to link the scripts to some object in my game or they will be called and run automatically to connect to my emotiv epoc and then I'll only need to create a playerControl script to use the functions there?
Thanks

**Comment by hoangphamemotiv** [comment]
@rendezvous just simple copy/include that plugin into your project. 
the plugin are wrapper classed to connect to SDK library. then you need to include them in your process classed and call APIs. it also supported all platforms desktop and mobile, i think there are document in the plugin already.

**Comment by rendezvous** [comment]
thanks @hoangphamemotiv , the problem is that when a function that is called by an event is called, for example: `void UserAddedEvent(object sender, EmoEngineEventArgs e)` , I get a Null Reference Exception and can't connect properly to the Emotiv Epoc. Do I also have to add to the project the edk.dll? The only way of making it connect to the device is by adding edk.dll and DotNetEmotivSDK.dll to the assets folder and adding "using Emotiv" to the scripts where it's needed, like in the outdated rolling ball example. 
Also, although I can control my object, I can only train push or neutral. I tried adding pull or right, but it doesn't throw the event of training started. I also tried adding a new movement to train in the Rolling Ball example, but it also doesn't work. I have a function like this: 
```
public void TrainRight()
    {
        engine.MentalCommandSetTrainingAction((uint)engineUserID, EdkDll.IEE_MentalCommandAction_t.MC_RIGHT);
        engine.MentalCommandSetTrainingControl((uint)engineUserID, EdkDll.IEE_MentalCommandTrainingControl_t.MC_START);
    }
``` 
and I checked if it was accessed and it was, but it doesn't throw the event of training started (IEE_MentalCommandTrainingStarted), only if it's push or neutral. If you want I can show you the complete scripts, maybe it's something I'm not setting up correctly on Unity, because to me it's strange that the new training commands don't work in the example provided in the SDK.

**Comment by hoangphamemotiv** [comment]
hi, i think you can using Mantal command C# example at the first to see it can work for you. after that you can try on Unity.

**Comment by rendezvous** [comment]
thanks @hoangphamemotiv , I checked it out and added some new things to my program. Now my training functions look like this: 
```
 public void TrainPush()
    {
        ulong action1 = (ulong)EdkDll.IEE_MentalCommandAction_t.MC_PUSH;
        ulong action2 = (ulong)EdkDll.IEE_MentalCommandAction_t.MC_RIGHT;
        ulong action3 = (ulong)EdkDll.IEE_MentalCommandAction_t.MC_PULL;
        ulong actions = action1 | action2 | action3;
        EmoEngine.Instance.MentalCommandSetActiveActions((uint)engineUserID, actions);
        Debug.Log("active" + (uint)EmoEngine.Instance.MentalCommandGetActiveActions((uint)engineUserID));
        engine.MentalCommandSetTrainingAction((uint)engineUserID, EdkDll.IEE_MentalCommandAction_t.MC_PUSH);
        engine.MentalCommandSetTrainingControl((uint)engineUserID, EdkDll.IEE_MentalCommandTrainingControl_t.MC_START);
        Debug.Log("ACTIOON p: " + engine.MentalCommandGetTrainingAction((uint)engineUserID));
    }
```
By printing the Mental Command Active Actions I get this value: 70
The problem is that when I add this code now I think my Emotiv CLoud profile gets "corrupted" and the mental commands don't work (not even push), and using that profile in the rolling ball example doesn't work either. Any ideas about why is this happening? I think it must be related to setting up the actions before saving the cloud profile, but I can't figure it out.
To detect the mental commands I use:
```
EmoState es = e.emoState;
        
        Debug.Log("Corrent action: " + es.MentalCommandGetCurrentAction().ToString());
        if (es.MentalCommandGetCurrentAction() == EdkDll.IEE_MentalCommandAction_t.MC_PUSH)
        {
            
            gameObject.transform.Translate(2f * Time.deltaTime, 0, 0);
            
            Debug.Log("Push");
        }
        if (es.MentalCommandGetCurrentAction() == EdkDll.IEE_MentalCommandAction_t.MC_PULL)
        {
           

            gameObject.transform.Translate(-2f * Time.deltaTime, 0, 0);

            Debug.Log("Pull");
        }
```
I don't know if I'm putting the code to set the active actions in the right place, I tried putting it in the awake method, but it didn't work. I tried putting it when I save the profile, but it also didn't work well.

**Comment by AdityaSher** [comment]
> just simple copy/include that plugin into your project.
> the plugin are wrapper classed to connect to SDK library. then you need to include them in your process classed and call APIs. it also supported all platforms desktop and mobile, i think there are the document in the plugin already.

@hoangphamemotiv 
The plugin is outdated and doesn't contain code for performance metrics what must I do?

**Comment by hoangphamemotiv** [comment]
@AdityaSher the Unity plugin up to date. that means, it is last version we have for SDK 3.5.x
yep, it missed PM. can you take a look in C# header files? https://github.com/Emotiv/community-sdk/blob/master/include/C%23/PerformanceMetric.cs
i think it is not hard to implement to the Plugin.
