### ISSUE TITLE
Lack of data through mind your osc?

### ISSUE THREAD

**Issue by Bambooze** [Emotiv/community-sdk#376]
Hey everyone,

I have been trying to bridge Mind Your OSC together with Ableton, and I ran into simultaneous issues, that I would like to understand. I have an Emotiv Insight, and as I would connect it with MYOSC through Emotiv engine, I can only see the the BLINK, SMILE, and SURPRISE data values changing. No clench or smirk or left/right wink. Regarding that, given that BCI software changed, is there still a way to connect to the Emotiv Control Panel through MYOSC? I'm failing to understand how do I fully get all the data in Mind Your OSC to able to send it? Or is that something that we don't have access to unless we spend the steep price of 99$ a month to get the data?

When i did a check over OSC monitor, the only thing i was getting was a smirk refreshing around 50 times a second with no attached values in it?
<img width="273" alt="Screen Shot 2019-05-30 at 5 42 58 PM" src="https://user-images.githubusercontent.com/37966539/58645555-e1ec2180-8303-11e9-84d7-98a5584d6c5a.png">

Could anyone be kind enough to explain how to navigate in this forest?

**Comment by hoangphamemotiv** [comment]
hi @Bambooze 
Facial Expression detections on MYOSC should be same with Emotiv BCI. can you use Emotiv Control Panel v3.5 (CP) to see more clear on the changes? yep, you can connect to CP on MYOSC. 

Faciall Expression and Mantal Command detections don't requires 99$ license. ^^!. 
each of detetions has different update time per seconds.

**Comment by Bambooze** [comment]
Hey @hoangphamemotiv ! Might be a dumb question, but where can i find Emotiv Control Panel v3.5 ?

**Comment by hoangphamemotiv** [comment]
@Bambooze 
we released Emotiv BCI instead of Emotiv Control panel. then if you don't have it before. i am not sure where you can get it now. 
but Mind Your OSCs only work with CP. Emotiv BCI hasn't supported it yet.

**Comment by AdityaSher** [comment]
@Bambooze please mail me for the file.
