### ISSUE TITLE
How do Windows users use the SDK

### ISSUE THREAD

**Issue by shanxiaofan** [Emotiv/community-sdk#380]
What shall I do after I download community-sdk to my computer?My computer system is Windows, I saw a TXT file in example_basic about the MacOS system users need to copy edk to a certain path of the computer, but I did not find the Windows system how to do?

**Comment by hoangphamemotiv** [comment]
hi @shanxiaofan . we don't support SDK kit anymore. please change to use Cortex service with many new features. thanks. ^^!

Cortex examples: https://github.com/Emotiv/cortex-v2-example
Cortex API docs: https://emotiv.gitbook.io/cortex-api
