### ISSUE TITLE
How to get start with this sdk? 

### ISSUE THREAD

**Issue by shanxiaofan** [Emotiv/community-sdk#381]
I download the zip file. Next I want to use the C++ language example. Do I need to configure anything? Thank you for your answer

**Comment by hoangphamemotiv** [comment]
hi @shanxiaofan . we don't support SDK kit anymore. please change to use Cortex service with many new features. thanks. ^^!

Cortex examples: https://github.com/Emotiv/cortex-v2-example
Cortex API docs: https://emotiv.gitbook.io/cortex-api
