### ISSUE TITLE
Can't you continue using the SDK package?

### ISSUE THREAD

**Issue by shanxiaofan** [Emotiv/community-sdk#384]
Hello, may I ask if you no longer support SDK toolkit, which means that users can no longer use this SDK?Or is it just not maintained?
Because I asked a few days ago, the answer they gave me was no maintenance, but I think it can still be used

**Comment by nguoithichkhampha** [comment]
@shanxiaofan , you still can use old sdk but it will not work with new headset and don't have any support from Emotiv.

**Comment by shanxiaofan** [comment]
Excuse me, but I still want to ask what to do after I download community-sdk to my computer?My computer system is Windows. I saw a TXT file about MacOS system in example_basic. The user needed to copy edk to some path of the computer.
Do you need to configure firmware or something?Since I am a college student in China, we are doing some research in this field. I hope to get your explanation. Thank you very much!

**Comment by shanxiaofan** [comment]
I don't know what to do after downloading the SDK to the computer. My system is Windows, can I directly start to run the code?If you can answer this question, I will be very grateful to you, because I have been troubled for a long time

**Comment by nguoithichkhampha** [comment]
yes, on Windows you can start with C# example, open project build visual studio and run it.

**Comment by shanxiaofan** [comment]
Thank you for your quick answer. I have been troubled by the problem of firmware configuration. Since my senior student is in the Mac system, he needs to put the edk into a folder on the computer

**Comment by shanxiaofan** [comment]
So I have been looking for how to do Windows system, thank you for solving my problem
