### ISSUE TITLE
EEG logger

### ISSUE THREAD

**Issue by KhangTruongBME** [Emotiv/community-sdk#391]
i can run the EEG logger and successfully add User ID, and run case 2 (get Data sample), but the Data Sample count is always 0, how can i fix it ?

**Comment by nguoithichkhampha** [comment]
@KhangTruongBME which version of headset you are using. old sdk does not support new headset version. I recommend you use Cortex API. we will shut down this repo at the end of year.

**Comment by KhangTruongBME** [comment]
It is Insight v1.0 and Epoc+ (but i don't remember the version)

**Comment by hoangphamemotiv** [comment]
@KhangTruongBME can you send me a data file for checking? you can check headset version on EmotivTool: https://github.com/Emotiv/community-sdk/tree/master/tools/EmotivTools
or on a Emotiv app. 
but i recommend you  using Cortex V2 for your work. https://github.com/Emotiv/cortex-v2-example

**Comment by KhangTruongBME** [comment]
I primary use INSIGHT(59684C7F)
and there is a piece of code i tried, problem is on the variables SamplesCount which is always 0.


```
if (dataWriter == null) {
                        return;
                    }
                    edkJava.IEE_DataUpdateHandle(UserID, DataHandlerPtr);// retrieval buffered data

                    edkJava.IEE_DataGetNumberOfSample(DataHandlerPtr, SamplesCountPtr);//how much buffered data is available
                    int SamplesCount = (int) edkJava.uint_p_value(SamplesCountPtr);

                    Log.e("Number of sample: ", String.valueOf(SamplesCount));
                    if (SamplesCount > 0) {
                        IsRecording.setText("Getting EEG Data");
                        data = edkJava.new_double_array(SamplesCount);
                        for (int i = 0; i < SamplesCount; i++) {
                            try {
                                for (IEE_DataChannel_t channel : Channel_list) {
                                    edkJava.IEE_DataGet(DataHandlerPtr, channel, data, SamplesCount);//get data held in spectific sensors
                                    dataWriter.write(String.valueOf(edkJava.double_array_getitem(data, i)) + ",");
                                }
                                dataWriter.newLine();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                        data = null;
                    }
```

**Comment by hoangphamemotiv** [comment]
@KhangTruongBME  SamplesCount  = 0. seem, you haven't activated a license key yet. ^^!.

**Comment by KhangTruongBME** [comment]
i havent done it yet, so, do i need to activate the license first ? and how do i do that ?

**Comment by hoangphamemotiv** [comment]
@KhangTruongBME you can use the tool i sent above, or using the example "Activate license"

**Comment by KhangTruongBME** [comment]
ya, i see it, thanks
