### ISSUE TITLE
EDK Library Multithreading support

### ISSUE THREAD

**Issue by tgraupmann** [Emotiv/community-sdk#50]
When the EDK libraries are used in Unity, if there are any blocking calls, the Editor will crash. And so the EDK calls need to support multithreading to avoid blocking the rendering thread.

Currently invoking the EDK init methods in a thread result in an Abort crash to desktop.

I intend to give the EDK library a dedicated thread.

**Comment by patdotme** [comment]
The EDK calls are non-blocking but not thread-safe at this stage. You may try putting the EDK calls in the same thread as the main event loop or the rendering thread.

**Comment by tgraupmann** [comment]
I used the Emotiv libraries on the main thread and found a way to make it work.

<a href="http://www.youtube.com/watch?feature=player_embedded&v=fhaFbWHtKDY" target="_blank">
<img src="http://img.youtube.com/vi/fhaFbWHtKDY/0.jpg" alt="Emotiv Unity Plugin" width="240" height="180" border="10" /></a>

Making the library thread safe will be a useful feature in the future.
