### ISSUE TITLE
Ubuntu 14.04 & Insight error using Python example...

### ISSUE THREAD

**Issue by jrmedd** [Emotiv/community-sdk#51]
When attempting to use the 'emostate_logger.py' example, I get the following error:

    undefined symbol: IS_PerformanceMetricGetInstantaneousExcitementScore

If I comment out the 'GetInstantaneousExcitement' lines, I get the same errors for 'ExcitementLongTerm' and 'EngagementBoredom'. Commenting out those sections, it eventually it runs, then gives the following error after trying to connect to the EmoEngine:

    Traceback (most recent call last):
      File "emostate_logger.py", line 170, in <module>
        state = libEDK.IEE_EngineGetNextEvent(eEvent)
    NameError: name 'eEvent' is not defined

**Comment by patdotme** [comment]
hi @jrmedd what version of Python are you using?
can you try again with the updated version please?

**Comment by jrmedd** [comment]
Cool, that prevents the code from crashing, although I notice those metrics have been removed. I'm using 2.7.6 FWIW.

I don't seem to be getting any feedback from the headset. Is there a Linux version of the Control Panel so I can  setup the headset with a user? The Composer would be useful for development too!

**Comment by jrmedd** [comment]
Also, I noticed that when I unplugged my BLE dongle or Emotiv Universal receiver, no error is thrown where you would expect it to on line 150:

    if libEDK.IEE_EngineConnect("Emotiv Systems-5") != 0:
        print "Emotiv Engine start up failed."

**Comment by patdotme** [comment]
IEE_EngineConnect should succeed without a headset connected, it is used to initialise the internal state of EmoEngine.
You can check for the following event types:
```
IEE_UserAdded   = 0x0010, //!< A headset is connected.
IEE_UserRemoved = 0x0020, //!< A headset has been disconnected.
```
as mentioned in iedk.h.

Also you can follow the instructions for [Ubuntu BTLE with BlueZ](https://github.com/Emotiv/community-sdk/blob/master/doc/Ubuntu%20BTLE%20with%20BlueZ.md).

**Comment by jrmedd** [comment]
Thanks for the clarifying that about the EmoEngine. 

I'm still unable to tell if the headset is connected. Once the code goes into a loop, the state never changes to 0. Would you be able to include headset connection status in the printed output? The Emotiv receiver LEDs suggest that it's connected, but I'm not convinced!

I'm afraid I get a little lost looking at the source for the libedk binary. Thanks for your support on this.

**Comment by patdotme** [comment]
Would you please try to run the [EmoStateLogger example](https://github.com/Emotiv/community-sdk/tree/master/examples/C%2B%2B/EmoStateLogger) in C++ and let me know if it works for you?

You can use cmake to build the example.

Try to follow these steps:
* build and run the example with a log file name as param, then enter `1` at the prompt to start EmoEngine
* plug in the Emotiv USB dongle
* turn on the Insight and check the LEDs on dongle to see if they are paired
* wear the Insight on your head ;)

You should then see the output "New EmoState from user..." on the screen if the detections are running correctly (Need to keep the Insight on your head in order to make the detection works).

Let me know if that doesn't work for you.

**Comment by jrmedd** [comment]
Unfortunately, after following all of those steps, we're still unable to get any detections from the headset.

We verified that the headset was setup correctly using a Windows machine beforehand. 

Linux & Python are a priority for us, so we'll keep an eye out. Thanks for your assistance so far.

**Comment by patdotme** [comment]
Looks like the dongle related issue should be fixed in commit `99d96bb4474442b9da3afb7f6db8d5ea99848a61`. Just checking if your local branch is most up to date?
Is it, by any chance, a virtual machine?

**Comment by jrmedd** [comment]
Okay, so running as su got some detections, although with no printed feedback. Also, running for 30 seconds only logged 2 seconds in the CSV (using the C++ EmoSateLogger example), with data only in the Frown column and a maxed out Instantaneous Excitement:

[ESTEST.zip](https://github.com/Emotiv/community-sdk/files/53812/ESTEST.zip)

**Comment by patdotme** [comment]
If there are logs in the file that means data are coming through and detections are running. You can check the contact quality via the Insight app (for iOS/Android) and make sure they are all greens which should improve the detection accuracy. You can also use CPanel from https://cpanel.emotivinsight.com for Windows / Mac.

Unfortunately at this time we don't have those apps available for Linux yet.

**Comment by havietnam** [comment]
The examples works well with 0f3ea5a. Please try again and let us know any problem. Thanks.
