### ISSUE TITLE
Ubuntu BTLE not working with example

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#52]
test environment : ubuntu 15.10 64 bit
target : Insight with EEG Model
connection method : Bluetooth directly
applied patch : https://github.com/Emotiv/community-sdk/blob/master/doc/Ubuntu%20BTLE%20with%20BlueZ.md
usb dongle working state : okay
language : c++
git head : 998a1ed123fe50ff083ea65d2811a074af12cb16

i applied 'ubuntu BTLE with Bluez' guide and test bluetoothctl like below.
it looks BTLE itself is working. but if i try any examples,  i can't  get data. anyhow usb dongle looks working with examples.

$ bluetoothctl 
[NEW] Controller 00:19:0E:17:A2:64 my-DeskTop-System-0 [default]
[NEW] Device C6:64:7D:53:E8:BE Insight (59684XXX)
[CHG] Device C6:64:7D:53:E8:BE Connected: yes
[NEW] Service /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0001 Generic Access Profile (Primary)
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0001/char0002 Device Name
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0001/char0004 Appearance
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0001/char0006 Peripheral Preferred Connection Parameters
[NEW] Service /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0008 Generic Attribute Profile (Primary)
[NEW] Service /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009 Vendor specific (Primary)
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Vendor specific
[NEW] Descriptor /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a/desc000c Client Characteristic Configuration
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000d Vendor specific
[NEW] Descriptor /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000d/desc000f Client Characteristic Configuration
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char0010 Vendor specific
[NEW] Service /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0012 Battery Service (Primary)
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0012/char0013 Battery Level
[NEW] Descriptor /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0012/char0013/desc0015 Client Characteristic Configuration
[NEW] Service /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0016 Device Information (Primary)
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0016/char0017 Manufacturer Name String
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0016/char0019 Serial Number String
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0016/char001b Hardware Revision String
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0016/char001d Firmware Revision String
[NEW] Characteristic /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0016/char001f Software Revision String

**Comment by patdotme** [comment]
May I ask which BTLE receiver are you using?
And would you please try to do `[bluetooth]# info C6:64:7D:53:E8:BE` and paste the output here?

**Comment by gouache** [comment]
i use 'Bus 001 Device 004: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0'
and info result is.
[Insight (596842D3)]# info C6:64:7D:53:E8:BE
Device C6:64:7D:53:E8:BE
	Name: Insight (596842D3)
	Alias: Insight (596842D3)
	Appearance: 0x03c0
	Paired: no
	Trusted: no
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID:                           (1800)
	UUID:                           (1801)
	UUID:                           (180a)
	UUID:                           (180f)
	UUID: Vendor specific           (81072f40-9f3d-11e3-a9dc-0002a5d5c51b)

**Comment by patdotme** [comment]
Looks like it is not paired from the output `Paired: no; Trusted: no` but connected is yes somehow?
Would you please try each step from the docs again and paste all the output here for us to check? Thanks.

**Comment by gouache** [comment]
I did it, paired & trusted are changed to yes
but example is still not working.,

[Insight (596842D3)]# pair C6:64:7D:53:E8:BE
Attempting to pair with C6:64:7D:53:E8:BE
[CHG] Device C6:64:7D:53:E8:BE Paired: yes
Pairing successful
[Insight (596842D3)]# trust C6:64:7D:53:E8:BE
[CHG] Device C6:64:7D:53:E8:BE Trusted: yes
Changing C6:64:7D:53:E8:BE trust succeeded
[Insight (596842D3)]# info C6:64:7D:53:E8:BE
Device C6:64:7D:53:E8:BE
	Name: Insight (596842D3)
	Alias: Insight (596842D3)
	Appearance: 0x03c0
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID:                           (1800)
	UUID:                           (1801)
	UUID:                           (180a)
	UUID:                           (180f)
	UUID: Vendor specific           (81072f40-9f3d-11e3-a9dc-0002a5d5c51b)

**Comment by patdotme** [comment]
Okay now try this:
`#select-attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a`
`#notify on`
Then if you can see the continuous printing of notification that means data is coming through the BT.
`#notify off` to stop the printing.

**Comment by gouache** [comment]
so many logs printed, i cut just some lines

[Insight (596842D3)]# select-attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a
[Insight (596842D3):/service0009/char000a]# notify on
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Notifying: yes
Notify started
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x00
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x01
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x7c
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x21
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x88
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0xc4
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x51
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0xe0
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0xe9
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x49
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x26
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x0b
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x21
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x13
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x21
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x7f
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x16
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x2a
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x00
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x00
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x00
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x02
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x92
....

**Comment by patdotme** [comment]
Looks like data is coming through via BTLE - we will check our code. Thanks for reporting.

**Comment by patdotme** [comment]
Please try again with commit f36e9df.

**Comment by gouache** [comment]
I met build break after pulling the git

~/community-sdk/examples/C++/SavingAndLoadingProfileCloud$ make
Scanning dependencies of target SavingAndLoadingProfileCloud
[100%] Building CXX object CMakeFiles/SavingAndLoadingProfileCloud.dir/main.cpp.o
Linking CXX executable SavingAndLoadingProfileCloud
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libedk.so: undefined reference to curl_easy_perform' /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libedk.so: undefined reference tocurl_easy_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libedk.so: undefined reference to curl_easy_cleanup' /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libedk.so: undefined reference tocurl_easy_setopt'
collect2: error: ld returned 1 exit status
CMakeFiles/SavingAndLoadingProfileCloud.dir/build.make:85: recipe for target 'SavingAndLoadingProfileCloud' failed
make[2]: *** [SavingAndLoadingProfileCloud] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/SavingAndLoadingProfileCloud.dir/all' failed
make[1]: *** [CMakeFiles/SavingAndLoadingProfileCloud.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gouache** [comment]
I found fixing build break, but it's not working. no update?

**Comment by gouache** [comment]
update status with 'Update Linux version 3.3.1'
USB dongle works well but BTLE still not works.

anyhow 'select-attribute' and 'notify on' commands looks working.

**Comment by havietnam** [comment]
Fixed with commit 0f3ea5a. Tested with BlueZ 5.37 on Ubuntu 15.10. Please try again. Thanks.

**Comment by gouache** [comment]
I upgraded bluz to 5.37 but same result. maybe there are something I missed..
please check my reproduce log.

check bluez version.
```
$ bluetoothctl --version
5.37
```

test 'notify on' with bluetoothctl
```
select-attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a
[Insight (596842D3):/service0009/char000a]# notify on
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Notifying: yes
Notify started
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x40
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x01
...
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Value: 0x6c
[Insight (596842D3):/service0009/char000a]# notify off
[CHG] Attribute /org/bluez/hci0/dev_C6_64_7D_53_E8_BE/service0009/char000a Notifying: no
Notify stopped
```

but example failed to start.
```
$ ./gyro 
Please make sure your headset is on and don't move your head.
```

**Comment by havietnam** [comment]
There is a bug relate with BTLE, so please try again with  4a7ec56.
P/S: After start gyro app, you should waiting for a while until you see:
"You can move your head now."
then you can move headset.

**Comment by gouache** [comment]
wow! finally it work well!!~

thanks for supporting~
