### ISSUE TITLE
Ubuntu GyroData is not working

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#53]
test environment : ubuntu 15.10 64 bit
Target : Insight with EEG Model
connection method : USB Dongle
language : c++
git head : 998a1ed123fe50ff083ea65d2811a074af12cb16

i tested examples with insight. i found some issues on GryoData example.
connection is okay but there is no gyro data printed.

[console log]
$ ./gyro 
Start after 8 seconds
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0

**Comment by patdotme** [comment]
There is a calibration period at the beginning so keep the headset still for 4 seconds after starting the example and see if would work.

**Comment by gouache** [comment]
I tested over 5 minutes. I cut log for convinient.

**Comment by gouache** [comment]
commit : 374e10434c12f2f984383c1ea92b8e122d2f11a7

I tested it again with latest version. but still not works.
how much time does it need for calibration? do i need to do something for setting?

```
$ ./gyro 
Please make sure your headset is on and don't move your head.
User added

No headset is connected
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
```

**Comment by manhtien2607** [comment]
have you ‎tried putting the headset on the table for about ten seconds. ?                                                                                                                                                                                  ‎                              From: sangho park‎Sent: Friday, January 1, 2016 13:47To: Emotiv/community-sdkReply To: Emotiv/community-sdkSubject: Re: [community-sdk] Ubuntu GyroData is not working (#53)commit : 374e104

I tested it again with latest version. but still not works.
how much time does it need for calibration? do i need to do something for setting?

$ ./gyro 
Please make sure your headset is on and don't move your head.
User added

No headset is connected
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.

**Comment by gouache** [comment]
@manhtien2607, it's same result with before. (on desk and head over 20 secs)
btw 'No headset is connected' is sane message?
anyhow i can find working log from HeadsetInformationLogger.

**Comment by gouache** [comment]
update status with 'Update Linux version 3.3.1'

gyro example looks fine with USB dongle.
although BTLE not works, this bug can be closed.

```
$ ./gyro 
Please make sure your headset is on and don't move your head.
User added

No headset is connected
Gyro is not calibrated. Please stay still.
Gyro is not calibrated. Please stay still.

You can move your head now.
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 0
xmax : 0 ; ymax : 2
xmax : 0 ; ymax : 2
xmax : 565 ; ymax : -138
xmax : 333 ; ymax : -82
xmax : 400 ; ymax : 156
xmax : 407 ; ymax : 315
xmax : 407 ; ymax : 309

```

**Comment by JaviHer93** [comment]
Hi, I working with Raspberry Pi 3, it's armhf lib libedk.so.3.3.3 but it's not working the Gyro Data, also I've a Mac, so I tested under macOS the same code and it works, but when I tried to emigrate to the Raspberry it doesn't work, just display:

Gyro is not calibrated. Please stay still.

Any suggestions? Btw, I did all the modification necessary (Libraries used in Linux, etc.)
