### ISSUE TITLE
Ubuntu trouble with EmoStateLogger (some data value is always '0')

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#54]
test environment : ubuntu 15.10 64 bit
target : Insight with EEG Model
connection method : USB Dongle
language : c++
git head : 998a1ed123fe50ff083ea65d2811a074af12cb16

if i execute EmoStateLogger, 'Time,UserID,Wireless Signal Status' looks okay
but Facial Expression values are always 0 and mental command is action is '1'

0,0,2,0,0,0,0,0,0,0,1,0
0.0312769,0,2,0,0,0,0,0,0,0,1,0 user 0 ...
0.531707,0,2,0,0,0,0,0.054799,0,0,1,00 ...
0.672453,0,2,0,0,0,0,0.0541588,0,0,1,0 ...
0.758464,0,2,0,0,0,0,0.053858,0,0,1,00 ...
0.89921,0,2,0,0,0,0,0.0546999,0,0,1,00 ...
1.09469,0,2,0,0,0,0,0.0538765,0,0,1,00 ...
1.1807,0,2,0,0,0,0,0.0621263,0,0,1,0 0 ...
1.32145,0,2,0,0,0,0,0.0672887,0,0,1,00 ...
1.47001,0,2,0,0,0,0,0.0677864,0,0,1,00 ...
1.5873,0,2,0,0,0,0,0.0746682,0,0,1,0 0 ...
1.72805,0,2,0,0,0,0,0.0705324,0,0,1,00 ...
1.87661,0,2,0,0,0,0,0.0575983,0,0,1,00 ...
1.96262,0,2,0,0,0,0,0.0542191,0,0,1,00 ...
2.10337,0,2,0,0,0,0,0.0563959,0,0,1,00 ...
2.21284,0,2,0,0,0,0,0.0597787,0,0,1,00 ...
2.35359,0,2,0,0,0,0,0.0729596,0,0,1,00 ...
2.46305,0,2,0,0,0,0,0.0838853,0,0,1,00 ...
2.61944,0,2,0,0,0,0,0.0795245,0,0,1,00 ...
2.77582,0,2,0,0,0,0,0.0741432,0,0,1,00 ...
2.89311,0,2,0,0,0,0,0.0714714,0,0,1,00 ...
3.01822,0,2,0,0,0,0,0.0638471,0,0,1,00 ...
3.18242,0,2,0,0,0,0,0.0647277,0,0,1,00 ...
3.30753,0,2,0,0,0,0,0.0646014,0,0,1,00 ...
3.43264,0,2,0,0,0,0,0.0591409,0,0,1,00 ...
3.5812,0,2,0,0,0,0,0.0560693,0,0,1,0 0 ...
3.74541,0,2,0,0,0,0,0.0617135,0,0,1,00 ...
3.87051,0,2,0,0,0,0,0.0545445,0,0,1,00 ...
4.01908,0,2,0,0,0,0,0.0549232,0,0,1,00 ...
4.12073,0,2,0,0,0,0,0.0616914,0,0,1,00 ...
4.24584,0,2,0,0,0,0,0.0559444,0,0,1,00 ...
4.37094,0,2,0,0,0,0,0.0707749,0,0,1,00 ...
4.52733,0,2,0,0,0,0,0.0821901,0,0,1,00 ...
4.69935,0,2,0,0,0,0,0.0792065,0,0,1,00 ...
4.82446,0,2,0,0,0,0,0.0866556,0,0,1,00 ...
4.94957,0,2,0,0,0,0,0.0739294,0,0,1,00 ...
5.08249,0,2,0,0,0,0,0.0665007,0,0,1,00 ...

**Comment by patdotme** [comment]
For Facial Expression it will output the corresponding expression state when they are being detected.
For Mental Commands the subject will need to train each action once (Neutral and Push, for example) in order to give results. You can have a look of the [Mental Commands demo](../tree/master/examples/C%2B%2B/MentalCommandDemo).

**Comment by gouache** [comment]
thanks~ i'll check it and try it again.
