### ISSUE TITLE
Ubuntu Prefix of EmoState functions

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#56]
test environment : ubuntu 15.10 64 bit
target : Insight with EEG Model
connection method : USB Dongle
language : c++
git head : 998a1ed123fe50ff083ea65d2811a074af12cb16

in the SDK docs main page(https://emotiv.com/api/3.3.0/),
"EmoState data is retrieved by Emotiv API functions that are prefixed with IES_."
but i can't find any IES_ prefix but IS_ in the IEmostateDLL.h.

what is right prefix of EmoState?

**Comment by patdotme** [comment]
Sorry that's a typo in the doc - should be IS_*.

**Comment by gouache** [comment]
thanks i got it.

**Comment by gouache** [comment]
oops. sorry i'll keep until fixed the typo.

**Comment by patdotme** [comment]
it is fixed :D
