### ISSUE TITLE
Ubuntu build break (example/C++/AverageBandPowers)

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#57]
test environment : ubuntu 15.10 64 bit
target : Insight with EEG Model
connection method : USB Dongle
language : c++
git head : 0a03e18986b41d437e449a55b95a55142d293116

after adding CMakeList.txt for AverageBandPowers, below error occurred

[compile log]
~/work/community-sdk/examples/C++/AverageBandPowers$ make
[100%] Building CXX object CMakeFiles/AverageBandPowers.dir/main.cpp.o
/home/gouache/work/community-sdk/examples/C++/AverageBandPowers/main.cpp:29:11: error: ‘::main’ must return ‘int’
 void  main() {
           ^
/home/gouache/work/community-sdk/examples/C++/AverageBandPowers/main.cpp: In function ‘int main()’:
/home/gouache/work/community-sdk/examples/C++/AverageBandPowers/main.cpp:42:46: error: no matching function for call to ‘std::basic_ofstream<char>::basic_ofstream(std::__cxx11::string&, const openmode&)’
  std::ofstream ofs(ouputFile, std::ios::trunc);
                                              ^
In file included from /home/gouache/work/community-sdk/examples/C++/AverageBandPowers/main.cpp:12:0:
/usr/include/c++/5/fstream:697:7: note: candidate: std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ofstream(const char* __s,
       ^
/usr/include/c++/5/fstream:697:7: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const char*’
In file included from /home/gouache/work/community-sdk/examples/C++/AverageBandPowers/main.cpp:12:0:
/usr/include/c++/5/fstream:682:7: note: candidate: std::basic_ofstream<_CharT, _Traits>::basic_ofstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ofstream(): __ostream_type(), _M_filebuf()
       ^
/usr/include/c++/5/fstream:682:7: note:   candidate expects 0 arguments, 2 provided
In file included from /home/gouache/work/community-sdk/examples/C++/AverageBandPowers/main.cpp:12:0:
/usr/include/c++/5/fstream:656:11: note: candidate: std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/5/fstream:656:11: note:   candidate expects 1 argument, 2 provided
/home/gouache/work/community-sdk/examples/C++/AverageBandPowers/main.cpp:58:17: error: ‘_kbhit’ was not declared in this scope
  while (!_kbhit())
                 ^
CMakeFiles/AverageBandPowers.dir/build.make:54: recipe for target 'CMakeFiles/AverageBandPowers.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/AverageBandPowers.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/AverageBandPowers.dir/all' failed
make[1]: *** [CMakeFiles/AverageBandPowers.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by patdotme** [comment]
Please try again with commit f62b39e.

**Comment by gouache** [comment]
fixed.
