### ISSUE TITLE
Ubuntu build break (example/C++/SavingAndLoadingProfileCloud)

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#58]
test environment : ubuntu 15.10 64 bit
target : Insight with EEG Model
connection method : USB Dongle
language : c++
git head : 0a03e18986b41d437e449a55b95a55142d293116

after adding CMakeList.txt for SavingAndLoadingProfileCloud, below error occurred

[compile log]
~/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud$ make
[100%] Building CXX object CMakeFiles/SavingAndLoadingProfileCloud.dir/main.cpp.o
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:25:11: error: ‘::main’ must return ‘int’
 void  main() {
           ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp: In function ‘int main()’:
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:59:29: error: ‘atoi’ was not declared in this scope
  option = atoi(input.c_str());
                             ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:64:3: error: return-statement with no value, in function returning ‘int’ [-fpermissive]
   return;
   ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:71:10: error: ‘_getch’ was not declared in this scope
   _getch();
          ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:72:3: error: return-statement with no value, in function returning ‘int’ [-fpermissive]
   return;
   ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:76:3: error: return-statement with no value, in function returning ‘int’ [-fpermissive]
   return;
   ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:78:17: error: ‘_kbhit’ was not declared in this scope
  while (!_kbhit())
                 ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:109:7: error: ‘profileFileType’ is not a class or namespace
       profileFileType::TRAINING))
       ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:115:13: error: ‘_getch’ was not declared in this scope
      _getch();
             ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:116:6: error: return-statement with no value, in function returning ‘int’ [-fpermissive]
      return;
      ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:124:13: error: ‘_getch’ was not declared in this scope
      _getch();
             ^
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:125:6: error: return-statement with no value, in function returning ‘int’ [-fpermissive]
      return;
      ^
CMakeFiles/SavingAndLoadingProfileCloud.dir/build.make:54: recipe for target 'CMakeFiles/SavingAndLoadingProfileCloud.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/SavingAndLoadingProfileCloud.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/SavingAndLoadingProfileCloud.dir/all' failed
make[1]: *** [CMakeFiles/SavingAndLoadingProfileCloud.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by patdotme** [comment]
Please try again with commit f62b39e.

**Comment by gouache** [comment]
fixed
