### ISSUE TITLE
Ubuntu battery level is not reliable

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#59]
test environment : ubuntu 15.10 64 bit
Target : Insight with EEG Model
connection method : USB Dongle
language : c++
git head : f62b39eca2f4eeb52344c9be1c3bc374e9917409

after I fully charged the battery, i can get battery level like below.
test example is HeadsetInformationLogger.

2 -> -1 -> -1 -> -1 -> -1 -> -1 -> -1 -> 4 -> -1 -> 0 -> -1 -> 4 -> -1 ->-> -1 -> ....

I checked maxChargeLevel is '5' with IS_GetBatteryChargeLevel().

[log]
Time, Wireless Strength, Battery Level, AF3, T7, Pz, T8, AF4
0,2,-1,0, 0, 0, 0, 0, 
0.0390961,2,4,4, 4, 4, 4, 4, 
0.516069,2,-1,4, 0, 0, 4, 0, 
0.648995,2,-1,4, 0, 0, 4, 0, 
0.781922,2,-1,4, 0, 0, 4, 0, 
0.90703,2,-1,4, 0, 0, 4, 0, 
1.00086,2,-1,4, 4, 0, 4, 4, 
1.12597,2,-1,4, 4, 0, 4, 4, 
1.25889,2,4,4, 4, 0, 4, 4, 
1.39182,2,-1,4, 4, 0, 4, 4, 
1.56384,2,0,4, 4, 4, 4, 4, 
1.69677,2,4,4, 4, 4, 4, 4, 
1.8297,2,-1,4, 4, 4, 4, 4, 
1.9548,2,-1,4, 4, 4, 4, 4, 
2.04864,2,-1,4, 4, 4, 4, 4, 
2.18156,2,-1,4, 4, 4, 4, 4, 
2.31449,2,2,4, 4, 4, 4, 4, 
2.44742,2,-1,4, 4, 4, 4, 4, 
2.5647,2,-1,4, 4, 4, 4, 4, 
2.69763,2,-1,4, 4, 4, 4, 4, 
2.83056,2,-1,4, 4, 4, 4, 4, 
2.92439,2,4,4, 4, 4, 4, 4, 
3.14333,2,-1,4, 4, 4, 4, 4, 
3.27625,2,-1,4, 4, 4, 4, 4, 
3.45609,2,-1,4, 4, 4, 4, 4, 
3.58902,2,-1,4, 4, 4, 4, 4, 
3.72195,2,-1,4, 4, 4, 4, 4, 
3.85488,2,-1,4, 4, 4, 4, 4, 
3.94089,2,4,4, 4, 4, 4, 4, 
4.09727,2,-1,4, 4, 4, 4, 4, 
4.2302,2,-1,4, 4, 4, 4, 4, 
4.31621,2,-1,4, 4, 4, 4, 4, 
4.44132,2,-1,4, 4, 4, 4, 4, 
4.57424,2,4,4, 4, 4, 4, 4, 
4.70717,2,4,4, 4, 4, 4, 4, 
4.87919,2,-1,4, 4, 4, 4, 4, 
5.01212,2,-1,4, 4, 4, 4, 4, 
5.13723,2,-1,4, 4, 4, 4, 4, 
5.27015,2,3,4, 4, 4, 4, 4, 
5.36398,2,-1,4, 4, 4, 4, 4, 
5.49691,2,1,4, 4, 4, 4, 4, 
5.62202,2,-1,4, 4, 4, 4, 4, 
5.75495,2,-1,4, 4, 4, 4, 4, 
5.88787,2,0,4, 4, 4, 4, 4, 
6.01298,2,-1,4, 4, 4, 4, 4, 
6.10681,2,-1,4, 4, 4, 4, 4, 
6.23192,2,-1,4, 4, 4, 4, 4, 
6.36484,2,3,4, 4, 4, 4, 4, 
6.48995,2,-1,4, 4, 4, 4, 4, 
6.62288,2,3,4, 4, 4, 4, 4, 
6.85746,2,-1,4, 4, 4, 4, 4, 
7.0373,2,-1,4, 4, 4, 4, 4, 
7.13113,2,4,4, 4, 4, 4, 4, 
7.25624,2,0,4, 4, 4, 4, 4, 
7.38916,2,4,4, 4, 4, 4, 4, 
7.56119,2,-1,4, 4, 4, 4, 4, 
7.68629,2,-1,4, 4, 4, 4, 4, 
7.81922,2,2,4, 4, 4, 4, 4, 
7.99124,2,-1,4, 4, 4, 4, 4, 
8.12417,2,-1,4, 4, 4, 4, 4, 
8.24928,2,-1,4, 4, 4, 4, 4, 
8.33529,2,-1,4, 4, 4, 4, 4, 
8.4604,2,-1,4, 4, 4, 4, 4, 
8.59332,2,-1,4, 4, 4, 4, 4, 
8.72625,2,-1,4, 4, 4, 4, 4, 
8.85136,2,-1,4, 4, 4, 4, 4, 
8.98428,2,-1,4, 4, 4, 4, 4, 
9.10939,2,-1,4, 4, 4, 4, 4, 
9.24232,2,4,4, 4, 4, 4, 4, 
9.37524,2,4,4, 4, 4, 4, 4, 
9.46126,2,4,4, 4, 4, 4, 4, 
9.62546,2,-1,4, 4, 4, 4, 4, 
9.75839,2,-1,4, 4, 4, 4, 4, 
9.88349,2,-1,4, 4, 4, 4, 4, 
10.0086,2,-1,4, 4, 4, 4, 4,
...

**Comment by patdotme** [comment]
In that case you may need to unplug the dongle and start over again. How often does it happen?

**Comment by gouache** [comment]
I got same results at every time :(

**Comment by gouache** [comment]
update status with 'Update Linux version 3.3.1'

it looks working well.
