### ISSUE TITLE
Ubuntu always 'certificate verify failed' with SavingAndLoadingProfileCloud example

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#60]
test environment : ubuntu 15.10 64 bit
Target : Insight with EEG Model
connection method : USB Dongle
language : c++
git head : f62b39eca2f4eeb52344c9be1c3bc374e9917409

I changed the userName and password to mine.
EC_Connect() was okay, but EC_Login met exception handshake.

$ ./SavingAndLoadingProfileCloud 
===================================================================
Example to saving and loading profile from Emotiv Cloud 
===================================================================
Press '1' to saving profile to Emotiv Cloud 
Press '2' to loading profile from Emotiv Cloud 
>> 1
Exception:   handshake: certificate verify failed
Your login attempt has failed. The username or password may be incorrect

**Comment by havietnam** [comment]
I missed add default location of certificate files. You can work around by copy `/usr/share/ca-certificates/*` to `/usr/local/share/ca-certificates/`.
Will fix soon.

**Comment by gouache** [comment]
the work around is working for me, i'll wait the fix in git. thanks.

**Comment by patdotme** [comment]
Please try again with commit f36e9df, thanks!

**Comment by gouache** [comment]
I met build break after pulling the git

~/community-sdk/examples/C++/SavingAndLoadingProfileCloud$ make
Scanning dependencies of target SavingAndLoadingProfileCloud
[100%] Building CXX object CMakeFiles/SavingAndLoadingProfileCloud.dir/main.cpp.o
Linking CXX executable SavingAndLoadingProfileCloud
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libedk.so: undefined reference to `curl_easy_perform'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libedk.so: undefined reference to `curl_easy_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libedk.so: undefined reference to `curl_easy_cleanup'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libedk.so: undefined reference to `curl_easy_setopt'
collect2: error: ld returned 1 exit status
CMakeFiles/SavingAndLoadingProfileCloud.dir/build.make:85: recipe for target 'SavingAndLoadingProfileCloud' failed
make[2]: *** [SavingAndLoadingProfileCloud] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/SavingAndLoadingProfileCloud.dir/all' failed
make[1]: *** [CMakeFiles/SavingAndLoadingProfileCloud.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by havietnam** [comment]
This version links with libcurl. Please try again with commit d4f21d6447374728738d02bb2c353be5c37dc0d0 . Thanks

**Comment by gouache** [comment]
compile is okay, but not working. it looks like blocking.
and all example do not work with this version, even usb dongle neither.

**Comment by gouache** [comment]
please seriously consider rollback to f62b39eca2f4eeb52344c9be1c3bc374e9917409
nothing work at d4f21d6447374728738d02bb2c353be5c37dc0d0
usb dongle and BTLE all not work.

**Comment by gouache** [comment]
update status with 'Update Linux version 3.3.1'

I met build break like below.

```
$ make
[100%] Building CXX object CMakeFiles/SavingAndLoadingProfileCloud.dir/main.cpp.o
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp: In function ‘int main()’:
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:118:93: error: too many arguments to function ‘bool EC_UpdateUserProfile(int, int, int)’
           if (EC_UpdateUserProfile(userCloudID, engineUserID, profileID, profileName.c_str())) {
                                                                                             ^
In file included from /home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/main.cpp:34:0:
/home/gouache/work/community-sdk/examples/C++/SavingAndLoadingProfileCloud/../../../include/EmotivCloudClient.h:170:9: note: declared here
         EC_UpdateUserProfile(int userCloudID, int engineUserID, int profileId);
         ^
CMakeFiles/SavingAndLoadingProfileCloud.dir/build.make:54: recipe for target 'CMakeFiles/SavingAndLoadingProfileCloud.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/SavingAndLoadingProfileCloud.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/SavingAndLoadingProfileCloud.dir/all' failed
make[1]: *** [CMakeFiles/SavingAndLoadingProfileCloud.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by havietnam** [comment]
I just update C/C++ examples. Please try again. Thanks.
