### ISSUE TITLE
Build errors - C++ Examples

### ISSUE THREAD

**Issue by jrmedd** [Emotiv/community-sdk#62]
Following the advice of @patdotme, I'm continuing to test our Insight with the C++ EmoStateLogger examples. In the latest commit, I'm now getting build errors:

    Scanning dependencies of target eslogger
    [100%] Building CXX object CMakeFiles/eslogger.dir/main.cpp.o
    Linking CXX executable eslogger
    /usr/bin/ld: cannot find -ledk
    /usr/bin/ld: cannot find -lcurl
    collect2: error: ld returned 1 exit status
    make[2]: *** [eslogger] Error 1
    make[1]: *** [CMakeFiles/eslogger.dir/all] Error 2
    make: *** [all] Error 2

**Comment by havietnam** [comment]
You should do as:
#mkdir EmoStateLogger/build
#cd EmoStateLogger/build
#cmake ../
#make
Please try with commit 4a60cc3f34c0c548b2c6b851a2ba3e049729d00a.
Thanks
