### ISSUE TITLE
Ubuntu - libcurl link error?

### ISSUE THREAD

**Issue by jrmedd** [Emotiv/community-sdk#63]
This error is thrown by emostatelogger.py:

    Error: cannot load EDK lib: /home/me/emotiv/community-sdk/examples/Python/../../bin/linux64/libedk.so: undefined symbol: curl_easy_perform

**Comment by havietnam** [comment]
Please try again with commit 4a60cc3f34c0c548b2c6b851a2ba3e049729d00a.
Thanks.
