### ISSUE TITLE
C# example different bit versions

### ISSUE THREAD

**Issue by codingyourlife** [Emotiv/community-sdk#65]
I thought the examples only work with the premium sdk (that support doesn't want to give me). Took me quite a while to find out how to get the C# projects working.
It took me quite long because of this misleading BadImageFormatException to find out what the problem was. I made a video ( see here https://youtu.be/F-z4gt5Rdk8 ). Maybe you could change this and push it on git?

**Comment by hoangphamemotiv** [comment]
Thanks Codingyourlife . I updated new 64b edk and implement some new C# examples. so, you can get them for your working. thanks.
