### ISSUE TITLE
Error in C# example C++ assert error in edk.dll when connecting device

### ISSUE THREAD

**Issue by codingyourlife** [Emotiv/community-sdk#66]
I have the win64 edk.dll in my project and finally got the project running but with the insight connected I get a strange C++ asssert error. See here: http://blog.codingyourlife.at/wp-content/uploads/C.png

I installed the Build Tools 2015 from here: https://www.microsoft.com/en-us/download/details.aspx?id=48159

And I installed "Common Tools for Visual Studio C++" plus "Microsoft Foundation Classes for C++" in VS2015 setup.

My current project state is well video documented here https://youtu.be/F-z4gt5Rdk8

**Comment by hoangphamemotiv** [comment]
I fixed this issue on newest commit. so you can get the win64 edk.dll for you working. 
Thanks  Codingyourlife .
