### ISSUE TITLE
IOS Example Not Building

### ISSUE THREAD

**Issue by hakim-ali** [Emotiv/community-sdk#67]
Hi,

I am facing this issue on compiling IOS Example.

ld: warning: ignoring file ../../../../lib/iOS/edk_ios.framework/edk_ios, missing required architecture x86_64 in file ../../../../lib/iOS/edk_ios.framework/edk_ios (3 slices)

Undefined symbols for architecture x86_64:
  "_IEE_ConnectInsightDevice", referenced from:
      -[MainViewController getInsightResult] in MainViewController.o
  "_IEE_EmoEngineEventCreate", referenced from:
      -[MainViewController viewDidLoad] in MainViewController.o
  "_IEE_EmoEngineEventGetType", referenced from:
      -[MainViewController getInsightResult] in MainViewController.o
  "_IEE_EmoInitDevice", referenced from:
      -[MainViewController ConnectWithBLE:] in MainViewController.o
  "_IEE_EmoStateCreate", referenced from:
      -[MainViewController viewDidLoad] in MainViewController.o
  "_IEE_EngineConnect", referenced from:
      -[MainViewController ConnectWithBLE:] in MainViewController.o
  "_IEE_EngineGetNextEvent", referenced from:
      -[MainViewController getInsightResult] in MainViewController.o
  "_IEE_GetInsightDeviceCount", referenced from:
      -[MainViewController getInsightResult] in MainViewController.o
  "_IEE_MotionDataCreate", referenced from:
      -[MainViewController StartProgram] in MainViewController.o
  "_IEE_MotionDataGet", referenced from:
      -[MainViewController getInsightResult] in MainViewController.o
  "_IEE_MotionDataGetNumberOfSample", referenced from:
      -[MainViewController getInsightResult] in MainViewController.o
  "_IEE_MotionDataSetBufferSizeInSec", referenced from:
      -[MainViewController StartProgram] in MainViewController.o
  "_IEE_MotionDataUpdateHandle", referenced from:
      -[MainViewController getInsightResult] in MainViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Regards,
Hakim

**Comment by tuEmotiv** [comment]
Emotiv headset connect with iOS device through BLE v4.0, so this framework only support for ARM architecture(armv7, armv7s, arm64), don't support simulator, please build with real device

**Comment by hakim-ali** [comment]
Thank you. Its working.
