### ISSUE TITLE
Memory Leakage

### ISSUE THREAD

**Issue by hakim-ali** [Emotiv/community-sdk#68]
I am building one application which is used the train the device and also testing with device in one application.

So i merge the code of "Mental Commands" and "Facial Expressions" ViewController in our application but i am facing the memory leakage in your library, even i can't navigate two time on one viewcontroller. 

So i am getting this exception.

error: memory read failed for 0x0
exc_bad_access code=1 address=0x0

And also i am getting this exception on including "EmotionalStates"
2015-12-30 10:40:22.462 SmartMind[5735:1465667] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString sizeWithTextStyle:]: unrecognized selector sent to instance 0xa000000000000301'

**Comment by nguoithichkhampha** [comment]
Did you use iOS SDK or Mac SDK ?

**Comment by hakim-ali** [comment]
i am using iOS SDK.

**Comment by tuEmotiv** [comment]
Did you add flag -ObjC in your project settings ? If you use EmotionalStates example, please add this flag because it use CorePlot framework and that framework must have flag -ObjC in swift project

**Comment by hakim-ali** [comment]
@tuEmotiv  thank you EmotionalStates example is working now but the Memory Leakage is still not resolved.

I can't initialize all ViewControl in one project its give me this error.

error: memory read failed for 0x0
exc_bad_access code=1 address=0x0

**Comment by hakim-ali** [comment]
Hi @tuEmotiv i try alot of things to solve above issue but no success. Can you please help me in this.

**Comment by tuEmotiv** [comment]
Sorry for late response, can you send your code ? Your message error is vague,  and I cant understand and support you

**Comment by hakim-ali** [comment]
I need to share full project or code snippet?

So what i am doing.
1- Merge the your example code into one project.
2- Create Instance.

let navigationController2 = createNavigationController("FE_ViewController") ;
let navigationController4 = createNavigationController("ES_ViewController");
let navigationController5 = createNavigationController("ViewController");

func createNavigationController (controllerName: String) -> UINavigationController{
     let storyboard = UIStoryboard(name: "MainView", bundle: nil)
     let viewController = storyboard.instantiateViewControllerWithIdentifier(controllerName) as! UIViewController
     let navigationController = UINavigationController(rootViewController: viewController);
     return navigationController;
}

If i only create one instance then there is no issue, this memory issue came when i create instance of two viewcontroller.

**Comment by tuEmotiv** [comment]
Did you create 1 EngineWidget with each ViewController ? You should create 1 engineWidget and send event to viewcontroller. Maybe you create many engineWidget and it can make app crash
