### ISSUE TITLE
Mac version of emotivExample needs change to support SDK change

### ISSUE THREAD

**Issue by 212433704** [Emotiv/community-sdk#69]
Looks like the APIs IEE_GetNumberDeviceInsight() & IEE_EmoConnectDevice(0) were depreciated.

In the file EngineWidget.mm, the method getNextEvent should be changed from:

    int couter_insight = IEE_GetNumberDeviceInsight();
    if(couter_insight > 0){
        if(!isConnected){
            IEE_EmoConnectDevice(0);
            isConnected = true;
        }
    }

TO:

    int counter_insight = IEE_GetInsightDeviceCount();
    if(counter_insight > 0){
        if(!isConnected){
            IEE_ConnectInsightDevice(0);
            isConnected=true;
        }
    }

It looks like most of the Mac apps have this issue in addition to other APIs that were changed, but not reflected in the example apps.

**Comment by nguoithichkhampha** [comment]
Thanks you your feedback. We will update code soon.
