### ISSUE TITLE
Headset Information Logger C# Project has Compile Errors

### ISSUE THREAD

**Issue by codingyourlife** [Emotiv/community-sdk#70]
Thanks for processing and closing my last 2 threads. The C# projects HeadsetInformationLogger has a compile error (see screenshot, I didn't modify anything).

![headsetinformationloggererror](https://cloud.githubusercontent.com/assets/10122382/12067174/9c032f04-aff5-11e5-8a7b-549113047296.png)

**Comment by hoangphamemotiv** [comment]
Hi @codingyourlife. it should change to IEE_CHAN_O1.  channel O1 and Channle Pz is same.
