### ISSUE TITLE
C# example projects are set to different bitversions

### ISSUE THREAD

**Issue by codingyourlife** [Emotiv/community-sdk#71]
Maybe this has a smart reason I don't see yet but why don't you set them all to "Any CPU" option or at least all the same CPU version. Some of the projects just throw a BadImageFormatException and people need to realize that the bit versions of the projects don't match.

![anycpu](https://cloud.githubusercontent.com/assets/10122382/12067256/1a7ad84a-aff7-11e5-8469-09e27f1d855f.png)

**Comment by hoangphamemotiv** [comment]
On 64bit mode, all project should config with x64. i will change it. 
Thanks codingyourlife!

**Comment by codingyourlife** [comment]
Yeah I know that but why don't you change it and update it? MotionDataLogger project is still x86 in case you don't know that. It's really hard to find out what the problem is and it's so easy to fix!
