### ISSUE TITLE
Login works Loading Profile fails half way

### ISSUE THREAD

**Issue by codingyourlife** [Emotiv/community-sdk#72]
+Login:
Login works.

+Saving
At my first attempt also saving failed but second attempt went through. Now saving tells me "Profile with MyName is existed." Not very good English but it works.

+Loading
Loading shows some numbers and then tells me "loading failed" -> see screenshot.

![loadingfailed](https://cloud.githubusercontent.com/assets/10122382/12275389/2a395428-b970-11e5-9e12-bb582d5b634f.png)

I think it must be smth with my profile. I would give you details but I think this is kinda sensitive data so contact me via mail in case you need more information.

I use the 64bit C# Example SavingAndLoadingProfileCloud, pressing F2 (pressed F1 before).

**Comment by hoangphamemotiv** [comment]
I fixed this issue in commit "088e9ac"

Thank Codingyourlife.

**Comment by Hermi1988** [comment]
I am getting the same error with the community SDK when integrated into Unreal 4. Is this still not resolved? :(
