### ISSUE TITLE
SavingLoadingFunction of SavingAndLoadingProfileCloud makes no sense

### ISSUE THREAD

**Issue by codingyourlife** [Emotiv/community-sdk#73]
Besides this project/method being overly complicated written (especially considering you should learn from it) it also makes no sense to me that in the end it just returns a boolean. What is the sense of logging in somewhere just to get an "ok it worked" back? What is this whole SavingAndLoadingProfileCloud project good for? You can direct me to a documentation but as far as I know such thing doesn't exist.
![whatsthedeal](https://cloud.githubusercontent.com/assets/10122382/12307687/1c0cbb48-ba41-11e5-89db-5de89e64d99f.png)

In case you add me as contributor I might improve one thing or another without bothering you guys.

**Comment by codingyourlife** [comment]
I don't see this as closed at all. I can clean up the code (see pull request) but if the code doesn't make sense or is not understandable it is you guys making a bad job. I mean I don't even know what you should learn from that example!?

> STILL makes no sense. I mean what is this userCloudID and where do I get it? What is even being saved/loaded and where is it stored (EC_LoadUserProfile now returns an integer for enum instead of boolean, I expect it to return a profile or what have you)
> BTW if version is always -1 why not make it a default value for the parameter?
> Glad I don't really need this example for my project...

**Comment by hoangphamemotiv** [comment]
Hi @codingyourlife
Thank you so much for your feedback. 

    i agree that int version = -1 should be a default parameter.

    cloud userID is number value of your Emotiv ID, we manage Cloud User follow that number, not EmotivID (your account name).

    EC_GetAllProfileName(cloudUserID);
    // Loading information of all profiles from Cloud to buffer and return number of profile in the list.
    and we need call it first before loading and saving a profile.
    i agree that name of this function is a bad name. but, we are using this function in many our project, so, we havent changed it yet. we will plan to fix that name in next version.

Thanks.
