### ISSUE TITLE
How to test after Training Mental Commands

### ISSUE THREAD

**Issue by hakim-ali** [Emotiv/community-sdk#74]
Hi,

how can i test the training data i-e left, right after training using mental commands code. Can you list down the steps.

**Comment by hoangphamemotiv** [comment]
Hi @hakim-ali . 
After you finished training processing. you can use:

    //! Returns the detected MentalCommand action of the user
    /*!
        \param state - EmoStateHandle
        \return MentalCommand action type
        \sa IEE_MentalCommandAction_t, IS_MentalCommandGetCurrentActionPower
    */
    EMOSTATE_DLL_API IEE_MentalCommandAction_t
        IS_MentalCommandGetCurrentAction(EmoStateHandle state);


    //! Returns the detected MentalCommand action power of the user
    /*!
        \param state - EmoStateHandle
        \return MentalCommand action power (0.0 to 1.0)
        \sa IS_MentalCommandGetCurrentAction
    */
    EMOSTATE_DLL_API float
        IS_MentalCommandGetCurrentActionPower(EmoStateHandle state);

to get power and current action of mentalCommand in Emostate Update. 

Thank @hakim-ali

**Comment by hakim-ali** [comment]
IS_MentalCommandGetCurrentActionPower is always returning zero. Please guide me what i am missing.

Can you please let me know why he is returing everytime zero. Due to this we can't after test the training.

**Comment by hakim-ali** [comment]
@hoangphamemotiv  can you help in above question?

**Comment by cwlmyjm** [comment]
I have same problem with it in Java, I try use IS_MentalCommandGetCurrentAction and IS_MentalCommandGetCurrentActionPower to  the command and the power. However, it always return 1 and 0 when I use epoc dongle directly but return both zero when use control panel as emoengine. My code is like following:
if (eventType == Edk.IEE_Event_t.IEE_EmoStateUpdated.ToInt()) {
			Edk.INSTANCE.IEE_EmoEngineEventGetEmoState(eEvent,eState);
			currentCommand = EmoState.INSTANCE
					.IS_MentalCommandGetCurrentAction(eState);
			currentPower = EmoState.INSTANCE
					.IS_MentalCommandGetCurrentActionPower(eState);
			System.out.println(currentCommand+"&"+currentPower);
}
I have update event by using GetNextEvent, but I am still confused with the output, hopefully you can give me some advice. :)

**Comment by eva0564** [comment]
I have the problem with emostatelogger demo in C++.

**Comment by albertorepo** [comment]
Same here with Java and Windows 10.

Have you any solution for this?

**Comment by hoangphamemotiv** [comment]
Hi @everyone, @cwlmyjm , @eva0564 , @albertorepo 

thank for your questions. 
To make Mental command detection work you need to be care something here:
- You need a profile and need training a action first. ex: we training neutral + push. 
  after traning, you need to save it to Cloud with a name. 
- Because Mental command need a profile to work. that why @eva0564  always get 0 on the power. EmostateLogger just a example demo for what / how do we get emostate from emoengine or emokey. 
so, you should look MentalCommandAndProfileCloud to find how to work on the detection. 
i think this issue is same with issue from @cwlmyjm . 

Thank you all. ^^!

**Comment by hoangphamemotiv** [comment]
one more. make sure you are using v3.3.3 or above of edk library. we have a issue in training session in v3.3.2

**Comment by albertorepo** [comment]
Hi @hoangphamemotiv,

First, thank you for your quick response.

I've been looking for he example you metion, but I can't fin it in Java. 

Is there available in Java or Python?

Thank you.

**Comment by hoangphamemotiv** [comment]
Hi @albertorepo . 
Sorry, i dont write it in Java or python yet. But, it is same with other languages. i think you are easy to read and write it.  ^^!

**Comment by albertorepo** [comment]
Hi @hoangphamemotiv 
I'm on it then. :)

Thank you!

**Comment by george-martin** [comment]
@hoangphamemotiv is it necessary to save it to cloud? I'm having trouble uploading both from my code as well as from emotiv control panel. how do I work around this? How do I update the emu file locally instead?
