### ISSUE TITLE
Battery always returns 80%

### ISSUE THREAD

**Issue by 212433704** [Emotiv/community-sdk#75]
This issue is not only in the SDK, but this is the case for the iOS apps on the app store as well as the Xavier Control Panel (Both web and Mac versions) when using the insight device.  From the SDK, the IS_GetBatteryChargeLevel call always returns 4 for chargeLevel and 5 for maxChargeLevel regardless of actual charge level.  The only exception would be when there is a problem with the signal, then it may return a negative number.

**Comment by hoangphamemotiv** [comment]
Hi  212433704 . 
we will fix this issue on next version. 
Thank  212433704 .

**Comment by hoangphamemotiv** [comment]
Hi 212433704!
We released version 3.3.1 Edk libraries. You can update current version for this issues. 

Thank 212433704.

**Comment by KLD0093** [comment]
Does battery level -1 mean anything? I get GOOD_SIG for wireless, but Battery level doesn't seem to change as it only gives -1 (even through in Xevier it's 2 bars worth of battery). 

I'm using the same function as the gentle man used: IS_GetBatteryChargeLevel

C# code with EPOC+
