### ISSUE TITLE
Record Insight EEG with python

### ISSUE THREAD

**Issue by mattjerhart** [Emotiv/community-sdk#76]
I would like to record raw insight EEG with python. I ran the python premium example 'eeg_logger.py', but got the error:
name 'libEDK' is not defined
```python
libEDK = cdll.LoadLibrary("edk.dll")# this is the problem here
```
I added the edk.dll file to the same dir as the .py file but no luck. I am on windows 10. The insight was purchased with EEG ability.

**Comment by manhtien2607** [comment]
Have you tried add dll on to system32 folder or system path

**Comment by mattjerhart** [comment]
Thanks, that fixed the above. Now I have this error:
```python
hData = libEDK.IEE_DataCreate()
```
AttributeError: function 'IEE_DataCreate' not found

Tried the 32 and 64 bit dlls.

**Comment by manhtien2607** [comment]
Where have you got premium SDK?

**Comment by mattjerhart** [comment]
I only have community. There is no premium download in my account (based on the forum, maybe insight users don't have access yet).

**Comment by manhtien2607** [comment]
that explain, community version will not have these APIs, you can test with Premium library for Epoc if you have it on your account

**Comment by matt-erhart** [comment]
As far as I can tell, IEE_DataCreate doesn't exist. IEE_MotionDataCreate might be what's needed.

**Comment by matt-erhart** [comment]
I believe the SDK was restructured/renamed since this example was created.
