### ISSUE TITLE
Get Started Page

### ISSUE THREAD

**Issue by lettergram** [Emotiv/community-sdk#78]
It would be nice if there was a few tutorials on how to get everything setup and working.

**Comment by NTTLuke** [comment]
HI Lettergram 
under doc folder I find how to use SDK headset and PDF documentation.
I found also interesting information for SDK here https://www.youtube.com/watch?v=Qv9I8F0wVfI
Can I help in some way ?

**Comment by codingyourlife** [comment]
This video is really helpful. You should split the Youtube channel in marketing stuff and tutorials for developers and make such videos more present and link to the tutorial channel in the docs etc.
