### ISSUE TITLE
MentalCommandTrainingStartedEventEventHandler

### ISSUE THREAD

**Issue by NTTLuke** [Emotiv/community-sdk#79]
Hi guys
I'm working with MentalCommandTrainingStartedEventEventHandler but I don't undestand how to retrieve informations about training data and above all how to work with them after training.
Is it possibile to have an example or just a suggestion ?

The prb is that after training  when engine_MentalCommandEmoStateUpdated fired, the value of cogAction is always MC_NEUTRAL but I have trained MC_PUSH (with F1 command). 
I'm working on with EmoStateLogger Prj in C# example.

Thanks and congratulation for your great work.

**Comment by hoangphamemotiv** [comment]
Thank NTTLuke. 
we will improve MentalCommand example as soon as posible with Training and how to get MentalCommand detection after training. 
for now, you can use API: 

    //! Returns the detected MentalCommand action of the user
    /*!
        \param state - EmoStateHandle
        \return MentalCommand action type
        \sa IEE_MentalCommandAction_t, IS_MentalCommandGetCurrentActionPower
    */
    EMOSTATE_DLL_API IEE_MentalCommandAction_t
        IS_MentalCommandGetCurrentAction(EmoStateHandle state);


    //! Returns the detected MentalCommand action power of the user
    /*!
        \param state - EmoStateHandle
        \return MentalCommand action power (0.0 to 1.0)
        \sa IS_MentalCommandGetCurrentAction
    */
    EMOSTATE_DLL_API float
        IS_MentalCommandGetCurrentActionPower(EmoStateHandle state);

in C#. MentalCommandGetCurrentAction()
and MentalCommandGetCurrentActionPower()

**Comment by eva0564** [comment]
I have tried the EmoStateLogger program  in C# example, the example  provide a method to train "push"  mental command. If i want to add several mental  commands like "neutral"  and  "pull" , i found only "neutral"  command works .When i train other mental commands  besides "neutral" and "push" , the program  shows there are unknown mistakes. And i meet the same problem in FacialExpression training process. 
I am wondering if the program can only train no more mental commands than "neutral" and "push"?
