### ISSUE TITLE
Ubuntu premium examples

### ISSUE THREAD

**Issue by gerardogtn** [Emotiv/community-sdk#80]
I have access to the premium libraries for Linux. However, even with the premium libraries installed I cannot run the premium examples. The reason is that the library "IEegData.h" was not found. After exploring the project it seems that the premium libraries for linux are stuck on version 2.2, whereas the community sdk is on version 3.3. 

Any ways of getting around this so that I can run the premium examples?

**Comment by hoangphamemotiv** [comment]
Hi gerardogtn.
You need a version 3.3.1 Premium of Edk libraries on Linux to get header files for example Premium. 
We have a some error on building this version. we will push it to website as soon as possible. 

Thank gerardogtn!
