### ISSUE TITLE
python premium eeg logger bug for insight

### ISSUE THREAD

**Issue by matt-erhart** [Emotiv/community-sdk#81]
I am trying to run eeg_logger.py with the insight. testbench etc is working. My problem is that the following line never evaluates to true:

```python
if nSamplesTaken[0] != 0:
```

It would be great if someone could comment the code in that example, as it's fairly difficult to figure out what a C library is doing in python. A barebones script known to work with the insight would be also be great. Any advice welcome.

**Comment by hoangphamemotiv** [comment]
hi mattjerhart. 
 nSamplesTaken value is number of samples Eeg data. so, make sure that your headset is turn on. and you are using premium version headset. 

Thank mattjerhart.
