### ISSUE TITLE
Connect Problem in Android

### ISSUE THREAD

**Issue by ZhengyaoJiang** [Emotiv/community-sdk#82]
There are some problem in the EngineConnector class ,the run method of the timerTask.
When IEdk.IEE_ConnectInsightDevice(0) return true, the USER_ADD event will not be happen immediately and isConnected flag will not be true. Therefore the run() method will still call IEdk.IEE_ConnectInsightDevice(0); which will cause the connect failed.

`if(numberDevice!=0)
				{
					if(!isConnected) {
						IEdk.IEE_ConnectInsightDevice(0);
					}
				}`

I don't know why , maybe there is some problem in the library(i mean C library) ,what i observed is the IEdk.IEE_GetInsightDeviceCount() return 0 and the IEdk.IEE_EngineGetNextEvent() return the error code which meant there are no event.

Use a boolean to record what the IEdk.IEE_ConnectInsightDevice(0) returned could solve the problem. However i think it's not a fundamental solution and some fixed should be done in the library.

`boolean has_successd=false;
			@Override
			public void run() {
				// TODO Auto-generated method stub
				int numberDevice=IEdk.IEE_GetInsightDeviceCount();

				if(numberDevice!=0)
				{
					if(!isConnected&&!has_successd) {
						has_successd=IEdk.IEE_ConnectInsightDevice(0);
					}
				}`

**Comment by nguoithichkhampha** [comment]
Hi ZhengyaoJiang ,
Event USER_ADD only appear when get succes all info of headset. May be android device is connected with headset but can't get info succes, so haven't event USER_ADD.
In your situation which you said. After call IEdk.IEE_ConnectInsightDevice(0) SDK will stop scan and clear list device scanned , therefor  numberDevice = 0 will don't call function 
IEdk.IEE_ConnectInsightDevice(0)

**Comment by ZhengyaoJiang** [comment]
Thanks for your explanation about the Event USER_ADD.

After call IEdk.IEE_ConnectInsightDevice(0), numberDevice will decrease to 0 but not immediately. On my phone, numberDevice = 1 last for about 80 milliseconds and the IEdk.IEE_ConnectInsightDevice(0) was called several times after first call. And that may cause problem what i have said. If use a boolean to keep the IEdk.IEE_ConnectInsightDevice(0) called just once every time, nothing strange will happened.

here is the test code:
`if(numberDevice!=0)
				{
					if(!isConnected) {
						Log.d("connecttest1", "before call numberDvice:" + IEdk.IEE_GetInsightDeviceCount());
						has_successd=IEdk.IEE_ConnectInsightDevice(0);
						Log.d("connecttest1", "after call numberDvice:" + IEdk.IEE_GetInsightDeviceCount()+" if successful: "+has_successd);
					}
				}`

here is the output log:
02-15 13:59:11.429 14049-14147/com.emotiv.mentalcommand D/connecttest1: before call numberDvice:1
02-15 13:59:11.429 14049-14147/com.emotiv.mentalcommand D/connecttest1: after call numberDvice:1 if successful: true
02-15 13:59:11.439 14049-14147/com.emotiv.mentalcommand D/connecttest1: before call numberDvice:1
02-15 13:59:11.439 14049-14147/com.emotiv.mentalcommand D/connecttest1: after call numberDvice:1 if successful: true
02-15 13:59:11.449 14049-14147/com.emotiv.mentalcommand D/connecttest1: before call numberDvice:1
02-15 13:59:11.449 14049-14147/com.emotiv.mentalcommand D/connecttest1: after call numberDvice:1 if successful: true
02-15 13:59:11.459 14049-14147/com.emotiv.mentalcommand D/connecttest1: before call numberDvice:1
02-15 13:59:11.459 14049-14147/com.emotiv.mentalcommand D/connecttest1: after call numberDvice:1 if successful: true
02-15 13:59:11.469 14049-14147/com.emotiv.mentalcommand D/connecttest1: before call numberDvice:1
02-15 13:59:11.469 14049-14147/com.emotiv.mentalcommand D/connecttest1: after call numberDvice:1 if successful: true
02-15 13:59:11.479 14049-14147/com.emotiv.mentalcommand D/connecttest1: before call numberDvice:1
02-15 13:59:11.479 14049-14147/com.emotiv.mentalcommand D/connecttest1: after call numberDvice:1 if successful: true
02-15 13:59:11.489 14049-14147/com.emotiv.mentalcommand D/connecttest1: before call numberDvice:1
02-15 13:59:11.489 14049-14147/com.emotiv.mentalcommand D/connecttest1: after call numberDvice:1 if successful: true
02-15 13:59:11.499 14049-14147/com.emotiv.mentalcommand D/connecttest1: before call numberDvice:1
02-15 13:59:11.509 14049-14147/com.emotiv.mentalcommand D/connecttest1: after call numberDvice:1 if successful: true

**Comment by nguoithichkhampha** [comment]
Thanks your share, We will check this issue again.

**Comment by nguoithichkhampha** [comment]
Hi ZhengyaoJiang , We have updated Android SDK 3.3.1. You can test it and send us your feedback.
Thanks, Cuong !

**Comment by ZhengyaoJiang** [comment]
Hi nguoithichkhampha,
The new Android SDK example worked well on my phone. I'm happy that my finding helped you.

**Comment by bizzareshishir** [comment]
I am getting isEnablGetData always equals false. Please help me out.
