### ISSUE TITLE
tools inside related folder are old version 

### ISSUE THREAD

**Issue by NTTLuke** [Emotiv/community-sdk#83]
Hi 
tools inside the related folder are old version.

**Comment by hoangphamemotiv** [comment]
Hi NTTLuke. 
what tools are old version?

**Comment by NTTLuke** [comment]
I am talking about emotiv composer and others application . I have downloaded from main branch and I installed on my pc but the version is older than my actual composer version. But..... I saw that you have update tools one day ago so I will retry to download and install this version
Thanks guys :)

**Comment by hoangphamemotiv** [comment]
Thank NTTLuke.

**Comment by NTTLuke** [comment]
HI Guys 
sorry for that but I have attached the difference between my installed Composer tool and the last Composer tool released inside tools folder

here the screenshot of mine
http://b3.ms/vzV9pyPWAwRa

here the screenshot of  Composer inside tools folder
http://b3.ms/Y2g9K4VBA0l3

As you can see my version has also PErfromance metrics command that the last release doesn't have

I'm missing something? ;)
Thx guy !!!!
