### ISSUE TITLE
Ubuntu FacialExpression can't train 'blink, wink_left, wink_right'

### ISSUE THREAD

**Issue by gouache** [Emotiv/community-sdk#86]
test environment : ubuntu 15.10 64 bit
Target : Insight with EEG Model
connection method : USB Dongle
language : c++
sdk version : 3.1.1
git head : b45b73238e3b1bc907f24a4ac5bad8c70f68a5cd

if i try 'help' in FacialExpressionDemo, i can get training_exp expressions as below,
[expressions: "neutral","smile","clench","surprise","frown"]

this is full help log.
```
FacialExpressionDemo> help
==> Available commands:
trained_sig [userID] 			 query if the user has trained sufficient actions to activate a trained signature
set_sig [userID] [signatureType]	 configure to use the built-in universal signature or a personal, trained signature
					 [signatureType: 0 for universal or 1 for trained signature]
training_exp [userID] [expression] 	 set FacialExpression training expression
					 [expressions: "neutral","smile","clench","surprise","frown"]
training_start [userID] 		 start FacialExpression training
training_accept [userID] 		 accept FacialExpression training
training_reject [userID] 		 reject FacialExpression training
training_erase [userID] 		 erase FacialExpression training data for the current expression
exit 					 exit this program
```

those expressions ("neutral","smile","clench","surprise","frown") are okay to be set.
but if i try 'blink', 'wink_left', 'wink_right', IEE_FacialExpressionSetTrainingAction return error.

here is some log for that.
```
FacialExpressionDemo> training_exp 0 blink
==> Setting FacialExpression training expression for user 0 to blink...Wrong argument(s) for command [training_exp]
```

**Comment by patdotme** [comment]
The help is correct: training is for [expressions: "neutral","smile","clench","surprise","frown"] only, so not really a bug.
