### ISSUE TITLE
MetalCommand get always return 1 with power 0.0

### ISSUE THREAD

**Issue by cwlmyjm** [Emotiv/community-sdk#87]
I have same problem with it in Java, I try use IS_MentalCommandGetCurrentAction and IS_MentalCommandGetCurrentActionPower to the command and the power. However, it always return 1 and 0 when I use epoc dongle directly but return both zero when use control panel as emoengine. My code is like following:
if (eventType == Edk.IEE_Event_t.IEE_EmoStateUpdated.ToInt()) {
Edk.INSTANCE.IEE_EmoEngineEventGetEmoState(eEvent,eState);
currentCommand = EmoState.INSTANCE
.IS_MentalCommandGetCurrentAction(eState);
currentPower = EmoState.INSTANCE
.IS_MentalCommandGetCurrentActionPower(eState);
System.out.println(currentCommand+"&"+currentPower);
}
I have update event by using GetNextEvent, but I am still confused with the output, hopefully you can give me some advice. :)

**Comment by hoangphamemotiv** [comment]
Hi Cwlmyjm

Did you have a training some detection of MentalCommand?

**Comment by cwlmyjm** [comment]
Yes, I first use IEE_MentalCommandSetActiveActions to enable the command and then use IEE_MentalCommandSetTrainingAction to set the action I want to train, I put push here and then call IEE_MentalCommandSetTrainingControl to start the trainning. Then I use another loop to listen the event, when command event said command train succeeded then I call IEE_MentalCommandSetTrainingControl to accepted it. 

Else, I found that in the provided java example, there has a function called EnableMentalCommandActionsList, it seems to tell the emoEngineer which commands are active, but it start from i=1, so the command Natural has not been included. In this case, I test command without trainning Natural with the control panel from emotive webpage, and it also does not work. So, I consider that may result from that Natural is not enabled, so I change it to i=0 to include the Natural, but it still not work. Thanks for your reply:)

**Comment by hoangphamemotiv** [comment]
i think you should training NEUTRAL first then other detection. Use IEE_MentalCommandTrainingStarted to start a traning. and check IEE_MentalCommandTrainingSucceeded when it is succeeded. 

if it still dont work for you. can you show me your code? maybe i can help.

**Comment by cwlmyjm** [comment]
Yeah, I have trained the command Neutral. The attached file is my code, thank you:)
[EmotivDeviceThread.txt](https://github.com/Emotiv/community-sdk/files/158026/EmotivDeviceThread.txt)

**Comment by eva0564** [comment]
Hello, I have the same problem with it  in C++, i try use EmoStateLogger to detect MentalCommandAction and  MentalCommandActionPower. But, when i use the emotiv Epoc, the data of MC_Action and MC_ActionPower is always 1 and 0,which means the mental command is always netural. Also, i use the function  "IS_MentalCommandIsActive(eState)". The result is 1 which means "active". However,when i use EmotivComposer, the demo can record MC_Action and MC_ActionPower correctly . 
          At the same time ,i try MentalCommandDemo.I have serveral questions: 
 1.Is it necessary to train mental command before control EmoCube? When i connect MentalCommandDemo with EmoCube ,i see nothing on  EmoCube . At the same time, i can control cube on control panel.
2.After training several mental commands ,how can i use it or find it?
I am doing a application that control unmanned plane by mind, firstly i need get mind detection result  by Emotiv headset .Now ,i have no idea about this problem and i have research many papers ,most of them use emokey or control panel as bridge to convey "minds" to external appliciation. I am wondering if it is possible to convey "minds" just by emotiv SDK.
I really need your help ,thanks a lot.

**Comment by eva0564** [comment]
Do you solve the problem? I have used the solution mentioned above ,but have no effects.

**Comment by cwlmyjm** [comment]
Still not, I do not know what lead the problem.

**Comment by hoangphamemotiv** [comment]
Sorry eva0564 and cwlmyjm for late. 

We are checking this issus. i will feedback you as soon as possible.

**Comment by Think0rSwim** [comment]
I have the same problem for C++ on the Insight, even with just the sample code. 
I always get 1 for IS_MentalCommandGetCurrentAction and 0 for IS_MentalCommandGetCurrentActionPower even after training. 

My process is this:
1) set_actions 0 push 
2) training_action 0 neutral  
3)training_start 0 
4)training_accept 0 
5)training_action 0 push 
6)training_start 0 
7)training_accept 0 

(I tried set_actions 0 push again for a step 8, but that doesn't fix it)

This is with the sample MentalCommandDemo code for Windows C++. 

Am I missing something?

**Comment by hoangphamemotiv** [comment]
This issue is only on version 3.3.1 edk libs. we have errors on developing new features. we will have a version fix soon.

**Comment by Think0rSwim** [comment]
Update/FYI: 
When I looked more into this, it appears that the training is not done properly. 
The skill rating is always 0 no matter how many times I tried to train. (My ControlPanel profile has a push skill rating of 50). 

This is likely the reason why detected command is always neutral.

**Comment by Think0rSwim** [comment]
@hoangphamemotiv  Could you please direct me to a version that works? I only need one version that works on Windows with C++.

**Comment by Think0rSwim** [comment]
@hoangphamemotiv  I found one. I downloaded a version all the way from October 21st 2015. The SDK in that master worked.  But I am ever more confused. Even though it works in that version. I get 0 skill rating for both Overall Skill Rating and Push skill rating.....

**Comment by hoangphamemotiv** [comment]
Hi Think0rSwim.
Version 3.3.0 works fine on Training issue. we are focusing to fix it.

**Comment by hoangphamemotiv** [comment]
Hi everyone. 

i updated Edk libraries v3.3.2 with fixing on training processing MentalCommand. pls update that version for your work. 

Thanks.

**Comment by eva0564** [comment]
I have tried the EmoStateLogger program in C# example, the example provide a method to train "push" mental command. If i want to add several mental commands like "neutral" and "pull" , i found only "neutral" command works .When i train other mental commands besides "neutral" and "push" , the program shows there are unknown mistakes. And i meet the same problem in FacialExpression training process. 
I am wondering if the program can only train no more mental commands than "neutral" and "push"?
