### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by PSCA120** [Emotiv/community-sdk#89]
I am planning on creating a Java application that I hope can utilize Mental Commands, Performance Information, and Facial Expression sensors in my program. Where would I find the documentation on the API/Library to achieve this? Also assuming that it is platform independent. -- I see the example files, however is there more documentation?

**Comment by hoangphamemotiv** [comment]
Hi PSCA120. 

we have a document to "How to run Java Examples" but dont have document for description API on JAVA. API on wraper Java is same with C++. so you can read some infor here:
https://github.com/Emotiv/community-sdk/blob/master/doc/User%20Manual%20for%20Example%20C%2B%2B_Insight_standard.pdf

**Comment by PSCA120** [comment]
Thank you for the reply, I will take a look at that documentation and try to use it as a outline for my application. I also forgot to mention that I will be using the Emotiv Insight. I also saw that you have a repo that you are working on for the Emotiv Insight:
https://github.com/hoangphamemotiv/insight_sdk
And also see it has Java and examples, do you recommend I use your repository?
My application will be using LWJGL3 https://www.lwjgl.org/ (also, I will be testing in Ubuntu Linux)
Any recommendations?

**Comment by hoangphamemotiv** [comment]
i think everything you need at here: https://github.com/Emotiv/community-sdk
^^!

**Comment by PSCA120** [comment]
Thank you.
