### ISSUE TITLE
Overall Skill Rating is still 0 after loading Training Profile from EmotivCloud

### ISSUE THREAD

**Issue by Think0rSwim** [Emotiv/community-sdk#90]
I wanted to get the Training Profile I uploaded from the ControlPanel. 

So I used the SavingAndLoadingProfileCloud demo code. 
And added the below code to see what the loaded profile contains:

[Added at the end of case 2 of switch (option), after the loading has finished] 
float pOverallSkillRatingOut;
if (IEE_MentalCommandGetOverallSkillRating(engineUserID, &pOverallSkillRatingOut) == EDK_OK) {
	std::cout << "\nOverallSkill Rating: " << pOverallSkillRatingOut << std::endl;
}
else {
	std::cout << "\nError" << std::endl;
}

However, when I run the code, while the program says that loading is finished, the OverallSkill Rating is still 0. (The profile I wanted to download has skill rating of push 50)

Am I not loading the profile correctly?

Thanks!

**Comment by hoangphamemotiv** [comment]
Hi Think0rSwim. 

i think you should use this API for get the current skill rating for Push action: 

//! Get the current skill rating for particular MentalCommand actions of the user
	/*!
		Blocking call

		\param userId - user ID
		\param action - a particular action of IEE_MentalCommandAction_t contant
		\param pActionSkillRatingOut - receives the action skill rating [from 0.0 to 1.0]

		\return EDK_ERROR_CODE
				- EDK_OK if successful

		\sa IedkErrorCode.h, IEE_MentalCommandAction_t
	*/
	EDK_API int
		IEE_MentalCommandGetActionSkillRating(unsigned int userId,
		                                      IEE_MentalCommandAction_t action,
		                                      float* pActionSkillRatingOut);

**Comment by Think0rSwim** [comment]
Thanks for the feed back @hoangphamemotiv   But I aslo get 0 for push ActionSkillRating after loading profile. :(

**Comment by hoangphamemotiv** [comment]
Thank Think0rSwim. we are checking this issue. i will send you a feedback soon

**Comment by hoangphamemotiv** [comment]
Hi Think0rSwim. 

i updated Edk libraries v3.3.2 with fixing on training processing MentalCommand. pls update that version for your work. 

Thank Think0rSwim.

**Comment by eva0564** [comment]
I have tried the EmoStateLogger program in C# example, the example provide a method to train "push" mental command. If i want to add several mental commands like "neutral" and "pull" , i found only "neutral" command works .When i train other mental commands besides "neutral" and "push" , the program shows there are unknown mistakes. And i meet the same problem in FacialExpression training process. 
I am wondering if the program can only train no more mental commands than "neutral" and "push"?
