### ISSUE TITLE
What does BTLE limitation in iOS 8.3/8.4 mean?

### ISSUE THREAD

**Issue by sasikiran** [Emotiv/community-sdk#91]
Hi,
 What does "Requires iOS 8.0 or later, except iOS 8.3/8.4 due to BTLE data transmission limitation in those versions" mean? I am not able to find any API differences in CoreBluetooth framework between those versions?

**Comment by nguoithichkhampha** [comment]
Hi sasikiran, don't have any differences in API CoreBluetooth. But in iOS8.3/8.4 Apple limit data transmisson.
