### ISSUE TITLE
Can i train more mental commands than "push" in C# program EmoStateLogger?

### ISSUE THREAD

**Issue by eva0564** [Emotiv/community-sdk#92]
I have tried the C# program EmoStateLogger in community-sdk-3.3.2. The program only provide code to train mental command "push" as follow 
`
case ConsoleKey.F1:
                    EmoEngine.Instance.MentalCommandSetTrainingAction(0, EdkDll.IEE_MentalCommandAction_t.MC_PUSH);
                    EmoEngine.Instance.MentalCommandSetTrainingControl(0, EdkDll.IEE_MentalCommandTrainingControl_t.MC_START);
                    break;
`
I add the code as follow
 `
case ConsoleKey.F4:
                    EmoEngine.Instance.MentalCommandSetTrainingAction(0, EdkDll.IEE_MentalCommandAction_t.MC_NEUTRAL);
                    EmoEngine.Instance.MentalCommandSetTrainingControl(0, EdkDll.IEE_MentalCommandTrainingControl_t.MC_START);
                    break;
case ConsoleKey.F3:
                    EmoEngine.Instance.MentalCommandSetTrainingAction(0, EdkDll.IEE_MentalCommandAction_t.MC_RIGHT);
                    EmoEngine.Instance.MentalCommandSetTrainingControl(0, EdkDll.IEE_MentalCommandTrainingControl_t.MC_START);
                    break;
`
When executing the program ,i meet some trouble. i can train "neutral " and "push " successfully，but "right " with this error
![image](https://github.com/eva0564/hello-world/blob/master/1.PNG)

when i want to train more FacialExpression than CLENCH, i meet the same problem.
 i am wondering if the SDK limit the mental command number or just allow specific command like "push". And after training completed ,can i  save my training results and reload it later?
 Can you help me ?

**Comment by hoangphamemotiv** [comment]
Hi eva0564 . 
you can training 4 action of mental command detection in same profile. this example is just simple example for how to training and geting mental command detection. 

Thank eva0564

**Comment by eva0564** [comment]
Does it mean that  i need generate a new program to  train more mental command?
“4 action of mental command " means i can train any mental command i want like "pull","lift" ?
And after training completed ,can i save my training results and reload it later?
Thank you!

**Comment by hoangphamemotiv** [comment]
Yes, you can train 4 action in a list 16 action of Mental Command detection. and you can save your training results and reload it later. ^^!

Thank you.

**Comment by eva0564** [comment]
However i only find 14 mental commands in "EdkDLL.cs"

> public enum IEE_MentalCommandAction_t
        {
            MC_NEUTRAL          = 0x0001,
            MC_PUSH             = 0x0002,
            MC_PULL             = 0x0004,
            MC_LIFT             = 0x0008,
            MC_DROP             = 0x0010,
            MC_LEFT             = 0x0020,
            MC_RIGHT            = 0x0040,
            MC_ROTATE_LEFT      = 0x0080,
            MC_ROTATE_RIGHT     = 0x0100,
            MC_ROTATE_CLOCKWISE = 0x0200,
            MC_ROTATE_COUNTER_CLOCKWISE = 0x0400,
            MC_ROTATE_FORWARDS  = 0x0800,
            MC_ROTATE_REVERSE   = 0x1000,
            MC_DISAPPEAR        = 0x2000

        } ;

**Comment by hoangphamemotiv** [comment]
Sorry eva0564. 

There are 14 action in the list (not 16). 

To get Motion data, you should work on Insight headset, or EPOC+ headset with EPOC+ mode. you can use IEE_SetSettingHeadset API to change setting. 

For training profile: 
- Login Emotiv ID. 
- EC_SaveUserProfile.  -> create a profile with a name and save it to cloud. 
- Training Processing. 
- EC_UpdateUserProfile -> Saving profile. 

To loading a profile: 
- Login Emotiv ID. 
- EC_LoadUserProfile

I will implement this process in a example soon. 
Thank eva0564 .
