### ISSUE TITLE
for help about c# example

### ISSUE THREAD

**Issue by rizhaoyunhai** [Emotiv/community-sdk#93]
We run the MotionDataLogger program，but  there is nothing in 'motionDataLogger.csv'. And we call the function "engine.HeadsetGetGyroDelta((uint)userID, out pXout, out pYout);", the log is blank, too . HELP.

**Comment by hoangphamemotiv** [comment]
Hi rizhaoyunhai.
What kind of headset are you using? EPOC/EPOC+/INSIGHT. 
Motion data works on EPOC+ with EPOC+ mode and INSIGHT headset. 

for HeadsetGetGyroDelta, every headset can call it. i write some code for this function with C++, but it is same on C#. i will implement it into C# after: 

while(true)
	{

		state = IEE_EngineGetNextEvent(hEvent);

		if (state == EDK_OK) 
		{
		    IEE_Event_t eventType = IEE_EmoEngineEventGetType(hEvent);
			IEE_EmoEngineEventGetUserId(hEvent, &userID);

			if (eventType == IEE_UserAdded) {
		         std::cout << "User added" << std::endl << std::endl;
				 userID = 0;
		         ready = true;
			}
		}

		if(!ready) continue;

		int gyroX = 0, gyroY = 0;
		int err = IEE_HeadsetGetGyroDelta(userID, &gyroX, &gyroY);
				
		if (err == EDK_OK){
			std::cout << std::endl;
			std::cout << "You can move your head now." << std::endl;

#ifdef _WIN32
			Sleep(1000);
#endif
#ifdef __linux__
            usleep(10000);
#endif
			break;
		}else if (err == EDK_GYRO_NOT_CALIBRATED){
			std::cout << "Gyro is not calibrated. Please stay still." << std::endl;
		}else if (err == EDK_CANNOT_ACQUIRE_DATA){
			std::cout << "Cannot acquire data" << std::endl;
		}else{
			std::cout << "No headset is connected" << std::endl;
		}

#ifdef _WIN32
		Sleep(100);
#endif
#ifdef __linux__
        usleep(10000);
#endif
	}

**Comment by rizhaoyunhai** [comment]
@hoangphamemotiv ,the HeadsetGetGyroDelta function work in c++ example, but doesn't work in C# example, and the demo "MotionDataLogger" in c# example outputs nothing in 'motionDataLogger.csv'

**Comment by rizhaoyunhai** [comment]
@hoangphamemotiv we use an EPOC+

**Comment by hoangphamemotiv** [comment]
Hi rizhaoyunhai. 
Did you change setting of your headset to EPOC+ mode? Epoc+ headset have 2 mode are EPOC mode (no motion) and EPOC+ mode (has motion data). 
You can use : IEE_SetSettingHeadset Api to change setting mode. 

Thank rizhaoyunhai.
