### ISSUE TITLE
Mac example Linking issue!

### ISSUE THREAD

**Issue by meiyor** [Emotiv/community-sdk#94]
Hi I'm new with emotiv, I have this problem when I try to run some example or premium examples from community SDK samples. For Example I tried the EmotionStateLogger using 

cmake . 
make 
and this is what I obtained 

_Linking CXX executable eslogger
Undefined symbols for architecture x86_64:
  "_IEE_EmoEngineEventCreate", referenced from:
      _main in main.cpp.o
  "_IEE_EmoEngineEventFree", referenced from:
      _main in main.cpp.o
  "_IEE_EmoEngineEventGetEmoState", referenced from:
      _main in main.cpp.o
  "_IEE_EmoEngineEventGetType", referenced from:
      _main in main.cpp.o
  "_IEE_EmoEngineEventGetUserId", referenced from:
      _main in main.cpp.o
  "_IEE_EmoStateCreate", referenced from:
      _main in main.cpp.o
  "_IEE_EmoStateFree", referenced from:
      _main in main.cpp.o
  "_IEE_EngineConnect", referenced from:
      _main in main.cpp.o
  "_IEE_EngineDisconnect", referenced from:
      _main in main.cpp.o
  "_IEE_EngineGetNextEvent", referenced from:
      _main in main.cpp.o
  "_IEE_EngineRemoteConnect", referenced from:
      _main in main.cpp.o
  "_IS_FacialExpressionGetLowerFaceAction", referenced from:
      _logEmoState in main.cpp.o
  "_IS_FacialExpressionGetLowerFaceActionPower", referenced from:
      _logEmoState in main.cpp.o
  "_IS_FacialExpressionGetUpperFaceAction", referenced from:
      _logEmoState in main.cpp.o
  "_IS_FacialExpressionGetUpperFaceActionPower", referenced from:
      _logEmoState in main.cpp.o
  "_IS_FacialExpressionIsBlink", referenced from:
      _logEmoState in main.cpp.o
  "_IS_FacialExpressionIsLeftWink", referenced from:
      _logEmoState in main.cpp.o
  "_IS_FacialExpressionIsRightWink", referenced from:
      _logEmoState in main.cpp.o
  "_IS_GetTimeFromStart", referenced from:
      _main in main.cpp.o
      _logEmoState in main.cpp.o
  "_IS_GetWirelessSignalStatus", referenced from:
      _logEmoState in main.cpp.o
  "_IS_MentalCommandGetCurrentAction", referenced from:
      _logEmoState in main.cpp.o
  "_IS_MentalCommandGetCurrentActionPower", referenced from:
      _logEmoState in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [eslogger] Error 1
make[1]: *** [CMakeFiles/eslogger.dir/all] Error 2
make: *** [all] Error 2_

Seems that the problem is the library libedk.so, but I have tried to point it from the CMake List.txt and the problem persists. I also add the edk from the SDK premium to /Library/Frameworks and the error is still there. I'm using a Mac 10.10.2 Yosemite.

Thanks your answer

Juan

**Comment by nguoithichkhampha** [comment]
Hi Juan, current We don't support build cmake with example C++ on Mac. You should use qt project to build. We will support cmake on next version.

**Comment by nguoithichkhampha** [comment]
Hi Juan, you can use 
target_Link_libraries(AverageBandPowers "-framework edk") instead
target_link_libraries(AverageBandPowers ${PROJECT_LINK_LIBS} )
to link with edk framework on Mac.
we will fully support cmake build on Mac in next version.
Thanks
Cuong

**Comment by meiyor** [comment]
Hi Cuong 

I add this symbolic link command and the examples are build properly from terminal 

ln -s /Library/Frameworks/edk.framework

The problem right now is with now is the premium examples, I'm trying to run the EEGlogger but the problem is with _kbhit() flag 

_**_Undefined symbols for architecture x86_64:
  "kbhit()", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64_
**_

I have to link another framework or this is a problem with conio.h in mac? I have to add other headers in the case of mac?

Thank you

Juan

**Comment by nguoithichkhampha** [comment]
function _kbhit() is a function for Wins. You should define that function for Mac.
int _kbhit(void)
{
    struct timeval tv;
    fd_set read_fd;

    tv.tv_sec=0;
    tv.tv_usec=0;

    FD_ZERO(&read_fd);
    FD_SET(0,&read_fd);

    if(select(1, &read_fd,NULL, NULL, &tv) == -1)
    return 0;

    if(FD_ISSET(0,&read_fd))
        return 1;

    return 0;
}
Anyway, you can't run premium example with community sdk.You need to run with premium sdk.

**Comment by meiyor** [comment]
yeap I have the premium SDK and I add the IEegData.h to the include folder.

From this I should only connect the Emotiv device by dongle using the testbench? or it will take it automatically?

_**./eeglogger 
===================================================================
Example to show how to log the EmoState from EmoEngine.
===================================================================**_

Thank you

**Comment by nguoithichkhampha** [comment]
You can use example and emotiv headset via dongle, no need Testbench.

**Comment by meiyor** [comment]
Hi Cuong

And thank you

I have two issues:

1. When I run the EEGlogger in  mac I found this floating point exception just when the application start to send data packets: _Floating point exception: 8 _ Is this a problem with a zero division ? what can I do to avoid it?

2. What can I do to send markers from another external API there's some example to do so?

Thank you

**Comment by nguoithichkhampha** [comment]
you can use function IEE_DataSetMarker to send external marker.
