### ISSUE TITLE
file IEegData.h does not appear to exist

### ISSUE THREAD

**Issue by dmedine** [Emotiv/community-sdk#95]
Hi. I am the maintainer of labstreaminglayer (https://github.com/sccn/labstreaminglayer) and I am developing a data acquisition app for your hardware. The example I am following is EEGLogger but the header file referenced on line 27 of main.cpp does not appear to exist. Can you please push this to the repository? Thank you very much.

**Comment by nguoithichkhampha** [comment]
Hi dmedine, this example only work with premium sdk, you need to buy sdk premium.

**Comment by dmedine** [comment]
Where can I make such a purchase? All I can find on your website is the 
SDK lite. Thanks.

**Comment by nguoithichkhampha** [comment]
you can email to hello@emotiv.com to get support.
