### ISSUE TITLE
problem on connection 

### ISSUE THREAD

**Issue by Walaafahad** [Emotiv/community-sdk#97]
when i run an example of android application that uploaded 
it is shown please "connect to your headset " . ?

**Comment by nguoithichkhampha** [comment]
Which example did you run ?

**Comment by Walaafahad** [comment]
Facial expression

**Comment by nguoithichkhampha** [comment]
yes, that mean , you must be connect to headset fist , after that you can use app.

**Comment by Walaafahad** [comment]
I already turn on the headset 
But. It seems to not see it . 
I tried the emotiv insight app on google play and it work fine .
