### ISSUE TITLE
Android: What is isTrain parameter and why do the Android examples continuously log "User added"

### ISSUE THREAD

**Issue by codingyourlife** [Emotiv/community-sdk#99]
What is this isTrain parameter in startTrainingMentalCommand method:
![istrain](https://cloud.githubusercontent.com/assets/10122382/14870087/1a35b6dc-0cd8-11e6-84b5-cbc8af45fa82.png)

Because there is no stopTrainingMentalCommand (why not? that would make sense!) I thought it's supposed to be called with false to stop the recording. So I call a START...(false, ...) ; method to end something? I now called the method as in my screenshot with true and it returned false. What's that supposed to mean? Comments or a documentation would be great!

I also noticed that the default Android examples continously log "User added" in Android Monitor logcat in Android Studio. For example the MotionDataLogger example. I debugged my app for half an hour and then found out that the original app example does that too. I only want to connect as single user and know when it's connected.
![logcat](https://cloud.githubusercontent.com/assets/10122382/14870384/441d1682-0cda-11e6-8066-33beb51caa1c.png)

Do I continuously have to send an empty message to keep the connection alive? The MentalCommand example seems to do that but it doesn't seem to be neccessary. Or is it?

**Comment by codingyourlife** [comment]
could you answer some of my questions @nguoithichkhampha ?

**Comment by nguoithichkhampha** [comment]
Hi, mental command haven't function stop training.
Training will stop after 8s you call training start.

About many log "User added " and "User removed" because issue with bluetooth connection. When mobile connected with headset appear event "User added" but after that mobile can't receive data from headset SDK will call disconnect headset -> appear event "User Removed".
this circle repeat until mobile can receive eeg data.

**Comment by codingyourlife** [comment]
Thanks for your answer. So if there is no stop training method, what is this "isTrain" parameter?
Ok you mean you don't have that connect disconnect loop issue?

**Comment by nguoithichkhampha** [comment]
yes, about "isTrain" parameter maybe because code of my guy. we will optimize code.
